{{- if .Values.qdrant.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "ciso-assistant.fullname" . }}-qdrant
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ciso-assistant.labels" (dict "context" . "component" "qdrant") | nindent 4 }}
  {{- with .Values.qdrant.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.qdrant.replicas }}
  selector:
    matchLabels:
      {{- include "ciso-assistant.selectorLabels" (dict "context" . "component" "qdrant") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ciso-assistant.labels" (dict "context" . "component" "qdrant") | nindent 8 }}
      {{- with .Values.qdrant.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.qdrant.imagePullSecrets | default .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.global.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ .Values.qdrant.name }}
        image: {{ .Values.qdrant.image.registry }}/{{ .Values.qdrant.image.repository }}:{{ .Values.qdrant.image.tag }}
        imagePullPolicy: {{ .Values.qdrant.image.imagePullPolicy }}
        {{- with .Values.qdrant.env }}
        env:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        ports:
          - name: http
            containerPort: 6333
            protocol: TCP
        volumeMounts:
          - name: qdrant-data
            mountPath: /qdrant/storage
        {{- if .Values.qdrant.resources }}
        resources:
          {{- toYaml .Values.qdrant.resources | nindent 10 }}
        {{- end }}
        {{- with .Values.qdrant.containerSecurityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- with .Values.qdrant.nodeSelector | default .Values.global.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.qdrant.tolerations | default .Values.global.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.qdrant.affinity | default .Values.global.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: qdrant-data
        {{- if .Values.qdrant.persistence.enabled }}
          persistentVolumeClaim:
            {{- if .Values.qdrant.persistence.existingClaim }}
            claimName: {{ .Values.qdrant.persistence.existingClaim }}
            {{- else }}
            claimName: {{ include "ciso-assistant.fullname" . }}-qdrant
            {{- end }}
        {{- else }}
          emptyDir: {}
        {{- end }}
{{- end }}
