{{- if .Values.qdrant.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ciso-assistant.fullname" . }}-qdrant
  namespace: {{ .Release.Namespace }}
  {{- with .Values.qdrant.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "ciso-assistant.labels" (dict "context" . "component" "qdrant") | nindent 4 }}
    {{- with .Values.qdrant.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ports:
  - name: {{ .Values.qdrant.service.portName }}
    protocol: TCP
    port: {{ .Values.qdrant.service.port }}
    targetPort: http
  selector:
    {{- include "ciso-assistant.selectorLabels" (dict "context" . "component" "qdrant") | nindent 4 }}
{{- end }}
