# Generated by Django 5.2.7 on 2025-12-19 18:16

import django.db.models.deletion
import iam.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0120_alter_terminology_field_path"),
        ("iam", "0016_folder_filtering_labels"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Dashboard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "ref_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="reference id",
                    ),
                ),
                (
                    "dashboard_definition",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Global dashboard configuration. Format: {'layout': {'columns': 12, 'row_height': 100}, 'global_filters': {'time_range': 'last_30_days', 'refresh_interval': 300}}",
                    ),
                ),
                (
                    "filtering_labels",
                    models.ManyToManyField(
                        blank=True, to="core.filteringlabel", verbose_name="Labels"
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        default=iam.models.Folder.get_root_folder_id,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_folder",
                        to="iam.folder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dashboard",
                "verbose_name_plural": "Dashboards",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MetricDefinition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "urn",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="URN",
                    ),
                ),
                (
                    "ref_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Reference ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Provider"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, null=True, verbose_name="Name"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "annotation",
                    models.TextField(blank=True, null=True, verbose_name="Annotation"),
                ),
                (
                    "translations",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Translations"
                    ),
                ),
                (
                    "locale",
                    models.CharField(
                        default="en", max_length=100, verbose_name="Locale"
                    ),
                ),
                (
                    "default_locale",
                    models.BooleanField(default=True, verbose_name="Default locale"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("qualitative", "Qualitative (Level)"),
                            ("quantitative", "Quantitative (Number)"),
                        ],
                        default="quantitative",
                        max_length=20,
                        verbose_name="Category",
                    ),
                ),
                (
                    "choices_definition",
                    models.JSONField(
                        blank=True,
                        help_text="For qualitative metrics: ordered list of options with translations. Format: [{'name': 'Low', 'description': '', 'translations': {'fr': {'name': 'Faible', 'description': ''}}}]",
                        null=True,
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Published"),
                ),
                (
                    "higher_is_better",
                    models.BooleanField(
                        default=True,
                        help_text="If true, an increase in value is considered positive (e.g., compliance score). If false, a decrease is considered positive (e.g., number of vulnerabilities).",
                        verbose_name="Higher is better",
                    ),
                ),
                (
                    "default_target",
                    models.FloatField(
                        blank=True,
                        help_text="Default target value for metric instances. Can be overridden at instance level.",
                        null=True,
                        verbose_name="Default target",
                    ),
                ),
                (
                    "filtering_labels",
                    models.ManyToManyField(
                        blank=True, to="core.filteringlabel", verbose_name="Labels"
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        default=iam.models.Folder.get_root_folder_id,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_folder",
                        to="iam.folder",
                    ),
                ),
                (
                    "library",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metric_definitions",
                        to="core.loadedlibrary",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Unit of measurement (e.g., count, users, bytes, percentage, score, event_per_second)",
                        limit_choices_to={
                            "field_path": "metric_definition.unit",
                            "is_visible": True,
                        },
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="metric_definition_units",
                        to="core.terminology",
                        verbose_name="Unit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Metric definition",
                "verbose_name_plural": "Metric definitions",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MetricInstance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "ref_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="reference id",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("stale", "Stale"),
                            ("deprecated", "Deprecated"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "target_value",
                    models.FloatField(
                        blank=True,
                        help_text="Target or optimal value for this metric instance",
                        null=True,
                        verbose_name="Target value",
                    ),
                ),
                (
                    "collection_frequency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("realtime", "Real-time (continuous)"),
                            ("hourly", "Hourly"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("yearly", "Yearly"),
                        ],
                        help_text="Expected frequency for collecting metric samples",
                        max_length=20,
                        null=True,
                        verbose_name="Collection frequency",
                    ),
                ),
                (
                    "filtering_labels",
                    models.ManyToManyField(
                        blank=True, to="core.filteringlabel", verbose_name="Labels"
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        default=iam.models.Folder.get_root_folder_id,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_folder",
                        to="iam.folder",
                    ),
                ),
                (
                    "metric_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="metrology.metricdefinition",
                        verbose_name="Metric definition",
                    ),
                ),
                (
                    "owner",
                    models.ManyToManyField(
                        blank=True,
                        related_name="metric_instances",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Metric instance",
                "verbose_name_plural": "Metric instances",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DashboardWidget",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
                (
                    "target_object_id",
                    models.UUIDField(
                        blank=True,
                        help_text="For builtin metrics: the ID of the specific object",
                        null=True,
                        verbose_name="Target object ID",
                    ),
                ),
                (
                    "metric_key",
                    models.CharField(
                        blank=True,
                        help_text="For builtin metrics: which metric to display (e.g., 'progress', 'result_breakdown')",
                        max_length=100,
                        null=True,
                        verbose_name="Metric key",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Custom title for the widget. If empty, uses metric instance name or metric key.",
                        max_length=200,
                        null=True,
                        verbose_name="Title",
                    ),
                ),
                (
                    "text_content",
                    models.TextField(
                        blank=True,
                        help_text="Markdown content for text widgets",
                        null=True,
                        verbose_name="Text content",
                    ),
                ),
                (
                    "position_x",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Horizontal position in grid (0-11)",
                        verbose_name="Position X",
                    ),
                ),
                (
                    "position_y",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Vertical position in grid (row number)",
                        verbose_name="Position Y",
                    ),
                ),
                (
                    "width",
                    models.PositiveIntegerField(
                        default=6,
                        help_text="Width in grid columns (1-12)",
                        verbose_name="Width",
                    ),
                ),
                (
                    "height",
                    models.PositiveIntegerField(
                        default=2,
                        help_text="Height in grid rows",
                        verbose_name="Height",
                    ),
                ),
                (
                    "chart_type",
                    models.CharField(
                        choices=[
                            ("kpi_card", "KPI Card"),
                            ("donut", "Donut Chart"),
                            ("pie", "Pie Chart"),
                            ("bar", "Bar Chart"),
                            ("line", "Line Chart"),
                            ("area", "Area Chart"),
                            ("gauge", "Gauge"),
                            ("sparkline", "Sparkline"),
                            ("table", "Table"),
                            ("text", "Text"),
                        ],
                        default="kpi_card",
                        max_length=20,
                        verbose_name="Chart type",
                    ),
                ),
                (
                    "time_range",
                    models.CharField(
                        choices=[
                            ("last_hour", "Last Hour"),
                            ("last_24_hours", "Last 24 Hours"),
                            ("last_7_days", "Last 7 Days"),
                            ("last_30_days", "Last 30 Days"),
                            ("last_90_days", "Last 90 Days"),
                            ("last_year", "Last Year"),
                            ("all_time", "All Time"),
                            ("custom", "Custom Range"),
                        ],
                        default="last_30_days",
                        max_length=20,
                        verbose_name="Time range",
                    ),
                ),
                (
                    "aggregation",
                    models.CharField(
                        choices=[
                            ("none", "None (Raw Data)"),
                            ("avg", "Average"),
                            ("sum", "Sum"),
                            ("min", "Minimum"),
                            ("max", "Maximum"),
                            ("count", "Count"),
                            ("last", "Last Value"),
                        ],
                        default="none",
                        max_length=20,
                        verbose_name="Aggregation",
                    ),
                ),
                (
                    "show_target",
                    models.BooleanField(
                        default=True,
                        help_text="Display target value line if defined on metric instance",
                        verbose_name="Show target",
                    ),
                ),
                (
                    "show_legend",
                    models.BooleanField(
                        default=True,
                        help_text="Display widget title bar and legend (for charts)",
                        verbose_name="Show title and legend",
                    ),
                ),
                (
                    "widget_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional widget configuration. Format: {'color_scheme': 'default', 'threshold_colors': {...}, 'custom_options': {...}}",
                    ),
                ),
                (
                    "dashboard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="widgets",
                        to="metrology.dashboard",
                        verbose_name="Dashboard",
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        default=iam.models.Folder.get_root_folder_id,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_folder",
                        to="iam.folder",
                    ),
                ),
                (
                    "target_content_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="For builtin metrics: the type of object (e.g., ComplianceAssessment)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="Target content type",
                    ),
                ),
                (
                    "metric_instance",
                    models.ForeignKey(
                        blank=True,
                        help_text="For custom metrics: the metric instance to display",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboard_widgets",
                        to="metrology.metricinstance",
                        verbose_name="Metric instance",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dashboard widget",
                "verbose_name_plural": "Dashboard widgets",
                "ordering": ["position_y", "position_x"],
            },
        ),
        migrations.CreateModel(
            name="CustomMetricSample",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When the metric sample was recorded",
                        verbose_name="Timestamp",
                    ),
                ),
                (
                    "value",
                    models.JSONField(
                        default=dict,
                        help_text="The metric value (format depends on metric definition category)",
                        verbose_name="Value",
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        default=iam.models.Folder.get_root_folder_id,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_folder",
                        to="iam.folder",
                    ),
                ),
                (
                    "metric_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="samples",
                        to="metrology.metricinstance",
                        verbose_name="Metric instance",
                    ),
                ),
            ],
            options={
                "verbose_name": "Custom metric sample",
                "verbose_name_plural": "Custom metric samples",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="BuiltinMetricSample",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
                (
                    "object_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="The ID of the object this metric is computed for",
                        verbose_name="Object ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        db_index=True,
                        help_text="The date this snapshot was recorded",
                        verbose_name="Date",
                    ),
                ),
                (
                    "metrics",
                    models.JSONField(
                        default=dict,
                        help_text="All computed metrics for this object. Format depends on object type (e.g., progress, result_breakdown, etc.)",
                        verbose_name="Metrics",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        help_text="The type of object this metric is computed for",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="Content type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Builtin metric sample",
                "verbose_name_plural": "Builtin metric samples",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id", "date"],
                        name="metrology_b_content_444e6b_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("content_type", "object_id", "date"),
                        name="unique_builtin_metric_sample_per_object_per_day",
                    )
                ],
            },
        ),
    ]
