# Generated by Django 5.2.7 on 2025-12-09 18:05

import django.db.models.deletion
import iam.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iam", "0016_folder_filtering_labels"),
        ("metrology", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dashboard",
            name="metric_instances",
        ),
        migrations.AlterField(
            model_name="dashboard",
            name="dashboard_definition",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Global dashboard configuration. Format: {'layout': {'columns': 12, 'row_height': 100}, 'global_filters': {'time_range': 'last_30_days', 'refresh_interval': 300}}",
            ),
        ),
        migrations.CreateModel(
            name="DashboardWidget",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Custom title for the widget. If empty, uses metric instance name.",
                        max_length=200,
                        null=True,
                        verbose_name="Title",
                    ),
                ),
                (
                    "position_x",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Horizontal position in grid (0-11)",
                        verbose_name="Position X",
                    ),
                ),
                (
                    "position_y",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Vertical position in grid (row number)",
                        verbose_name="Position Y",
                    ),
                ),
                (
                    "width",
                    models.PositiveIntegerField(
                        default=6,
                        help_text="Width in grid columns (1-12)",
                        verbose_name="Width",
                    ),
                ),
                (
                    "height",
                    models.PositiveIntegerField(
                        default=2,
                        help_text="Height in grid rows",
                        verbose_name="Height",
                    ),
                ),
                (
                    "chart_type",
                    models.CharField(
                        choices=[
                            ("line", "Line Chart"),
                            ("bar", "Bar Chart"),
                            ("area", "Area Chart"),
                            ("gauge", "Gauge"),
                            ("kpi_card", "KPI Card"),
                            ("sparkline", "Sparkline"),
                            ("table", "Table"),
                        ],
                        default="line",
                        max_length=20,
                        verbose_name="Chart type",
                    ),
                ),
                (
                    "time_range",
                    models.CharField(
                        choices=[
                            ("last_hour", "Last Hour"),
                            ("last_24_hours", "Last 24 Hours"),
                            ("last_7_days", "Last 7 Days"),
                            ("last_30_days", "Last 30 Days"),
                            ("last_90_days", "Last 90 Days"),
                            ("last_year", "Last Year"),
                            ("all_time", "All Time"),
                            ("custom", "Custom Range"),
                        ],
                        default="last_30_days",
                        max_length=20,
                        verbose_name="Time range",
                    ),
                ),
                (
                    "aggregation",
                    models.CharField(
                        choices=[
                            ("none", "None (Raw Data)"),
                            ("avg", "Average"),
                            ("sum", "Sum"),
                            ("min", "Minimum"),
                            ("max", "Maximum"),
                            ("count", "Count"),
                            ("last", "Last Value"),
                        ],
                        default="none",
                        max_length=20,
                        verbose_name="Aggregation",
                    ),
                ),
                (
                    "show_target",
                    models.BooleanField(
                        default=True,
                        help_text="Display target value line if defined on metric instance",
                        verbose_name="Show target",
                    ),
                ),
                (
                    "show_legend",
                    models.BooleanField(default=True, verbose_name="Show legend"),
                ),
                (
                    "widget_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional widget configuration. Format: {'color_scheme': 'default', 'threshold_colors': {...}, 'custom_options': {...}}",
                    ),
                ),
                (
                    "dashboard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="widgets",
                        to="metrology.dashboard",
                        verbose_name="Dashboard",
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        default=iam.models.Folder.get_root_folder_id,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_folder",
                        to="iam.folder",
                    ),
                ),
                (
                    "metric_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboard_widgets",
                        to="metrology.metricinstance",
                        verbose_name="Metric instance",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dashboard widget",
                "verbose_name_plural": "Dashboard widgets",
                "ordering": ["position_y", "position_x"],
            },
        ),
    ]
