# Generated by Django 5.2.7 on 2025-12-12 19:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iam", "0016_folder_filtering_labels"),
        ("metrology", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MetricSample",
            new_name="CustomMetricSample",
        ),
        migrations.AlterModelOptions(
            name="custommetricsample",
            options={
                "ordering": ["-timestamp"],
                "verbose_name": "Custom metric sample",
                "verbose_name_plural": "Custom metric samples",
            },
        ),
    ]
