# Generated by Django 5.2.9 on 2026-01-08 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0125_team_actor"),
        ("metrology", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="metricinstance",
            name="new_owner",
            field=models.ManyToManyField(
                blank=True,
                related_name="metric_instances",
                to="core.actor",
                verbose_name="Owner",
            ),
        ),
    ]
