# Generated by Django 5.2.7 on 2025-11-25 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0117_alter_terminology_field_path"),
        ("metrology", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metricdefinition",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                help_text="Unit of measurement (e.g., count, users, bytes, percentage, score, event_per_second)",
                limit_choices_to={
                    "field_path": "metric_definition.unit",
                    "is_visible": True,
                },
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="metric_definition_units",
                to="core.terminology",
                verbose_name="Unit",
            ),
        ),
    ]
