# Generated by Django 5.2.7 on 2025-12-17 08:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metrology", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dashboardwidget",
            name="text_content",
            field=models.TextField(
                blank=True,
                help_text="Markdown content for text widgets",
                null=True,
                verbose_name="Text content",
            ),
        ),
        migrations.AlterField(
            model_name="dashboardwidget",
            name="chart_type",
            field=models.CharField(
                choices=[
                    ("kpi_card", "KPI Card"),
                    ("donut", "Donut Chart"),
                    ("bar", "Bar Chart"),
                    ("area", "Area Chart"),
                    ("gauge", "Gauge"),
                    ("sparkline", "Sparkline"),
                    ("table", "Table"),
                    ("text", "Text"),
                ],
                default="kpi_card",
                max_length=20,
                verbose_name="Chart type",
            ),
        ),
    ]
