# Generated by Django 5.2.7 on 2025-12-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metrology", "0002_dashboardwidget_text_content_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dashboardwidget",
            name="chart_type",
            field=models.CharField(
                choices=[
                    ("kpi_card", "KPI Card"),
                    ("donut", "Donut Chart"),
                    ("pie", "Pie Chart"),
                    ("bar", "Bar Chart"),
                    ("line", "Line Chart"),
                    ("area", "Area Chart"),
                    ("gauge", "Gauge"),
                    ("sparkline", "Sparkline"),
                    ("table", "Table"),
                    ("text", "Text"),
                ],
                default="kpi_card",
                max_length=20,
                verbose_name="Chart type",
            ),
        ),
        migrations.AlterField(
            model_name="dashboardwidget",
            name="show_legend",
            field=models.BooleanField(
                default=True,
                help_text="Display widget title bar and legend (for charts)",
                verbose_name="Show title and legend",
            ),
        ),
    ]
