# Generated by Django 5.2.7 on 2025-12-12 19:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("metrology", "0002_rename_metricsample_custommetricsample_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dashboardwidget",
            name="metric_key",
            field=models.CharField(
                blank=True,
                help_text="For builtin metrics: which metric to display (e.g., 'progress', 'result_breakdown')",
                max_length=100,
                null=True,
                verbose_name="Metric key",
            ),
        ),
        migrations.AddField(
            model_name="dashboardwidget",
            name="target_content_type",
            field=models.ForeignKey(
                blank=True,
                help_text="For builtin metrics: the type of object (e.g., ComplianceAssessment)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
                verbose_name="Target content type",
            ),
        ),
        migrations.AddField(
            model_name="dashboardwidget",
            name="target_object_id",
            field=models.UUIDField(
                blank=True,
                help_text="For builtin metrics: the ID of the specific object",
                null=True,
                verbose_name="Target object ID",
            ),
        ),
        migrations.AlterField(
            model_name="dashboardwidget",
            name="metric_instance",
            field=models.ForeignKey(
                blank=True,
                help_text="For custom metrics: the metric instance to display",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dashboard_widgets",
                to="metrology.metricinstance",
                verbose_name="Metric instance",
            ),
        ),
        migrations.AlterField(
            model_name="dashboardwidget",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="Custom title for the widget. If empty, uses metric instance name or metric key.",
                max_length=200,
                null=True,
                verbose_name="Title",
            ),
        ),
        migrations.CreateModel(
            name="BuiltinMetricSample",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
                (
                    "object_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="The ID of the object this metric is computed for",
                        verbose_name="Object ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        db_index=True,
                        help_text="The date this snapshot was recorded",
                        verbose_name="Date",
                    ),
                ),
                (
                    "metrics",
                    models.JSONField(
                        default=dict,
                        help_text="All computed metrics for this object. Format depends on object type (e.g., progress, result_breakdown, etc.)",
                        verbose_name="Metrics",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        help_text="The type of object this metric is computed for",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="Content type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Builtin metric sample",
                "verbose_name_plural": "Builtin metric samples",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id", "date"],
                        name="metrology_b_content_444e6b_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("content_type", "object_id", "date"),
                        name="unique_builtin_metric_sample_per_object_per_day",
                    )
                ],
            },
        ),
    ]
