# Generated by Django 5.2.9 on 2026-02-04 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0134_populate_riskscenario_folder"),
        ("metrology", "0003_remove_metricinstance_new_owner_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="custommetricsample",
            name="evidence_revision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="samples",
                to="core.evidencerevision",
            ),
        ),
        migrations.AddField(
            model_name="custommetricsample",
            name="observation",
            field=models.TextField(blank=True, null=True, verbose_name="Observation"),
        ),
        migrations.AddField(
            model_name="metricinstance",
            name="evidences",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="metric_instances",
                to="core.evidence",
            ),
        ),
    ]
