# Generated by Django 5.2.7 on 2025-12-13 08:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metrology", "0003_dashboardwidget_metric_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="metricdefinition",
            name="default_target",
            field=models.FloatField(
                blank=True,
                help_text="Default target value for metric instances. Can be overridden at instance level.",
                null=True,
                verbose_name="Default target",
            ),
        ),
        migrations.AlterField(
            model_name="dashboardwidget",
            name="chart_type",
            field=models.CharField(
                choices=[
                    ("kpi_card", "KPI Card"),
                    ("donut", "Donut Chart"),
                    ("bar", "Bar Chart"),
                    ("area", "Area Chart"),
                    ("gauge", "Gauge"),
                    ("sparkline", "Sparkline"),
                    ("table", "Table"),
                ],
                default="kpi_card",
                max_length=20,
                verbose_name="Chart type",
            ),
        ),
    ]
