# Generated by Django 6.0.8 on 2026-08-28 06:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("metrology", "0004_custommetricsample_evidence_revision_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="builtinmetricsample",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="custommetricsample",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="dashboard",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="dashboardwidget",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="metricdefinition",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="metricinstance",
            name="is_published",
        ),
    ]
