# Generated by Django 6.1.1 on 2026-09-18 18:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metrology", "0005_remove_builtinmetricsample_is_published_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dashboardwidget",
            name="chart_type",
            field=models.CharField(
                choices=[
                    ("kpi_card", "KPI Card"),
                    ("donut", "Donut Chart"),
                    ("pie", "Pie Chart"),
                    ("bar", "Bar Chart"),
                    ("line", "Line Chart"),
                    ("area", "Area Chart"),
                    ("gauge", "Gauge"),
                    ("sparkline", "Sparkline"),
                    ("small_multiples", "Small Multiples"),
                    ("table", "Table"),
                    ("text", "Text"),
                ],
                default="kpi_card",
                max_length=20,
                verbose_name="Chart type",
            ),
        ),
    ]
