# Generated by Django 6.1.1 on 2026-10-09 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metrology", "0006_small_multiples_chart_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="custommetricsample",
            name="period_start",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Period start"
            ),
        ),
        migrations.AddField(
            model_name="custommetricsample",
            name="source",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("workflow", "Workflow"),
                    ("derived", "Derived"),
                ],
                default="manual",
                help_text="What wrote the sample: a person, a workflow, or the metric's own formula",
                max_length=20,
                verbose_name="Source",
            ),
        ),
        migrations.AddField(
            model_name="metricdefinition",
            name="datasets",
            field=models.JSONField(
                blank=True,
                help_text="For derived metrics: named read configurations, each answering aggregates the expression can use",
                null=True,
                verbose_name="Datasets",
            ),
        ),
        migrations.AddField(
            model_name="metricdefinition",
            name="expression",
            field=models.TextField(
                blank=True,
                default="",
                help_text="For derived metrics: the CEL expression computing the value",
                verbose_name="Expression",
            ),
        ),
        migrations.AddField(
            model_name="metricdefinition",
            name="inputs",
            field=models.JSONField(
                blank=True,
                help_text="For metrics computed from other metrics: the metrics the expression combines, period by period",
                null=True,
                verbose_name="Inputs",
            ),
        ),
        migrations.AddField(
            model_name="metricinstance",
            name="input_choices",
            field=models.JSONField(
                blank=True,
                help_text="For metrics computed from other metrics: which instances an input reads when the domain holds several",
                null=True,
                verbose_name="Input choices",
            ),
        ),
        migrations.AddField(
            model_name="metricinstance",
            name="last_computation_error",
            field=models.TextField(
                blank=True, default="", verbose_name="Last computation error"
            ),
        ),
        migrations.AddField(
            model_name="metricinstance",
            name="last_computed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Last computed at"
            ),
        ),
        migrations.AddField(
            model_name="metricinstance",
            name="recompute_from",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Recompute from"
            ),
        ),
        migrations.AddConstraint(
            model_name="custommetricsample",
            constraint=models.UniqueConstraint(
                condition=models.Q(("period_start__isnull", False)),
                fields=("metric_instance", "period_start"),
                name="unique_metric_sample_per_period",
            ),
        ),
    ]
