# Generated by Django 5.2.8 on 2025-11-28 15:42

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("iam", "0016_folder_filtering_labels"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the client company/organization",
                        max_length=255,
                        verbose_name="Company Name",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Unique identifier for the account (URL-friendly)",
                        max_length=100,
                        unique=True,
                        verbose_name="Account Slug",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Primary contact email for the account",
                        max_length=254,
                        verbose_name="Contact Email",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Phone Number",
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="Address"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("expired", "Expired"),
                            ("trial", "Trial"),
                        ],
                        default="trial",
                        max_length=20,
                        verbose_name="Account Status",
                    ),
                ),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("basic", "Basic"),
                            ("pro", "Professional"),
                            ("enterprise", "Enterprise"),
                        ],
                        default="free",
                        max_length=20,
                        verbose_name="Subscription Plan",
                    ),
                ),
                (
                    "subscription_start",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Subscription Start Date",
                    ),
                ),
                (
                    "subscription_end",
                    models.DateField(
                        help_text="Date when the subscription expires",
                        verbose_name="Subscription End Date",
                    ),
                ),
                (
                    "max_users",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="Maximum number of users allowed for this account",
                        verbose_name="Maximum Users",
                    ),
                ),
                (
                    "max_domains",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Maximum number of sub-domains/projects allowed",
                        verbose_name="Maximum Domains",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal notes about this account",
                        null=True,
                        verbose_name="Notes",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="account_logos/",
                        verbose_name="Company Logo",
                    ),
                ),
                (
                    "admin_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Primary administrator for this account",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="administered_accounts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Account Administrator",
                    ),
                ),
                (
                    "folder",
                    models.OneToOneField(
                        blank=True,
                        help_text="The folder/domain associated with this account",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_account",
                        to="iam.folder",
                        verbose_name="Domain Folder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Client Account",
                "verbose_name_plural": "Client Accounts",
                "ordering": ["-created_at"],
            },
        ),
    ]
