# Generated by Django 5.1 on 2024-09-17 19:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tprm", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entity",
            name="reference_link",
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
    ]
