# Generated by Django 5.1 on 2024-10-01 09:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tprm", "0002_alter_entity_reference_link"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="entityassessment",
            name="representatives",
            field=models.ManyToManyField(
                blank=True,
                related_name="entity_assessments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Representative",
            ),
        ),
    ]
