# Generated by Django 5.1.4 on 2025-01-28 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0050_rename_project_perimeter_alter_perimeter_options_and_more"),
        ("tprm", "0003_entityassessment_representatives"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="entityassessment",
            name="project",
        ),
        migrations.AddField(
            model_name="entityassessment",
            name="perimeter",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.perimeter",
                verbose_name="Perimeter",
            ),
        ),
    ]
