# Generated by Django 5.1.5 on 2025-02-04 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0051_rename_project_perimeter_alter_perimeter_options_and_more"),
        ("tprm", "0003_entityassessment_representatives"),
    ]

    operations = [
        migrations.RenameField(
            model_name="entityassessment",
            old_name="project",
            new_name="perimeter",
        ),
        migrations.AlterField(
            model_name="entityassessment",
            name="perimeter",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.perimeter",
                verbose_name="Perimeter",
            ),
        ),
    ]
