# Generated by Django 5.1.7 on 2025-03-26 11:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0062_appliedcontrol_filtering_labels_and_more"),
        ("tprm", "0004_remove_entityassessment_project_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="solution",
            name="assets",
            field=models.ManyToManyField(
                blank=True,
                help_text="Assets related to the solution",
                related_name="solutions",
                to="core.asset",
                verbose_name="Related assets",
            ),
        ),
    ]
