# Generated by Django 5.1.10 on 2025-06-16 09:58

from django.db import migrations


def update_audits_perimeter(apps, schema_editor):
    Perimeter = apps.get_model("core", "Perimeter")
    EntityAssessment = apps.get_model("tprm", "EntityAssessment")

    for instance in EntityAssessment.objects.all():
        audit = instance.compliance_assessment
        if not audit:
            continue
        enclave = audit.folder
        enclave.name = f"{instance.perimeter.name}/{instance.name}"
        enclave.save()
        perimeter = Perimeter.objects.create(
            name=f"{instance.name}",
            folder=enclave,
        )
        audit.perimeter = perimeter
        audit.save()


class Migration(migrations.Migration):
    dependencies = [
        ("tprm", "0005_solution_assets"),
    ]

    operations = [
        migrations.RunPython(update_audits_perimeter),
    ]
