# Generated by Django 5.1.9 on 2025-06-25 14:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tprm', '0005_solution_assets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='reference_link',
            field=models.URLField(blank=True, max_length=2048, null=True, validators=[django.core.validators.URLValidator(schemes={'http', 'https'})]),
        ),
    ]
