# Generated by Django 5.2.7 on 2025-10-03 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0103_alter_terminology_field_path"),
        ("tprm", "0006_entityassessment_is_locked"),
    ]

    operations = [
        migrations.AddField(
            model_name="entity",
            name="relationship",
            field=models.ManyToManyField(
                blank=True,
                help_text="Type of relationship with this entity",
                limit_choices_to={
                    "field_path": "entity.relationship",
                    "is_visible": True,
                },
                related_name="entities",
                to="core.terminology",
                verbose_name="Relationship",
            ),
        ),
    ]
