# Generated by Django 5.2.7 on 2025-11-07 18:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tprm", "0007_entity_relationship"),
    ]

    operations = [
        migrations.AddField(
            model_name="entity",
            name="legal_identifiers",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Legal identifiers (LEI, EUID, VAT, DUNS, etc.)",
                verbose_name="Legal identifiers",
            ),
        ),
    ]
