# Generated by Django 5.2.7 on 2025-11-14 12:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tprm", "0008_entity_country_entity_currency_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="solution",
            name="owner",
            field=models.ManyToManyField(
                blank=True,
                related_name="solutions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Owner",
            ),
        ),
    ]
