# Generated by Django 5.2.7 on 2025-11-11 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tprm", "0008_entity_country_entity_currency_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contract",
            name="entities",
        ),
        migrations.RemoveField(
            model_name="contract",
            name="solutions",
        ),
        migrations.AddField(
            model_name="contract",
            name="provider_entity",
            field=models.ForeignKey(
                blank=True,
                help_text="Entity providing this contract",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contracts",
                to="tprm.entity",
                verbose_name="Provider entity",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="solution",
            field=models.ForeignKey(
                blank=True,
                help_text="Solution covered by this contract",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contracts",
                to="tprm.solution",
                verbose_name="Solution",
            ),
        ),
    ]
