# Generated by Django 5.2.7 on 2025-11-07 20:57

import django.db.models.deletion
import iam.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0112_asset_is_critical"),
        ("iam", "0016_folder_filtering_labels"),
        ("tprm", "0008_entity_legal_identifiers"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("terminated", "Terminated"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="Start date"),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="End date"),
                ),
                (
                    "ref_id",
                    models.CharField(
                        blank=True,
                        help_text="Contract reference number or identifier",
                        max_length=255,
                        verbose_name="Reference ID",
                    ),
                ),
                (
                    "entities",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Entities involved in this contract",
                        related_name="contracts",
                        to="tprm.entity",
                        verbose_name="Entities",
                    ),
                ),
                (
                    "evidences",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Supporting evidence for this contract",
                        related_name="contracts",
                        to="core.evidence",
                        verbose_name="Evidences",
                    ),
                ),
                (
                    "filtering_labels",
                    models.ManyToManyField(
                        blank=True, to="core.filteringlabel", verbose_name="Labels"
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        default=iam.models.Folder.get_root_folder_id,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_folder",
                        to="iam.folder",
                    ),
                ),
                (
                    "owner",
                    models.ManyToManyField(
                        blank=True,
                        related_name="contracts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner",
                    ),
                ),
                (
                    "solutions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Solutions covered by this contract",
                        related_name="contracts",
                        to="tprm.solution",
                        verbose_name="Solutions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contract",
                "verbose_name_plural": "Contracts",
            },
        ),
    ]
