# Generated by Django 5.2.9 on 2026-01-08 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0128_appliedcontrol_new_owner_asset_new_owner_and_more"),
        ("tprm", "0009_migrate_solution_to_solutions"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="new_owner",
            field=models.ManyToManyField(
                blank=True,
                related_name="contracts",
                to="core.actor",
                verbose_name="Owner",
            ),
        ),
        migrations.AddField(
            model_name="entityassessment",
            name="new_authors",
            field=models.ManyToManyField(
                blank=True,
                related_name="%(class)s_authors_new",
                to="core.actor",
                verbose_name="Authors",
            ),
        ),
        migrations.AddField(
            model_name="entityassessment",
            name="new_reviewers",
            field=models.ManyToManyField(
                blank=True,
                related_name="%(class)s_reviewers_new",
                to="core.actor",
                verbose_name="Reviewers",
            ),
        ),
        migrations.AddField(
            model_name="solution",
            name="new_owner",
            field=models.ManyToManyField(
                blank=True,
                related_name="solutions",
                to="core.actor",
                verbose_name="Owner",
            ),
        ),
    ]
