# Generated by Django 5.2.7 on 2025-11-11 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tprm", "0009_remove_contract_entities_remove_contract_solutions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="entity",
            name="parent_entity",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent entity for branch/subsidiary relationships",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="branches",
                to="tprm.entity",
                verbose_name="Parent entity",
            ),
        ),
    ]
