# Generated by Django 5.2.7 on 2025-11-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tprm", "0010_entity_parent_entity"),
    ]

    operations = [
        migrations.AddField(
            model_name="entity",
            name="dora_provider_person_type",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "eba_CT:x212",
                        "Legal person, excluding individual acting in a business capacity",
                    ),
                    ("eba_CT:x213", "Individual acting in a business capacity"),
                ],
                help_text="Type of person for ICT third-party service providers",
                max_length=20,
                verbose_name="DORA provider person type",
            ),
        ),
    ]
