# Generated by Django 5.2.9 on 2026-01-09 14:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0129_remove_appliedcontrol_new_owner_and_more"),
        ("tprm", "0010_contract_new_owner_entityassessment_new_authors_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contract",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="entityassessment",
            name="authors",
        ),
        migrations.RemoveField(
            model_name="entityassessment",
            name="reviewers",
        ),
        migrations.RemoveField(
            model_name="solution",
            name="owner",
        ),
        migrations.RenameField(
            model_name="contract",
            old_name="new_owner",
            new_name="owner",
        ),
        migrations.RenameField(
            model_name="entityassessment",
            old_name="new_authors",
            new_name="authors",
        ),
        migrations.RenameField(
            model_name="entityassessment",
            old_name="new_reviewers",
            new_name="reviewers",
        ),
        migrations.RenameField(
            model_name="solution",
            old_name="new_owner",
            new_name="owner",
        ),
    ]
