# Generated by Django 5.2.9 on 2026-01-28 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0133_alter_complianceassessment_perimeter_and_more"),
        ("tprm", "0011_remove_contract_new_owner_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entityassessment",
            name="perimeter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.perimeter",
                verbose_name="Perimeter",
            ),
        ),
    ]
