# Generated by Django 5.2.7 on 2025-11-11 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tprm", "0011_entity_dora_provider_person_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="solution",
            name="dora_alternative_providers",
            field=models.TextField(
                blank=True,
                help_text="Identification of alternative ICT third-party service providers",
                verbose_name="Alternative providers",
            ),
        ),
        migrations.AddField(
            model_name="solution",
            name="dora_alternative_providers_identified",
            field=models.CharField(
                blank=True,
                choices=[("eba_BT:x28", "Yes"), ("eba_BT:x29", "No")],
                help_text="Are there alternative ICT third-party service providers identified?",
                max_length=20,
                verbose_name="Alternative providers identified",
            ),
        ),
        migrations.AddField(
            model_name="solution",
            name="dora_discontinuing_impact",
            field=models.CharField(
                blank=True,
                choices=[
                    ("eba_ZZ:x791", "Low"),
                    ("eba_ZZ:x792", "Medium"),
                    ("eba_ZZ:x793", "High"),
                    ("eba_ZZ:x799", "Assessment not performed"),
                ],
                help_text="Impact of discontinuing the ICT services",
                max_length=20,
                verbose_name="Discontinuing impact",
            ),
        ),
        migrations.AddField(
            model_name="solution",
            name="dora_has_exit_plan",
            field=models.CharField(
                blank=True,
                choices=[("eba_BT:x28", "Yes"), ("eba_BT:x29", "No")],
                help_text="Existence of an exit plan",
                max_length=20,
                verbose_name="Exit plan",
            ),
        ),
        migrations.AddField(
            model_name="solution",
            name="dora_non_substitutability_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("eba_ZZ:x963", "Lack of real alternatives"),
                    ("eba_ZZ:x964", "Difficulties in migrating or reintegrating"),
                    (
                        "eba_ZZ:x965",
                        "Lack of real alternatives and difficulties in migrating or reintegrating",
                    ),
                ],
                help_text="Reason if the ICT third-party service provider is considered not substitutable or difficult to be substitutable",
                max_length=20,
                verbose_name="Non-substitutability reason",
            ),
        ),
        migrations.AddField(
            model_name="solution",
            name="dora_reintegration_possibility",
            field=models.CharField(
                blank=True,
                choices=[
                    ("eba_ZZ:x798", "Easy"),
                    ("eba_ZZ:x966", "Difficult"),
                    ("eba_ZZ:x967", "Highly complex"),
                ],
                help_text="Possibility of reintegration of the contracted ICT service",
                max_length=20,
                verbose_name="Reintegration possibility",
            ),
        ),
        migrations.AddField(
            model_name="solution",
            name="dora_substitutability",
            field=models.CharField(
                blank=True,
                choices=[
                    ("eba_ZZ:x959", "Not substitutable"),
                    ("eba_ZZ:x962", "Easily substitutable"),
                    ("eba_ZZ:x961", "Medium complexity in terms of substitutability"),
                    ("eba_ZZ:x960", "Highly complex substitutability"),
                ],
                help_text="Substitutability of the ICT third-party service provider",
                max_length=20,
                verbose_name="Substitutability",
            ),
        ),
    ]
