# Generated by Django 5.2.9 on 2026-01-09 15:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0131_alter_complianceassessment_authors_and_more"),
        ("tprm", "0011_remove_contract_new_owner_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entityassessment",
            name="authors",
            field=models.ManyToManyField(
                blank=True,
                related_name="%(class)s_authors",
                to="core.actor",
                verbose_name="Authors",
            ),
        ),
        migrations.AlterField(
            model_name="entityassessment",
            name="reviewers",
            field=models.ManyToManyField(
                blank=True,
                related_name="%(class)s_reviewers",
                to="core.actor",
                verbose_name="Reviewers",
            ),
        ),
    ]
