# Generated by Django 5.1.1 on 2026-01-30

from django.db import migrations


def rename_enclaves_to_entity_name(apps, schema_editor):
    """
    Rename existing enclaves from {perimeter.name}/{assessment.name}
    to {entity.name}/{assessment.name} for consistency.
    """
    EntityAssessment = apps.get_model("tprm", "EntityAssessment")

    for assessment in EntityAssessment.objects.filter(
        compliance_assessment__isnull=False
    ).select_related("compliance_assessment__folder", "entity"):
        enclave = assessment.compliance_assessment.folder
        if enclave and enclave.content_type == "EN":  # ENCLAVE
            new_name = f"{assessment.entity.name}/{assessment.name}"
            if enclave.name != new_name:
                enclave.name = new_name
                enclave.save(update_fields=["name"])


class Migration(migrations.Migration):
    dependencies = [
        ("tprm", "0012_alter_entityassessment_perimeter"),
    ]

    operations = [
        migrations.RunPython(rename_enclaves_to_entity_name, migrations.RunPython.noop),
    ]
