# Generated by Django 5.2.7 on 2025-11-12 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tprm", "0012_solution_dora_alternative_providers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="beneficiary_entity",
            field=models.ForeignKey(
                blank=True,
                help_text="Entity benefiting from/receiving this contract",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="beneficiary_contracts",
                to="tprm.entity",
                verbose_name="Beneficiary entity",
            ),
        ),
    ]
