# Generated by Django 6.0.2 on 2026-02-25 12:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tprm", "0013_rename_enclaves_to_entity_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solution",
            name="dora_alternative_providers_identified",
            field=models.CharField(
                blank=True,
                choices=[
                    ("eba_BT:x28", "Yes"),
                    ("eba_BT:x29", "No"),
                    ("eba_BT:x21", "Assessment not performed"),
                ],
                help_text="Are there alternative ICT third-party service providers identified?",
                max_length=20,
                verbose_name="Alternative providers identified",
            ),
        ),
    ]
