# Generated by Django 5.2.7 on 2025-11-12 19:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0114_remove_asset_is_critical_and_more"),
        ("tprm", "0013_contract_beneficiary_entity"),
    ]

    operations = [
        migrations.AddField(
            model_name="entity",
            name="filtering_labels",
            field=models.ManyToManyField(
                blank=True, to="core.filteringlabel", verbose_name="Labels"
            ),
        ),
        migrations.AddField(
            model_name="entity",
            name="ref_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="representative",
            name="filtering_labels",
            field=models.ManyToManyField(
                blank=True, to="core.filteringlabel", verbose_name="Labels"
            ),
        ),
        migrations.AddField(
            model_name="representative",
            name="ref_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="solution",
            name="filtering_labels",
            field=models.ManyToManyField(
                blank=True, to="core.filteringlabel", verbose_name="Labels"
            ),
        ),
    ]
