# Generated by Django 6.0.3 on 2026-03-12 19:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tprm", "0014_alter_solution_dora_alternative_providers_identified"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="dora_exclude",
            field=models.BooleanField(
                default=False,
                help_text="Exclude this contract from DORA RoI reporting",
                verbose_name="Exclude from DORA",
            ),
        ),
        migrations.AlterField(
            model_name="solution",
            name="dora_reintegration_possibility",
            field=models.CharField(
                blank=True,
                choices=[
                    ("eba_ZZ:x798", "Easy"),
                    ("eba_ZZ:x966", "Difficult"),
                    ("eba_ZZ:x967", "Highly complex"),
                    ("eba_ZZ:x0", "Not applicable"),
                ],
                help_text="Possibility of reintegration of the contracted ICT service",
                max_length=20,
                verbose_name="Reintegration possibility",
            ),
        ),
    ]
