# Generated by Django 5.2.7 on 2025-11-12 20:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tprm", "0014_entity_filtering_labels_entity_ref_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="entity",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is active"),
        ),
        migrations.AddField(
            model_name="solution",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is active"),
        ),
        migrations.AddField(
            model_name="solution",
            name="reference_link",
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
    ]
