# Generated by Django 6.0.3 on 2026-04-14 16:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tprm", "0015_contract_dora_exclude_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SolutionSubcontractor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        blank=True,
                        help_text="Entity that sub-contracted to this subcontractor. Leave empty when the direct provider is the parent.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subcontract_recipients",
                        to="tprm.entity",
                        verbose_name="Recipient",
                    ),
                ),
                (
                    "solution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcontracting_chain",
                        to="tprm.solution",
                        verbose_name="Solution",
                    ),
                ),
                (
                    "subcontractor",
                    models.ForeignKey(
                        help_text="Entity providing the sub-contracted ICT service",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subcontracts",
                        to="tprm.entity",
                        verbose_name="Subcontractor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Solution subcontractor",
                "verbose_name_plural": "Solution subcontractors",
                "ordering": ["created_at"],
                "unique_together": {("solution", "subcontractor")},
            },
        ),
    ]
