# Generated by Django 5.2.7 on 2025-11-12 22:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tprm", "0015_entity_is_active_solution_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="entity",
            name="default_dependency",
            field=models.PositiveSmallIntegerField(
                blank=True,
                default=0,
                help_text="Default dependency level for stakeholder assessment (0-4)",
                validators=[django.core.validators.MaxValueValidator(4)],
                verbose_name="Default dependency",
            ),
        ),
        migrations.AddField(
            model_name="entity",
            name="default_maturity",
            field=models.PositiveSmallIntegerField(
                blank=True,
                default=1,
                help_text="Default maturity level for stakeholder assessment (1-4)",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(4),
                ],
                verbose_name="Default maturity",
            ),
        ),
        migrations.AddField(
            model_name="entity",
            name="default_penetration",
            field=models.PositiveSmallIntegerField(
                blank=True,
                default=0,
                help_text="Default penetration level for stakeholder assessment (0-4)",
                validators=[django.core.validators.MaxValueValidator(4)],
                verbose_name="Default penetration",
            ),
        ),
        migrations.AddField(
            model_name="entity",
            name="default_trust",
            field=models.PositiveSmallIntegerField(
                blank=True,
                default=1,
                help_text="Default trust level for stakeholder assessment (1-4)",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(4),
                ],
                verbose_name="Default trust",
            ),
        ),
    ]
