# Generated by Django 6.0.3 on 2026-04-17 16:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tprm", "0016_solutionsubcontractor"),
    ]

    operations = [
        migrations.AddField(
            model_name="entityassessment",
            name="reference_link",
            field=models.URLField(
                blank=True, max_length=2048, null=True, verbose_name="Reference link"
            ),
        ),
    ]
