# Generated by Django 6.0.3 on 2026-04-14 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tprm", "0016_solutionsubcontractor"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="solutionsubcontractor",
            unique_together={("solution", "subcontractor")},
        ),
        migrations.AddField(
            model_name="solutionsubcontractor",
            name="recipient",
            field=models.ForeignKey(
                blank=True,
                help_text="Entity that sub-contracted to this subcontractor. Leave empty for rank-2 entries — defaults to the solution's direct provider.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subcontract_recipients",
                to="tprm.entity",
                verbose_name="Recipient",
            ),
        ),
        migrations.AlterField(
            model_name="solutionsubcontractor",
            name="rank",
            field=models.PositiveSmallIntegerField(
                help_text="Depth in the subcontracting tree (2 = direct subcontractor, 3 = sub-subcontractor, ...)",
                verbose_name="Rank",
            ),
        ),
    ]
