# Generated by Django 6.0.3 on 2026-04-14 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tprm", "0017_alter_solutionsubcontractor_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="solutionsubcontractor",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Solution subcontractor",
                "verbose_name_plural": "Solution subcontractors",
            },
        ),
        migrations.RemoveField(
            model_name="solutionsubcontractor",
            name="rank",
        ),
        migrations.AlterField(
            model_name="solutionsubcontractor",
            name="recipient",
            field=models.ForeignKey(
                blank=True,
                help_text="Entity that sub-contracted to this subcontractor. Leave empty when the direct provider is the parent.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subcontract_recipients",
                to="tprm.entity",
                verbose_name="Recipient",
            ),
        ),
    ]
