# Generated by Django 6.0.8 on 2026-08-17 14:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tprm", "0018_assign_third_parties_to_audits"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contract",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="entity",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="entityassessment",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="representative",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="solution",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="solutionsubcontractor",
            name="is_published",
        ),
    ]
