# Generated by Django 6.0.6 on 2026-07-16 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tprm', '0018_assign_third_parties_to_audits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='reference_link',
            field=models.URLField(blank=True, max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='entityassessment',
            name='reference_link',
            field=models.URLField(blank=True, max_length=4096, null=True, verbose_name='Reference link'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='reference_link',
            field=models.URLField(blank=True, max_length=4096, null=True),
        ),
    ]
