# Generated by Django 6.0.8 on 2026-08-30 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0186_campaign_entities_campaign_target_scope'),
        ('iam', '0027_cleanup_stray_domain_iam_groups'),
        ('tprm', '0019_null_perimeter_on_enclave_audits'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='default_assignee',
            field=models.ManyToManyField(blank=True, related_name='entity_default_assignee', to='core.actor', verbose_name='Default assignee'),
        ),
        migrations.AddField(
            model_name='entity',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Is main'),
        ),
        migrations.AddField(
            model_name='entity',
            name='scope',
            field=models.CharField(choices=[('internal', 'Internal'), ('external', 'External')], default='external', max_length=10, verbose_name='Scope'),
        ),
        migrations.AddConstraint(
            model_name='entity',
            constraint=models.UniqueConstraint(condition=models.Q(('is_main', True)), fields=('is_main',), name='unique_main_entity'),
        ),
    ]
