# Generated by Django 6.0.8 on 2026-08-31 18:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0186_commitment_remove_comment_comment_exactly_one_parent_and_more"),
        ("iam", "0027_cleanup_stray_domain_iam_groups"),
        ("tprm", "0020_entityscore"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="entityscore",
            constraint=models.UniqueConstraint(
                fields=("entity", "provider", "as_of"),
                name="unique_entity_score_per_provider_and_date",
            ),
        ),
    ]
