# Generated by Django 6.0.8 on 2026-09-02 21:10

import django.core.validators
import django.db.models.deletion
import iam.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0186_commitment_remove_comment_comment_exactly_one_parent_and_more"),
        ("iam", "0028_idpgroup_source_user_is_jit_provisioned"),
        ("tprm", "0020_normalize_entity_workspaces"),
    ]

    operations = [
        migrations.CreateModel(
            name="EntityScore",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
                (
                    "score",
                    models.FloatField(
                        help_text="Value as published by the provider",
                        verbose_name="Score",
                    ),
                ),
                (
                    "scale_max",
                    models.FloatField(
                        default=100,
                        help_text="Top of the provider's scale, so scores can be compared",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Scale maximum",
                    ),
                ),
                (
                    "grade",
                    models.CharField(
                        blank=True,
                        help_text="Letter rating, when the provider publishes one (A, B+, ...)",
                        max_length=8,
                        verbose_name="Grade",
                    ),
                ),
                (
                    "as_of",
                    models.DateField(
                        help_text="Date the provider published this score",
                        verbose_name="As of",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="Link to the report on the provider's platform",
                        max_length=2048,
                        verbose_name="Link",
                    ),
                ),
                (
                    "observation",
                    models.TextField(blank=True, null=True, verbose_name="Observation"),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="tprm.entity",
                        verbose_name="Entity",
                    ),
                ),
                (
                    "filtering_labels",
                    models.ManyToManyField(
                        blank=True, to="core.filteringlabel", verbose_name="Labels"
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        default=iam.models.Folder.get_root_folder_id,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_folder",
                        to="iam.folder",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        help_text="Service that published this score",
                        limit_choices_to={
                            "field_path": "entity_score.provider",
                            "is_visible": True,
                        },
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entity_scores",
                        to="core.terminology",
                        verbose_name="Provider",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entity score",
                "verbose_name_plural": "Entity scores",
                "ordering": ["-as_of"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("entity", "provider", "as_of"),
                        name="unique_entity_score_per_provider_and_date",
                    )
                ],
            },
        ),
    ]
