# Generated by Django 6.1.1 on 2026-09-05 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tprm", "0021_entityscore"),
    ]

    operations = [
        migrations.AddField(
            model_name="entity",
            name="address",
            field=models.TextField(
                blank=True,
                help_text="Postal address, as it should appear on formal documents",
                verbose_name="Address",
            ),
        ),
        migrations.AddField(
            model_name="entityassessment",
            name="expiry_date",
            field=models.DateField(
                blank=True,
                help_text="Date after which the conclusion is no longer considered valid",
                null=True,
                verbose_name="Expiry date",
            ),
        ),
    ]
