# Generated by Django 6.0.8 on 2026-08-17 14:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        # 0021 (findings epic, merged from main) creates EntityScore WITH is_published,
        # since it was generated while AbstractBaseModel still carried the field;
        # this migration must run after it to drop that column too.
        ("tprm", "0022_entity_address_entityassessment_expiry_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="entityscore",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="contract",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="entity",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="entityassessment",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="representative",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="solution",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="solutionsubcontractor",
            name="is_published",
        ),
    ]
