# Generated by Django 6.1.1 on 2026-10-03 09:46

import django.db.models.deletion
import iam.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0192_quick_form_tiering"),
        ("iam", "0031_remove_iam_is_published_fields"),
        ("tprm", "0023_remove_contract_is_published_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="entity",
            name="tier_response",
            field=models.ForeignKey(
                blank=True,
                help_text="The accepted response the current tier came from",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="core.quickformresponse",
                verbose_name="Tier assessment",
            ),
        ),
        migrations.AddField(
            model_name="entity",
            name="tier_set_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Tier set at"
            ),
        ),
        migrations.AddField(
            model_name="entity",
            name="tier_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("assessment", "Assessment"),
                    ("override", "Override"),
                    ("manual", "Manual"),
                ],
                default="",
                max_length=20,
                verbose_name="Tier source",
            ),
        ),
        migrations.AddField(
            model_name="entity",
            name="tier_value",
            field=models.FloatField(blank=True, null=True, verbose_name="Tier value"),
        ),
        migrations.CreateModel(
            name="Tier",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                ("rank", models.PositiveIntegerField(unique=True, verbose_name="Rank")),
                (
                    "hexcolor",
                    models.CharField(
                        blank=True, default="", max_length=9, verbose_name="Color"
                    ),
                ),
                (
                    "builtin",
                    models.BooleanField(default=False, verbose_name="Built-in"),
                ),
                (
                    "is_visible",
                    models.BooleanField(default=True, verbose_name="Is visible"),
                ),
                (
                    "translations",
                    models.JSONField(
                        blank=True, default=dict, null=True, verbose_name="Translations"
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        default=iam.models.Folder.get_root_folder_id,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_folder",
                        to="iam.folder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tier",
                "verbose_name_plural": "Tiers",
                "ordering": ["-rank"],
            },
        ),
        migrations.CreateModel(
            name="EntityTierChange",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("assessment", "Assessment"),
                            ("override", "Override"),
                            ("manual", "Manual"),
                        ],
                        max_length=20,
                        verbose_name="Source",
                    ),
                ),
                (
                    "value",
                    models.FloatField(blank=True, null=True, verbose_name="Value"),
                ),
                ("note", models.TextField(blank=True, default="", verbose_name="Note")),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="entity_tier_changes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Changed by",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tier_changes",
                        to="tprm.entity",
                        verbose_name="Entity",
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        default=iam.models.Folder.get_root_folder_id,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_folder",
                        to="iam.folder",
                    ),
                ),
                (
                    "response",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.quickformresponse",
                        verbose_name="Assessment",
                    ),
                ),
                (
                    "previous_tier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tprm.tier",
                        verbose_name="Previous tier",
                    ),
                ),
                (
                    "tier",
                    models.ForeignKey(
                        blank=True,
                        help_text="Empty when the tier was cleared",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="changes",
                        to="tprm.tier",
                        verbose_name="Tier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entity tier change",
                "verbose_name_plural": "Entity tier changes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="entity",
            name="tier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="entities",
                to="tprm.tier",
                verbose_name="Tier",
            ),
        ),
    ]
