# Generated by Django 6.1.1 on 2026-10-03 09:46

import django.db.models.deletion
import iam.models
import uuid
from django.conf import settings
from django.db import migrations, models
from django.db.models import Max
from django.utils import timezone

# Tiers did not exist before this release: the scale is the default one.
BY_CRITICALITY = {4: "critical", 3: "important", 2: "standard", 1: "low-impact"}
DEFAULT_TIERS = [
    ("critical", 4, "#dc2626"),
    ("important", 3, "#ea580c"),
    ("standard", 2, "#ca8a04"),
    ("low-impact", 1, "#16a34a"),
]


def carry_over(apps, schema_editor):
    Folder = apps.get_model("iam", "Folder")
    Tier = apps.get_model("tprm", "Tier")
    Entity = apps.get_model("tprm", "Entity")
    EntityAssessment = apps.get_model("tprm", "EntityAssessment")
    EntityTierChange = apps.get_model("tprm", "EntityTierChange")
    Solution = apps.get_model("tprm", "Solution")

    highest = dict(
        EntityAssessment.objects.filter(criticality__in=BY_CRITICALITY)
        .values("entity")
        .annotate(top=Max("criticality"))
        .values_list("entity", "top")
    )
    solutions = Solution.objects.filter(criticality__in=BY_CRITICALITY)
    if not highest and not solutions.exists():
        return

    # Normally seeded at startup, which runs after migrations.
    root = Folder.objects.filter(content_type="GL").first()
    if root is None:
        return
    if not Tier.objects.exists():
        for key, rank, hexcolor in DEFAULT_TIERS:
            Tier.objects.create(
                name=key,
                key=key,
                rank=rank,
                hexcolor=hexcolor,
                builtin=True,
                folder=root,
            )
    tiers = {t.key: t for t in Tier.objects.filter(key__in=BY_CRITICALITY.values())}

    now = timezone.now()
    for entity in Entity.objects.filter(pk__in=highest, tier__isnull=True):
        criticality = highest[entity.pk]
        tier = tiers.get(BY_CRITICALITY[criticality])
        if tier is None:
            continue
        entity.tier = tier
        entity.tier_source = "manual"
        entity.tier_set_at = now
        entity.save(update_fields=["tier", "tier_source", "tier_set_at"])
        EntityTierChange.objects.create(
            entity=entity,
            tier=tier,
            source="manual",
            folder_id=entity.folder_id,
            note=f"Set from the highest previous criticality ({criticality})",
        )

    for criticality, key in BY_CRITICALITY.items():
        if key in tiers:
            solutions.filter(criticality=criticality, tier__isnull=True).update(
                tier=tiers[key]
            )


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0193_quick_form_tiering"),
        ("iam", "0031_remove_iam_is_published_fields"),
        ("tprm", "0023_remove_contract_is_published_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="entity",
            name="tier_response",
            field=models.ForeignKey(
                blank=True,
                help_text="The accepted response the current tier came from",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="core.quickformresponse",
                verbose_name="Tier assessment",
            ),
        ),
        migrations.AddField(
            model_name="entity",
            name="tier_set_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Tier set at"
            ),
        ),
        migrations.AddField(
            model_name="entity",
            name="tier_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("assessment", "Assessment"),
                    ("override", "Override"),
                    ("manual", "Manual"),
                ],
                default="",
                max_length=20,
                verbose_name="Tier source",
            ),
        ),
        migrations.AddField(
            model_name="entity",
            name="tier_value",
            field=models.FloatField(blank=True, null=True, verbose_name="Tier value"),
        ),
        migrations.CreateModel(
            name="Tier",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "key",
                    models.SlugField(max_length=100, unique=True, verbose_name="Key"),
                ),
                ("rank", models.PositiveIntegerField(unique=True, verbose_name="Rank")),
                (
                    "hexcolor",
                    models.CharField(
                        blank=True, default="", max_length=9, verbose_name="Color"
                    ),
                ),
                (
                    "builtin",
                    models.BooleanField(default=False, verbose_name="Built-in"),
                ),
                (
                    "is_visible",
                    models.BooleanField(default=True, verbose_name="Is visible"),
                ),
                (
                    "translations",
                    models.JSONField(
                        blank=True, default=dict, null=True, verbose_name="Translations"
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        default=iam.models.Folder.get_root_folder_id,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_folder",
                        to="iam.folder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tier",
                "verbose_name_plural": "Tiers",
                "ordering": ["-rank"],
            },
        ),
        migrations.CreateModel(
            name="EntityTierChange",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("assessment", "Assessment"),
                            ("override", "Override"),
                            ("manual", "Manual"),
                        ],
                        max_length=20,
                        verbose_name="Source",
                    ),
                ),
                (
                    "value",
                    models.FloatField(blank=True, null=True, verbose_name="Value"),
                ),
                ("note", models.TextField(blank=True, default="", verbose_name="Note")),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="entity_tier_changes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Changed by",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tier_changes",
                        to="tprm.entity",
                        verbose_name="Entity",
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        default=iam.models.Folder.get_root_folder_id,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_folder",
                        to="iam.folder",
                    ),
                ),
                (
                    "response",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.quickformresponse",
                        verbose_name="Assessment",
                    ),
                ),
                (
                    "previous_tier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tprm.tier",
                        verbose_name="Previous tier",
                    ),
                ),
                (
                    "tier",
                    models.ForeignKey(
                        blank=True,
                        help_text="Empty when the tier was cleared",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="changes",
                        to="tprm.tier",
                        verbose_name="Tier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entity tier change",
                "verbose_name_plural": "Entity tier changes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="entity",
            name="tier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="entities",
                to="tprm.tier",
                verbose_name="Tier",
            ),
        ),
        migrations.AddField(
            model_name="solution",
            name="tier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="solutions",
                to="tprm.tier",
                verbose_name="Tier",
            ),
        ),
        # The former 1-4 criticality of entity assessments and solutions, carried
        # over to the scale; the old columns are kept, untouched.
        migrations.RunPython(carry_over, migrations.RunPython.noop),
    ]
