# Generated by Django 6.1.1 on 2026-10-05 09:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0191_roto_target_objective_category"),
        ("tprm", "0023_remove_contract_is_published_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="entityassessment",
            name="filtering_labels",
            field=models.ManyToManyField(
                blank=True, to="core.filteringlabel", verbose_name="Labels"
            ),
        ),
    ]
