"""Friendly name generator: <adjective>-<animal>-<4digit>.

Used to give freshly-created records a memorable label when the user hasn't
provided one. Keeps the word lists small, neutral, and free of anything that
could read as judgmental or culturally awkward.

Pure-stdlib; no Django imports, so it's safe to use from any layer.
"""

from __future__ import annotations

import random
import secrets

ADJECTIVES = (
    "agile",
    "amber",
    "ancient",
    "azure",
    "balmy",
    "bold",
    "breezy",
    "brisk",
    "bright",
    "calm",
    "candid",
    "cheery",
    "clever",
    "cosmic",
    "cozy",
    "crimson",
    "crisp",
    "curious",
    "daring",
    "dazzling",
    "earnest",
    "eager",
    "easy",
    "fancy",
    "fearless",
    "feisty",
    "fluffy",
    "frosty",
    "gentle",
    "gleaming",
    "golden",
    "grand",
    "happy",
    "hazel",
    "honest",
    "humble",
    "jaunty",
    "jolly",
    "joyful",
    "keen",
    "kind",
    "lively",
    "lucid",
    "lucky",
    "merry",
    "mighty",
    "mindful",
    "misty",
    "neat",
    "nimble",
    "noble",
    "patient",
    "peaceful",
    "plucky",
    "polite",
    "proud",
    "quiet",
    "radiant",
    "rapid",
    "ready",
    "regal",
    "ruby",
    "rustic",
    "sapphire",
    "savvy",
    "scarlet",
    "serene",
    "sharp",
    "shiny",
    "silent",
    "silky",
    "silver",
    "sleek",
    "smiling",
    "snappy",
    "snowy",
    "spry",
    "steady",
    "stellar",
    "stoic",
    "sturdy",
    "sunny",
    "swift",
    "tame",
    "tidy",
    "tranquil",
    "trusty",
    "valiant",
    "verdant",
    "vibrant",
    "vivid",
    "warm",
    "whimsical",
    "wise",
    "zesty",
)

ANIMALS = (
    "antelope",
    "badger",
    "bear",
    "beaver",
    "bee",
    "bison",
    "bobcat",
    "buffalo",
    "camel",
    "capybara",
    "cardinal",
    "caribou",
    "cheetah",
    "chinchilla",
    "cobra",
    "coyote",
    "crane",
    "deer",
    "dolphin",
    "donkey",
    "dove",
    "dragon",
    "eagle",
    "elk",
    "falcon",
    "ferret",
    "finch",
    "flamingo",
    "fox",
    "frog",
    "gecko",
    "giraffe",
    "goose",
    "gull",
    "hare",
    "hawk",
    "hedgehog",
    "heron",
    "horse",
    "ibex",
    "ibis",
    "iguana",
    "jackal",
    "jaguar",
    "jay",
    "kangaroo",
    "kestrel",
    "koala",
    "kookaburra",
    "lemur",
    "leopard",
    "lion",
    "llama",
    "lynx",
    "macaw",
    "magpie",
    "manatee",
    "marmot",
    "meerkat",
    "mole",
    "moose",
    "newt",
    "ocelot",
    "octopus",
    "okapi",
    "orca",
    "osprey",
    "otter",
    "owl",
    "panda",
    "panther",
    "parrot",
    "pelican",
    "penguin",
    "platypus",
    "puffin",
    "puma",
    "quail",
    "rabbit",
    "raccoon",
    "raven",
    "robin",
    "salamander",
    "seal",
    "shrew",
    "skylark",
    "sloth",
    "snail",
    "sparrow",
    "squirrel",
    "starling",
    "stork",
    "swan",
    "tapir",
    "tiger",
    "toucan",
    "turtle",
    "vicuna",
    "viper",
    "walrus",
    "weasel",
    "whale",
    "wolf",
    "wombat",
    "yak",
    "zebra",
)


def generate_friendly_name(rng: random.Random | None = None) -> str:
    """Return a name like ``serene-fox-4271``.

    Roughly 95 × 105 × 9000 ≈ 90M combinations; collisions are rare for typical
    use but not impossible — callers that need uniqueness should retry or pair
    with their own UUID. Uses :mod:`secrets` for the digits so the suffix isn't
    predictable from a seed; pass ``rng`` to make the word selection
    deterministic for tests.
    """
    chooser = rng or random
    adjective = chooser.choice(ADJECTIVES)
    animal = chooser.choice(ANIMALS)
    suffix = secrets.randbelow(9000) + 1000  # 1000..9999, never starts with 0
    return f"{adjective}-{animal}-{suffix}"
