# Generated by Django 6.1.1 on 2026-09-20 08:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="recipient_count",
            field=models.PositiveIntegerField(default=1, verbose_name="Recipients"),
        ),
    ]
