# Generated by Django 6.1.1 on 2026-09-19 18:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="context",
            field=models.JSONField(blank=True, default=dict, verbose_name="Context"),
        ),
    ]
