# Generated by Django 6.1.1 on 2026-09-19 19:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0002_notification_context"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="title",
        ),
    ]
