# Generated by Django 6.1.1 on 2026-09-19 20:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0003_remove_notification_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="folder",
        ),
    ]
