# Generated by Django 6.1.1 on 2026-09-20 05:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0004_remove_notification_folder"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="read_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Read at"),
        ),
    ]
