engine-strict: true

allowBuilds:
  '@tailwindcss/oxide': true
  esbuild: true
  maplibre-gl: true

overrides:
  esbuild: ^0.27.3
  devalue: ^5.8.1
  glob: ^10.5.0
  valibot: ^1.2.0
  validator: ^13.15.22
  js-yaml: ^4.1.1
  '@eslint/plugin-kit': ^0.5.1
  cookie: ^1.1.1
  tar: ^7.5.11
  lodash: ^4.18.1
  lodash-es: ^4.18.1
  minimatch: ^10.2.3
  ajv: ^6.14.0
  rollup: ^4.59.0
  flatted: ^3.4.2
  kysely: ^0.28.17
  effect: ^3.21.0
  picomatch: ^4.0.4
  yaml: ^1.10.3
  brace-expansion: ^5.0.5
  postcss: ^8.5.10
