# Generated by Django 6.0.6 on 2026-07-09 09:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicdocument",
            name="filename",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
