# Generated by Django 6.0.6 on 2026-06-25 18:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="frameworksnapshot",
            name="display_mode",
            field=models.CharField(
                choices=[
                    ("both", "Score and result"),
                    ("score", "Score only"),
                    ("result", "Result only"),
                ],
                default="both",
                max_length=10,
            ),
        ),
    ]
