# Generated by Django 6.0.8 on 2026-08-17 14:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("portals", "0002_publicdocument_filename"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="frameworksnapshot",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="portal",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="portalpreset",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="publicdocument",
            name="is_published",
        ),
    ]
