# Generated by Django 6.1.1 on 2026-09-13 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0188_quickformpublication_quickformresponse_and_more"),
        ("portals", "0003_remove_frameworksnapshot_is_published_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="portalpreset",
            name="default_locale",
            field=models.BooleanField(default=True, verbose_name="Default locale"),
        ),
        migrations.AddField(
            model_name="portalpreset",
            name="library",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="portal_presets",
                to="core.loadedlibrary",
                verbose_name="Library",
            ),
        ),
        migrations.AddField(
            model_name="portalpreset",
            name="locale",
            field=models.CharField(default="en", max_length=100, verbose_name="Locale"),
        ),
    ]
