# Generated by Django 6.1.1 on 2026-09-13 08:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portals", "0003_remove_frameworksnapshot_is_published_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="portalpreset",
            name="urn",
        ),
        migrations.AddField(
            model_name="portalpreset",
            name="source_urn",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="portalpreset",
            name="source_version",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
