# Generated by Django 4.2 on 2023-05-03 08:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('version', models.CharField(blank=True, default='0.1', max_length=100, null=True, verbose_name='Version')),
                ('is_draft', models.BooleanField(default=True, verbose_name='is a draft')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Analysis',
                'verbose_name_plural': 'Analyses',
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('business_value', models.CharField(blank=True, max_length=200, verbose_name='business value')),
                ('type', models.CharField(choices=[('PR', 'Primary'), ('SP', 'Support')], default='SP', max_length=2, verbose_name='type')),
                ('is_published', models.BooleanField(default=True, verbose_name='published')),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('internal_reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='Internal reference')),
                ('lc_status', models.CharField(choices=[('undefined', '--'), ('in_design', 'Design'), ('in_dev', 'Development'), ('in_prod', 'Production'), ('eol', 'End Of Life'), ('dropped', 'Dropped')], default='in_design', max_length=20, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='RiskAcceptance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('state', models.CharField(choices=[('created', 'Created'), ('submitted', 'Submitted'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('revoked', 'Revoked')], default='created', max_length=20, verbose_name='State')),
                ('expiry_date', models.DateField(help_text='Specify when the risk acceptance will no longer apply', null=True, verbose_name='Expiry date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('accepted_date', models.DateTimeField(blank=True, null=True, verbose_name='Acceptance date')),
                ('rejected_date', models.DateTimeField(blank=True, null=True, verbose_name='Rejection date')),
                ('revoked_date', models.DateTimeField(blank=True, null=True, verbose_name='Revocation date')),
                ('comments', models.CharField(blank=True, max_length=500, null=True, verbose_name='Comments')),
            ],
            options={
                'verbose_name': 'Risk acceptance',
                'verbose_name_plural': 'Risk acceptances',
                'permissions': [('validate_riskacceptance', 'Can validate/rejected risk acceptances')],
            },
        ),
        migrations.CreateModel(
            name='RiskMatrix',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('json_definition', models.JSONField(default=dict, help_text='JSON definition of the matrix.         See the documentation for more information.', verbose_name='JSON definition')),
                ('is_enabled', models.BooleanField(default=True, help_text='If the matrix is set as disabled, it will not be available for selection for new risk analyses.', verbose_name='enabled')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RiskScenario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('existing_measures', models.TextField(blank=True, help_text='The existing security measures to manage this risk. Edit the risk scenario to add extra security measures.', max_length=2000, verbose_name='Existing measures')),
                ('current_proba', models.SmallIntegerField(default=-1, verbose_name='Current probability')),
                ('current_impact', models.SmallIntegerField(default=-1, verbose_name='Current impact')),
                ('current_level', models.SmallIntegerField(default=-1, help_text='The risk level given the current measures. Automatically updated on Save, based on the chosen matrix', verbose_name='Current level')),
                ('residual_proba', models.SmallIntegerField(default=-1, verbose_name='Residual probability')),
                ('residual_impact', models.SmallIntegerField(default=-1, verbose_name='Residual impact')),
                ('residual_level', models.SmallIntegerField(default=-1, help_text='The risk level when all the extra measures are done. Automatically updated on Save, based on the chosen matrix', verbose_name='Residual level')),
                ('treatment', models.CharField(choices=[('open', 'Open'), ('mitigated', 'Mitigated'), ('accepted', 'Accepted'), ('blocker', 'Show-stopper'), ('transferred', 'Transferred')], default='open', max_length=20, verbose_name='Treatment status')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('comments', models.CharField(blank=True, max_length=500, null=True, verbose_name='Comments')),
            ],
            options={
                'verbose_name': 'Risk scenario',
                'verbose_name_plural': 'Risk scenarios',
            },
        ),
        migrations.CreateModel(
            name='SecurityFunction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('provider', models.CharField(blank=True, max_length=200, null=True, verbose_name='Provider')),
                ('is_published', models.BooleanField(default=True, verbose_name='published')),
            ],
            options={
                'verbose_name': 'Security function',
                'verbose_name_plural': 'Security functions',
            },
        ),
        migrations.CreateModel(
            name='SecurityMeasure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('type', models.CharField(choices=[('n/a', 'N/A'), ('technical', 'Technical'), ('organizational', 'Organizational')], default='n/a', max_length=20, verbose_name='Type')),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In progress'), ('on_hold', 'On hold'), ('done', 'Done')], default='open', max_length=20, verbose_name='Status')),
                ('eta', models.DateField(blank=True, help_text='Estimated Time of Arrival', null=True, verbose_name='ETA')),
                ('link', models.CharField(blank=True, help_text='External url for action follow-up (eg. Jira ticket)', max_length=1000, null=True, verbose_name='Link')),
                ('effort', models.CharField(blank=True, choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra-Large')], help_text='Relative effort of the measure (using T-Shirt sizing)', max_length=2, null=True, verbose_name='Effort')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Security measure',
                'verbose_name_plural': 'Security measures',
            },
        ),
        migrations.CreateModel(
            name='Threat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('provider', models.CharField(blank=True, max_length=200, null=True, verbose_name='Provider')),
                ('is_published', models.BooleanField(default=True, verbose_name='published')),
            ],
            options={
                'verbose_name': 'Threat',
                'verbose_name_plural': 'Threats',
            },
        ),
    ]
