# Generated by Django 4.2 on 2023-05-03 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import iam.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iam', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='threat',
            name='folder',
            field=models.ForeignKey(default=iam.models.Folder.get_root_folder, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_folder', to='iam.folder'),
        ),
        migrations.AddField(
            model_name='securitymeasure',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iam.folder', verbose_name='Domain'),
        ),
        migrations.AddField(
            model_name='securitymeasure',
            name='security_function',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.securityfunction', verbose_name='Security Function'),
        ),
        migrations.AddField(
            model_name='securityfunction',
            name='folder',
            field=models.ForeignKey(default=iam.models.Folder.get_root_folder, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_folder', to='iam.folder'),
        ),
        migrations.AddField(
            model_name='riskscenario',
            name='analysis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.analysis', verbose_name='Analysis'),
        ),
        migrations.AddField(
            model_name='riskscenario',
            name='assets',
            field=models.ManyToManyField(blank=True, help_text='Assets impacted by the risk scenario', to='core.asset', verbose_name='Assets'),
        ),
        migrations.AddField(
            model_name='riskscenario',
            name='security_measures',
            field=models.ManyToManyField(blank=True, to='core.securitymeasure', verbose_name='Security measures'),
        ),
        migrations.AddField(
            model_name='riskscenario',
            name='threat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.threat', verbose_name='Threat'),
        ),
        migrations.AddField(
            model_name='riskmatrix',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_folder', to='iam.folder'),
        ),
        migrations.AddField(
            model_name='riskacceptance',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iam.folder', verbose_name='Domain'),
        ),
        migrations.AddField(
            model_name='riskacceptance',
            name='risk_scenarios',
            field=models.ManyToManyField(help_text='Select the risk scenarios to be accepted, attention they must be part of the chosen domain', to='core.riskscenario', verbose_name='Risk scenarios'),
        ),
        migrations.AddField(
            model_name='riskacceptance',
            name='validator',
            field=models.ForeignKey(blank=True, help_text='Risk owner and validator identity', max_length=200, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Validator'),
        ),
        migrations.AddField(
            model_name='project',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iam.folder', verbose_name='Domain'),
        ),
        migrations.AddField(
            model_name='asset',
            name='folder',
            field=models.ForeignKey(default=iam.models.Folder.get_root_folder, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_folder', to='iam.folder'),
        ),
        migrations.AddField(
            model_name='asset',
            name='parent_assets',
            field=models.ManyToManyField(blank=True, to='core.asset', verbose_name='parent assets'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='auditor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Auditor'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.project', verbose_name='Project'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='rating_matrix',
            field=models.ForeignKey(help_text='WARNING! After choosing it, you will not be able to change it', on_delete=django.db.models.deletion.PROTECT, to='core.riskmatrix', verbose_name='Rating matrix'),
        ),
    ]
