# Generated by Django 4.2 on 2023-07-04 22:37

from django.db import migrations, models
import django.db.models.deletion
import iam.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iam', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='threat',
            name='folder',
            field=models.ForeignKey(default=iam.models.Folder.get_root_folder, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_folder', to='iam.folder'),
        ),
        migrations.AddField(
            model_name='securitymeasure',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iam.folder', verbose_name='Domain'),
        ),
        migrations.AddField(
            model_name='securitymeasure',
            name='security_function',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.securityfunction', verbose_name='Security Function'),
        ),
        migrations.AddField(
            model_name='securityfunction',
            name='folder',
            field=models.ForeignKey(default=iam.models.Folder.get_root_folder, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_folder', to='iam.folder'),
        ),
        migrations.AddField(
            model_name='requirementlevel',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_folder', to='iam.folder'),
        ),
        migrations.AddField(
            model_name='requirementlevel',
            name='framework',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.framework', verbose_name='Framework'),
        ),
        migrations.AddField(
            model_name='requirementgroup',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_folder', to='iam.folder'),
        ),
        migrations.AddField(
            model_name='requirementgroup',
            name='framework',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.framework', verbose_name='Framework'),
        ),
        migrations.AddField(
            model_name='requirementassessment',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.assessment', verbose_name='Assessment'),
        ),
        migrations.AddField(
            model_name='requirementassessment',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_folder', to='iam.folder'),
        ),
        migrations.AddField(
            model_name='requirementassessment',
            name='requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.requirement', verbose_name='Requirement'),
        ),
        migrations.AddField(
            model_name='requirementassessment',
            name='security_measures',
            field=models.ManyToManyField(blank=True, related_name='requirement_assessments', to='core.securitymeasure', verbose_name='Security measures'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_folder', to='iam.folder'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='framework',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.framework', verbose_name='Framework'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='security_functions',
            field=models.ManyToManyField(blank=True, related_name='requirements', to='core.securityfunction', verbose_name='Security functions'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='threats',
            field=models.ManyToManyField(blank=True, related_name='requirements', to='core.threat', verbose_name='Threats'),
        ),
        migrations.AddField(
            model_name='project',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iam.folder', verbose_name='Domain'),
        ),
        migrations.AddField(
            model_name='framework',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_folder', to='iam.folder'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='folder',
            field=models.ForeignKey(default=iam.models.Folder.get_root_folder, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_folder', to='iam.folder'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='measure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.securitymeasure', verbose_name='Security measure'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='framework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.framework', verbose_name='Framework'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.project', verbose_name='Project'),
        ),
    ]
