# Generated by Django 3.2.13 on 2022-06-02 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_auto_20220602_1207'),
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mitigation',
            options={'verbose_name': 'Measure', 'verbose_name_plural': 'Measures'},
        ),
        migrations.AlterModelOptions(
            name='riskinstance',
            options={'verbose_name': 'Risk Scenario', 'verbose_name_plural': 'Risk Scenarios'},
        ),
        migrations.AlterField(
            model_name='mitigation',
            name='effort',
            field=models.CharField(blank=True, choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra-Large')], help_text='Relative effort of the measure (using T-Shirt sizing)', max_length=2, null=True, verbose_name='Effort'),
        ),
        migrations.AlterField(
            model_name='mitigation',
            name='risk_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.riskinstance', verbose_name='Risk scenario'),
        ),
        migrations.AlterField(
            model_name='mitigation',
            name='title',
            field=models.CharField(default='<short title for the measure>', max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='riskacceptance',
            name='risk_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.riskinstance', verbose_name='Risk scenario'),
        ),
        migrations.AlterField(
            model_name='riskinstance',
            name='existing_measures',
            field=models.TextField(default='<we have solution A and Process B to handle this>', help_text='The existing measures to manage this risk. Edit the risk scenario to add extra measures.', max_length=2000, verbose_name='Existing Measures'),
        ),
        migrations.AlterField(
            model_name='riskinstance',
            name='parent_risk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.parentrisk', verbose_name='Threat'),
        ),
        migrations.AlterField(
            model_name='riskinstance',
            name='residual_level',
            field=models.CharField(choices=[('VL', 'Very Low'), ('L', 'Low'), ('M', 'Medium'), ('H', 'High'), ('VH', 'Very High')], default='VL', help_text='The risk level when all the extra measures are done. Automatically updated on Save, based on the chosen matrix', max_length=2, verbose_name='Residual Level'),
        ),
        migrations.AlterField(
            model_name='riskinstance',
            name='title',
            field=models.CharField(default='<risk scenario short title>', max_length=200, verbose_name='Title'),
        ),
    ]
