# Generated by Django 3.2.13 on 2022-06-17 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_auto_20220617_1055'),
        ('core', '0003_auto_20220602_1207'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mitigation',
            options={'verbose_name': 'Security measure', 'verbose_name_plural': 'Security measures'},
        ),
        migrations.AlterModelOptions(
            name='riskacceptance',
            options={'verbose_name': 'Risk acceptance', 'verbose_name_plural': 'Risk acceptances'},
        ),
        migrations.AlterModelOptions(
            name='riskinstance',
            options={'verbose_name': 'Risk scenario', 'verbose_name_plural': 'Risk scenarios'},
        ),
        migrations.AddField(
            model_name='riskinstance',
            name='assets',
            field=models.ManyToManyField(to='general.Asset'),
        ),
        migrations.AlterField(
            model_name='mitigation',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In progress'), ('on_hold', 'On hold'), ('done', 'Done')], default='open', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='riskinstance',
            name='analysis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.analysis', verbose_name='Analysis'),
        ),
        migrations.AlterField(
            model_name='riskinstance',
            name='current_impact',
            field=models.CharField(choices=[('VL', 'Very low'), ('L', 'Low'), ('M', 'Medium'), ('H', 'High'), ('VH', 'Very high')], default='VL', max_length=2, verbose_name='Current impact'),
        ),
        migrations.AlterField(
            model_name='riskinstance',
            name='current_level',
            field=models.CharField(choices=[('VL', 'Very low'), ('L', 'Low'), ('M', 'Medium'), ('H', 'High'), ('VH', 'Very high')], default='VL', help_text='The risk level given the current measures. Automatically updated on Save, based on the chosen matrix', max_length=2, verbose_name='Current level'),
        ),
        migrations.AlterField(
            model_name='riskinstance',
            name='current_proba',
            field=models.CharField(choices=[('VL', 'Very low'), ('L', 'Low'), ('M', 'Medium'), ('H', 'High'), ('VH', 'Very high')], default='VL', max_length=2, verbose_name='Current probability'),
        ),
        migrations.AlterField(
            model_name='riskinstance',
            name='existing_measures',
            field=models.TextField(default='<we have solution A and Process B to handle this>', help_text='The existing security measures to manage this risk. Edit the risk scenario to add extra security measures.', max_length=2000, verbose_name='Existing measures'),
        ),
        migrations.AlterField(
            model_name='riskinstance',
            name='residual_impact',
            field=models.CharField(choices=[('VL', 'Very low'), ('L', 'Low'), ('M', 'Medium'), ('H', 'High'), ('VH', 'Very high')], default='VL', max_length=2, verbose_name='Residual impact'),
        ),
        migrations.AlterField(
            model_name='riskinstance',
            name='residual_level',
            field=models.CharField(choices=[('VL', 'Very low'), ('L', 'Low'), ('M', 'Medium'), ('H', 'High'), ('VH', 'Very high')], default='VL', help_text='The risk level when all the extra measures are done. Automatically updated on Save, based on the chosen matrix', max_length=2, verbose_name='Residual level'),
        ),
        migrations.AlterField(
            model_name='riskinstance',
            name='residual_proba',
            field=models.CharField(choices=[('VL', 'Very low'), ('L', 'Low'), ('M', 'Medium'), ('H', 'High'), ('VH', 'Very high')], default='VL', max_length=2, verbose_name='Residual probability'),
        ),
    ]
