# Generated by Django 4.2.1 on 2023-07-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirementassessment',
            name='comment',
        ),
        migrations.AddField(
            model_name='requirementassessment',
            name='conformity',
            field=models.CharField(choices=[('non_compliant_scheduled', 'Non-compliant - scheduled'), ('compliant', 'Compliant'), ('non_compliant_major', 'Non-compliant - major'), ('non_compliant_minor', 'Non-compliant - minor'), ('not_evaluated', 'Not evaluated')], default='not_evaluated', max_length=100, verbose_name='Conformity'),
        ),
        migrations.AddField(
            model_name='requirementassessment',
            name='observation',
            field=models.TextField(blank=True, null=True, verbose_name='Observation'),
        ),
        migrations.AlterField(
            model_name='requirementassessment',
            name='status',
            field=models.CharField(choices=[('N/A', '--'), ('in_progress', 'In progress'), ('done', 'Done')], default='N/A', max_length=100, verbose_name='Status'),
        ),
    ]
