# Generated by Django 4.2.1 on 2023-07-04 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_requirementassessment_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirementassessment',
            name='major',
            field=models.TextField(blank=True, null=True, verbose_name='Major'),
        ),
        migrations.AddField(
            model_name='requirementassessment',
            name='minor',
            field=models.TextField(blank=True, null=True, verbose_name='Minor'),
        ),
    ]
