# Generated by Django 4.2.1 on 2023-07-05 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_requirementassessment_major_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='securitymeasure',
            old_name='type',
            new_name='status',
        ),
    ]
