# Generated by Django 4.2.1 on 2023-07-05 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_type_securitymeasure_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requirementassessment',
            old_name='status',
            new_name='work_status',
        ),
        migrations.RemoveField(
            model_name='requirementassessment',
            name='conformity',
        ),
    ]
