# Generated by Django 4.2.1 on 2023-07-06 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_requirementassessment_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirementassessment',
            name='major',
        ),
        migrations.RemoveField(
            model_name='requirementassessment',
            name='minor',
        ),
        migrations.RemoveField(
            model_name='requirementassessment',
            name='observation',
        ),
        migrations.RemoveField(
            model_name='requirementassessment',
            name='work_status',
        ),
        migrations.AddField(
            model_name='requirementassessment',
            name='status',
            field=models.CharField(choices=[('to_do', 'To do'), ('in_progress', 'In progress'), ('non_compliant', 'Non compliant'), ('partially_compliant', 'Partially compliant'), ('compliant', 'Compliant'), ('not_applicable', 'Not applicable')], default='to_do', max_length=100, verbose_name='Status'),
        ),
    ]
