# Generated by Django 4.2.3 on 2023-07-19 11:03

import core.validators
from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_evidence_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='attachment',
            field=models.FileField(blank=True, help_text='File for evidence (eg. screenshot, log file, etc.)', null=True, upload_to='', validators=[core.validators.validate_file_size, core.validators.validate_file_name], verbose_name='File'),
        ),
        migrations.AddConstraint(
            model_name='securitymeasure',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='name_unique'),
        ),
    ]
