# Generated by Django 4.2.3 on 2023-07-27 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_evidence_attachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityfunction',
            name='version',
            field=models.CharField(blank=True, default='1.0', help_text='Version of the security function (eg. 1.0, 2.0, etc.)', max_length=100, null=True, verbose_name='Version'),
        ),
        migrations.AddField(
            model_name='threat',
            name='version',
            field=models.CharField(blank=True, default='1.0', help_text='Version of the threat (eg. 1.0, 2.0, etc.)', max_length=100, null=True, verbose_name='Version'),
        ),
        migrations.AlterField(
            model_name='securitymeasure',
            name='security_function',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.securityfunction', verbose_name='Security Function'),
        ),
    ]
