# Generated by Django 4.2.3 on 2023-08-02 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_securityfunction_version_threat_version_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evidence',
            name='ref_url',
        ),
    ]
