# Generated by Django 6.0.6 on 2026-07-09 13:49

import workflows.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflows", "0003_unique_webhook_secrets"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflow",
            name="webhook_secret",
            field=models.CharField(
                default=workflows.models.generate_webhook_secret,
                max_length=64,
                unique=True,
            ),
        ),
    ]
