# Generated by Django 6.0.6 on 2026-07-09 16:36

import django.db.models.deletion
import iam.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iam", "0023_alter_folder_content_type"),
        ("workflows", "0004_alter_workflow_webhook_secret"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflow",
            name="webhook_hmac_secret",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="workflowtoken",
            name="retry_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="workflowtoken",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("waiting", "Waiting"),
                    ("consumed", "Consumed"),
                    ("completed", "Completed"),
                    ("retrying", "Retrying"),
                    ("error", "Error"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="WorkflowSecret",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
                ("name", models.CharField(max_length=100)),
                ("encrypted_value", models.BinaryField()),
                (
                    "folder",
                    models.ForeignKey(
                        default=iam.models.Folder.get_root_folder_id,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_folder",
                        to="iam.folder",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("folder", "name"), name="unique_workflow_secret_name"
                    )
                ],
            },
        ),
    ]
