# Generated by Django 6.0.6 on 2026-07-16 15:12

import django.db.models.deletion
import iam.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iam", "0023_alter_folder_content_type"),
        ("workflows", "0005_workflow_webhook_hmac_secret_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflowinstance",
            name="trigger",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("webhook", "Webhook"),
                    ("subprocess", "Subprocess"),
                    ("scheduled", "Scheduled"),
                ],
                default="manual",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="WorkflowSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                ("cron_expression", models.CharField(max_length=100)),
                ("timezone", models.CharField(default="UTC", max_length=50)),
                ("enabled", models.BooleanField(default=True)),
                ("next_run_at", models.DateTimeField(blank=True, null=True)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_result",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("triggered", "Triggered"),
                            ("skipped_overlap", "Skipped (previous run still active)"),
                            ("skipped_unpublished", "Skipped (no published version)"),
                            ("error", "Error"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        default=iam.models.Folder.get_root_folder_id,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_folder",
                        to="iam.folder",
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="workflows.workflow",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AddField(
            model_name="workflowinstance",
            name="schedule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="instances",
                to="workflows.workflowschedule",
            ),
        ),
    ]
