# Generated by Django 6.0.6 on 2026-07-17 09:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflows", "0006_alter_workflowinstance_trigger_workflowschedule_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workflowsecret",
            name="encrypted_value",
        ),
        migrations.AddField(
            model_name="workflowsecret",
            name="value",
            field=models.TextField(default=""),
        ),
    ]
