# Generated by Django 6.0.6 on 2026-07-17 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflows", "0007_remove_workflowsecret_encrypted_value_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowinstance",
            name="node_outputs",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="workflownode",
            name="ref",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
