# Generated by Django 6.0.6 on 2026-07-21 08:22

import django.db.models.deletion
import iam.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iam", "0023_alter_folder_content_type"),
        ("workflows", "0008_workflowinstance_node_outputs_workflownode_ref"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowinstance",
            name="trigger_depth",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="workflowinstance",
            name="trigger",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("webhook", "Webhook"),
                    ("subprocess", "Subprocess"),
                    ("scheduled", "Scheduled"),
                    ("internal_event", "Internal event"),
                ],
                default="manual",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="WorkflowEventTrigger",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                ("event_key", models.CharField(db_index=True, max_length=200)),
                ("filters", models.JSONField(blank=True, default=dict)),
                ("enabled", models.BooleanField(default=True)),
                ("last_triggered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_result",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("triggered", "Triggered"),
                            ("skipped_unpublished", "Skipped (unpublished)"),
                            ("skipped_depth", "Skipped (chain depth)"),
                            ("error", "Error"),
                        ],
                        max_length=30,
                    ),
                ),
                ("trigger_count", models.PositiveIntegerField(default=0)),
                (
                    "folder",
                    models.ForeignKey(
                        default=iam.models.Folder.get_root_folder_id,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_folder",
                        to="iam.folder",
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_triggers",
                        to="workflows.workflow",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AddField(
            model_name="workflowinstance",
            name="event_trigger",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="instances",
                to="workflows.workfloweventtrigger",
            ),
        ),
    ]
