# Generated by Django 6.0.6 on 2026-07-22 13:17

import django.db.models.deletion
import iam.models
import uuid
import workflows.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iam", "0023_alter_folder_content_type"),
        ("workflows", "0009_workflowinstance_trigger_depth_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workflowinstance",
            name="event_trigger",
        ),
        migrations.RemoveField(
            model_name="workflowschedule",
            name="folder",
        ),
        migrations.RemoveField(
            model_name="workflowschedule",
            name="workflow",
        ),
        migrations.RemoveField(
            model_name="workflowinstance",
            name="schedule",
        ),
        migrations.RemoveField(
            model_name="workflow",
            name="webhook_hmac_secret",
        ),
        migrations.RemoveField(
            model_name="workflow",
            name="webhook_secret",
        ),
        migrations.AddField(
            model_name="workflownode",
            name="trigger_config",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="workflownode",
            name="type",
            field=models.CharField(
                choices=[
                    ("trigger", "Trigger"),
                    ("end", "End"),
                    ("task", "Task"),
                    ("condition", "Condition"),
                    ("action", "Action"),
                    ("subprocess", "Subprocess"),
                    ("event", "Event"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="WorkflowTrigger",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
                ("node_ref", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("webhook", "Webhook"),
                            ("schedule", "Schedule"),
                            ("internal_event", "Internal event"),
                        ],
                        max_length=20,
                    ),
                ),
                ("config", models.JSONField(blank=True, default=dict)),
                ("enabled", models.BooleanField(default=False)),
                (
                    "secret",
                    models.CharField(
                        default=workflows.models.generate_webhook_secret,
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("hmac_secret", models.CharField(blank=True, max_length=128)),
                ("next_run_at", models.DateTimeField(blank=True, null=True)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                (
                    "event_key",
                    models.CharField(blank=True, db_index=True, max_length=200),
                ),
                ("last_triggered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_result",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("triggered", "Triggered"),
                            ("skipped_overlap", "Skipped (previous run still active)"),
                            ("skipped_unpublished", "Skipped (unpublished)"),
                            ("skipped_depth", "Skipped (chain depth)"),
                            ("error", "Error"),
                        ],
                        max_length=30,
                    ),
                ),
                ("trigger_count", models.PositiveIntegerField(default=0)),
                (
                    "folder",
                    models.ForeignKey(
                        default=iam.models.Folder.get_root_folder_id,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_folder",
                        to="iam.folder",
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="triggers",
                        to="workflows.workflow",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AddField(
            model_name="workflowinstance",
            name="trigger_registration",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="instances",
                to="workflows.workflowtrigger",
            ),
        ),
        migrations.DeleteModel(
            name="WorkflowEventTrigger",
        ),
        migrations.DeleteModel(
            name="WorkflowSchedule",
        ),
        migrations.AddConstraint(
            model_name="workflowtrigger",
            constraint=models.UniqueConstraint(
                fields=("workflow", "node_ref"), name="unique_workflow_trigger_node_ref"
            ),
        ),
    ]
