# Generated by Django 6.0.7 on 2026-07-28 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0011_condition_branches'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='source_urn',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='workflow',
            name='source_version',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
