# Generated by Django 6.0.7 on 2026-07-29 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0013_workflowedge_source_port_workflownode_loop_config_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workflowedge',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveField(
            model_name='workflowedge',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='workflownode',
            name='fork_type',
        ),
        migrations.AlterField(
            model_name='workflowinstancelog',
            name='event_type',
            field=models.CharField(choices=[('instance_started', 'Instance started'), ('node_entered', 'Node entered'), ('action_executed', 'Action executed'), ('task_waiting', 'Waiting for task'), ('event_waiting', 'Waiting for event'), ('event_received', 'Event received'), ('join_arrival', 'Join arrival'), ('join_fired', 'Join fired'), ('subprocess_started', 'Subprocess started'), ('loop_completed', 'Loop completed'), ('instance_completed', 'Instance completed'), ('error', 'Error')], max_length=30),
        ),
        migrations.AlterField(
            model_name='workflownode',
            name='join_type',
            field=models.CharField(choices=[('none', 'None'), ('and', 'AND')], default='none', max_length=20),
        ),
    ]
