# Generated by Django 6.0.7 on 2026-07-29 13:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflows", "0014_alter_workflowedge_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workflownode",
            name="join_type",
        ),
        migrations.AlterField(
            model_name="workflowinstancelog",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("instance_started", "Instance started"),
                    ("node_entered", "Node entered"),
                    ("action_executed", "Action executed"),
                    ("task_waiting", "Waiting for task"),
                    ("event_waiting", "Waiting for event"),
                    ("event_received", "Event received"),
                    ("subprocess_started", "Subprocess started"),
                    ("loop_completed", "Loop completed"),
                    ("instance_completed", "Instance completed"),
                    ("error", "Error"),
                ],
                max_length=30,
            ),
        ),
    ]
