# Generated by Django 6.0.7 on 2026-08-03 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflows", "0017_workflow_is_active_workflowversion_is_active_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowversion",
            name="published_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="workflowversion",
            name="run_as",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="workflowinstancelog",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("instance_started", "Instance started"),
                    ("node_entered", "Node entered"),
                    ("action_executed", "Action executed"),
                    ("task_waiting", "Waiting for task"),
                    ("event_waiting", "Waiting for event"),
                    ("event_received", "Event received"),
                    ("subprocess_started", "Subprocess started"),
                    ("loop_completed", "Loop completed"),
                    ("authorization_denied", "Authorization denied"),
                    ("instance_completed", "Instance completed"),
                    ("error", "Error"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="workflowtrigger",
            name="last_result",
            field=models.CharField(
                blank=True,
                choices=[
                    ("triggered", "Triggered"),
                    ("skipped_overlap", "Skipped (previous run still active)"),
                    ("skipped_unpublished", "Skipped (unpublished)"),
                    ("skipped_depth", "Skipped (chain depth)"),
                    ("skipped_inactive", "Skipped (workflow inactive)"),
                    ("run_identity_missing", "Skipped (no run identity)"),
                    ("error", "Error"),
                ],
                max_length=30,
            ),
        ),
    ]
