# Generated by Django 6.0.7 on 2026-08-05 10:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "workflows",
            "0018_workflowversion_published_by_workflowversion_run_as_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflowinstancelog",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("instance_started", "Instance started"),
                    ("node_entered", "Node entered"),
                    ("action_executed", "Action executed"),
                    ("task_waiting", "Waiting for task"),
                    ("event_waiting", "Waiting for event"),
                    ("event_received", "Event received"),
                    ("subprocess_started", "Subprocess started"),
                    ("loop_completed", "Loop completed"),
                    ("authorization_denied", "Authorization denied"),
                    ("run_terminated", "Run terminated"),
                    ("instance_completed", "Instance completed"),
                    ("error", "Error"),
                ],
                max_length=30,
            ),
        ),
    ]
