# Generated by Django 6.0.7 on 2026-08-06 08:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflows", "0019_alter_workflowinstancelog_event_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflow",
            name="timeout_seconds",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="workflowversion",
            name="timeout_seconds",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
