# Generated by Django 6.0.4 on 2026-04-28 06:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="metrics",
            field=models.JSONField(
                blank=True,
                help_text="Token utilization snapshot for this turn (prompt/context/history/summary tokens, over_budget, high_watermark).",
                null=True,
                verbose_name="Turn metrics",
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="tool_observation",
            field=models.JSONField(
                blank=True,
                help_text="Captured read-only tool result (tool name, args, truncated text). Replayed in the next ~2 turns; not enforced beyond that window.",
                null=True,
                verbose_name="Tool observation",
            ),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="summary",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Compact summary of older exchanges that have fallen off the verbatim window. Updated incrementally one exchange at a time.",
                verbose_name="Rolling summary",
            ),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="summary_until_ts",
            field=models.DateTimeField(
                blank=True,
                help_text="Watermark — created_at of the most recent message folded into the rolling summary. Null = nothing folded yet.",
                null=True,
                verbose_name="Summarized up to",
            ),
        ),
    ]
