# Generated by Django 6.0.4 on 2026-04-30 19:11

import core.validators
import django.db.models.deletion
import iam.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_chatmessage_metrics_chatmessage_tool_observation_and_more"),
        ("iam", "0021_fix_auditee_iam_groups"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionnaireRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="Title"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="questionnaires/",
                        validators=[
                            core.validators.validate_file_size,
                            core.validators.validate_file_name,
                        ],
                        verbose_name="File",
                    ),
                ),
                ("filename", models.CharField(max_length=255, verbose_name="Filename")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("parsing", "Parsing"),
                            ("parsed", "Parsed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, default="", verbose_name="Error message"
                    ),
                ),
                (
                    "parsed_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="{sheets: [{name, header_row, headers, row_count, rows_preview}], active_sheet}. Populated by the parse task.",
                        verbose_name="Parsed data",
                    ),
                ),
                (
                    "column_mapping",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="{sheet, question_col, answer_col, comment_col, section_col}. Indices are 0-based positions inside that sheet's headers.",
                        verbose_name="Column mapping",
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        default=iam.models.Folder.get_root_folder_id,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_folder",
                        to="iam.folder",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questionnaire_runs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Questionnaire run",
                "verbose_name_plural": "Questionnaire runs",
                "ordering": ["-created_at"],
            },
        ),
    ]
