# Generated by Django 6.0.4 on 2026-04-30 20:10

import django.db.models.deletion
import iam.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_questionnairerun"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("iam", "0021_fix_auditee_iam_groups"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("questionnaire_prefill", "Questionnaire prefill")],
                        max_length=40,
                        verbose_name="Kind",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="queued",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "strictness",
                    models.CharField(
                        choices=[("fast", "Fast"), ("thorough", "Thorough")],
                        default="fast",
                        max_length=20,
                        verbose_name="Strictness",
                    ),
                ),
                (
                    "target_object_id",
                    models.UUIDField(
                        blank=True, null=True, verbose_name="Target object ID"
                    ),
                ),
                (
                    "total_steps",
                    models.IntegerField(default=0, verbose_name="Total steps"),
                ),
                (
                    "completed_steps",
                    models.IntegerField(default=0, verbose_name="Completed steps"),
                ),
                (
                    "current_step_label",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=300,
                        verbose_name="Current step label",
                    ),
                ),
                (
                    "last_heartbeat_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last heartbeat"
                    ),
                ),
                (
                    "total_tokens",
                    models.IntegerField(default=0, verbose_name="Total tokens"),
                ),
                (
                    "estimated_cost_usd",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=10,
                        verbose_name="Estimated cost (USD)",
                    ),
                ),
                (
                    "model_used",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="Model used",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Started at"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Finished at"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, default="", verbose_name="Error message"
                    ),
                ),
                (
                    "chat_session",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional — only set when the run uses chat (e.g. ask_user).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_runs",
                        to="chat.chatsession",
                        verbose_name="Chat session",
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        default=iam.models.Folder.get_root_folder_id,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_folder",
                        to="iam.folder",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_runs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner",
                    ),
                ),
                (
                    "target_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="contenttypes.contenttype",
                        verbose_name="Target content type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent run",
                "verbose_name_plural": "Agent runs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AgentAction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("retrieve", "Retrieve"),
                            ("propose_answer", "Propose answer"),
                            ("critique", "Critique"),
                            ("retry", "Retry"),
                        ],
                        max_length=30,
                        verbose_name="Kind",
                    ),
                ),
                (
                    "target_object_id",
                    models.UUIDField(
                        blank=True, null=True, verbose_name="Target object ID"
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Action result. For propose_answer: {status, comment}.",
                        verbose_name="Payload",
                    ),
                ),
                (
                    "rationale",
                    models.TextField(blank=True, default="", verbose_name="Rationale"),
                ),
                (
                    "source_refs",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="[{kind, id, name, score, snippet}]",
                        verbose_name="Source references",
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(blank=True, null=True, verbose_name="Confidence"),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("proposed", "Proposed"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                        ],
                        default="proposed",
                        max_length=20,
                        verbose_name="State",
                    ),
                ),
                ("iteration", models.IntegerField(default=0, verbose_name="Iteration")),
                ("tokens", models.IntegerField(default=0, verbose_name="Tokens")),
                (
                    "duration_ms",
                    models.IntegerField(default=0, verbose_name="Duration (ms)"),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Approved at"
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_actions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Approved by",
                    ),
                ),
                (
                    "target_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="contenttypes.contenttype",
                        verbose_name="Target content type",
                    ),
                ),
                (
                    "agent_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="chat.agentrun",
                        verbose_name="Agent run",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent action",
                "verbose_name_plural": "Agent actions",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="QuestionnaireQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
                (
                    "ord",
                    models.IntegerField(
                        help_text="0-based row index in the source sheet, used for export.",
                        verbose_name="Order",
                    ),
                ),
                (
                    "ref_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Reference ID",
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="Section"
                    ),
                ),
                ("text", models.TextField(verbose_name="Question text")),
                (
                    "questionnaire_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="chat.questionnairerun",
                        verbose_name="Questionnaire run",
                    ),
                ),
            ],
            options={
                "verbose_name": "Questionnaire question",
                "verbose_name_plural": "Questionnaire questions",
                "ordering": ["ord"],
                "unique_together": {("questionnaire_run", "ord")},
            },
        ),
    ]
