# Generated by Django 6.0.8 on 2026-08-17 14:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_agentrun_agentaction_questionnairerun_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agentaction",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="agentrun",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="chatsession",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="indexeddocument",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="questionnairequestion",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="questionnairerun",
            name="is_published",
        ),
    ]
