# Generated by Django 6.0.5 on 2026-05-17 07:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_agentrun_agentaction_questionnairerun_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentaction",
            name="kind",
            field=models.CharField(
                choices=[
                    ("retrieve", "Retrieve"),
                    ("propose_answer", "Propose answer"),
                    ("critique", "Critique"),
                    ("retry", "Retry"),
                    ("extract_control", "Extract control"),
                    ("link_control_existing", "Link existing control"),
                    ("propose_result", "Propose requirement result"),
                    ("link_evidence_control", "Link evidence to control"),
                ],
                max_length=30,
                verbose_name="Kind",
            ),
        ),
        migrations.AlterField(
            model_name="agentrun",
            name="kind",
            field=models.CharField(
                choices=[
                    ("questionnaire_prefill", "Questionnaire prefill"),
                    ("audit_prefill", "Audit prefill"),
                ],
                max_length=40,
                verbose_name="Kind",
            ),
        ),
    ]
