# Generated by Django 6.0.4 on 2026-05-01 05:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0004_agentrun_agentaction_questionnairequestion"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionnairerun",
            name="value_mapping",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="{yes, partial, no, needs_info, source} — maps internal status labels onto the customer's vocabulary, plus a 'source' tag ('data_validation' | 'distinct_values' | 'fallback'). Computed asynchronously after column mapping is saved; export uses it when present.",
                verbose_name="Value mapping",
            ),
        ),
    ]
