# Generated by Django 6.0.4 on 2026-05-01 18:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0005_questionnairerun_value_mapping"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionnairequestion",
            name="answer_candidates",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Controlled vocabulary the customer expects in this question's answer cell, captured from the Excel data-validation list (or distinct existing values). Empty list = free-text cell.",
                verbose_name="Answer candidates",
            ),
        ),
        migrations.AddField(
            model_name="questionnairequestion",
            name="answer_mapping",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="{yes, partial, no, source} mapping our internal status onto this question's vocabulary. Filled by suggest_value_mapping after extract; export uses it per-question (rather than the run-level value_mapping) so questionnaires with mixed vocabularies still produce a clean fill.",
                verbose_name="Answer mapping",
            ),
        ),
    ]
