# Generated by Django 5.2.9 on 2026-01-20 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pmbok", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="accreditation",
            name="new_author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="authored_accreditations",
                to="core.actor",
            ),
        ),
    ]
