# Generated by Django 5.2.7 on 2025-10-03 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pmbok", "0001_initial"),
        ("tprm", "0007_entity_relationship"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accreditation",
            name="authority",
            field=models.ForeignKey(
                blank=True,
                help_text="Accreditation authority entity",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="accreditation_authority",
                to="tprm.entity",
            ),
        ),
    ]
