# Generated by Django 5.2.9 on 2026-01-20 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0130_remove_organisationobjective_new_assigned_to_and_more"),
        ("pmbok", "0002_alter_accreditation_author"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accreditation",
            name="author",
        ),
        migrations.RenameField(
            model_name="accreditation",
            old_name="new_author",
            new_name="author",
        ),
    ]
