# Generated by Django 6.0.3 on 2026-03-19 07:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0149_alter_evidencerevision_attachment"),
        ("pmbok", "0003_remove_accreditation_new_author_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="accreditation",
            name="authority_name",
            field=models.CharField(
                blank=True,
                help_text="Free-text authority name, for authorities not registered as entities",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="accreditation",
            name="commission_date",
            field=models.DateField(
                blank=True,
                help_text="Date of the accreditation commission decision",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="accreditation",
            name="decision_evidence",
            field=models.ManyToManyField(
                blank=True,
                help_text="Evidence documents for the accreditation decision (e.g. minutes/PV)",
                related_name="accreditation_decisions",
                to="core.evidence",
            ),
        ),
        migrations.AddField(
            model_name="accreditation",
            name="duration_months",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Accreditation validity duration in months",
                null=True,
            ),
        ),
    ]
