# Generated by Django 6.0.5 on 2026-05-13 14:10

import django.db.models.deletion
import iam.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0168_consolidate_visibility_booleans"),
        ("iam", "0021_fix_auditee_iam_groups"),
        ("pmbok", "0004_accreditation_authority_name_and_more"),
        ("resilience", "0007_doraincidentreport"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResponsibilityMatrix",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                ("ref_id", models.CharField(blank=True, max_length=100)),
                (
                    "preset",
                    models.CharField(
                        choices=[
                            ("raci", "RACI"),
                            ("rasci", "RASCI"),
                            ("rapid", "RAPID"),
                            ("custom", "Custom"),
                        ],
                        default="raci",
                        max_length=20,
                    ),
                ),
                (
                    "filtering_labels",
                    models.ManyToManyField(
                        blank=True, to="core.filteringlabel", verbose_name="Labels"
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        default=iam.models.Folder.get_root_folder_id,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_folder",
                        to="iam.folder",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ResponsibilityMatrixActivity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
                ("name", models.CharField(max_length=500)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Markdown-formatted long-form description of this activity",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "applied_controls",
                    models.ManyToManyField(
                        blank=True,
                        related_name="responsibility_activities",
                        to="core.appliedcontrol",
                    ),
                ),
                (
                    "assets",
                    models.ManyToManyField(
                        blank=True,
                        related_name="responsibility_activities",
                        to="core.asset",
                    ),
                ),
                (
                    "business_impact_analyses",
                    models.ManyToManyField(
                        blank=True,
                        related_name="responsibility_activities",
                        to="resilience.businessimpactanalysis",
                    ),
                ),
                (
                    "compliance_assessments",
                    models.ManyToManyField(
                        blank=True,
                        related_name="responsibility_activities",
                        to="core.complianceassessment",
                    ),
                ),
                (
                    "findings_assessments",
                    models.ManyToManyField(
                        blank=True,
                        related_name="responsibility_activities",
                        to="core.findingsassessment",
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        default=iam.models.Folder.get_root_folder_id,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_folder",
                        to="iam.folder",
                    ),
                ),
                (
                    "matrix",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="pmbok.responsibilitymatrix",
                    ),
                ),
                (
                    "risk_assessments",
                    models.ManyToManyField(
                        blank=True,
                        related_name="responsibility_activities",
                        to="core.riskassessment",
                    ),
                ),
                (
                    "task_templates",
                    models.ManyToManyField(
                        blank=True,
                        related_name="responsibility_activities",
                        to="core.tasktemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ResponsibilityRole",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                ("is_published", models.BooleanField(default=True)),
                (
                    "code",
                    models.CharField(
                        help_text="Short letter shown in matrix cells (e.g. 'R', 'A', 'C', 'I')",
                        max_length=8,
                    ),
                ),
                ("color", models.CharField(blank=True, max_length=20)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "taxonomy",
                    models.CharField(
                        choices=[
                            ("raci", "RACI"),
                            ("rasci", "RASCI"),
                            ("rapid", "RAPID"),
                            ("custom", "Custom"),
                        ],
                        default="custom",
                        help_text="Which responsibility taxonomy this role belongs to",
                        max_length=20,
                    ),
                ),
                ("builtin", models.BooleanField(default=False)),
                ("is_visible", models.BooleanField(default=True)),
                ("translations", models.JSONField(blank=True, default=dict, null=True)),
                (
                    "folder",
                    models.ForeignKey(
                        default=iam.models.Folder.get_root_folder_id,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_folder",
                        to="iam.folder",
                    ),
                ),
            ],
            options={
                "ordering": ["taxonomy", "order", "code"],
            },
        ),
        migrations.AddField(
            model_name="responsibilitymatrix",
            name="roles",
            field=models.ManyToManyField(
                blank=True, related_name="matrices", to="pmbok.responsibilityrole"
            ),
        ),
        migrations.CreateModel(
            name="ResponsibilityMatrixActor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matrix_memberships",
                        to="core.actor",
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        default=iam.models.Folder.get_root_folder_id,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_folder",
                        to="iam.folder",
                    ),
                ),
                (
                    "matrix",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matrix_actors",
                        to="pmbok.responsibilitymatrix",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("matrix", "actor"), name="unique_matrix_actor"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ResponsibilityAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responsibility_assignments",
                        to="core.actor",
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        default=iam.models.Folder.get_root_folder_id,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_folder",
                        to="iam.folder",
                    ),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="pmbok.responsibilitymatrixactivity",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignments",
                        to="pmbok.responsibilityrole",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("activity", "actor"), name="unique_responsibility_cell"
                    )
                ],
            },
        ),
    ]
