# Generated by Django 6.0.5 on 2026-05-23 09:18

import django.core.validators
import django.db.models.deletion
import iam.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0170_alter_terminology_field_path"),
        ("iam", "0021_fix_auditee_iam_groups"),
        ("pmbok", "0005_responsibilitymatrix_responsibilitymatrixactivity_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("portfolio", "Portfolio"),
                            ("program", "Program"),
                            ("project", "Project"),
                        ],
                        default="project",
                        max_length=20,
                    ),
                ),
                ("ref_id", models.CharField(blank=True, max_length=100)),
                ("ref_link", models.URLField(blank=True)),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[(1, "P1"), (2, "P2"), (3, "P3"), (4, "P4")],
                        null=True,
                        verbose_name="Priority",
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("eta", models.DateField(blank=True, null=True)),
                ("closed_at", models.DateField(blank=True, null=True)),
                (
                    "progress",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("purpose", models.TextField(blank=True)),
                ("objectives", models.TextField(blank=True)),
                ("success_criteria", models.TextField(blank=True)),
                ("business_case", models.TextField(blank=True)),
                ("deliverables", models.TextField(blank=True)),
                ("assumptions", models.TextField(blank=True)),
                ("constraints", models.TextField(blank=True)),
                ("dependencies_note", models.TextField(blank=True)),
                ("exit_criteria", models.TextField(blank=True)),
                ("organizational_alignment", models.TextField(blank=True)),
                ("approval_requirements", models.TextField(blank=True)),
                (
                    "budget",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "actual_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("currency", models.CharField(blank=True, max_length=3)),
                ("tolerances", models.JSONField(blank=True, default=dict)),
                ("observation", models.TextField(blank=True, null=True)),
                (
                    "filtering_labels",
                    models.ManyToManyField(
                        blank=True, to="core.filteringlabel", verbose_name="Labels"
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        default=iam.models.Folder.get_root_folder_id,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_folder",
                        to="iam.folder",
                    ),
                ),
                (
                    "health",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={
                            "field_path": "project.health",
                            "is_visible": True,
                        },
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="project_health",
                        to="core.terminology",
                    ),
                ),
                (
                    "linked_collection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projects",
                        to="pmbok.genericcollection",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_projects",
                        to="core.actor",
                    ),
                ),
                (
                    "parent_project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sub_projects",
                        to="pmbok.project",
                    ),
                ),
                (
                    "sponsor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sponsored_projects",
                        to="core.actor",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={
                            "field_path": "project.status",
                            "is_visible": True,
                        },
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="project_status",
                        to="core.terminology",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="responsibilitymatrix",
            name="projects",
            field=models.ManyToManyField(
                blank=True, related_name="responsibility_matrices", to="pmbok.project"
            ),
        ),
    ]
