# Generated by Django 6.0.6 on 2026-07-16 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmbok', '0006_project_responsibilitymatrix_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='ref_link',
            field=models.URLField(blank=True, max_length=4096),
        ),
    ]
