# Generated by Django 6.0.8 on 2026-08-25 18:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pmbok", "0007_alter_project_ref_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="kind",
            field=models.CharField(
                choices=[
                    ("portfolio", "Portfolio"),
                    ("program", "Program"),
                    ("project", "Project"),
                    ("engagement", "Engagement"),
                ],
                default="project",
                max_length=20,
            ),
        ),
    ]
