# Generated by Django 6.0.8 on 2026-08-17 14:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pmbok", "0007_alter_project_ref_link"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accreditation",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="genericcollection",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="project",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="responsibilityassignment",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="responsibilitymatrix",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="responsibilitymatrixactivity",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="responsibilitymatrixactor",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="responsibilityrole",
            name="is_published",
        ),
    ]
