# Generated by Django 5.1.6 on 2025-03-04 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "operation",
                    models.CharField(
                        choices=[("C", "Create"), ("U", "Update"), ("D", "Delete")],
                        max_length=1,
                    ),
                ),
                ("object_id", models.CharField(max_length=255)),
                ("event_data", models.JSONField(blank=True, null=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="ca_audit_lo_content_b8800a_idx",
                    ),
                    models.Index(
                        fields=["timestamp"], name="ca_audit_lo_timesta_86eaf0_idx"
                    ),
                    models.Index(
                        fields=["user"], name="ca_audit_lo_user_id_9a5c9b_idx"
                    ),
                    models.Index(
                        fields=["operation"], name="ca_audit_lo_operati_86e6d7_idx"
                    ),
                ],
            },
        ),
    ]
