# Generated by Django 5.1.7 on 2025-03-20 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("privacy", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="processing",
            name="dpia_required",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="processing",
            name="legal_basis",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
