# Generated by Django 5.1.7 on 2025-03-24 18:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("privacy", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datasubject",
            name="category",
            field=models.CharField(
                choices=[
                    ("customer", "Customer/Client"),
                    ("prospect", "Prospective Customer/Client"),
                    ("employee", "Employee"),
                    ("job_applicant", "Job Applicant"),
                    ("contractor", "Contractor/Vendor"),
                    ("business_partner", "Business Partner"),
                    ("user", "Website/App User"),
                    ("visitor", "Visitor"),
                    ("minor", "Child/Minor"),
                    ("vulnerable", "Vulnerable Person"),
                    ("public", "General Public"),
                    ("other", "Other Data Subject Category"),
                ],
                max_length=255,
            ),
        ),
    ]
