# Generated by Django 5.1.7 on 2025-03-20 17:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0061_findingsassessment_ref_id"),
        ("privacy", "0002_alter_processing_dpia_required_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="processing",
            name="labels",
        ),
        migrations.AddField(
            model_name="processing",
            name="filtering_labels",
            field=models.ManyToManyField(
                blank=True, to="core.filteringlabel", verbose_name="Labels"
            ),
        ),
    ]
