# Generated by Django 5.1.8 on 2025-04-06 23:57

from django.db import migrations
import re


def fix_privacy_prefix(apps, schema_editor):
    # Processing model
    Processing = apps.get_model("privacy", "Processing")
    for obj in Processing.objects.all():
        if not re.match(r"^privacy_.*", obj.legal_basis):
            obj.legal_basis = "privacy_" + obj.legal_basis
            obj.save()


class Migration(migrations.Migration):
    dependencies = [
        ("privacy", "0003_migrate_privacy_prefixes"),
    ]

    operations = [
        migrations.RunPython(fix_privacy_prefix),
    ]
