# Generated by Django 5.1.10 on 2025-08-14 12:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0088_tasktemplate_link"),
        ("privacy", "0005_alter_datacontractor_country_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="personaldata",
            name="assets",
            field=models.ManyToManyField(
                blank=True, related_name="personal_data", to="core.asset"
            ),
        ),
    ]
