# Generated by Django 5.2.6 on 2025-09-26 15:39

import django.db.models.deletion
import iam.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iam", "0015_user_expiry_date"),
        ("privacy", "0006_personaldata_assets"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RightRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                ("ref_id", models.CharField(blank=True, max_length=100)),
                ("requested_on", models.DateField()),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("deletion", "Deletion / Erasure"),
                            ("rectification", "Rectification"),
                            ("access", "Access / Extract"),
                            ("portability", "Portability"),
                            ("restriction", "Restriction"),
                            ("objection", "Objection"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("in_progress", "In Progress"),
                            ("on_hold", "On hold"),
                            ("done", "Done"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("observation", models.TextField(blank=True)),
                (
                    "folder",
                    models.ForeignKey(
                        default=iam.models.Folder.get_root_folder_id,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_folder",
                        to="iam.folder",
                    ),
                ),
                (
                    "owner",
                    models.ManyToManyField(
                        blank=True,
                        related_name="assigned_right_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "processings",
                    models.ManyToManyField(
                        blank=True,
                        related_name="right_requests",
                        to="privacy.processing",
                    ),
                ),
            ],
            options={
                "verbose_name": "Right Request",
                "verbose_name_plural": "Right Requests",
                "ordering": ["-requested_on"],
            },
        ),
    ]
