# Generated by Django 5.2.7 on 2025-10-03 12:43

from django.db import migrations, models


def copy_legal_basis_to_purposes(apps, schema_editor):
    """
    Copy legal_basis from Processing to all related Purpose objects.
    If a Processing has a legal_basis but no purposes, create a default purpose.
    """
    Processing = apps.get_model("privacy", "Processing")
    Purpose = apps.get_model("privacy", "Purpose")

    for processing in Processing.objects.all():
        # Only process if processing has a legal_basis set
        if processing.legal_basis:
            existing_purposes = Purpose.objects.filter(processing=processing)

            if existing_purposes.exists():
                # Update all existing purposes
                existing_purposes.update(legal_basis=processing.legal_basis)
            else:
                # Create a default purpose to preserve the legal_basis
                Purpose.objects.create(
                    processing=processing,
                    name="Default Purpose",
                    description=f"Auto-generated purpose to preserve legal basis: {processing.legal_basis}",
                    legal_basis=processing.legal_basis,
                    folder=processing.folder,
                )


class Migration(migrations.Migration):
    dependencies = [
        ("privacy", "0007_rightrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="purpose",
            name="legal_basis",
            field=models.CharField(
                choices=[
                    ("privacy_consent", "Consent"),
                    ("privacy_contract", "Performance of a Contract"),
                    ("privacy_legal_obligation", "Compliance with a Legal Obligation"),
                    ("privacy_vital_interests", "Protection of Vital Interests"),
                    (
                        "privacy_public_interest",
                        "Performance of a Task in the Public Interest",
                    ),
                    ("privacy_legitimate_interests", "Legitimate Interests"),
                    (
                        "privacy_explicit_consent",
                        "Explicit Consent for Special Categories",
                    ),
                    (
                        "privacy_employment_social_security",
                        "Employment and Social Security Law",
                    ),
                    (
                        "privacy_vital_interests_incapacity",
                        "Vital Interests (Subject Physically/Legally Incapable)",
                    ),
                    (
                        "privacy_nonprofit_organization",
                        "Processing by Nonprofit Organization",
                    ),
                    (
                        "privacy_public_data",
                        "Data Manifestly Made Public by the Data Subject",
                    ),
                    (
                        "privacy_legal_claims",
                        "Establishment, Exercise or Defense of Legal Claims",
                    ),
                    (
                        "privacy_substantial_public_interest",
                        "Substantial Public Interest",
                    ),
                    (
                        "privacy_preventive_medicine",
                        "Preventive or Occupational Medicine",
                    ),
                    ("privacy_public_health", "Public Health"),
                    (
                        "privacy_archiving_research",
                        "Archiving, Research or Statistical Purposes",
                    ),
                    (
                        "privacy_child_consent",
                        "Child's Consent with Parental Authorization",
                    ),
                    (
                        "privacy_data_transfer_adequacy",
                        "Transfer Based on Adequacy Decision",
                    ),
                    (
                        "privacy_data_transfer_safeguards",
                        "Transfer Subject to Appropriate Safeguards",
                    ),
                    (
                        "privacy_data_transfer_binding_rules",
                        "Transfer Subject to Binding Corporate Rules",
                    ),
                    (
                        "privacy_data_transfer_derogation",
                        "Transfer Based on Derogation for Specific Situations",
                    ),
                    ("privacy_consent_and_contract", "Consent and Contract"),
                    (
                        "privacy_contract_and_legitimate_interests",
                        "Contract and Legitimate Interests",
                    ),
                    ("privacy_not_applicable", "Not Applicable"),
                    ("privacy_other", "Other Legal Basis (Specify in Description)"),
                ],
                default="privacy_other",
                max_length=255,
            ),
        ),
        migrations.RunPython(
            copy_legal_basis_to_purposes,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="processing",
            name="legal_basis",
        ),
    ]
