# Generated by Django 5.2.7 on 2025-10-03 20:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("privacy", "0008_databreach"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="databreach",
            name="assigned_to",
            field=models.ManyToManyField(
                blank=True, to=settings.AUTH_USER_MODEL, verbose_name="Assigned to"
            ),
        ),
        migrations.AddField(
            model_name="processing",
            name="assigned_to",
            field=models.ManyToManyField(
                blank=True, to=settings.AUTH_USER_MODEL, verbose_name="Assigned to"
            ),
        ),
    ]
