# Generated by Django 5.2.7 on 2025-12-04 17:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0118_riskscenario_antecedent_scenarios_and_more"),
        ("privacy", "0010_alter_datacontractor_country_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="processing",
            name="evidences",
            field=models.ManyToManyField(
                blank=True,
                related_name="processings",
                to="core.evidence",
                verbose_name="Evidences",
            ),
        ),
    ]
