# Generated by Django 5.2.9 on 2026-01-08 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0125_team_actor"),
        ("privacy", "0011_processing_evidences"),
    ]

    operations = [
        migrations.AddField(
            model_name="rightrequest",
            name="new_owner",
            field=models.ManyToManyField(
                blank=True, related_name="assigned_right_requests", to="core.actor"
            ),
        ),
    ]
