# Generated by Django 5.2.9 on 2026-01-09 14:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0127_remove_appliedcontrol_new_owner_and_more"),
        ("privacy", "0012_rightrequest_new_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rightrequest",
            name="owner",
        ),
        migrations.RenameField(
            model_name="rightrequest",
            old_name="new_owner",
            new_name="owner",
        ),
    ]
