# Generated by Django 5.2.9 on 2026-01-20 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("privacy", "0013_remove_rightrequest_new_owner_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="processing",
            name="owner",
        ),
        migrations.AddField(
            model_name="processing",
            name="new_assigned_to",
            field=models.ManyToManyField(
                blank=True, related_name="assigned_processings", to="core.actor"
            ),
        ),
        migrations.AddField(
            model_name="databreach",
            name="new_assigned_to",
            field=models.ManyToManyField(
                blank=True, related_name="assigned_data_breaches", to="core.actor"
            ),
        ),
    ]
