# Generated by Django 5.2.9 on 2026-01-20 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0130_remove_organisationobjective_new_assigned_to_and_more"),
        ("privacy", "0014_remove_processing_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="databreach",
            name="assigned_to",
        ),
        migrations.RemoveField(
            model_name="processing",
            name="assigned_to",
        ),
        migrations.RemoveField(
            model_name="processing",
            name="author",
        ),
        migrations.RenameField(
            model_name="databreach",
            old_name="new_assigned_to",
            new_name="assigned_to",
        ),
        migrations.RenameField(
            model_name="processing",
            old_name="new_assigned_to",
            new_name="assigned_to",
        ),
        migrations.RenameField(
            model_name="processing",
            old_name="new_author",
            new_name="author",
        ),
        migrations.AlterField(
            model_name="databreach",
            name="assigned_to",
            field=models.ManyToManyField(
                blank=True,
                related_name="assigned_data_breaches",
                to="core.actor",
                verbose_name="Assigned to",
            ),
        ),
        migrations.AlterField(
            model_name="processing",
            name="assigned_to",
            field=models.ManyToManyField(
                blank=True,
                related_name="assigned_processings",
                to="core.actor",
                verbose_name="Assigned to",
            ),
        ),
    ]
