# Generated by Django 5.2.9 on 2026-01-27 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0131_remove_findingsassessment_owner'),
        ('privacy', '0015_remove_databreach_new_assigned_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datatransfer',
            name='legal_basis',
        ),
        migrations.AddField(
            model_name='datatransfer',
            name='transfer_mechanism',
            field=models.CharField(blank=True, choices=[('privacy_adequacy_decision', 'Adequacy Decision (Art. 45)'), ('privacy_appropriate_safeguards', 'Appropriate Safeguards (Art. 46)'), ('privacy_binding_corporate_rules', 'Binding Corporate Rules (Art. 47)'), ('privacy_derogation', 'Derogation for Specific Situations (Art. 49)')], max_length=255),
        ),
        migrations.AddField(
            model_name='processing',
            name='perimeters',
            field=models.ManyToManyField(blank=True, related_name='processings', to='core.perimeter'),
        ),
        migrations.AddField(
            model_name='purpose',
            name='article_9_condition',
            field=models.CharField(blank=True, choices=[('privacy_explicit_consent', 'Explicit Consent for Special Categories'), ('privacy_employment_social_security', 'Employment and Social Security Law'), ('privacy_vital_interests_incapacity', 'Vital Interests (Subject Physically/Legally Incapable)'), ('privacy_nonprofit_organization', 'Processing by Nonprofit Organization'), ('privacy_public_data', 'Data Manifestly Made Public by the Data Subject'), ('privacy_legal_claims', 'Establishment, Exercise or Defense of Legal Claims'), ('privacy_substantial_public_interest', 'Substantial Public Interest'), ('privacy_preventive_medicine', 'Preventive or Occupational Medicine'), ('privacy_public_health', 'Public Health'), ('privacy_archiving_research', 'Archiving, Research or Statistical Purposes')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datacontractor',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='datarecipient',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='datasubject',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='datatransfer',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='purpose',
            name='legal_basis',
            field=models.CharField(choices=[('privacy_consent', 'Consent'), ('privacy_contract', 'Performance of a Contract'), ('privacy_legal_obligation', 'Compliance with a Legal Obligation'), ('privacy_vital_interests', 'Protection of Vital Interests'), ('privacy_public_interest', 'Performance of a Task in the Public Interest'), ('privacy_legitimate_interests', 'Legitimate Interests')], default='privacy_consent', max_length=255),
        ),
        migrations.AlterField(
            model_name='purpose',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Name'),
        ),
    ]
