# Generated by Django 5.2.9 on 2026-01-26 17:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("privacy", "0015_remove_databreach_new_assigned_to_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personaldata",
            name="name",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Name"
            ),
        ),
    ]
