# Generated by Django 5.2.9 on 2026-01-26 19:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0131_remove_findingsassessment_owner"),
        ("privacy", "0016_alter_datacontractor_name_alter_datarecipient_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="processing",
            name="perimeters",
            field=models.ManyToManyField(
                blank=True, related_name="processings", to="core.perimeter"
            ),
        ),
    ]
