# Generated by Django 6.0.3 on 2026-03-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("privacy", "0017_data_split_legal_basis_choices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datatransfer",
            name="transfer_mechanism",
            field=models.CharField(
                blank=True,
                choices=[
                    ("privacy_adequacy_decision", "Adequacy Decision (Art. 45)"),
                    (
                        "privacy_standard_contractual_clauses",
                        "Standard Contractual Clauses (Art. 46.2c)",
                    ),
                    (
                        "privacy_appropriate_safeguards",
                        "Appropriate Safeguards (Art. 46)",
                    ),
                    (
                        "privacy_binding_corporate_rules",
                        "Binding Corporate Rules (Art. 47)",
                    ),
                    ("privacy_codes_of_conduct", "Codes of Conduct (Art. 46.2e)"),
                    (
                        "privacy_certification_mechanisms",
                        "Certification Mechanisms (Art. 46.2f)",
                    ),
                    (
                        "privacy_derogation",
                        "Derogation for Specific Situations (Art. 49)",
                    ),
                ],
                max_length=255,
            ),
        ),
    ]
