# Generated by Django 6.0.6 on 2026-07-02 08:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0172_view_compliance_assessment_full_permission"),
        ("privacy", "0018_alter_datatransfer_transfer_mechanism"),
    ]

    operations = [
        migrations.AddField(
            model_name="databreach",
            name="evidences",
            field=models.ManyToManyField(
                blank=True,
                related_name="data_breaches",
                to="core.evidence",
                verbose_name="Evidences",
            ),
        ),
    ]
