# Generated by Django 6.0.6 on 2026-07-16 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privacy', '0020_convert_nature_and_category_to_terminology'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databreach',
            name='reference_link',
            field=models.URLField(blank=True, max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='datacontractor',
            name='documentation_link',
            field=models.URLField(blank=True, max_length=4096),
        ),
        migrations.AlterField(
            model_name='datatransfer',
            name='documentation_link',
            field=models.URLField(blank=True, max_length=4096),
        ),
    ]
