# Generated by Django 6.0.8 on 2026-08-17 14:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("privacy", "0021_alter_datacontractor_documentation_link_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="databreach",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="datacontractor",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="datarecipient",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="datasubject",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="datatransfer",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="personaldata",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="processing",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="purpose",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="rightrequest",
            name="is_published",
        ),
    ]
