# Generated by Django 6.0.6 on 2026-06-18 08:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IntegrationSchemaCache",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
                ("tables", models.JSONField(default=list)),
                ("columns", models.JSONField(default=dict)),
                ("choices", models.JSONField(default=dict)),
                ("fetched_at", models.DateTimeField(blank=True, null=True)),
                (
                    "configuration",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schema_cache",
                        to="integrations.integrationconfiguration",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
