# Generated by Django 6.0.2 on 2026-03-17 09:00

import django.db.models.deletion
import iam.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iam", "0021_fix_auditee_iam_groups"),
        ("integrations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="syncevent",
            name="folder",
            field=models.ForeignKey(
                default=iam.models.Folder.get_root_folder_id,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_folder",
                to="iam.folder",
            ),
        ),
        migrations.AddField(
            model_name="syncevent",
            name="is_published",
            field=models.BooleanField(default=False, verbose_name="published"),
        ),
        migrations.AddField(
            model_name="syncevent",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
        migrations.AlterField(
            model_name="syncevent",
            name="id",
            field=models.IntegerField(
                editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
