# Generated by Django 6.0.6 on 2026-07-16 20:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0002_integrationschemacache"),
    ]

    operations = [
        migrations.AlterField(
            model_name="integrationconfiguration",
            name="webhook_url",
            field=models.URLField(blank=True, max_length=2048),
        ),
    ]
