# Generated by Django 5.2.7 on 2025-10-27 19:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0002_alter_integrationconfiguration_provider_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="syncmapping",
            name="last_sync_direction",
            field=models.CharField(
                blank=True, choices=[("push", "Push"), ("pull", "Pull")], max_length=10
            ),
        ),
    ]
