# Generated by Django 6.0.8 on 2026-08-17 14:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0003_alter_integrationconfiguration_webhook_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="integrationconfiguration",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="integrationprovider",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="integrationschemacache",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="syncmapping",
            name="is_published",
        ),
    ]
