# Generated by Django 6.0.3 on 2026-04-09 14:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sec_intel", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cve",
            name="references",
            field=models.JSONField(blank=True, null=True, verbose_name="References"),
        ),
    ]
