# Generated by Django 6.0.8 on 2026-08-17 14:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sec_intel", "0002_tactic_ttpcatalog_technique_tactic_catalog"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cwe",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="securityadvisory",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="tactic",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="technique",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="ttpcatalog",
            name="is_published",
        ),
    ]
