# Generated by Django 5.1.1 on 2024-09-04 14:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientsettings',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='client_favicons', validators=[django.core.validators.FileExtensionValidator(['ico', 'png', 'jpeg', 'jpg', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='clientsettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='client_logos', validators=[django.core.validators.FileExtensionValidator(['png', 'jpeg', 'jpg', 'webp', 'svg'])]),
        ),
    ]
