# Generated by Django 5.1 on 2024-10-14 08:48

import django.db.models.deletion
import iam.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise_core', '0001_initial'),
        ('iam', '0008_user_is_third_party'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientsettings',
            name='folder',
            field=models.ForeignKey(default=iam.models.Folder.get_root_folder_id, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_folder', to='iam.folder'),
        ),
    ]
