# Generated by Django 6.0.8 on 2026-08-19 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise_core', '0003_alter_clientsettings_favicon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientsettings',
            name='is_published',
        ),
    ]
