# Generated by Django 5.1.2 on 2024-10-23 10:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise_core', '0003_alter_clientsettings_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientsettings',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='client_favicons', validators=[django.core.validators.FileExtensionValidator(['ico', 'png', 'jpeg', 'jpg'])]),
        ),
        migrations.AlterField(
            model_name='clientsettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='client_logos', validators=[django.core.validators.FileExtensionValidator(['png', 'jpeg', 'jpg'])]),
        ),
    ]
