# Generated by Django 5.0.2 on 2024-02-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='published'),
        ),
        migrations.AddField(
            model_name='role',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='published'),
        ),
        migrations.AddField(
            model_name='roleassignment',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='published'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='published'),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='published'),
        ),
    ]
