# Generated by Django 5.0.2 on 2024-03-05 13:51

from django.db import migrations

def delete_validator(apps, schema_editor):
    # We can't import the models directly as they may be newer
    UserGroup = apps.get_model("iam", "UserGroup")
    validator_user_group = UserGroup.objects.get(name="BI-UG-GVA").delete() if UserGroup.objects.filter(name="BI-UG-GVA").exists() else None
    Role = apps.get_model("iam", "Role")
    validator_role = Role.objects.get(name="BI-RL-VAL").delete() if Role.objects.filter(name="BI-RL-VAL").exists() else None



class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(delete_validator),
    ]
