# Generated by Django 5.0.2 on 2024-03-05 13:51

from django.db import migrations

def purge_validator(apps, schema_editor):
    """
    Purge the validator role since it has been replaced by approver.
    """
    UserGroup = apps.get_model("iam", "UserGroup")
    validator_user_group = UserGroup.objects.filter(name="BI-UG-GVA")
    if validator_user_group.exists():
        validator_user_group.delete()
    Role = apps.get_model("iam", "Role")
    validator_role = Role.objects.filter(name="BI-RL-VAL")
    if validator_role.exists():
        validator_role.delete()



class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(purge_validator),
    ]
