# Generated by Django 5.0.2 on 2024-02-24 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='builtin',
            field=models.BooleanField(default=False),
        ),
    ]
