# Generated by Django 5.0.2 on 2024-02-29 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0002_folder_is_published_role_is_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='published'),
        ),
        migrations.AlterField(
            model_name='role',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='published'),
        ),
        migrations.AlterField(
            model_name='roleassignment',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='published'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='published'),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='published'),
        ),
    ]
