# Generated by Django 5.0.4 on 2024-06-14 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0003_alter_folder_updated_at_alter_role_updated_at_and_more'),
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SSOSettings',
            fields=[
                ('provider', models.CharField(max_length=30, verbose_name='provider')),
                ('provider_id', models.CharField(blank=True, max_length=200, verbose_name='provider ID')),
                ('provider_name', models.CharField(max_length=200, verbose_name='name')),
                ('client_id', models.CharField(help_text='App ID, or consumer key', max_length=191, verbose_name='client id')),
                ('secret', models.CharField(blank=True, help_text='API secret, client secret, or consumer secret', max_length=191, verbose_name='secret key')),
                ('key', models.CharField(blank=True, help_text='Key', max_length=191, verbose_name='key')),
                ('settings', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'managed': False,
                'proxy': True,
            },
            bases=('settings.globalsettings',),
        ),
    ]
