# Generated by Django 5.0.4 on 2024-06-11 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0003_alter_folder_updated_at_alter_role_updated_at_and_more'),
        ('socialaccount', '0006_alter_socialaccount_extra_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityProvider',
            fields=[
                ('socialapp_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='socialaccount.socialapp')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            bases=('socialaccount.socialapp',),
        ),
    ]
