# Generated by Django 5.0.6 on 2024-06-21 16:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iam", "0004_ssosettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_sso",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="password"
            ),
        ),
    ]
