# Generated by Django 5.0.6 on 2024-07-05 08:58

import iam.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0004_ssosettings_user_is_sso'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', iam.models.CaseInsensitiveUserManager()),
            ],
        ),
    ]
