# Generated by Django 5.1.1 on 2024-09-12 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iam", "0005_alter_user_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="folder",
            name="content_type",
            field=models.CharField(
                choices=[("GL", "GLOBAL"), ("DO", "DOMAIN"), ("EN", "ENCLAVE")],
                default="DO",
                max_length=2,
            ),
        ),
    ]
