# Generated by Django 5.1 on 2024-09-13 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iam", "0007_alter_folder_content_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_third_party",
            field=models.BooleanField(default=False),
        ),
    ]
