# Generated by Django 5.1.1 on 2024-10-23 17:42

from django.db import migrations


def create_emailaddress_objects(apps, schema_editor):
    try:
        EmailAddress = apps.get_model("account", "EmailAddress")
        User = apps.get_model("iam", "User")

        for user in User.objects.all():
            EmailAddress.objects.create(
                user=user,
                email=user.email,
                verified=True,
                primary=True,
            )
    finally:
        pass


class Migration(migrations.Migration):
    dependencies = [
        ("iam", "0008_user_is_third_party"),
    ]

    operations = [
        migrations.RunPython(create_emailaddress_objects),
    ]
