# Generated by Django 5.1.1 on 2024-11-22 01:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iam", "0008_user_is_third_party"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="preferences",
            field=models.JSONField(default=dict),
        ),
    ]
