# Generated by Django 5.1.1 on 2024-12-04 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iam", "0009_create_allauth_emailaddress_objects"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="preferences",
            field=models.JSONField(default=dict),
        ),
    ]
