# Generated by Django 5.1.1 on 2024-10-23 17:42

from django.db import migrations

def create_emailaddress_objects(apps, schema_editor):
    try:
        from allauth.account.models import EmailAddress
        from iam.models import User

        for user in User.objects.all():
            EmailAddress.objects.create(
                user=user,
                email=user.email,
                verified=True,
                primary=True,
            )
    finally:
        pass

class Migration(migrations.Migration):
    dependencies = [
        ("iam", "0009_user_preferences"),
    ]

    operations = [
        migrations.RunPython(create_emailaddress_objects),
    ]
