# Generated by Django 5.1.1 on 2024-11-13 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0010_folder_ref_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='ref_id',
        ),
    ]
