# Generated by Django 5.1.8 on 2025-04-28 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0011_replace_slash_in_folder_names'),
        migrations.swappable_dependency(settings.KNOX_TOKEN_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('auth_token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.KNOX_TOKEN_MODEL)),
            ],
        ),
    ]
