# Generated by Django 5.1.8 on 2025-04-19 01:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iam", "0011_replace_slash_in_folder_names"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="keep_local_login",
            field=models.BooleanField(
                default=False,
                help_text="If True allow the user to log in using the normal login form even with SSO forced.",
            ),
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_sso",
        ),
    ]
