# Generated by Django 5.1.1 on 2024-11-14 11:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iam", "0012_folder_ref_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="folder",
            name="ref_id",
        ),
    ]
