# Generated by Django 5.1.10 on 2025-07-29 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iam", "0013_personalaccesstoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="observation",
            field=models.TextField(
                blank=True, null=True, verbose_name="Notes about a user"
            ),
        ),
    ]
