# Generated by Django 5.1.10 on 2025-06-17 07:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iam", "0013_personalaccesstoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="allow_pat",
            field=models.BooleanField(
                default=False,
                help_text="If True allow the user to create Personal Access Tokens (PAT)",
            ),
        ),
    ]
