# Generated by Django 5.2.6 on 2025-09-23 10:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iam", "0014_user_observation"),
    ]

    operations = [
        migrations.AddField(
            model_name="folder",
            name="ref_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="reference ID"
            ),
        ),
    ]
