# Generated by Django 5.1.10 on 2025-07-22 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0014_user_groups_user_is_staff_user_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
    ]
