# Generated by Django 5.2.6 on 2025-09-25 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iam", "0014_user_observation"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="expiry_date",
            field=models.DateField(blank=True, null=True, verbose_name="Expiry date"),
        ),
    ]
