# Generated by Django 5.2.7 on 2025-10-10 15:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0104_add_info_severity"),
        ("iam", "0015_user_expiry_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="folder",
            name="filtering_labels",
            field=models.ManyToManyField(
                blank=True,
                related_name="folders",
                to="core.filteringlabel",
                verbose_name="Labels",
            ),
        ),
    ]
