# Generated by Django 5.2.9 on 2026-01-14 13:20

from django.db import migrations


def set_is_published(apps, schema_editor):
    """Set is_published=true for forlders (except enclaves) and users"""
    Folder = apps.get_model("iam", "Folder")
    User = apps.get_model("iam", "User")
    Folder.objects.filter(content_type__in=["GL", "DO"]).update(is_published=True)
    User.objects.all().update(is_published=True)


class Migration(migrations.Migration):
    dependencies = [
        ("iam", "0016_folder_filtering_labels"),
    ]

    operations = [
        migrations.RunPython(set_is_published, None),
    ]
