# Generated by Django 5.2.9 on 2026-01-14 13:20

from django.db import migrations


def set_enclave_is_published_false(apps, schema_editor):
    """Set is_published=False for all ENCLAVE folders, True for others"""
    Folder = apps.get_model("iam", "Folder")
    Folder.objects.filter(content_type__in=["GL", "DO"]).update(is_published=True)
    Folder.objects.filter(content_type="EN").update(is_published=False)


def reverse_set_enclave_is_published(apps, schema_editor):
    """Reverse the operation by setting is_published=True for all enclaves"""
    Folder = apps.get_model("iam", "Folder")
    Folder.objects.filter(content_type="EN").update(is_published=True)


class Migration(migrations.Migration):
    dependencies = [
        ("iam", "0016_folder_filtering_labels"),
    ]

    operations = [
        migrations.RunPython(
            set_enclave_is_published_false, reverse_set_enclave_is_published
        ),
    ]
