# Generated by Django 5.2.9 on 2026-01-01 00:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iam", "0016_folder_filtering_labels"),
    ]

    operations = [
        migrations.CreateModel(
            name="CacheVersion",
            fields=[
                (
                    "key",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Cache version",
                "verbose_name_plural": "Cache versions",
            },
        ),
    ]
