# Generated by Django 5.2.9 on 2026-01-22 12:03

from django.db import migrations


def add_view_globalsettings_permission(apps, schema_editor):
    Role = apps.get_model("iam", "Role")
    Permission = apps.get_model("auth", "Permission")
    ContentType = apps.get_model("contenttypes", "ContentType")

    content_type = ContentType.objects.get(app_label="iam", model="globalsettings")

    permission = Permission.objects.get(
        codename="view_globalsettings",
        content_type=content_type,
    )

    for role in Role.objects.all():
        if not role.permissions.filter(id=permission.id).exists():
            role.permissions.add(permission)


class Migration(migrations.Migration):
    dependencies = [
        ("iam", "0018_cacheversion"),
    ]

    operations = [
        migrations.RunPython(add_view_globalsettings_permission),
    ]
