# Generated by Django 6.0.6 on 2026-06-22 14:50

import django.db.models.deletion
import iam.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iam", "0021_fix_auditee_iam_groups"),
        migrations.swappable_dependency(settings.KNOX_TOKEN_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="scim_external_id",
            field=models.CharField(
                blank=True,
                max_length=512,
                null=True,
                unique=True,
                verbose_name="SCIM external ID",
            ),
        ),
        migrations.CreateModel(
            name="IdPGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
                (
                    "name",
                    models.CharField(max_length=512, unique=True, verbose_name="Name"),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        default=iam.models.Folder.get_root_folder_id,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_folder",
                        to="iam.folder",
                    ),
                ),
                (
                    "user_groups",
                    models.ManyToManyField(
                        blank=True,
                        related_name="idp_groups",
                        to="iam.usergroup",
                        verbose_name="User groups",
                    ),
                ),
            ],
            options={
                "verbose_name": "IdP group",
                "verbose_name_plural": "IdP groups",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="idp_groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="External IdP groups this user belongs to (SCIM-managed). The user additionally inherits the user groups granted by each IdP group.",
                related_name="users",
                to="iam.idpgroup",
                verbose_name="IdP groups",
            ),
        ),
        migrations.CreateModel(
            name="SCIMToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(default="SCIM provisioning token", max_length=255),
                ),
                (
                    "auth_token",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scim_token",
                        to=settings.KNOX_TOKEN_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "SCIM token",
                "verbose_name_plural": "SCIM tokens",
            },
        ),
    ]
