# Generated by Django 6.0.6 on 2026-06-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iam", "0021_fix_auditee_iam_groups"),
    ]

    operations = [
        migrations.AlterField(
            model_name="folder",
            name="content_type",
            field=models.CharField(
                choices=[
                    ("GL", "GLOBAL"),
                    ("DO", "DOMAIN"),
                    ("EN", "ENCLAVE"),
                    ("PE", "PERSONAL"),
                ],
                default="DO",
                max_length=2,
            ),
        ),
    ]
