# Generated by Django 6.0.5 on 2026-06-13 03:31

from django.db import migrations, models


def fill_folder_descendants(apps, schema_editor):
    Folder = apps.get_model("iam", "Folder")

    folders = list(Folder.objects.select_related("parent_folder"))

    folder_to_descendants = {}

    for folder in folders:
        parent = folder.parent_folder

        while parent is not None:
            folder_to_descendants.setdefault(parent.id, []).append(folder.id)
            parent = parent.parent_folder

    descendant_model = Folder.descendants.through

    # We clear out the table in case the `iam/signals.py` already added entries to the table.
    descendant_model.objects.all().delete()

    descendant_relation_generator = (
        descendant_model(from_folder_id=ancestor_id, to_folder_id=descendant_id)
        for ancestor_id, descendant_ids in folder_to_descendants.items()
        for descendant_id in descendant_ids
    )

    descendant_model.objects.bulk_create(
        descendant_relation_generator,
        batch_size=1000,
        ignore_conflicts=True,
    )


class Migration(migrations.Migration):
    dependencies = [
        ("iam", "0021_fix_auditee_iam_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="folder",
            name="descendants",
            field=models.ManyToManyField(to="iam.folder", related_name="ancestors"),
        ),
        migrations.RunPython(fill_folder_descendants),
    ]
