# Generated by Django 6.0.6 on 2026-06-17 08:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0021_fix_auditee_iam_groups'),
        migrations.swappable_dependency(settings.KNOX_TOKEN_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdPGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_published', models.BooleanField(default=False, verbose_name='published')),
                ('external_group_id', models.CharField(help_text='Group name, UUID, or DN as provided by the IdP', max_length=512, unique=True, verbose_name='External group identifier')),
                ('scim_external_id', models.CharField(blank=True, help_text='Opaque identifier assigned by the SCIM client the first time the IdP pushes this group.', max_length=512, null=True, unique=True, verbose_name='SCIM external ID')),
            ],
            options={
                'verbose_name': 'IdP group',
                'verbose_name_plural': 'IdP groups',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='scim_external_id',
            field=models.CharField(blank=True, max_length=512, null=True, unique=True, verbose_name='SCIM external ID'),
        ),
        migrations.CreateModel(
            name='IdPGroupMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_published', models.BooleanField(default=False, verbose_name='published')),
                ('idp_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='iam.idpgroup', verbose_name='IdP group')),
                ('user_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idp_mappings', to='iam.usergroup', verbose_name='User group')),
            ],
            options={
                'verbose_name': 'IdP group mapping',
                'verbose_name_plural': 'IdP group mappings',
            },
        ),
        migrations.CreateModel(
            name='GroupMembershipSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_published', models.BooleanField(default=False, verbose_name='published')),
                ('channel', models.CharField(choices=[('manual', 'Manual'), ('sso', 'SSO'), ('scim', 'SCIM')], default='manual', max_length=16)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_membership_sources', to=settings.AUTH_USER_MODEL)),
                ('user_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_sources', to='iam.usergroup')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membership_sources', to='iam.idpgroupmapping', verbose_name='Source mapping')),
            ],
            options={
                'verbose_name': 'Group membership source',
                'verbose_name_plural': 'Group membership sources',
            },
        ),
        migrations.CreateModel(
            name='SCIMToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='SCIM provisioning token', max_length=255)),
                ('auth_token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scim_token', to=settings.KNOX_TOKEN_MODEL)),
            ],
            options={
                'verbose_name': 'SCIM token',
                'verbose_name_plural': 'SCIM tokens',
            },
        ),
        migrations.AddConstraint(
            model_name='idpgroupmapping',
            constraint=models.UniqueConstraint(fields=('idp_group', 'user_group'), name='unique_idp_group_user_group'),
        ),
        migrations.AddConstraint(
            model_name='groupmembershipsource',
            constraint=models.UniqueConstraint(fields=('user', 'user_group', 'source', 'channel'), name='unique_group_membership_source'),
        ),
    ]
