# Generated by Django 6.0.5 on 2026-05-27 10:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0021_fix_auditee_iam_groups'),
        migrations.swappable_dependency(settings.KNOX_TOKEN_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='scim_external_id',
            field=models.CharField(blank=True, max_length=512, null=True, unique=True, verbose_name='SCIM external ID'),
        ),
        migrations.CreateModel(
            name='IdPGroupMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_published', models.BooleanField(default=False, verbose_name='published')),
                ('external_group_id', models.CharField(help_text='Group name, UUID, or DN as provided by the IdP', max_length=512, unique=True, verbose_name='External group identifier')),
                ('scim_external_id', models.CharField(blank=True, help_text='Opaque identifier assigned by the SCIM client when this mapping is first touched by a SCIM push. Stable join key across renames.', max_length=512, null=True, unique=True, verbose_name='SCIM external ID')),
                ('user_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idp_mappings', to='iam.usergroup', verbose_name='User group')),
            ],
            options={
                'verbose_name': 'IdP group mapping',
                'verbose_name_plural': 'IdP group mappings',
            },
        ),
        migrations.CreateModel(
            name='SCIMToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='SCIM provisioning token', max_length=255)),
                ('auth_token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scim_token', to=settings.KNOX_TOKEN_MODEL)),
            ],
            options={
                'verbose_name': 'SCIM token',
                'verbose_name_plural': 'SCIM tokens',
            },
        ),
    ]
