# Generated by Django 6.0.4 on 2026-04-20 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iam", "0021_fix_auditee_iam_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_service_account",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether this user is a service account. Service accounts can only authenticate via API keys, not via login form or SSO.",
            ),
        ),
    ]
