# Generated by Django 6.0.7 on 2026-08-04 11:07

from django.db import migrations


def cleanup_stray_domain_iam_groups(apps, schema_editor):
    Folder = apps.get_model("iam", "Folder")
    UserGroup = apps.get_model("iam", "UserGroup")
    RoleAssignment = apps.get_model("iam", "RoleAssignment")
    User = apps.get_model("iam", "User")

    for folder in Folder.objects.filter(content_type="DO", create_iam_groups=False):
        builtin_groups = UserGroup.objects.filter(folder=folder, builtin=True)
        if not builtin_groups.exists():
            continue

        has_members = User.objects.filter(user_groups__in=builtin_groups).exists()
        if has_members:
            Folder.objects.filter(id=folder.id).update(create_iam_groups=True)
        else:
            group_ids = list(builtin_groups.values_list("id", flat=True))
            RoleAssignment.objects.filter(user_group_id__in=group_ids).delete()
            UserGroup.objects.filter(id__in=group_ids).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("iam", "0023_alter_folder_content_type"),
    ]
    operations = [
        migrations.RunPython(
            cleanup_stray_domain_iam_groups,
            migrations.RunPython.noop,
        ),
    ]
