# Generated by Django 6.0.6 on 2026-07-21 09:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("allauth_idp_oidc", "0003_client_allow_uri_wildcards"),
        ("iam", "0023_alter_folder_content_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="Name"),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "expiry_date",
                    models.DateField(blank=True, null=True, verbose_name="Expiry date"),
                ),
                (
                    "previous_secret_hash",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "previous_secret_expires_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "client",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="service_account",
                        to="allauth_idp_oidc.client",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_service_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "role",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="service_account",
                        to="iam.role",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="service_account",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Service account",
                "verbose_name_plural": "Service accounts",
            },
        ),
    ]
