# Generated by Django 6.0.7 on 2026-07-25 18:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iam", "0025_folder_descendants"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CacheVersion",
        ),
    ]
