# Generated by Django 6.0.8 on 2026-08-17 14:37

from django.db import migrations, models


def set_root_folder_viewable_from_descendants(apps, schema_editor):
    Folder = apps.get_model("iam", "Folder")
    Folder.objects.filter(content_type="GL").update(viewable_from_descendants=True)


class Migration(migrations.Migration):
    dependencies = [
        ("iam", "0026_delete_cacheversion"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="folder",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="idpgroup",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="role",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="roleassignment",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="serviceaccount",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="usergroup",
            name="is_published",
        ),
        migrations.AddField(
            model_name="folder",
            name="viewable_from_descendants",
            field=models.BooleanField(
                default=False,
                help_text="Make all `MAY_BE_VIEWABLE` objects in this folder be viewable from their descendants (descendant folders).",
            ),
        ),
        migrations.RunPython(
            set_root_folder_viewable_from_descendants, migrations.RunPython.noop
        ),
    ]
