# Generated by Django 6.0.8 on 2026-08-25 12:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iam", "0027_cleanup_stray_domain_iam_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="idpgroup",
            name="source",
            field=models.CharField(
                blank=True,
                choices=[("scim", "SCIM"), ("sso", "SSO")],
                max_length=8,
                null=True,
                verbose_name="Source",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_jit_provisioned",
            field=models.BooleanField(
                default=False,
                help_text="True when this account was auto-provisioned on first SSO login. Like SCIM-managed accounts, it stays SSO-only regardless of the global 'Force SSO' setting, unless 'Keep local login' is set.",
                verbose_name="JIT provisioned",
            ),
        ),
    ]
