# Generated by Django 6.0.8 on 2026-08-25 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iam", "0027_cleanup_stray_domain_iam_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_jit_provisioned",
            field=models.BooleanField(
                default=False,
                help_text="True when this account was auto-provisioned on first SSO login. Like SCIM-managed accounts, it stays SSO-only regardless of the global 'Force SSO' setting, unless 'Keep local login' is set.",
                verbose_name="JIT provisioned",
            ),
        ),
    ]
