# Generated by Django 6.0.8 on 2026-08-28 06:19

from dataclasses import dataclass
import itertools

from django.db import migrations, models
from django.db.models.deletion import SET_NULL
from django.apps import apps as django_apps

from iam.models import RoleAssignment


@dataclass(frozen=True)
class ModelConfig:
    view_permission: str
    app_name: str
    model_name: str

    def get_model(self, apps) -> type[models.Model]:
        model = apps.get_model(self.app_name, self.model_name)
        assert issubclass(model, models.Model)
        return model

    def get_real_model(self) -> type[models.Model]:
        return self.get_model(django_apps)


def fill_default_roles(apps, schema_editor):
    READER_CATALOG_MODEL_LIST = [
        ModelConfig("view_securityadvisory", "sec_intel", "SecurityAdvisory"),
        ModelConfig("view_cwe", "sec_intel", "CWE"),
        ModelConfig("view_technique", "sec_intel", "Technique"),
        ModelConfig("view_ttpcatalog", "sec_intel", "TTPCatalog"),
        ModelConfig("view_tactic", "sec_intel", "Tactic"),
        ModelConfig("view_responsibilityrole", "pmbok", "ResponsibilityRole"),
        ModelConfig("view_metricdefinition", "metrology", "MetricDefinition"),
        ModelConfig("view_metricinstance", "metrology", "MetricInstance"),
        ModelConfig("view_terminology", "core", "Terminology"),
        ModelConfig("view_riskmatrix", "core", "RiskMatrix"),
        ModelConfig("view_framework", "core", "Framework"),
        ModelConfig("view_question", "core", "Question"),
        ModelConfig("view_questionchoice", "core", "QuestionChoice"),
        ModelConfig("view_requirementnode", "core", "RequirementNode"),
        ModelConfig("view_referencecontrol", "core", "ReferenceControl"),
        ModelConfig("view_elementaryaction", "ebios_rm", "ElementaryAction"),
        ModelConfig("view_asset", "core", "Asset"),
        ModelConfig("view_threat", "core", "Threat"),
        ModelConfig("view_evidence", "core", "Evidence"),
        ModelConfig("view_evidencerevision", "core", "EvidenceRevision"),
        ModelConfig("view_comment", "core", "Comment"),
        ModelConfig("view_appliedcontrol", "core", "AppliedControl"),
        ModelConfig("view_policy", "core", "Policy"),
        ModelConfig("view_vulnerability", "core", "Vulnerability"),
        ModelConfig("view_folder", "iam", "Folder"),
        # "view_actor" isn't added (as its permissions aren't directly used by the IAM)
        ModelConfig("view_user", "iam", "User"),
        ModelConfig("view_team", "core", "Team"),
        ModelConfig("view_storedlibrary", "core", "StoredLibrary"),
        ModelConfig("view_loadedlibrary", "core", "LoadedLibrary"),
        ModelConfig("view_filteringlabel", "core", "FilteringLabel"),
        ModelConfig("view_libraryfilteringlabel", "core", "LibraryFilteringLabel"),
        ModelConfig("view_assetclass", "core", "AssetClass"),
        ModelConfig("view_assetcapability", "core", "AssetCapability"),
        ModelConfig("view_objectclassification", "core", "ObjectClassification"),
        ModelConfig("view_entity", "tprm", "Entity"),
        ModelConfig("view_documenttemplate", "doc_management", "DocumentTemplate"),
        ModelConfig(
            "view_customfielddefinition", "custom_fields", "CustomFieldDefinition"
        ),
        ModelConfig("view_requirementmapping", "core", "RequirementMapping"),
        ModelConfig("view_requirementmappingset", "core", "RequirementMappingSet"),
    ]

    # Copied from `core/startup.py` (`READER_MIGRATION_REMOVED_PERMISSIONS_LIST`)
    READER_MIGRATION_REMOVED_PERMISSIONS_LIST = {
        "view_tactic",
        "view_metricinstance",
        "view_riskmatrix",
        "view_framework",
        "view_question",
        "view_questionchoice",
        "view_requirementnode",
        "view_entity",
        "view_documenttemplate",
        "view_customfielddefinition",
    }

    READER_MIGRATION_MODEL_LIST = [
        model_config
        for model_config in READER_CATALOG_MODEL_LIST
        if model_config.view_permission not in READER_MIGRATION_REMOVED_PERMISSIONS_LIST
    ]

    READER_CATALOG_PERMISSIONS_LIST = [
        model_config.view_permission for model_config in READER_CATALOG_MODEL_LIST
    ]
    READER_MIGRATION_PERMISSIONS_LIST = [
        model_config.view_permission for model_config in READER_MIGRATION_MODEL_LIST
    ]

    Permission = apps.get_model("auth", "Permission")
    Folder = apps.get_model("iam", "Folder")
    Role = apps.get_model("iam", "Role")

    reader_catalog_role, _ = Role.objects.get_or_create(name="BI-RL-CAT", builtin=True)
    reader_catalog_role.permissions.set(
        Permission.objects.filter(codename__in=READER_CATALOG_PERMISSIONS_LIST)
    )

    reader_migration_role, _ = Role.objects.get_or_create(
        name="BI-RL-MIG", builtin=True
    )
    reader_migration_role.permissions.set(
        Permission.objects.filter(codename__in=READER_MIGRATION_PERMISSIONS_LIST)
    )

    non_leaf_folder_ids = set(
        Folder.descendants.through.objects.values_list(
            "from_folder_id", flat=True
        ).distinct()
    )

    root_folder = Folder.objects.filter(content_type="GL").first()
    assert root_folder is not None, "No root folder found in the database."

    non_leaf_folder_ids.discard(root_folder.id)

    root_folder.default_role = reader_catalog_role
    root_folder.save()

    affected_folder_ids = set()
    for model_config in READER_MIGRATION_MODEL_LIST:
        model = model_config.get_model(apps)
        real_model = model_config.get_real_model()

        if model is Folder:
            # Every folder is `is_published=True` so including the `Folder` model in this loop would add every single non-leaf-folder to `affected_folder_ids` (as a folder it considered as being a is_published=True object within itself otherwise).
            continue

        try:
            iam_folder_field = RoleAssignment.get_iam_folder_field(real_model)
        except Exception:
            continue

        folder_ids = (
            model.objects.filter(
                **{f"{iam_folder_field}__in": non_leaf_folder_ids}, is_published=True
            )
            .values_list(iam_folder_field, flat=True)
            .distinct()
        )

        affected_folder_ids.update(folder_ids)

    # Batch by 1_000 to avoid crashes due to overly large SQL requests.
    for affected_folder_ids_batch in itertools.batched(affected_folder_ids, 1_000):
        Folder.objects.filter(id__in=affected_folder_ids_batch).update(
            default_role=reader_migration_role
        )


class Migration(migrations.Migration):
    dependencies = [
        ("iam", "0028_idpgroup_source_user_is_jit_provisioned"),
    ]

    run_before = [
        # We need to ensure this migraton runs BEFORE all migrations which remove an `is_published` field from a model.
        # (as `fill_default_roles` relies on the `is_published` fields to assign the appropriate `default_role` to the folders (`Folder` objects)).
        ("automation", "0006_remove_condition_is_published_and_more"),
        ("core", "0186_remove_actor_is_published_remove_answer_is_published_and_more"),
        ("crq", "0004_remove_quantitativeriskhypothesis_is_published_and_more"),
        ("custom_fields", "0002_remove_customfieldchoice_is_published_and_more"),
        ("doc_management", "0006_remove_documentattachment_is_published_and_more"),
        ("ebios_rm", "0026_remove_attackpath_is_published_and_more"),
        ("global_settings", "0007_remove_globalsettings_is_published"),
        ("integrations", "0004_remove_integrationconfiguration_is_published_and_more"),
        ("metrology", "0005_remove_builtinmetricsample_is_published_and_more"),
        ("pmbok", "0008_remove_accreditation_is_published_and_more"),
        ("portals", "0003_remove_frameworksnapshot_is_published_and_more"),
        ("privacy", "0022_remove_databreach_is_published_and_more"),
        ("resilience", "0008_remove_assetassessment_is_published_and_more"),
        ("sec_intel", "0003_remove_cwe_is_published_and_more"),
        ("threat_modeling", "0002_remove_threatmodel_is_published_and_more"),
        ("tprm", "0020_remove_contract_is_published_and_more"),
        ("webhooks", "0006_remove_webhookendpoint_is_published"),
        # The `("enterprise_core, "0004_remove_clientsettings_is_published")` dependency isn't added as it could break community edition migrations + this migration doesn't depend on any model in `enterprise_core` anyway.
    ]

    operations = [
        migrations.AddField(
            model_name="folder",
            name="default_role",
            field=models.ForeignKey(
                blank=True,
                help_text="Role which permissions are applied(assigned) to this folder only which is granted for ANY user with ANY RoleAssignment on a descendant(folder) of this folder.",
                null=True,
                on_delete=SET_NULL,
                related_name="default_role_folders",
                to="iam.role",
            ),
        ),
        migrations.RunPython(fill_default_roles),
        migrations.RemoveField(
            model_name="folder",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="idpgroup",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="role",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="roleassignment",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="serviceaccount",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="usergroup",
            name="is_published",
        ),
    ]
