# Generated by Django 6.0.8 on 2026-08-28 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("allauth_idp_oidc", "0003_client_allow_uri_wildcards"),
        ("iam", "0028_idpgroup_source_user_is_jit_provisioned"),
        ("socialaccount", "0006_alter_socialaccount_extra_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceaccount",
            name="federated_subject",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="serviceaccount",
            name="identity_source",
            field=models.CharField(
                choices=[("local", "Local"), ("federated", "Federated")],
                default="local",
                max_length=16,
                verbose_name="Identity source",
            ),
        ),
        migrations.AddField(
            model_name="serviceaccount",
            name="social_app",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="federated_service_accounts",
                to="socialaccount.socialapp",
            ),
        ),
        migrations.AlterField(
            model_name="serviceaccount",
            name="client",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="service_account",
                to="allauth_idp_oidc.client",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="serviceaccount",
            unique_together={("social_app", "federated_subject")},
        ),
    ]
