# Generated by Django 6.0.8 on 2026-08-31 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iam", "0029_remove_folder_is_published_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="folder",
            name="default_role",
            field=models.ForeignKey(
                blank=True,
                help_text="Role whose permissions are granted, on this folder only, to the members of the standard IAM groups of its sub-folders (enclaves excluded). Only roles containing view permissions exclusively are eligible.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_role_folders",
                to="iam.role",
            ),
        ),
    ]
