# Generated by Django 6.0.8 on 2026-08-31 15:20

from django.db import migrations


class Migration(migrations.Migration):
    """
    Split out of `0029_remove_folder_is_published_and_more.py`: on PostgreSQL,
    running these `RemoveField` operations in the same migration/transaction as
    `fill_default_roles` fails with `cannot ALTER TABLE "iam_role" because it
    has pending trigger events`, since that data migration writes to `iam_role`
    (and `iam_folder`) earlier in the same transaction. Running them here, in a
    separate migration, avoids the conflict.
    """

    dependencies = [
        ('iam', '0030_alter_folder_default_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='idpgroup',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='role',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='roleassignment',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='serviceaccount',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='usergroup',
            name='is_published',
        ),
    ]
