# Generated by Django 6.1.1 on 2026-09-22 17:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iam", "0031_remove_iam_is_published_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username_hash", models.CharField(db_index=True, max_length=64)),
                ("ip", models.CharField(blank=True, default="", max_length=45)),
                ("failure_count", models.PositiveIntegerField(default=0)),
                (
                    "window_start",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("username_hash", "ip"), name="unique_login_attempt_key"
                    )
                ],
            },
        ),
    ]
