# Generated by Django 6.0.6 on 2026-07-21 11:06

import django.core.validators
import django.db.models.deletion
import iam.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0178_finding_asset_finding_requirement_node_and_more"),
        ("iam", "0023_alter_folder_content_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PostureAssessment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                ("eta", models.DateField(blank=True, null=True, verbose_name="ETA")),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="Due date"),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True,
                        default="1.0",
                        help_text="Version of the compliance assessment (eg. 1.0, 2.0, etc.)",
                        max_length=100,
                        null=True,
                        verbose_name="Version",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("planned", "Planned"),
                            ("in_progress", "In progress"),
                            ("in_review", "In review"),
                            ("done", "Done"),
                            ("deprecated", "Deprecated"),
                        ],
                        default="planned",
                        max_length=100,
                        null=True,
                        verbose_name="Status",
                    ),
                ),
                (
                    "observation",
                    models.TextField(blank=True, null=True, verbose_name="Observation"),
                ),
                (
                    "is_locked",
                    models.BooleanField(
                        default=False, null=True, verbose_name="Is locked"
                    ),
                ),
                (
                    "selected_implementation_groups",
                    models.JSONField(
                        blank=True,
                        null=True,
                        verbose_name="Selected implementation groups",
                    ),
                ),
                (
                    "history_depth",
                    models.PositiveSmallIntegerField(
                        default=10,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="History depth",
                    ),
                ),
                (
                    "ref_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="reference id",
                    ),
                ),
                (
                    "assets",
                    models.ManyToManyField(
                        blank=True,
                        related_name="posture_assessments",
                        to="core.asset",
                        verbose_name="Assets",
                    ),
                ),
                (
                    "authors",
                    models.ManyToManyField(
                        blank=True,
                        related_name="%(class)s_authors",
                        to="core.actor",
                        verbose_name="Authors",
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        default=iam.models.Folder.get_root_folder_id,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_folder",
                        to="iam.folder",
                    ),
                ),
                (
                    "follow_up_assessment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posture_assessments",
                        to="core.findingsassessment",
                        verbose_name="Follow-up assessment",
                    ),
                ),
                (
                    "framework",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.framework",
                        verbose_name="Framework",
                    ),
                ),
                (
                    "perimeter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.perimeter",
                        verbose_name="Perimeter",
                    ),
                ),
                (
                    "reviewers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="%(class)s_reviewers",
                        to="core.actor",
                        verbose_name="Reviewers",
                    ),
                ),
            ],
            options={
                "verbose_name": "Posture assessment",
                "verbose_name_plural": "Posture assessments",
            },
        ),
        migrations.CreateModel(
            name="PostureRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
                ("started_at", models.DateTimeField()),
                ("tool", models.CharField(blank=True, max_length=100)),
                (
                    "posture_assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="automation.postureassessment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Posture run",
                "verbose_name_plural": "Posture runs",
            },
        ),
        migrations.CreateModel(
            name="PostureResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("pass", "Pass"),
                            ("fail", "Fail"),
                            ("not_applicable", "Not applicable"),
                            ("error", "Error"),
                            ("not_checked", "Not checked"),
                        ],
                        default="not_checked",
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("actual", models.CharField(blank=True, max_length=255)),
                ("expected", models.CharField(blank=True, max_length=255)),
                ("message", models.TextField(blank=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("api", "API"),
                            ("import", "Import"),
                        ],
                        default="api",
                        max_length=10,
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posture_results",
                        to="core.asset",
                    ),
                ),
                (
                    "imported_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requirement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posture_results",
                        to="core.requirementnode",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="automation.posturerun",
                    ),
                ),
            ],
            options={
                "verbose_name": "Posture result",
                "verbose_name_plural": "Posture results",
            },
        ),
        migrations.AddIndex(
            model_name="posturerun",
            index=models.Index(
                fields=["posture_assessment", "started_at"],
                name="automation__posture_9a456d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="postureresult",
            index=models.Index(
                fields=["asset", "requirement", "timestamp"],
                name="automation__asset_i_f70eb4_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="postureresult",
            constraint=models.UniqueConstraint(
                fields=("run", "asset", "requirement"),
                name="unique_posture_result_per_run",
            ),
        ),
    ]
