# Generated by Django 6.0.7 on 2026-07-28 09:41

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("automation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="posturerun",
            name="attachment",
            field=models.FileField(
                blank=True,
                max_length=500,
                null=True,
                upload_to="",
                validators=[
                    core.validators.validate_file_size,
                    core.validators.validate_file_name,
                ],
                verbose_name="Attachment",
            ),
        ),
        migrations.AddField(
            model_name="posturerun",
            name="observation",
            field=models.TextField(blank=True, verbose_name="Observation"),
        ),
    ]
