# Generated by Django 6.0.8 on 2026-08-17 14:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("automation", "0003_workflow_engine"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="condition",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="conditionbranch",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="conditiongroup",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="postureassessment",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="postureresult",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="posturerun",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="workflow",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="workflowedge",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="workflowinstance",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="workflowinstancelog",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="workflownode",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="workflowsecret",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="workflowtoken",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="workflowtrigger",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="workflowvariable",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="workflowversion",
            name="is_published",
        ),
    ]
