# Generated by Django 6.0.8 on 2026-08-21 15:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("automation", "0003_workflow_engine"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowtoken",
            name="dispatch_id",
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
