# Generated by Django 6.0.8 on 2026-08-23 18:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("automation", "0004_workflowtoken_dispatch_id"),
        ("iam", "0027_cleanup_stray_domain_iam_groups"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowinstance",
            name="trigger_cid",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="workflowtrigger",
            name="last_result",
            field=models.CharField(
                blank=True,
                choices=[
                    ("triggered", "Triggered"),
                    ("skipped_overlap", "Skipped (previous run still active)"),
                    ("skipped_unpublished", "Skipped (unpublished)"),
                    ("skipped_depth", "Skipped (chain depth)"),
                    ("skipped_inactive", "Skipped (workflow inactive)"),
                    ("run_identity_missing", "Skipped (no run identity)"),
                    ("invalid_schedule", "Skipped (invalid schedule)"),
                    ("skipped_coalesced", "Skipped (same user action already handled)"),
                    ("error", "Error"),
                ],
                max_length=30,
            ),
        ),
        migrations.AddIndex(
            model_name="workflowinstance",
            index=models.Index(
                fields=["trigger_registration", "trigger_cid"],
                name="automation__trigger_70b335_idx",
            ),
        ),
    ]
