# coding:utf-8

url = "http://0.0.0.0:8000/"
core = url + "core/"
composer = core + "composer/"
login = url + "accounts/login/"
loginfirst = login + "?next=/"
logout = url + "accounts/logout/"
search = url + "search/"
xrays = url + "staff/x-rays"
calendar = core + "calendar/"
myprojects = core + "my-projects/"
analytics = core + "analytics/"
scoringassistant = core + "scoring-assistant/"
riskmatrix = core + "risk-matrix/"
ra = core + "RA/"