# coding:utf-8

URL = "http://127.0.0.1:8000/"
CORE = URL + "core/"
COMPOSER = CORE + "composer/"
LOGIN = URL + "accounts/login/"
LOGINFIRST = LOGIN + "?next=/"
LOGOUT = URL + "accounts/logout/"
SEARCH = URL + "search/"
XRAYS = URL + "staff/x-rays"
CALENDAR = CORE + "calendar/"
MYPROJECTS = CORE + "my-projects/"
OVERVIEW = CORE + "overview/"
SCORINGASSISTANT = CORE + "scoring-assistant/"
RISKMATRIX = CORE + "risk-matrix/"
RA = CORE + "RA/"
MAILHOG = "http://0.0.0.0:8025/"
RESET_DONE = URL + "password_reset/done/"
