# Generated by Django 5.0.4 on 2024-06-14 12:42

import django.db.models.deletion
import iam.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iam', '0003_alter_folder_updated_at_alter_role_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('name', models.CharField(choices=[('general', 'General'), ('sso', 'SSO')], default='general', max_length=30, primary_key=True, serialize=False, unique=True)),
                ('value', models.JSONField()),
                ('folder', models.ForeignKey(default=iam.models.Folder.get_root_folder, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_folder', to='iam.folder')),
            ],
        ),
    ]
