# Generated by Django 5.0.4 on 2024-06-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="globalsettings",
            name="value",
            field=models.JSONField(default=dict),
        ),
    ]
