{{- if .Values.huey.persistence.sqlite.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "ciso-assistant.fullname" . }}-huey-sqlite
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ciso-assistant.labels" (dict "context" . "component" "huey") | nindent 4 }}
spec:
  accessModes: 
    - {{ .Values.huey.persistence.sqlite.accessMode }}
  resources:
    requests:
      storage: {{ .Values.huey.persistence.sqlite.size }}
  {{- if .Values.huey.persistence.sqlite.storageClass }}
  storageClassName: {{ .Values.huey.persistence.sqlite.storageClass }}
  {{- end }}
{{- end }}
