# Generated by Django 5.1.10 on 2025-08-26 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crq', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quantitativeriskhypothesis',
            old_name='qantitative_risk_aggregations',
            new_name='quantitative_risk_aggregations',
        ),
    ]
