# Generated by Django 5.1.10 on 2025-09-08 07:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0093_appliedcontrol_cost_to_json"),
        ("crq", "0001_initial"),
        ("iam", "0014_user_observation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="quantitativeriskscenario",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Quantitative Risk Scenario",
                "verbose_name_plural": "Quantitative Risk Scenarios",
            },
        ),
        migrations.AddConstraint(
            model_name="quantitativeriskhypothesis",
            constraint=models.UniqueConstraint(
                fields=("quantitative_risk_scenario", "name"),
                name="unique_hypothesis_name_per_scenario",
            ),
        ),
        migrations.AddConstraint(
            model_name="quantitativeriskscenario",
            constraint=models.UniqueConstraint(
                fields=("quantitative_risk_study", "name"),
                name="unique_scenario_name_per_study",
            ),
        ),
    ]
