# Generated by Django 5.2.9 on 2026-01-08 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0127_appliedcontrol_new_owner_asset_new_owner_and_more'),
        ('crq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quantitativeriskscenario',
            name='new_owner',
            field=models.ManyToManyField(blank=True, related_name='quantitative_risk_scenarios', to='core.actor', verbose_name='Owner'),
        ),
    ]
