# Generated by Django 5.2.9 on 2026-01-09 14:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0130_remove_appliedcontrol_new_owner_and_more"),
        ("crq", "0002_quantitativeriskscenario_new_owner_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quantitativeriskscenario",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="quantitativeriskstudy",
            name="authors",
        ),
        migrations.RemoveField(
            model_name="quantitativeriskstudy",
            name="reviewers",
        ),
        migrations.RenameField(
            model_name="quantitativeriskscenario",
            old_name="new_owner",
            new_name="owner",
        ),
        migrations.RenameField(
            model_name="quantitativeriskstudy",
            old_name="new_authors",
            new_name="authors",
        ),
        migrations.RenameField(
            model_name="quantitativeriskstudy",
            old_name="new_reviewers",
            new_name="reviewers",
        ),
    ]
