# Generated by Django 5.2.9 on 2026-01-09 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0127_remove_appliedcontrol_new_owner_and_more"),
        ("crq", "0002_fix_folder_inheritance"),
        ("crq", "0002_quantitativeriskscenario_new_owner_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quantitativeriskscenario",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="quantitativeriskstudy",
            name="authors",
        ),
        migrations.RemoveField(
            model_name="quantitativeriskstudy",
            name="reviewers",
        ),
        migrations.RenameField(
            model_name="quantitativeriskscenario",
            old_name="new_owner",
            new_name="owner",
        ),
        migrations.RenameField(
            model_name="quantitativeriskstudy",
            old_name="new_authors",
            new_name="authors",
        ),
        migrations.RenameField(
            model_name="quantitativeriskstudy",
            old_name="new_reviewers",
            new_name="reviewers",
        ),
        migrations.AlterField(
            model_name="quantitativeriskstudy",
            name="authors",
            field=models.ManyToManyField(
                blank=True,
                related_name="quantitative_risk_study_authors",
                to="core.actor",
                verbose_name="Authors",
            ),
        ),
        migrations.AlterField(
            model_name="quantitativeriskstudy",
            name="reviewers",
            field=models.ManyToManyField(
                blank=True,
                related_name="quantitative_risk_study_reviewers",
                to="core.actor",
                verbose_name="Reviewers",
            ),
        ),
    ]
