# Generated by Django 6.0.8 on 2026-08-17 14:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("crq", "0003_remove_quantitativeriskscenario_new_owner_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quantitativeriskhypothesis",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="quantitativeriskscenario",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="quantitativeriskstudy",
            name="is_published",
        ),
    ]
