# Generated by Django 6.0.3 on 2026-03-16 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0148_alter_asset_dora_licenced_activity"),
        ("doc_management", "0002_documentattachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="manageddocument",
            name="default_locale",
            field=models.BooleanField(default=True, verbose_name="Default locale"),
        ),
        migrations.AddField(
            model_name="manageddocument",
            name="locale",
            field=models.CharField(default="en", max_length=100, verbose_name="Locale"),
        ),
        migrations.AlterField(
            model_name="manageddocument",
            name="policy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="core.policy",
            ),
        ),
    ]
