# Generated by Django 6.0.6 on 2026-07-01 15:41

import django.db.models.deletion
import iam.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0172_view_compliance_assessment_full_permission"),
        ("doc_management", "0002_sync_is_published"),
        ("iam", "0023_alter_folder_content_type"),
        ("privacy", "0018_alter_datatransfer_transfer_mechanism"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manageddocument",
            name="policy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="core.policy",
            ),
        ),
        migrations.CreateModel(
            name="DocumentContainer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("policy", "Policy"),
                            ("procedure", "Procedure"),
                            ("charter", "Charter"),
                            ("record", "Record"),
                            ("other", "Other"),
                        ],
                        default="policy",
                        max_length=20,
                        verbose_name="Document type",
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=200, verbose_name="Name"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "applied_controls",
                    models.ManyToManyField(
                        blank=True,
                        related_name="control_documents",
                        to="core.appliedcontrol",
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        default=iam.models.Folder.get_root_folder_id,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_folder",
                        to="iam.folder",
                    ),
                ),
                (
                    "policies",
                    models.ManyToManyField(
                        blank=True, related_name="documents", to="core.policy"
                    ),
                ),
                (
                    "processings",
                    models.ManyToManyField(
                        blank=True, related_name="documents", to="privacy.processing"
                    ),
                ),
                (
                    "task_templates",
                    models.ManyToManyField(
                        blank=True, related_name="documents", to="core.tasktemplate"
                    ),
                ),
            ],
            options={
                "verbose_name": "Document container",
                "verbose_name_plural": "Document containers",
            },
        ),
        migrations.AddField(
            model_name="manageddocument",
            name="container",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="doc_management.documentcontainer",
            ),
        ),
    ]
