# Generated by Django 6.0.6 on 2026-07-08 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0175_customdochtmltemplate_objectclassification_and_more"),
        ("doc_management", "0003_documents_management"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentcontainer",
            name="classification",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="core.classificationlevel",
                verbose_name="Classification",
            ),
        ),
        migrations.AddField(
            model_name="documentrevision",
            name="url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="documentrevision",
            name="source",
            field=models.CharField(
                choices=[
                    ("authored", "Authored"),
                    ("uploaded", "Uploaded"),
                    ("link", "Linked"),
                ],
                default="authored",
                max_length=20,
            ),
        ),
    ]
