# Generated by Django 6.0.6 on 2026-07-06 08:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doc_management", "0003_documents_management"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentrevision",
            name="url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="documentrevision",
            name="source",
            field=models.CharField(
                choices=[
                    ("authored", "Authored"),
                    ("uploaded", "Uploaded"),
                    ("link", "Linked"),
                ],
                default="authored",
                max_length=20,
            ),
        ),
    ]
