# Generated by Django 6.0.6 on 2026-07-01 17:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("doc_management", "0004_backfill_document_containers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="manageddocument",
            name="document_type",
        ),
        migrations.RemoveField(
            model_name="manageddocument",
            name="policy",
        ),
    ]
