# Generated by Django 6.0.6 on 2026-07-07 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0175_objectclassification_classificationlevel"),
        ("doc_management", "0004_documentrevision_url_alter_documentrevision_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentcontainer",
            name="classification",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="core.classificationlevel",
                verbose_name="Classification",
            ),
        ),
    ]
