# Generated by Django 6.0.6 on 2026-07-10 04:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doc_management", "0004_documentcontainer_classification_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentcontainer",
            name="ref_id",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Reference ID"
            ),
        ),
    ]
