# Generated by Django 6.0.6 on 2026-07-01 17:54

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doc_management", "0005_remove_manageddocument_document_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentrevision",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="",
                validators=[
                    core.validators.validate_file_size,
                    core.validators.validate_file_name,
                ],
            ),
        ),
        migrations.AddField(
            model_name="documentrevision",
            name="source",
            field=models.CharField(
                choices=[("authored", "Authored"), ("uploaded", "Uploaded")],
                default="authored",
                max_length=20,
            ),
        ),
    ]
