# Generated by Django 6.0.8 on 2026-08-17 14:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("doc_management", "0005_alter_documentrevision_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documentattachment",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="documentcontainer",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="documentedit",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="documentreference",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="documentrevision",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="documenttemplate",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="manageddocument",
            name="is_published",
        ),
    ]
