# Generated by Django 6.1.1 on 2026-09-15 15:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0188_quickformpublication_quickformresponse_and_more"),
        ("doc_management", "0006_remove_documentattachment_is_published_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentcontainer",
            name="assets",
            field=models.ManyToManyField(
                blank=True, related_name="documents", to="core.asset"
            ),
        ),
    ]
