# Generated by Django 6.0.6 on 2026-07-01 19:08

import django.db.models.deletion
import iam.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doc_management", "0006_documentrevision_file_documentrevision_source"),
        ("iam", "0023_alter_folder_content_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
                (
                    "locale",
                    models.CharField(
                        default="en", max_length=100, verbose_name="Locale"
                    ),
                ),
                (
                    "default_locale",
                    models.BooleanField(default=True, verbose_name="Default locale"),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("policy", "Policy"),
                            ("procedure", "Procedure"),
                            ("charter", "Charter"),
                            ("record", "Record"),
                            ("other", "Other"),
                        ],
                        default="policy",
                        max_length=20,
                        verbose_name="Document type",
                    ),
                ),
                ("ref_id", models.CharField(max_length=100, verbose_name="Reference")),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("content", models.TextField(blank=True)),
                ("category", models.CharField(blank=True, max_length=100)),
                ("builtin", models.BooleanField(default=False)),
                (
                    "folder",
                    models.ForeignKey(
                        default=iam.models.Folder.get_root_folder_id,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_folder",
                        to="iam.folder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document template",
                "verbose_name_plural": "Document templates",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("ref_id", "locale"), name="unique_template_ref_locale"
                    )
                ],
            },
        ),
    ]
