# Generated by Django 6.0.6 on 2026-07-02 06:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0172_view_compliance_assessment_full_permission"),
        ("doc_management", "0007_documenttemplate"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentcontainer",
            name="filtering_labels",
            field=models.ManyToManyField(
                blank=True, to="core.filteringlabel", verbose_name="Labels"
            ),
        ),
    ]
