# Generated by Django 6.0.6 on 2026-07-02 07:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doc_management", "0008_documentcontainer_filtering_labels"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentcontainer",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("policy", "Policy"),
                    ("procedure", "Procedure"),
                    ("charter", "Charter"),
                    ("record", "Record"),
                    ("meeting_minutes", "Meeting minutes"),
                    ("other", "Other"),
                ],
                default="policy",
                max_length=20,
                verbose_name="Document type",
            ),
        ),
        migrations.AlterField(
            model_name="documenttemplate",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("policy", "Policy"),
                    ("procedure", "Procedure"),
                    ("charter", "Charter"),
                    ("record", "Record"),
                    ("meeting_minutes", "Meeting minutes"),
                    ("other", "Other"),
                ],
                default="policy",
                max_length=20,
                verbose_name="Document type",
            ),
        ),
    ]
