# Generated by Django 6.0.6 on 2026-07-02 08:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("doc_management", "0009_alter_documentcontainer_document_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documenttemplate",
            name="category",
        ),
    ]
