# Generated by Django 6.0.6 on 2026-07-02 12:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doc_management", "0010_remove_documenttemplate_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentReference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
                (
                    "source_container",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_references",
                        to="doc_management.documentcontainer",
                    ),
                ),
                (
                    "target_container",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_references",
                        to="doc_management.documentcontainer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document reference",
                "verbose_name_plural": "Document references",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source_container", "target_container"),
                        name="unique_document_reference",
                    )
                ],
            },
        ),
    ]
