# Generated by Django 5.1.1 on 2024-12-03 16:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ebios_rm", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ebiosrmstudy",
            name="ref_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="fearedevent",
            name="ref_id",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
