# Generated by Django 5.1.4 on 2024-12-12 18:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ebios_rm", "0003_remove_ebiosrmstudy_risk_assessments"),
        ("ebios_rm", "0003_remove_roto_pertinence_alter_roto_feared_events"),
    ]

    operations = []
