# Generated by Django 5.1.4 on 2024-12-18 01:25

import core.validators
import ebios_rm.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ebios_rm", "0006_alter_attackpath_stakeholders"),
    ]

    operations = [
        migrations.AddField(
            model_name="ebiosrmstudy",
            name="meta",
            field=models.JSONField(
                default=ebios_rm.models.get_initial_meta,
                validators=[
                    core.validators.JSONSchemaInstanceValidator(
                        {
                            "$id": "https://ciso-assistant.com/schemas/ebiosrmstudy/meta.schema.json",
                            "$schema": "https://json-schema.org/draft/2020-12/schema",
                            "description": "Metadata of the EBIOS RM Study",
                            "properties": {
                                "workshops": {
                                    "description": "A list of workshops, each containing steps",
                                    "items": {
                                        "additionalProperties": False,
                                        "properties": {
                                            "steps": {
                                                "description": "The list of steps in the workshop",
                                                "items": {
                                                    "additionalProperties": False,
                                                    "properties": {
                                                        "status": {
                                                            "description": "The current status of the step",
                                                            "enum": [
                                                                "to_do",
                                                                "in_progress",
                                                                "done",
                                                            ],
                                                            "type": "string",
                                                        }
                                                    },
                                                    "required": ["status"],
                                                    "type": "object",
                                                },
                                                "type": "array",
                                            }
                                        },
                                        "required": ["steps"],
                                        "type": "object",
                                    },
                                    "type": "array",
                                }
                            },
                            "title": "Metadata",
                            "type": "object",
                        }
                    )
                ],
                verbose_name="Metadata",
            ),
        ),
    ]
