# Generated by Django 5.1.4 on 2024-12-21 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0046_riskassessment_ebios_rm_study"),
        ("ebios_rm", "0009_alter_roto_activity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ebiosrmstudy",
            name="risk_matrix",
            field=models.ForeignKey(
                blank=True,
                help_text="Risk matrix used as a reference for the study",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ebios_rm_studies",
                to="core.riskmatrix",
                verbose_name="Risk matrix",
            ),
        ),
    ]
