# Generated by Django 5.1.4 on 2024-12-30 01:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ebios_rm", "0010_alter_ebiosrmstudy_risk_matrix"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roto",
            name="risk_origin",
            field=models.CharField(
                choices=[
                    ("state", "State"),
                    ("organized_crime", "Organized crime"),
                    ("terrorist", "Terrorist"),
                    ("activist", "Activist"),
                    ("competitor", "Competitor"),
                    ("amateur", "Amateur"),
                    ("avenger", "Avenger"),
                    ("pathological", "Pathological"),
                ],
                max_length=32,
                verbose_name="Risk origin",
            ),
        ),
    ]
