# Generated by Django 5.1.10 on 2025-08-28 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0092_terminology"),
        (
            "ebios_rm",
            "0012_ebiosrmstudy_quotation_method_alter_roto_risk_origin_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="roto",
            name="risk_origin_fk",
            field=models.ForeignKey(
                to="core.Terminology",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="roto_risk_origins",
                limit_choices_to={
                    "field_path": "ro_to.risk_origin",
                    "is_visible": True,
                },
                null=True,
            ),
        ),
    ]
