# Generated by Django 5.1.10 on 2025-08-28 21:26

import django.db.models.deletion
from django.db import migrations, models


def migrate_risk_origin(apps, schema_editor):
    Roto = apps.get_model('ebios_rm', 'Roto')
    Terminology = apps.get_model('core', 'Terminology')

    for roto in Roto.objects.all():
        if roto.risk_origin:
            try:
                term = Terminology.objects.get(name=roto.risk_origin)
                roto.risk_origin_fk = term
                roto.save()
            except Terminology.DoesNotExist:
                pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0092_terminology'),
        ('ebios_rm', '0012_ebiosrmstudy_quotation_method_alter_roto_risk_origin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roto',
            name='risk_origin_fk',
            field=models.ForeignKey(
                to='core.Terminology',
                on_delete=models.PROTECT,
                related_name='roto_risk_origins',
                limit_choices_to={'field_path': 'ro_to.risk_origin', 'is_visible': True},
                null=True,
            ),
        ),
        migrations.RunPython(migrate_risk_origin),
        migrations.RemoveField(
            model_name='roto',
            name='risk_origin',
        ),
        migrations.AlterField(
            model_name='roto',
            name='risk_origin_fk',
            field=models.ForeignKey(
                to='core.Terminology',
                on_delete=models.PROTECT,
                related_name='roto_risk_origins',
                limit_choices_to={'field_path': 'ro_to.risk_origin', 'is_visible': True},
            ),
        ),
        migrations.RenameField(
            model_name='roto',
            old_name='risk_origin_fk',
            new_name='risk_origin',
        ),
    ]
