# Generated by Django 5.1.10 on 2025-08-28 14:56

import django.db.models.deletion
from django.db import migrations, models


def migrate_risk_origin(apps, schema_editor):
    RoTo = apps.get_model("ebios_rm", "RoTo")
    Terminology = apps.get_model("core", "Terminology")

    values = [
        "state",
        "organized_crime",
        "terrorist",
        "activist",
        "competitor",
        "amateur",
        "avenger",
        "pathological",
        "other",
    ]

    for key in values:
        term, _ = Terminology.objects.get(field_path="ro_to.risk_origin", name=key)
        RoTo.objects.filter(risk_origin=key).update(risk_origin=term.id)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0092_terminology"),
        (
            "ebios_rm",
            "0012_ebiosrmstudy_quotation_method_alter_roto_risk_origin_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="roto",
            name="risk_origin",
            field=models.ForeignKey(
                limit_choices_to={
                    "field_path": "ro_to.risk_origin",
                    "is_visible": True,
                },
                on_delete=django.db.models.deletion.PROTECT,
                related_name="roto_risk_origins",
                to="core.terminology",
                verbose_name="Risk origin",
            ),
        ),
        migrations.RunPython(migrate_risk_origin),
    ]
