# Generated by Django 5.1.10 on 2025-07-09 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebios_rm', '0012_ebiosrmstudy_quotation_method_elementaryaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementaryaction',
            name='icon',
            field=models.CharField(blank=True, choices=[('server', 'Server'), ('computer', 'Computer'), ('cloud', 'Cloud'), ('file', 'File'), ('diamond', 'Diamond'), ('phone', 'Phone'), ('cube', 'Cube'), ('blocks', 'Blocks'), ('shapes', 'Shapes'), ('network', 'Network'), ('database', 'Database'), ('key', 'Key')], help_text='Icon representing the elementary action', max_length=100, null=True, verbose_name='Icon'),
        ),
    ]
