# Generated by Django 5.1.10 on 2025-08-28 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0094_alter_terminology_field_path'),
        ('ebios_rm', '0013_alter_roto_risk_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roto',
            name='risk_origin',
            field=models.ForeignKey(limit_choices_to={'field_path': 'ro_to/risk_origin', 'is_visible': True}, on_delete=django.db.models.deletion.PROTECT, related_name='roto_risk_origins', to='core.terminology', verbose_name='Risk origin'),
        ),
    ]
