# Generated by Django 5.1.10 on 2025-08-28 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ebios_rm", "0014_migrate_risk_origin"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="roto",
            name="risk_origin",
        ),
        migrations.AlterField(
            model_name="roto",
            name="risk_origin_fk",
            field=models.ForeignKey(
                limit_choices_to={
                    "field_path": "ro_to.risk_origin",
                    "is_visible": True,
                },
                on_delete=django.db.models.deletion.PROTECT,
                related_name="roto_risk_origins",
                to="core.terminology",
                verbose_name="Risk origin",
            ),
        ),
        migrations.RenameField(
            model_name="roto",
            old_name="risk_origin_fk",
            new_name="risk_origin",
        ),
    ]
