# Generated by Django 5.2.7 on 2025-10-08 10:08

import django.db.models.deletion
from django.db import migrations, models


def migrate_category_to_terminology(apps, schema_editor):
    Stakeholder = apps.get_model("ebios_rm", "Stakeholder")
    Terminology = apps.get_model("core", "Terminology")

    # Mapping of old category values to terminology names
    category_mapping = {
        "client": "client",
        "partner": "partner",
        "supplier": "supplier",
    }

    for stakeholder in Stakeholder.objects.all():
        if stakeholder.category_old:
            terminology_name = category_mapping.get(stakeholder.category_old)
            if terminology_name:
                try:
                    terminology = Terminology.objects.get(
                        name=terminology_name, field_path="entity.relationship"
                    )
                    stakeholder.category = terminology
                    stakeholder.save(update_fields=["category"])
                except Terminology.DoesNotExist:
                    print(
                        f"Warning: Terminology '{terminology_name}' not found for stakeholder {stakeholder.id}"
                    )


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0104_add_info_severity"),
        ("ebios_rm", "0016_alter_fearedevent_qualifications"),
    ]

    operations = [
        # Step 1: Rename old category field to category_old
        migrations.RenameField(
            model_name="stakeholder",
            old_name="category",
            new_name="category_old",
        ),
        # Step 2: Add new category field as ForeignKey (nullable temporarily)
        migrations.AddField(
            model_name="stakeholder",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                limit_choices_to={
                    "field_path": "entity.relationship",
                    "is_visible": True,
                },
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stakeholders_category",
                to="core.terminology",
                verbose_name="Category",
            ),
        ),
        # Step 3: Migrate data from category_old to category
        migrations.RunPython(
            migrate_category_to_terminology, migrations.RunPython.noop
        ),
        # Step 4: Make category non-nullable
        migrations.AlterField(
            model_name="stakeholder",
            name="category",
            field=models.ForeignKey(
                limit_choices_to={
                    "field_path": "entity.relationship",
                    "is_visible": True,
                },
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stakeholders_category",
                to="core.terminology",
                verbose_name="Category",
            ),
        ),
        # Step 5: Remove old category field
        migrations.RemoveField(
            model_name="stakeholder",
            name="category_old",
        ),
    ]
