# Generated by Django 5.2.7 on 2025-10-07 18:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ebios_rm", "0016_alter_fearedevent_qualifications"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operationalscenario",
            name="operating_modes_description",
            field=models.TextField(
                blank=True,
                help_text="Description of the operating modes of the operational scenario",
                verbose_name="Operating modes description",
            ),
        ),
    ]
