# Generated by Django 5.2.7 on 2025-11-17 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ebios_rm", "0018_convert_stakeholder_category_to_terminology"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ebiosrmstudy",
            name="quotation_method",
            field=models.CharField(
                choices=[("manual", "Manual"), ("express", "Express")],
                default="express",
                help_text="Method used to quote the study: 'manual' for manual likelihood assessment, 'express' for automatic propagation from operating modes",
                max_length=100,
                verbose_name="Quotation method",
            ),
        ),
    ]
