# Generated by Django 5.2.7 on 2025-12-11 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ebios_rm", "0019_alter_ebiosrmstudy_quotation_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fearedevent",
            name="ebios_rm_study",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feared_events",
                to="ebios_rm.ebiosrmstudy",
                verbose_name="EBIOS RM study",
            ),
        ),
    ]
