# Generated by Django 5.2.6 on 2025-10-13 13:30
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ebios_rm", "0019_stakeholder_data_migration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stakeholder",
            name="category",
            field=models.ForeignKey(
                # null=True and blank=True are removed
                limit_choices_to={
                    "field_path": "entity.relationship",
                    "is_visible": True,
                },
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stakeholders_category",
                to="core.terminology",
                verbose_name="Category",
            ),
        ),
        migrations.RemoveField(
            model_name="stakeholder",
            name="category_old",
        ),
    ]
