# Generated by Django 5.2.9 on 2025-12-26 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ebios_rm", "0020_alter_fearedevent_ebios_rm_study"),
    ]

    operations = [
        migrations.AddField(
            model_name="strategicscenario",
            name="focused_feared_event",
            field=models.ForeignKey(
                blank=True,
                help_text="Override gravity with this specific feared event's gravity",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="focused_strategic_scenarios",
                to="ebios_rm.fearedevent",
                verbose_name="Focused feared event",
            ),
        ),
    ]
