# Generated by Django 5.2.9 on 2026-01-09 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0127_appliedcontrol_new_owner_asset_new_owner_and_more"),
        ("ebios_rm", "0021_strategicscenario_focused_feared_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="ebiosrmstudy",
            name="new_authors",
            field=models.ManyToManyField(
                blank=True,
                related_name="ebios_rm_study_authors_new",
                to="core.actor",
                verbose_name="Authors",
            ),
        ),
        migrations.AddField(
            model_name="ebiosrmstudy",
            name="new_reviewers",
            field=models.ManyToManyField(
                blank=True,
                related_name="ebios_rm_study_reviewers_new",
                to="core.actor",
                verbose_name="Reviewers",
            ),
        ),
    ]
