# Generated by Django 5.2.9 on 2026-01-09 14:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0130_remove_appliedcontrol_new_owner_and_more"),
        ("ebios_rm", "0022_ebiosrmstudy_new_authors_ebiosrmstudy_new_reviewers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ebiosrmstudy",
            name="authors",
        ),
        migrations.RemoveField(
            model_name="ebiosrmstudy",
            name="reviewers",
        ),
        migrations.RenameField(
            model_name="ebiosrmstudy",
            old_name="new_authors",
            new_name="authors",
        ),
        migrations.RenameField(
            model_name="ebiosrmstudy",
            old_name="new_reviewers",
            new_name="reviewers",
        ),
    ]
