# Generated by Django 6.0.2 on 2026-03-02 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ebios_rm", "0023_remove_ebiosrmstudy_new_authors_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="operatingmode",
            name="elementary_actions",
        ),
        migrations.AddField(
            model_name="killchain",
            name="position_x",
            field=models.FloatField(
                default=0, help_text="X position of the node in the graph editor"
            ),
        ),
        migrations.AddField(
            model_name="killchain",
            name="position_y",
            field=models.FloatField(
                default=0, help_text="Y position of the node in the graph editor"
            ),
        ),
        migrations.AddField(
            model_name="operatingmode",
            name="graph_columns",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Stage column positions and sizes in the graph editor",
            ),
        ),
    ]
