# Generated by Django 5.2.9 on 2026-02-04 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ebios_rm", "0023_remove_ebiosrmstudy_new_authors_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attackpath",
            name="ebios_rm_study",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attack_paths",
                to="ebios_rm.ebiosrmstudy",
                verbose_name="EBIOS RM study",
            ),
        ),
        migrations.AlterField(
            model_name="roto",
            name="ebios_rm_study",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rotos",
                to="ebios_rm.ebiosrmstudy",
                verbose_name="EBIOS RM study",
            ),
        ),
    ]
