# Generated by Django 6.0.7 on 2026-07-28 07:08

from django.db import migrations, models


def update_is_published(apps, schema_editor):
    ElementaryAction = apps.get_model("ebios_rm", "ElementaryAction")
    ElementaryAction.objects.update(is_published=True)


class Migration(migrations.Migration):
    dependencies = [
        ("ebios_rm", "0024_remove_operatingmode_elementary_actions_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="elementaryaction",
            name="is_published",
            field=models.BooleanField(default=True, verbose_name="published"),
        ),
        migrations.RunPython(update_is_published),
    ]
