# Generated by Django 6.0.4 on 2026-04-23 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ebios_rm", "0024_remove_operatingmode_elementary_actions_and_more"),
        ("tprm", "0017_entityassessment_reference_link"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stakeholder",
            name="entity",
        ),
        migrations.AddField(
            model_name="stakeholder",
            name="entity_name",
            field=models.TextField(default="", verbose_name="Entity name"),
        ),
        migrations.AddField(
            model_name="stakeholder",
            name="third_party_entity",
            field=models.ForeignKey(
                blank=True,
                help_text="Related third party entity",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stakeholders",
                to="tprm.entity",
                verbose_name="Third Party Entity",
            ),
        ),
    ]
