# Generated by Django 5.2.11 on 2026-03-06 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ebios_rm", "0024_remove_operatingmode_elementary_actions_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attackpath",
            name="ebios_rm_study",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attack_paths",
                to="ebios_rm.ebiosrmstudy",
                verbose_name="EBIOS RM study",
            ),
        ),
        migrations.AlterField(
            model_name="roto",
            name="ebios_rm_study",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rotos",
                to="ebios_rm.ebiosrmstudy",
                verbose_name="EBIOS RM study",
            ),
        ),
    ]
