# Generated by Django 6.0.8 on 2026-08-17 14:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ebios_rm", "0025_alter_elementaryaction_is_published"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attackpath",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="ebiosrmstudy",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="elementaryaction",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="fearedevent",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="killchain",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="operatingmode",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="operationalscenario",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="roto",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="stakeholder",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="strategicscenario",
            name="is_published",
        ),
    ]
