# Generated by Django 6.1.1 on 2026-09-21 16:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ebios_rm", "0026_remove_attackpath_is_published_and_more"),
        ("sec_intel", "0003_remove_cwe_is_published_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="operationalscenario",
            name="techniques",
            field=models.ManyToManyField(
                blank=True,
                help_text="Adversary techniques leveraged by the operational scenario",
                related_name="operational_scenarios",
                to="sec_intel.technique",
                verbose_name="Techniques",
            ),
        ),
    ]
