# Generated by Django 6.1.1 on 2026-10-01 13:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def antecedent_actions_to_steps(apps, schema_editor):
    """Antecedents pointed at elementary actions; point them at the step of the
    same operating mode that uses that action (unique per mode until now)."""
    KillChain = apps.get_model("ebios_rm", "KillChain")
    for step in KillChain.objects.prefetch_related("antecedents"):
        for action in step.antecedents.all():
            antecedent = (
                KillChain.objects.filter(
                    operating_mode_id=step.operating_mode_id,
                    elementary_action_id=action.id,
                )
                .exclude(pk=step.pk)
                .first()
            )
            if antecedent is not None:
                step.antecedent_steps.add(antecedent)


def antecedent_steps_to_actions(apps, schema_editor):
    KillChain = apps.get_model("ebios_rm", "KillChain")
    for step in KillChain.objects.prefetch_related("antecedent_steps"):
        step.antecedents.set(
            [
                antecedent.elementary_action_id
                for antecedent in step.antecedent_steps.all()
            ]
        )


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0190_compliance_assessment_score_scale"),
        ("ebios_rm", "0027_operationalscenario_techniques"),
        ("pmbok", "0008_remove_accreditation_is_published_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ebiosrmstudy",
            name="classification",
            field=models.ForeignKey(
                blank=True,
                help_text="Protection marking of the study",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="core.classificationlevel",
                verbose_name="Classification",
            ),
        ),
        migrations.AddField(
            model_name="ebiosrmstudy",
            name="constraints_hypotheses",
            field=models.TextField(
                blank=True, verbose_name="Constraints and hypotheses"
            ),
        ),
        migrations.AddField(
            model_name="ebiosrmstudy",
            name="objectives",
            field=models.TextField(blank=True, verbose_name="Objectives"),
        ),
        migrations.AddField(
            model_name="ebiosrmstudy",
            name="responsibility_matrix",
            field=models.ForeignKey(
                blank=True,
                help_text="RACI of the study participants",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ebios_rm_studies",
                to="pmbok.responsibilitymatrix",
                verbose_name="Responsibility matrix",
            ),
        ),
        migrations.AddField(
            model_name="killchain",
            name="assets",
            field=models.ManyToManyField(
                blank=True,
                help_text="Supporting assets this elementary action applies to",
                related_name="kill_chain_steps",
                to="core.asset",
                verbose_name="Supporting assets",
            ),
        ),
        migrations.AddField(
            model_name="killchain",
            name="success_probability",
            field=models.SmallIntegerField(
                default=-1,
                help_text="Level on the study's likelihood scale, -1 when not rated",
                verbose_name="Success probability",
            ),
        ),
        migrations.AddField(
            model_name="killchain",
            name="success_probability_pct",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Success probability (%)",
            ),
        ),
        migrations.AddField(
            model_name="killchain",
            name="technical_difficulty",
            field=models.SmallIntegerField(
                default=-1,
                help_text="Level on the study's likelihood scale, -1 when not rated",
                verbose_name="Technical difficulty",
            ),
        ),
        migrations.AlterField(
            model_name="ebiosrmstudy",
            name="quotation_method",
            field=models.CharField(
                choices=[
                    ("manual", "quotationMethodExpressDirect"),
                    ("express", "quotationMethodExpressOperatingModes"),
                    ("standard", "quotationMethodStandard"),
                    ("advanced", "quotationMethodAdvanced"),
                ],
                default="express",
                help_text="Likelihood method: 'manual' and 'express' are variants of the guide's express method (direct estimate, most likely operating mode); 'standard' and 'advanced' rate each elementary action",
                max_length=100,
                verbose_name="Quotation method",
            ),
        ),
        migrations.AddField(
            model_name="killchain",
            name="antecedent_steps",
            field=models.ManyToManyField(
                blank=True,
                help_text="Kill chain steps of the same operating mode that precede this step",
                related_name="successors",
                to="ebios_rm.killchain",
            ),
        ),
        migrations.RunPython(antecedent_actions_to_steps, antecedent_steps_to_actions),
        migrations.RemoveField(
            model_name="killchain",
            name="antecedents",
        ),
        migrations.RenameField(
            model_name="killchain",
            old_name="antecedent_steps",
            new_name="antecedents",
        ),
    ]
