# Generated by Django 6.0.4 on 2026-04-23 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebios_rm', '0027_alter_stakeholder_third_party_entity'),
        ('tprm', '0017_entityassessment_reference_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stakeholder',
            name='third_party_entity',
            field=models.ForeignKey(blank=True, help_text='Related third party entity', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stakeholders', to='tprm.entity', verbose_name='Third Party Entity'),
        ),
    ]
