# Generated by Django 6.0.8 on 2026-08-17 00:50

import django.db.models.deletion
import iam.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0181_customizable_asset_classes'),
        ('iam', '0026_delete_cacheversion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RemediationIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_published', models.BooleanField(default=False, verbose_name='published')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('ref_id', models.CharField(blank=True, max_length=100, verbose_name='Reference ID')),
                ('priority', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'P1'), (2, 'P2'), (3, 'P3'), (4, 'P4')], null=True, verbose_name='Priority')),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_discussion', 'In discussion'), ('in_remediation', 'In remediation'), ('in_review', 'In review'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='planned', max_length=32, verbose_name='Status')),
                ('resolution', models.CharField(blank=True, choices=[('remediated', 'Remediated'), ('accepted_as_is', 'Accepted as-is'), ('not_applicable', 'Not applicable')], max_length=32, verbose_name='Resolution')),
                ('closure_justification', models.TextField(blank=True, verbose_name='Closure justification')),
                ('cancellation_reason', models.CharField(blank=True, choices=[('duplicate', 'Duplicate'), ('superseded', 'Superseded'), ('withdrawn', 'Withdrawn'), ('created_in_error', 'Created in error'), ('other', 'Other')], max_length=32, verbose_name='Cancellation reason')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Closed at')),
                ('applied_controls', models.ManyToManyField(blank=True, related_name='remediation_issues', to='core.appliedcontrol', verbose_name='Applied controls')),
                ('evidences', models.ManyToManyField(blank=True, related_name='remediation_issues', to='core.evidence', verbose_name='Evidences')),
                ('filtering_labels', models.ManyToManyField(blank=True, to='core.filteringlabel', verbose_name='Labels')),
                ('findings', models.ManyToManyField(blank=True, related_name='remediation_issues', to='core.finding', verbose_name='Findings')),
                ('folder', models.ForeignKey(default=iam.models.Folder.get_root_folder_id, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_folder', to='iam.folder')),
                ('lead_contributors', models.ManyToManyField(blank=True, related_name='lead_contributor_issues', to='core.actor', verbose_name='Lead contributors')),
                ('lead_representatives', models.ManyToManyField(blank=True, related_name='lead_representative_issues', to='core.actor', verbose_name='Lead representatives')),
                ('requirement_assessments', models.ManyToManyField(blank=True, related_name='remediation_issues', to='core.requirementassessment', verbose_name='Requirement assessments')),
                ('respondent_contributors', models.ManyToManyField(blank=True, related_name='respondent_contributor_issues', to='core.actor', verbose_name='Respondent contributors')),
                ('respondent_representatives', models.ManyToManyField(blank=True, related_name='respondent_representative_issues', to='core.actor', verbose_name='Respondent representatives')),
            ],
            options={
                'verbose_name': 'Remediation issue',
                'verbose_name_plural': 'Remediation issues',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommitmentVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_published', models.BooleanField(default=False, verbose_name='published')),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('text', models.TextField(verbose_name='Commitment')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Due date')),
                ('author_side', models.CharField(choices=[('lead', 'Lead'), ('respondent', 'Respondent')], max_length=16)),
                ('lead_acceptance', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('changes_requested', 'Changes requested')], default='pending', max_length=20)),
                ('lead_acceptance_at', models.DateTimeField(blank=True, null=True)),
                ('respondent_acceptance', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('changes_requested', 'Changes requested')], default='pending', max_length=20)),
                ('respondent_acceptance_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_commitment_versions', to=settings.AUTH_USER_MODEL)),
                ('folder', models.ForeignKey(default=iam.models.Folder.get_root_folder_id, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_folder', to='iam.folder')),
                ('lead_acceptance_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('respondent_acceptance_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commitment_versions', to='issues.remediationissue', verbose_name='Issue')),
            ],
            options={
                'verbose_name': 'Commitment version',
                'verbose_name_plural': 'Commitment versions',
                'ordering': ['-version_number'],
                'constraints': [models.UniqueConstraint(fields=('issue', 'version_number'), name='unique_commitment_version_per_issue')],
            },
        ),
    ]
