{{- if not .Values.backend.config.oidcProvider.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ciso-assistant.idpOidcSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ciso-assistant.labels" (dict "context" . "component" "backend") | nindent 4 }}
type: Opaque
data:
  idp-oidc-private-key: {{ include "ciso-assistant.idpOidcPrivateKey" . | b64enc | quote }}
{{- end }}
