{{- if or .Values.backend.config.smtp.primary.password .Values.backend.config.smtp.rescue.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ciso-assistant.fullname" . }}-backend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ciso-assistant.labels" (dict "context" . "name" .Values.backend.name "component" .Values.backend.name) | nindent 4 }}
type: Opaque
data:
  django-secret-key: {{ .Values.backend.config.djangoSecretKey | b64enc | quote}}
  {{- if .Values.backend.config.smtp.primary.password }}
  email-primary-password: {{ .Values.backend.config.smtp.primary.password | b64enc | quote}}
  {{- end }}
  {{- if .Values.backend.config.smtp.rescue.password }}
  email-rescue-password: {{ .Values.backend.config.smtp.rescue.password | b64enc | quote}}
  {{- end }}
{{- end }}