{{- if or (and (not .Values.backend.config.smtp.existingSecret) (or .Values.backend.config.smtp.primary.password (and .Values.backend.config.smtp.rescue.enabled .Values.backend.config.smtp.rescue.password))) (and (not .Values.backend.config.djangoExistingSecretKey) .Values.backend.config.djangoSecretKey) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ciso-assistant.fullname" . }}-backend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ciso-assistant.labels" (dict "context" . "name" .Values.backend.name "component" .Values.backend.name) | nindent 4 }}
type: Opaque
data:
  {{- if and (not .Values.backend.config.djangoExistingSecretKey) .Values.backend.config.djangoSecretKey }}
  django-secret-key: {{ .Values.backend.config.djangoSecretKey | b64enc | quote}}
  {{- end }}
  {{- if and (not .Values.backend.config.smtp.existingSecret) .Values.backend.config.smtp.primary.password }}
  email-primary-password: {{ .Values.backend.config.smtp.primary.password | b64enc | quote}}
  {{- end }}
  {{- if and (not .Values.backend.config.smtp.existingSecret) .Values.backend.config.smtp.rescue.enabled .Values.backend.config.smtp.rescue.password }}
  email-rescue-password: {{ .Values.backend.config.smtp.rescue.password | b64enc | quote}}
  {{- end }}
{{- end }}
