# Generated by Django 3.2.13 on 2022-06-02 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('type', models.CharField(choices=[('undefined', '--'), ('cs', 'control systems'), ('das', 'data acquisition systems'), ('ne', 'networking equipment'), ('hpvms', 'hardware platforms for virtual machines or storage')], default='undefined', max_length=20, verbose_name='type')),
            ],
            options={
                'verbose_name': 'asset',
                'verbose_name_plural': 'assets',
            },
        ),
        migrations.AlterModelOptions(
            name='parentrisk',
            options={'verbose_name': 'Threat', 'verbose_name_plural': 'Threats'},
        ),
        migrations.AlterField(
            model_name='project',
            name='parent_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.projectsgroup', verbose_name='Parent domain'),
        ),
    ]
