# Generated by Django 3.2.13 on 2022-06-02 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_auto_20220602_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='is_critical',
            field=models.BooleanField(default=False, verbose_name='critical'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='type',
            field=models.CharField(choices=[('undefined', '--'), ('cs', 'Control Systems'), ('das', 'Data Acquisition Systems'), ('ne', 'Networking Equipment'), ('hpvms', 'Hardware Platforms for Virtual Machines or Storage')], default='undefined', max_length=20, verbose_name='type'),
        ),
    ]
