# Generated by Django 3.2.13 on 2022-06-02 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_auto_20220602_1135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'verbose_name': 'Asset', 'verbose_name_plural': 'Assets'},
        ),
        migrations.RemoveField(
            model_name='asset',
            name='is_critical',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='type',
        ),
        migrations.AddField(
            model_name='asset',
            name='business_value',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='parentrisk',
            name='title',
            field=models.CharField(default='<threat short title>', max_length=200, verbose_name='Title'),
        ),
    ]
