# Generated by Django 3.2.13 on 2022-06-17 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_auto_20220602_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='business_value',
            field=models.TextField(blank=True, verbose_name='business value'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='comments',
            field=models.TextField(blank=True, verbose_name='comments'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='lc_status',
            field=models.CharField(choices=[('undefined', '--'), ('in_design', 'Design'), ('in_dev', 'Development'), ('in_prod', 'Production'), ('eol', 'End Of Life'), ('dropped', 'Dropped')], default='in_design', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='project',
            name='parent_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.projectsgroup', verbose_name='Domain'),
        ),
    ]
