apiVersion: v1
kind: ConfigMap
metadata:
  name: ciso-assistant-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
data:
  DEFAULT_FROM_EMAIL: {{ .Values.email.defaultFrom | quote }}
  DJANGO_DEBUG: {{ .Values.email.debug | quote }}
  EMAIL_HOST: {{ .Values.email.primary.host | quote }}
  EMAIL_HOST_RESCUE: {{ .Values.email.rescue.host | quote }}
  EMAIL_HOST_USER: {{ .Values.email.primary.user | quote }}
  EMAIL_HOST_USER_RESCUE: {{ .Values.email.rescue.user | quote }}
  EMAIL_PORT: {{ .Values.email.primary.port | quote }}
  EMAIL_PORT_RESCUE: {{ .Values.email.rescue.port | quote }}
  EMAIL_USE_TLS: {{ .Values.email.primary.useTls | quote }}
  EMAIL_USE_TLS_RESCUE: {{ .Values.email.rescue.useTls | quote }}
  BODY_SIZE_LIMIT: {{ .Values.bodySizeLimit | quote }}
