apiVersion: v1
kind: Secret
metadata:
  name: smtp-out
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  EMAIL_HOST_PASSWORD: {{ .Values.email.primary.password | b64enc }}
  EMAIL_HOST_PASSWORD_RESCUE: {{ .Values.email.rescue.password | b64enc }}