apiVersion: v1
kind: Service
metadata:
  name: ciso-assistant-{{ .Values.clientName }}
  labels:
    client: {{ .Values.clientName }}
    {{- include "common.labels" . | nindent 4 }}
spec:
  ports:
  - name: backend
    port: 8000
    protocol: TCP
    targetPort: 8000
  - name: frontend
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: ciso-assistant
    client: {{ .Values.clientName }}
  type: ClusterIP
