# Generated by Django 5.1.10 on 2025-08-20 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resilience", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessimpactanalysis",
            name="is_locked",
            field=models.BooleanField(default=False, verbose_name="Is locked"),
        ),
    ]
