# Generated by Django 5.1.10 on 2025-08-22 08:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resilience", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessimpactanalysis",
            name="is_locked",
            field=models.BooleanField(
                default=False, null=True, verbose_name="Is locked"
            ),
        ),
    ]
