# Generated by Django 5.1.8 on 2025-05-07 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resilience", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assetassessment",
            name="observation",
            field=models.TextField(blank=True, null=True),
        ),
    ]
