# Generated by Django 5.1.8 on 2025-05-07 10:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resilience", "0002_assetassessment_observation"),
    ]

    operations = [
        migrations.AddField(
            model_name="assetassessment",
            name="recovery_tested",
            field=models.BooleanField(default=False),
        ),
    ]
