# Generated by Django 5.1.8 on 2025-05-05 17:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0070_auto_fix_finding_folider"),
        ("resilience", "0002_assetassessment_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assetassessment",
            name="associated_controls",
            field=models.ManyToManyField(blank=True, to="core.appliedcontrol"),
        ),
        migrations.AlterField(
            model_name="assetassessment",
            name="dependencies",
            field=models.ManyToManyField(
                blank=True, related_name="dependencies", to="core.asset"
            ),
        ),
    ]
