# Generated by Django 5.1.10 on 2025-08-29 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0092_qualification_library_and_more'),
        ('resilience', '0002_businessimpactanalysis_is_locked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escalationthreshold',
            name='qualifications',
            field=models.ManyToManyField(blank=True, related_name='escalation_thresholds', to='core.qualification'),
        ),
    ]
