# Generated by Django 5.1.8 on 2025-05-05 18:15

import django.db.models.deletion
import iam.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iam", "0011_replace_slash_in_folder_names"),
        ("resilience", "0003_alter_assetassessment_associated_controls_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assetassessment",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="assetassessment",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="assetassessment",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="escalationthreshold",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="escalationthreshold",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="escalationthreshold",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="assetassessment",
            name="folder",
            field=models.ForeignKey(
                default=iam.models.Folder.get_root_folder_id,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_folder",
                to="iam.folder",
            ),
        ),
        migrations.AddField(
            model_name="escalationthreshold",
            name="folder",
            field=models.ForeignKey(
                default=iam.models.Folder.get_root_folder_id,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_folder",
                to="iam.folder",
            ),
        ),
        migrations.AlterField(
            model_name="assetassessment",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="escalationthreshold",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
