# Generated by Django 5.1.8 on 2025-05-07 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resilience", "0003_assetassessment_recovery_tested"),
    ]

    operations = [
        migrations.AddField(
            model_name="assetassessment",
            name="met_recovery_targets",
            field=models.BooleanField(default=False),
        ),
    ]
