# Generated by Django 5.2.9 on 2026-01-08 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0127_appliedcontrol_new_owner_asset_new_owner_and_more"),
        ("resilience", "0003_alter_escalationthreshold_qualifications"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessimpactanalysis",
            name="new_authors",
            field=models.ManyToManyField(
                blank=True,
                related_name="%(class)s_authors_new",
                to="core.actor",
                verbose_name="Authors",
            ),
        ),
        migrations.AddField(
            model_name="businessimpactanalysis",
            name="new_reviewers",
            field=models.ManyToManyField(
                blank=True,
                related_name="%(class)s_reviewers_new",
                to="core.actor",
                verbose_name="Reviewers",
            ),
        ),
    ]
