# Generated by Django 5.1.8 on 2025-05-07 11:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resilience", "0004_assetassessment_met_recovery_targets"),
    ]

    operations = [
        migrations.AddField(
            model_name="assetassessment",
            name="recovery_documented",
            field=models.BooleanField(default=False),
        ),
    ]
