# Generated by Django 5.2.9 on 2026-01-09 14:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0127_remove_appliedcontrol_new_owner_and_more"),
        ("resilience", "0004_businessimpactanalysis_new_authors_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="businessimpactanalysis",
            name="authors",
        ),
        migrations.RemoveField(
            model_name="businessimpactanalysis",
            name="reviewers",
        ),
        migrations.RenameField(
            model_name="businessimpactanalysis",
            old_name="new_authors",
            new_name="authors",
        ),
        migrations.RenameField(
            model_name="businessimpactanalysis",
            old_name="new_reviewers",
            new_name="reviewers",
        ),
    ]
