# Generated by Django 5.2.9 on 2026-01-09 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0127_remove_appliedcontrol_new_owner_and_more"),
        ("resilience", "0004_businessimpactanalysis_new_authors_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="businessimpactanalysis",
            name="authors",
        ),
        migrations.RemoveField(
            model_name="businessimpactanalysis",
            name="reviewers",
        ),
        migrations.RenameField(
            model_name="businessimpactanalysis",
            old_name="new_authors",
            new_name="authors",
        ),
        migrations.RenameField(
            model_name="businessimpactanalysis",
            old_name="new_reviewers",
            new_name="reviewers",
        ),
        migrations.AlterField(
            model_name="businessimpactanalysis",
            name="authors",
            field=models.ManyToManyField(
                blank=True,
                related_name="%(class)s_authors",
                to="core.actor",
                verbose_name="Authors",
            ),
        ),
        migrations.AlterField(
            model_name="businessimpactanalysis",
            name="reviewers",
            field=models.ManyToManyField(
                blank=True,
                related_name="%(class)s_reviewers",
                to="core.actor",
                verbose_name="Reviewers",
            ),
        ),
    ]
