# Generated by Django 5.1.8 on 2025-05-05 18:18

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resilience", "0004_remove_assetassessment_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assetassessment",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Created at",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="assetassessment",
            name="is_published",
            field=models.BooleanField(default=False, verbose_name="published"),
        ),
        migrations.AddField(
            model_name="assetassessment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
        migrations.AddField(
            model_name="escalationthreshold",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Created at",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="escalationthreshold",
            name="is_published",
            field=models.BooleanField(default=False, verbose_name="published"),
        ),
        migrations.AddField(
            model_name="escalationthreshold",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
        migrations.AlterField(
            model_name="assetassessment",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="escalationthreshold",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
