# Generated by Django 5.2.9 on 2026-01-29 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0133_riskscenario_folder_and_more"),
        ("resilience", "0005_remove_businessimpactanalysis_new_authors_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businessimpactanalysis",
            name="perimeter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.perimeter",
                verbose_name="Perimeter",
            ),
        ),
    ]
