# Generated by Django 5.1.8 on 2025-05-07 11:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("resilience", "0005_assetassessment_recovery_documented"),
    ]

    operations = [
        migrations.RenameField(
            model_name="assetassessment",
            old_name="met_recovery_targets",
            new_name="recovery_targets_met",
        ),
    ]
