# Generated by Django 5.1.8 on 2025-05-05 18:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("resilience", "0005_assetassessment_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assetassessment",
            name="folder",
        ),
        migrations.RemoveField(
            model_name="escalationthreshold",
            name="folder",
        ),
    ]
