# Generated by Django 6.0.3 on 2026-04-03 14:03

import django.db.models.deletion
import iam.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0156_incident_is_bcp_activated_incident_occurred_at_and_more"),
        ("iam", "0021_fix_auditee_iam_groups"),
        ("resilience", "0006_alter_businessimpactanalysis_perimeter"),
        ("tprm", "0015_contract_dora_exclude_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DoraIncidentReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
                (
                    "incident_submission",
                    models.CharField(
                        choices=[
                            ("initial_notification", "Initial notification"),
                            ("intermediate_report", "Intermediate report"),
                            ("final_report", "Final report"),
                            (
                                "major_incident_reclassified_as_non-major",
                                "Reclassified as non-major",
                            ),
                        ],
                        max_length=60,
                    ),
                ),
                ("report_currency", models.CharField(blank=True, max_length=3)),
                ("primary_contact_name", models.CharField(blank=True, max_length=255)),
                (
                    "primary_contact_email",
                    models.EmailField(blank=True, max_length=254),
                ),
                ("primary_contact_phone", models.CharField(blank=True, max_length=255)),
                (
                    "secondary_contact_name",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "secondary_contact_email",
                    models.EmailField(blank=True, max_length=254),
                ),
                (
                    "secondary_contact_phone",
                    models.CharField(blank=True, max_length=255),
                ),
                ("financial_entity_code", models.CharField(blank=True, max_length=255)),
                ("detection_date_time", models.DateTimeField(blank=True, null=True)),
                (
                    "classification_date_time",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("incident_description", models.TextField(blank=True)),
                ("other_information", models.TextField(blank=True)),
                ("incident_duration", models.CharField(blank=True, max_length=20)),
                ("originates_from_third_party_provider", models.TextField(blank=True)),
                ("incident_discovery", models.CharField(blank=True, max_length=60)),
                (
                    "competent_authority_code",
                    models.CharField(blank=True, max_length=255),
                ),
                ("classification_types", models.JSONField(blank=True, default=list)),
                ("incident_type", models.JSONField(blank=True, default=dict)),
                (
                    "root_cause_hl_classification",
                    models.JSONField(blank=True, default=list),
                ),
                (
                    "root_causes_detailed_classification",
                    models.JSONField(blank=True, default=list),
                ),
                (
                    "root_causes_additional_classification",
                    models.JSONField(blank=True, default=list),
                ),
                ("root_causes_other", models.TextField(blank=True)),
                ("root_causes_information", models.TextField(blank=True)),
                (
                    "root_cause_addressing_date_time",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("incident_resolution_vs_planned", models.TextField(blank=True)),
                (
                    "assessment_of_risk_to_critical_functions",
                    models.TextField(blank=True),
                ),
                (
                    "information_relevant_to_resolution_authorities",
                    models.TextField(blank=True),
                ),
                (
                    "financial_recoveries_amount",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "gross_amount_indirect_direct_costs",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "recurring_non_major_incidents_description",
                    models.TextField(blank=True),
                ),
                (
                    "recurring_incident_date",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("impact_assessment", models.JSONField(blank=True, default=dict)),
                (
                    "reporting_to_other_authorities",
                    models.JSONField(blank=True, default=list),
                ),
                ("reporting_to_other_authorities_other", models.TextField(blank=True)),
                (
                    "info_duration_service_downtime_actual_or_estimate",
                    models.CharField(blank=True, max_length=50),
                ),
                (
                    "affected_entities",
                    models.ManyToManyField(
                        blank=True, related_name="dora_ir_affected", to="tprm.entity"
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        default=iam.models.Folder.get_root_folder_id,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_folder",
                        to="iam.folder",
                    ),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dora_reports",
                        to="core.incident",
                    ),
                ),
                (
                    "submitting_entity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dora_ir_submitting",
                        to="tprm.entity",
                    ),
                ),
                (
                    "ultimate_parent_entity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dora_ir_parent",
                        to="tprm.entity",
                    ),
                ),
            ],
            options={
                "verbose_name": "DORA incident report",
                "verbose_name_plural": "DORA incident reports",
            },
        ),
    ]
