# Generated by Django 5.2.9 on 2026-02-16 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resilience", "0006_alter_businessimpactanalysis_perimeter"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessimpactanalysis",
            name="auto_sync",
            field=models.BooleanField(
                default=False, verbose_name="Automatic sync to actions"
            ),
        ),
    ]
