# Generated by Django 5.1.8 on 2025-05-05 18:38

import django.db.models.deletion
import iam.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iam", "0011_replace_slash_in_folder_names"),
        ("resilience", "0006_remove_assetassessment_folder_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assetassessment",
            name="folder",
            field=models.ForeignKey(
                default=iam.models.Folder.get_root_folder_id,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_folder",
                to="iam.folder",
            ),
        ),
        migrations.AddField(
            model_name="escalationthreshold",
            name="folder",
            field=models.ForeignKey(
                default=iam.models.Folder.get_root_folder_id,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_folder",
                to="iam.folder",
            ),
        ),
    ]
