# Generated by Django 5.1.8 on 2025-05-07 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0070_auto_fix_finding_folider"),
        (
            "resilience",
            "0006_rename_met_recovery_targets_assetassessment_recovery_targets_met",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="assetassessment",
            name="evidences",
            field=models.ManyToManyField(blank=True, to="core.evidence"),
        ),
    ]
