# Generated by Django 5.1.8 on 2025-05-05 19:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resilience", "0007_assetassessment_folder_escalationthreshold_folder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="escalationthreshold",
            name="rationale",
            field=models.TextField(blank=True, null=True),
        ),
    ]
