# Generated by Django 6.0.8 on 2026-08-17 14:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("resilience", "0007_doraincidentreport"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assetassessment",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="businessimpactanalysis",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="doraincidentreport",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="escalationthreshold",
            name="is_published",
        ),
    ]
