# Generated by Django 6.0.3 on 2026-04-04 08:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resilience", "0007_doraincidentreport"),
    ]

    operations = [
        migrations.AddField(
            model_name="doraincidentreport",
            name="is_submitted",
            field=models.BooleanField(default=False, verbose_name="Submitted"),
        ),
    ]
