# Generated by Django 5.1.8 on 2025-05-05 19:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resilience", "0008_alter_escalationthreshold_rationale"),
    ]

    operations = [
        migrations.AlterField(
            model_name="escalationthreshold",
            name="point_in_time",
            field=models.IntegerField(),
        ),
    ]
