# Generated by Django 6.0.3 on 2026-04-04 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0156_incident_is_bcp_activated_incident_occurred_at_and_more"),
        ("resilience", "0008_doraincidentreport_is_submitted"),
    ]

    operations = [
        migrations.AddField(
            model_name="doraincidentreport",
            name="submitted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Submitted at"
            ),
        ),
        migrations.AlterField(
            model_name="doraincidentreport",
            name="incident",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dora_reports",
                to="core.incident",
            ),
        ),
    ]
