# Generated by Django 5.1.8 on 2025-05-05 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0070_auto_fix_finding_folider"),
        ("resilience", "0009_alter_escalationthreshold_point_in_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assetassessment",
            name="asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.asset"
            ),
        ),
    ]
