# Generated by Django 5.1.8 on 2025-05-05 20:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resilience", "0010_alter_assetassessment_asset"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="escalationthreshold",
            name="time_unit",
        ),
        migrations.AlterField(
            model_name="escalationthreshold",
            name="quanti_impact_unit",
            field=models.CharField(
                choices=[
                    ("people", "People"),
                    ("currency", "Currency"),
                    ("records", "Records"),
                    ("man_hours", "Man-hours"),
                    ("data_gb", "Data (GB)"),
                    ("gu", "Generic Unit"),
                ],
                default="currency",
                max_length=20,
            ),
        ),
    ]
