# Generated by Django 5.1.8 on 2025-05-05 20:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0070_auto_fix_finding_folider"),
        ("resilience", "0011_remove_escalationthreshold_time_unit_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="assetassessment",
            unique_together={("bia", "asset")},
        ),
        migrations.AlterUniqueTogether(
            name="escalationthreshold",
            unique_together={("asset_assessment", "point_in_time")},
        ),
    ]
