# Generated by Django 5.1.8 on 2025-05-06 07:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("resilience", "0012_alter_assetassessment_unique_together_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="escalationthreshold",
            old_name="rationale",
            new_name="justification",
        ),
        migrations.RenameField(
            model_name="escalationthreshold",
            old_name="quali_impact_level",
            new_name="quali_impact",
        ),
        migrations.RenameField(
            model_name="escalationthreshold",
            old_name="quanti_impact_number",
            new_name="quanti_impact",
        ),
    ]
