# Auto-generated privacy terminology seed data (built-in Processing natures and Personal data categories).
DEFAULT_PROCESSING_NATURES = [
    {
        "name": "privacy_collection",
        "builtin": True,
        "field_path": "processing.nature",
        "is_visible": True,
        "translations": {"en": "Collection", "fr": "Collecte"},
    },
    {
        "name": "privacy_recording",
        "builtin": True,
        "field_path": "processing.nature",
        "is_visible": True,
        "translations": {"en": "Recording", "fr": "Enregistrement"},
    },
    {
        "name": "privacy_organization",
        "builtin": True,
        "field_path": "processing.nature",
        "is_visible": True,
        "translations": {"en": "Organization", "fr": "Organisation"},
    },
    {
        "name": "privacy_structuring",
        "builtin": True,
        "field_path": "processing.nature",
        "is_visible": True,
        "translations": {"en": "Structuring", "fr": "Structuration"},
    },
    {
        "name": "privacy_storage",
        "builtin": True,
        "field_path": "processing.nature",
        "is_visible": True,
        "translations": {"en": "Storage", "fr": "Conservation"},
    },
    {
        "name": "privacy_adaptationOrAlteration",
        "builtin": True,
        "field_path": "processing.nature",
        "is_visible": True,
        "translations": {
            "en": "Adaptation or Alteration",
            "fr": "Adaptation ou modification",
        },
    },
    {
        "name": "privacy_retrieval",
        "builtin": True,
        "field_path": "processing.nature",
        "is_visible": True,
        "translations": {"en": "Retrieval", "fr": "Extraction"},
    },
    {
        "name": "privacy_consultation",
        "builtin": True,
        "field_path": "processing.nature",
        "is_visible": True,
        "translations": {"en": "Consultation", "fr": "Consultation"},
    },
    {
        "name": "privacy_use",
        "builtin": True,
        "field_path": "processing.nature",
        "is_visible": True,
        "translations": {"en": "Use", "fr": "Utilisation"},
    },
    {
        "name": "privacy_disclosureByTransmission",
        "builtin": True,
        "field_path": "processing.nature",
        "is_visible": True,
        "translations": {
            "en": "Disclosure by Transmission",
            "fr": "Communication par transmission",
        },
    },
    {
        "name": "privacy_disseminationOrOtherwiseMakingAvailable",
        "builtin": True,
        "field_path": "processing.nature",
        "is_visible": True,
        "translations": {
            "en": "Dissemination or Otherwise Making Available",
            "fr": "Diffusion ou toute autre forme de mise à disposition",
        },
    },
    {
        "name": "privacy_alignmentOrCombination",
        "builtin": True,
        "field_path": "processing.nature",
        "is_visible": True,
        "translations": {
            "en": "Alignment or Combination",
            "fr": "Rapprochement ou interconnexion",
        },
    },
    {
        "name": "privacy_restriction",
        "builtin": True,
        "field_path": "processing.nature",
        "is_visible": True,
        "translations": {"en": "Restriction", "fr": "Limitation"},
    },
    {
        "name": "privacy_erasureOrDestruction",
        "builtin": True,
        "field_path": "processing.nature",
        "is_visible": True,
        "translations": {
            "en": "Erasure or Destruction",
            "fr": "Effacement ou destruction",
        },
    },
]

DEFAULT_PERSONAL_DATA_CATEGORIES = [
    {
        "name": "privacy_basic_identity",
        "builtin": True,
        "field_path": "personal_data.category",
        "is_visible": True,
        "translations": {
            "en": "Basic Identity Information",
            "fr": "Informations d'identité de base",
        },
    },
    {
        "name": "privacy_name",
        "builtin": True,
        "field_path": "personal_data.category",
        "is_visible": True,
        "translations": {"en": "Name", "fr": "Nom"},
    },
    {
        "name": "privacy_identification_numbers",
        "builtin": True,
        "field_path": "personal_data.category",
        "is_visible": True,
        "translations": {
            "en": "Identification Numbers",
            "fr": "Numéros d'identification",
        },
    },
    {
        "name": "privacy_online_identifiers",
        "builtin": True,
        "field_path": "personal_data.category",
        "is_visible": True,
        "translations": {"en": "Online Identifiers", "fr": "Identifiants en ligne"},
    },
    {
        "name": "privacy_location_data",
        "builtin": True,
        "field_path": "personal_data.category",
        "is_visible": True,
        "translations": {"en": "Location Data", "fr": "Données de localisation"},
    },
    {
        "name": "privacy_contact_details",
        "builtin": True,
        "field_path": "personal_data.category",
        "is_visible": True,
        "translations": {"en": "Contact Details", "fr": "Coordonnées"},
    },
    {
        "name": "privacy_address",
        "builtin": True,
        "field_path": "personal_data.category",
        "is_visible": True,
        "translations": {"en": "Address", "fr": "Adresse"},
    },
    {
        "name": "privacy_email",
        "builtin": True,
        "field_path": "personal_data.category",
        "is_visible": True,
        "translations": {"en": "Email Address", "fr": "Adresse email"},
    },
    {
        "name": "privacy_phone_number",
        "builtin": True,
        "field_path": "personal_data.category",
        "is_visible": True,
        "translations": {"en": "Phone Number", "fr": "Numéro de téléphone"},
    },
    {
        "name": "privacy_financial_data",
        "builtin": True,
        "field_path": "personal_data.category",
        "is_visible": True,
        "translations": {"en": "Financial Data", "fr": "Données financières"},
    },
    {
        "name": "privacy_bank_account",
        "builtin": True,
        "field_path": "personal_data.category",
        "is_visible": True,
        "translations": {
            "en": "Bank Account Information",
            "fr": "Informations de compte bancaire",
        },
    },
    {
        "name": "privacy_payment_card",
        "builtin": True,
        "field_path": "personal_data.category",
        "is_visible": True,
        "translations": {
            "en": "Payment Card Information",
            "fr": "Informations de carte de paiement",
        },
    },
    {
        "name": "privacy_transaction_history",
        "builtin": True,
        "field_path": "personal_data.category",
        "is_visible": True,
        "translations": {
            "en": "Transaction History",
            "fr": "Historique des transactions",
        },
    },
    {
        "name": "privacy_salary_information",
        "builtin": True,
        "field_path": "personal_data.category",
        "is_visible": True,
        "translations": {"en": "Salary Information", "fr": "Informations de salaire"},
    },
    {
        "name": "privacy_health_data",
        "builtin": True,
        "field_path": "personal_data.category",
        "is_visible": True,
        "translations": {"en": "Health Data", "fr": "Données de santé"},
    },
    {
        "name": "privacy_genetic_data",
        "builtin": True,
        "field_path": "personal_data.category",
        "is_visible": True,
        "translations": {"en": "Genetic Data", "fr": "Données génétiques"},
    },
    {
        "name": "privacy_biometric_data",
        "builtin": True,
        "field_path": "personal_data.category",
        "is_visible": True,
        "translations": {"en": "Biometric Data", "fr": "Données biométriques"},
    },
    {
        "name": "privacy_racial_ethnic_origin",
        "builtin": True,
        "field_path": "personal_data.category",
        "is_visible": True,
        "translations": {
            "en": "Racial or Ethnic Origin",
            "fr": "Origine raciale ou ethnique",
        },
    },
    {
        "name": "privacy_political_opinions",
        "builtin": True,
        "field_path": "personal_data.category",
        "is_visible": True,
        "translations": {"en": "Political Opinions", "fr": "Opinions politiques"},
    },
    {
        "name": "privacy_religious_beliefs",
        "builtin": True,
        "field_path": "personal_data.category",
        "is_visible": True,
        "translations": {
            "en": "Religious or Philosophical Beliefs",
            "fr": "Croyances religieuses ou philosophiques",
        },
    },
    {
        "name": "privacy_trade_union_membership",
        "builtin": True,
        "field_path": "personal_data.category",
        "is_visible": True,
        "translations": {
            "en": "Trade Union Membership",
            "fr": "Appartenance syndicale",
        },
    },
    {
        "name": "privacy_sexual_orientation",
        "builtin": True,
        "field_path": "personal_data.category",
        "is_visible": True,
        "translations": {"en": "Sexual Orientation", "fr": "Orientation sexuelle"},
    },
    {
        "name": "privacy_sex_life_data",
        "builtin": True,
        "field_path": "personal_data.category",
        "is_visible": True,
        "translations": {"en": "Sex Life Data", "fr": "Données sur la vie sexuelle"},
    },
    {
        "name": "privacy_browsing_history",
        "builtin": True,
        "field_path": "personal_data.category",
        "is_visible": True,
        "translations": {"en": "Browsing History", "fr": "Historique de navigation"},
    },
    {
        "name": "privacy_search_history",
        "builtin": True,
        "field_path": "personal_data.category",
        "is_visible": True,
        "translations": {"en": "Search History", "fr": "Historique de recherche"},
    },
    {
        "name": "privacy_cookies",
        "builtin": True,
        "field_path": "personal_data.category",
        "is_visible": True,
        "translations": {"en": "Cookie Data", "fr": "Données de cookies"},
    },
    {
        "name": "privacy_device_information",
        "builtin": True,
        "field_path": "personal_data.category",
        "is_visible": True,
        "translations": {
            "en": "Device Information",
            "fr": "Informations sur l'appareil",
        },
    },
    {
        "name": "privacy_ip_address",
        "builtin": True,
        "field_path": "personal_data.category",
        "is_visible": True,
        "translations": {"en": "IP Address", "fr": "Adresse IP"},
    },
    {
        "name": "privacy_user_behavior",
        "builtin": True,
        "field_path": "personal_data.category",
        "is_visible": True,
        "translations": {"en": "User Behavior", "fr": "Comportement de l'utilisateur"},
    },
    {
        "name": "privacy_employment_details",
        "builtin": True,
        "field_path": "personal_data.category",
        "is_visible": True,
        "translations": {"en": "Employment Details", "fr": "Détails d'emploi"},
    },
    {
        "name": "privacy_education_history",
        "builtin": True,
        "field_path": "personal_data.category",
        "is_visible": True,
        "translations": {"en": "Education History", "fr": "Historique d'éducation"},
    },
    {
        "name": "privacy_professional_qualifications",
        "builtin": True,
        "field_path": "personal_data.category",
        "is_visible": True,
        "translations": {
            "en": "Professional Qualifications",
            "fr": "Qualifications professionnelles",
        },
    },
    {
        "name": "privacy_work_performance",
        "builtin": True,
        "field_path": "personal_data.category",
        "is_visible": True,
        "translations": {
            "en": "Work Performance Data",
            "fr": "Données de performance au travail",
        },
    },
    {
        "name": "privacy_family_details",
        "builtin": True,
        "field_path": "personal_data.category",
        "is_visible": True,
        "translations": {"en": "Family Details", "fr": "Détails familiaux"},
    },
    {
        "name": "privacy_social_network",
        "builtin": True,
        "field_path": "personal_data.category",
        "is_visible": True,
        "translations": {"en": "Social Network", "fr": "Réseau social"},
    },
    {
        "name": "privacy_lifestyle_information",
        "builtin": True,
        "field_path": "personal_data.category",
        "is_visible": True,
        "translations": {
            "en": "Lifestyle Information",
            "fr": "Informations sur le mode de vie",
        },
    },
    {
        "name": "privacy_correspondence",
        "builtin": True,
        "field_path": "personal_data.category",
        "is_visible": True,
        "translations": {
            "en": "Correspondence Content",
            "fr": "Contenu de correspondance",
        },
    },
    {
        "name": "privacy_messaging_content",
        "builtin": True,
        "field_path": "personal_data.category",
        "is_visible": True,
        "translations": {"en": "Messaging Content", "fr": "Contenu de messagerie"},
    },
    {
        "name": "privacy_communication_metadata",
        "builtin": True,
        "field_path": "personal_data.category",
        "is_visible": True,
        "translations": {
            "en": "Communication Metadata",
            "fr": "Métadonnées de communication",
        },
    },
    {
        "name": "privacy_government_identifiers",
        "builtin": True,
        "field_path": "personal_data.category",
        "is_visible": True,
        "translations": {
            "en": "Government Identifiers",
            "fr": "Identifiants gouvernementaux",
        },
    },
    {
        "name": "privacy_tax_information",
        "builtin": True,
        "field_path": "personal_data.category",
        "is_visible": True,
        "translations": {"en": "Tax Information", "fr": "Informations fiscales"},
    },
    {
        "name": "privacy_social_security",
        "builtin": True,
        "field_path": "personal_data.category",
        "is_visible": True,
        "translations": {
            "en": "Social Security Information",
            "fr": "Informations de sécurité sociale",
        },
    },
    {
        "name": "privacy_drivers_license",
        "builtin": True,
        "field_path": "personal_data.category",
        "is_visible": True,
        "translations": {
            "en": "Driver's License Information",
            "fr": "Informations de permis de conduire",
        },
    },
    {
        "name": "privacy_passport_information",
        "builtin": True,
        "field_path": "personal_data.category",
        "is_visible": True,
        "translations": {
            "en": "Passport Information",
            "fr": "Informations de passeport",
        },
    },
    {
        "name": "privacy_legal_records",
        "builtin": True,
        "field_path": "personal_data.category",
        "is_visible": True,
        "translations": {"en": "Legal Records", "fr": "Dossiers juridiques"},
    },
    {
        "name": "privacy_criminal_records",
        "builtin": True,
        "field_path": "personal_data.category",
        "is_visible": True,
        "translations": {"en": "Criminal Records", "fr": "Casier judiciaire"},
    },
    {
        "name": "privacy_judicial_data",
        "builtin": True,
        "field_path": "personal_data.category",
        "is_visible": True,
        "translations": {"en": "Judicial Data", "fr": "Données judiciaires"},
    },
    {
        "name": "privacy_preferences",
        "builtin": True,
        "field_path": "personal_data.category",
        "is_visible": True,
        "translations": {"en": "Preferences", "fr": "Préférences"},
    },
    {
        "name": "privacy_opinions",
        "builtin": True,
        "field_path": "personal_data.category",
        "is_visible": True,
        "translations": {"en": "Opinions", "fr": "Opinions"},
    },
    {
        "name": "privacy_feedback",
        "builtin": True,
        "field_path": "personal_data.category",
        "is_visible": True,
        "translations": {"en": "Feedback", "fr": "Retour d'information"},
    },
    {
        "name": "privacy_images_photos",
        "builtin": True,
        "field_path": "personal_data.category",
        "is_visible": True,
        "translations": {"en": "Images and Photos", "fr": "Images et photos"},
    },
    {
        "name": "privacy_voice_recordings",
        "builtin": True,
        "field_path": "personal_data.category",
        "is_visible": True,
        "translations": {"en": "Voice Recordings", "fr": "Enregistrements vocaux"},
    },
    {
        "name": "privacy_video_recordings",
        "builtin": True,
        "field_path": "personal_data.category",
        "is_visible": True,
        "translations": {"en": "Video Recordings", "fr": "Enregistrements vidéo"},
    },
    {
        "name": "privacy_other",
        "builtin": True,
        "field_path": "personal_data.category",
        "is_visible": True,
        "translations": {
            "en": "Other (Specify in Description)",
            "fr": "Autre (Préciser dans la description)",
        },
    },
]
