"""
Convert a YAML mapping into an Excel mapping

Please note that this script doesn't replace "prepare_mapping.py".

Tested with v1 mappings only.
"""

import yaml
import pandas as pd
import sys
import os
from openpyxl import load_workbook
from openpyxl.styles import Font

def extract_last_segment(urn: str) -> str:
    return urn.split(':')[-1] if urn else ''

def convert_yaml_to_excel(yaml_file: str, excel_file: str):
    # Load YAML file
    with open(yaml_file, 'r', encoding='utf-8') as f:
        data = yaml.safe_load(f)

    # Get mappings
    mappings = data.get("objects", {}) \
                   .get("requirement_mapping_set", {}) \
                   .get("requirement_mappings", [])

    # Extract rows
    rows = []
    for item in mappings:
        row = {
            "source_requirement_urn": extract_last_segment(item.get("source_requirement_urn", "")),
            "target_requirement_urn": extract_last_segment(item.get("target_requirement_urn", "")),
            "relationship": item.get("relationship", ""),
            "rationale": item.get("rationale", ""),
            "annotation": item.get("annotation", "")
        }
        rows.append(row)

    # Create dataframe
    df = pd.DataFrame(rows, columns=[
        "source_requirement_urn",
        "target_requirement_urn",
        "relationship",
        "rationale",
        "annotation"
    ])

    # Write to Excel (to a sheet named "mappings")
    with pd.ExcelWriter(excel_file, engine='openpyxl') as writer:
        df.to_excel(writer, sheet_name="mappings", index=False)

        # Add "info" sheet manually
        workbook = writer.book
        info_sheet = workbook.create_sheet(title="info", index=0)

        # Row 1: Title
        info_sheet["A1"] = "YAML to Excel Mapping Converter v1"
        info_sheet["A1"].font = Font(size=48, bold=True)

        # Row 2: Source file
        info_sheet["A2"] = "Source file : " + os.path.basename(yaml_file)
        info_sheet["A2"].font = Font(size=15)

        # Row 3: Note
        info_sheet["A3"] = "Please note that this Excel file doesn't replace the one generated by prepare_mapping.py."
        info_sheet["A3"].font = Font(size=20, italic=True)

    print(f"✅ Conversion completed: \"{excel_file}\"")

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python yaml_to_excel.py <yaml_file> [excel_file]")
        sys.exit(1)

    yaml_input = sys.argv[1]
    excel_output = sys.argv[2] if len(sys.argv) > 2 else os.path.splitext(yaml_input)[0] + ".xlsx"

    convert_yaml_to_excel(yaml_input, excel_output)

