# Generated by Django 6.0.5 on 2026-05-25 10:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0170_alter_terminology_field_path"),
    ]

    operations = [
        migrations.CreateModel(
            name="FieldDefinition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Lowercase ASCII slug. Used as ?field_<name>= in API filters.",
                        max_length=64,
                        verbose_name="Internal name",
                    ),
                ),
                ("label", models.CharField(max_length=200, verbose_name="Label")),
                ("description", models.TextField(blank=True, default="")),
                (
                    "translations",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Per-locale label overrides, e.g. {"fr": "Criticité"}.',
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("long_text", "Long text"),
                            ("url", "URL"),
                            ("number", "Number"),
                            ("boolean", "Boolean"),
                            ("date", "Date"),
                            ("datetime", "Date and time"),
                            ("single_choice", "Single choice"),
                            ("multi_choice", "Multi choice"),
                            ("actor", "Actor"),
                        ],
                        default="text",
                        max_length=32,
                    ),
                ),
                ("required", models.BooleanField(default=False)),
                (
                    "default",
                    models.JSONField(
                        blank=True,
                        help_text="Default value when no FieldValue exists. Must match `type`.",
                        null=True,
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("is_visible", models.BooleanField(default=True)),
                ("filterable", models.BooleanField(default=True)),
                (
                    "builtin",
                    models.BooleanField(
                        default=False,
                        help_text="Seeded by migration/library. Protected from UI deletion.",
                    ),
                ),
                (
                    "target_content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="contenttypes.contenttype",
                        verbose_name="Target model",
                    ),
                ),
            ],
            options={
                "verbose_name": "Field definition",
                "verbose_name_plural": "Field definitions",
                "ordering": ["target_content_type", "order", "name"],
            },
        ),
        migrations.CreateModel(
            name="FieldChoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
                ("value", models.CharField(max_length=64)),
                ("label", models.CharField(max_length=200)),
                ("translations", models.JSONField(blank=True, default=dict)),
                ("color", models.CharField(blank=True, default="", max_length=32)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("is_visible", models.BooleanField(default=True)),
                (
                    "definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        to="custom_fields.fielddefinition",
                    ),
                ),
            ],
            options={
                "verbose_name": "Field choice",
                "verbose_name_plural": "Field choices",
                "ordering": ["definition", "order", "value"],
            },
        ),
        migrations.CreateModel(
            name="FieldValue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
                ("object_id", models.UUIDField()),
                ("value_text", models.TextField(blank=True, null=True)),
                (
                    "value_number",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=20, null=True
                    ),
                ),
                ("value_boolean", models.BooleanField(blank=True, null=True)),
                ("value_date", models.DateField(blank=True, null=True)),
                ("value_datetime", models.DateTimeField(blank=True, null=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="values",
                        to="custom_fields.fielddefinition",
                    ),
                ),
                (
                    "value_actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.actor",
                    ),
                ),
                (
                    "value_choice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="custom_fields.fieldchoice",
                    ),
                ),
                (
                    "value_choices",
                    models.ManyToManyField(
                        blank=True,
                        related_name="multi_values",
                        to="custom_fields.fieldchoice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Field value",
                "verbose_name_plural": "Field values",
            },
        ),
        migrations.AddConstraint(
            model_name="fielddefinition",
            constraint=models.UniqueConstraint(
                fields=("target_content_type", "name"),
                name="uniq_field_def_per_ct_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="fieldchoice",
            constraint=models.UniqueConstraint(
                fields=("definition", "value"), name="uniq_field_choice_per_def_value"
            ),
        ),
        migrations.AddIndex(
            model_name="fieldvalue",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="custom_fiel_content_c8a63a_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="fieldvalue",
            constraint=models.UniqueConstraint(
                fields=("definition", "content_type", "object_id"),
                name="uniq_field_value_per_def_host",
            ),
        ),
    ]
