# Generated by Django 6.0.6 on 2026-06-17 09:07

import django.db.models.deletion
import iam.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("iam", "0021_fix_auditee_iam_groups"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomFieldDefinition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
                ("key", models.SlugField(max_length=64, verbose_name="key")),
                ("label", models.CharField(max_length=200, verbose_name="label")),
                (
                    "help_text",
                    models.TextField(blank=True, default="", verbose_name="help text"),
                ),
                (
                    "translations",
                    models.JSONField(
                        blank=True, null=True, verbose_name="translations"
                    ),
                ),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("number", "Number"),
                            ("date", "Date"),
                            ("boolean", "Boolean"),
                            ("choice", "Choice"),
                            ("multi_choice", "Multiple choice"),
                        ],
                        max_length=20,
                        verbose_name="field type",
                    ),
                ),
                (
                    "required",
                    models.BooleanField(default=False, verbose_name="required"),
                ),
                ("visible", models.BooleanField(default=True, verbose_name="visible")),
                (
                    "searchable",
                    models.BooleanField(default=False, verbose_name="searchable"),
                ),
                (
                    "filterable",
                    models.BooleanField(default=True, verbose_name="filterable"),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="order"),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_field_definitions",
                        to="contenttypes.contenttype",
                        verbose_name="model",
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        default=iam.models.Folder.get_root_folder_id,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_folder",
                        to="iam.folder",
                    ),
                ),
            ],
            options={
                "verbose_name": "custom field definition",
                "verbose_name_plural": "custom field definitions",
                "ordering": ["order", "key"],
            },
        ),
        migrations.CreateModel(
            name="CustomFieldChoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
                ("value", models.SlugField(max_length=64, verbose_name="value")),
                ("label", models.CharField(max_length=200, verbose_name="label")),
                (
                    "translations",
                    models.JSONField(
                        blank=True, null=True, verbose_name="translations"
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="order"),
                ),
                (
                    "definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        to="custom_fields.customfielddefinition",
                        verbose_name="definition",
                    ),
                ),
            ],
            options={
                "verbose_name": "custom field choice",
                "verbose_name_plural": "custom field choices",
                "ordering": ["order", "value"],
            },
        ),
        migrations.CreateModel(
            name="CustomFieldValue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
                ("object_id", models.UUIDField()),
                ("value_text", models.TextField(blank=True, null=True)),
                (
                    "value_number",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=20, null=True
                    ),
                ),
                ("value_date", models.DateField(blank=True, null=True)),
                ("value_boolean", models.BooleanField(blank=True, null=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="custom_fields.customfielddefinition",
                        verbose_name="definition",
                    ),
                ),
            ],
            options={
                "verbose_name": "custom field value",
                "verbose_name_plural": "custom field values",
            },
        ),
        migrations.AddConstraint(
            model_name="customfielddefinition",
            constraint=models.UniqueConstraint(
                fields=("content_type", "folder", "key"),
                name="unique_custom_field_key_per_model_folder",
            ),
        ),
        migrations.AddConstraint(
            model_name="customfieldchoice",
            constraint=models.UniqueConstraint(
                fields=("definition", "value"), name="unique_custom_field_choice_value"
            ),
        ),
        migrations.AddIndex(
            model_name="customfieldvalue",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="custom_fiel_content_a0fece_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="customfieldvalue",
            index=models.Index(
                fields=["definition", "value_text"],
                name="custom_fiel_definit_5bb224_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="customfieldvalue",
            index=models.Index(
                fields=["definition", "value_number"],
                name="custom_fiel_definit_5766e6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="customfieldvalue",
            index=models.Index(
                fields=["definition", "value_date"],
                name="custom_fiel_definit_2c8e4d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="customfieldvalue",
            index=models.Index(
                fields=["definition", "value_boolean"],
                name="custom_fiel_definit_29e388_idx",
            ),
        ),
    ]
