# Generated by Django 6.1.1 on 2026-09-03 09:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("custom_fields", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customfielddefinition",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("number", "Number"),
                    ("date", "Date"),
                    ("boolean", "Boolean"),
                    ("choice", "Choice"),
                    ("multi_choice", "Multiple choice"),
                    ("url", "URL"),
                ],
                max_length=20,
                verbose_name="field type",
            ),
        ),
    ]
