# Generated by Django 6.0.8 on 2026-08-17 14:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("custom_fields", "0002_alter_customfielddefinition_field_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customfieldchoice",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="customfielddefinition",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="customfieldvalue",
            name="is_published",
        ),
    ]
