# Generated by Django 5.1.8 on 2025-04-22 11:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("global_settings", "0002_alter_globalsettings_folder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="globalsettings",
            name="name",
            field=models.CharField(
                choices=[
                    ("general", "General"),
                    ("sso", "SSO"),
                    ("feature-flags", "Feature Flags"),
                ],
                default="general",
                max_length=30,
                unique=True,
            ),
        ),
    ]
