# Generated by Django 6.0.3 on 2026-04-09 19:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("global_settings", "0003_alter_globalsettings_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="globalsettings",
            name="name",
            field=models.CharField(
                choices=[
                    ("general", "General"),
                    ("sso", "SSO"),
                    ("feature-flags", "Feature Flags"),
                    ("vulnerability-sla", "Vulnerability SLA"),
                    ("sec-intel-feeds", "Security Intelligence Feeds"),
                ],
                default="general",
                max_length=30,
                unique=True,
            ),
        ),
    ]
