# Generated by Django 5.1.9 on 2025-05-31 17:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("global_settings", "0003_alter_globalsettings_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="globalsettings",
            name="name",
            field=models.CharField(
                choices=[
                    ("general", "General"),
                    ("sso", "SSO"),
                    ("feature-flags", "Feature Flags"),
                    ("feeds-settings", "Feeds Settings"),
                ],
                default="general",
                max_length=30,
                unique=True,
            ),
        ),
    ]
