# Generated by Django 6.0.5 on 2026-06-01 15:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("global_settings", "0004_alter_globalsettings_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="globalsettings",
            name="name",
            field=models.CharField(
                choices=[
                    ("general", "General"),
                    ("sso", "SSO"),
                    ("feature-flags", "Feature Flags"),
                    ("vulnerability-sla", "Vulnerability SLA"),
                    ("sec-intel-feeds", "Vulnerability Feeds"),
                    ("infra-config", "Infra config"),
                ],
                default="general",
                max_length=30,
                unique=True,
            ),
        ),
    ]
