# Generated by Django 6.0.6 on 2026-06-10 13:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("global_settings", "0005_alter_globalsettings_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="globalsettings",
            options={
                "permissions": [
                    ("view_central_auditlog", "Can access the central audit log"),
                    ("view_object_audittrail", "Can view object audit trails"),
                ]
            },
        ),
    ]
