# Generated by Django 6.0.8 on 2026-08-17 14:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("global_settings", "0006_alter_globalsettings_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="globalsettings",
            name="is_published",
        ),
    ]
