# Generated by Django 5.2.8 on 2025-11-20 14:04

import django.db.models.deletion
import iam.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("iam", "0016_folder_filtering_labels"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookEventType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The event type string, e.g., 'appliedcontrol.created'",
                        max_length=100,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WebhookEndpoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "payload_format",
                    models.CharField(
                        choices=[("thin", "Thin"), ("full", "Full")],
                        default="full",
                        help_text="The format of the webhook payload sent to this endpoint.",
                        max_length=10,
                        verbose_name="Payload Format",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="The consumer URL to send webhook events to.",
                        max_length=512,
                    ),
                ),
                (
                    "secret",
                    models.CharField(help_text="HMAC signing secret.", max_length=100),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Global toggle to enable/disable sending events to this endpoint.",
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        default=iam.models.Folder.get_root_folder_id,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_folder",
                        to="iam.folder",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="The user or team that owns this endpoint.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhook_endpoints",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_folders",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Folders to which this webhook endpoint is scoped. If empty, the endpoint applies to all folders the owner has access to.",
                        to="iam.folder",
                    ),
                ),
                (
                    "event_types",
                    models.ManyToManyField(
                        blank=True,
                        help_text="A list of event types this endpoint subscribes to.",
                        to="webhooks.webhookeventtype",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "abstract": False,
            },
        ),
    ]
