# Generated by Django 5.2.8 on 2025-11-18 09:41

import django.db.models.deletion
import iam.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0016_folder_filtering_labels'),
        ('webhooks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookendpoint',
            name='folder',
            field=models.ForeignKey(default=iam.models.Folder.get_root_folder_id, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_folder', to='iam.folder'),
        ),
    ]
