# Generated by Django 5.2.8 on 2025-11-20 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0016_folder_filtering_labels'),
        ('webhooks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookendpoint',
            name='target_folders',
            field=models.ManyToManyField(blank=True, help_text='Folders to which this webhook endpoint is scoped. If empty, the endpoint applies to all folders the owner has access to.', to='iam.folder'),
        ),
    ]
