# Generated by Django 5.2.9 on 2026-01-09 14:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0129_remove_appliedcontrol_new_owner_and_more"),
        ("webhooks", "0002_webhookendpoint_new_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="webhookendpoint",
            name="owner",
        ),
        migrations.RenameField(
            model_name="webhookendpoint",
            old_name="new_owmner",
            new_name="owner",
        ),
    ]
