# Generated by Django 5.2.8 on 2025-11-20 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0002_webhookendpoint_target_folders'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookendpoint',
            name='format',
            field=models.CharField(choices=[('thin', 'Thin'), ('full', 'Full')], default='thin', help_text='The format of the webhook payload sent to this endpoint.', max_length=10, verbose_name='Payload Format'),
        ),
    ]
