# Generated by Django 5.2.8 on 2025-11-20 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0003_webhookendpoint_format'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webhookendpoint',
            old_name='format',
            new_name='payload_format',
        ),
    ]
