# Generated by Django 6.0.6 on 2026-06-13 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webhooks", "0003_remove_webhookendpoint_new_owner_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="webhookendpoint",
            name="body_format",
            field=models.CharField(
                choices=[
                    ("ciso_native", "CISO Assistant (HMAC-signed)"),
                    ("ocsf", "OCSF"),
                    ("raw", "Raw LogEntry"),
                    ("cef", "CEF"),
                    ("leef", "LEEF"),
                ],
                default="ocsf",
                help_text="Canonical event schema for audit sinks.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="webhookendpoint",
            name="headers",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Static headers added to each request, e.g. {"Authorization": "Splunk <token>"}. Used for audit-sink auth.',
            ),
        ),
        migrations.AddField(
            model_name="webhookendpoint",
            name="kafka_config",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Kafka transport: {bootstrap_servers, topic, config:{...}}.",
            ),
        ),
        migrations.AddField(
            model_name="webhookendpoint",
            name="kind",
            field=models.CharField(
                choices=[("integration", "Integration"), ("audit_sink", "Audit sink")],
                default="integration",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="webhookendpoint",
            name="syslog_config",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Syslog transport: {host, port, protocol: tcp|udp|tls}.",
            ),
        ),
        migrations.AddField(
            model_name="webhookendpoint",
            name="transport",
            field=models.CharField(
                choices=[("http", "HTTP"), ("kafka", "Kafka"), ("syslog", "Syslog")],
                default="http",
                help_text="Delivery transport (audit sinks only). Kafka is not yet implemented.",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="webhookendpoint",
            name="secret",
            field=models.CharField(
                blank=True,
                default="",
                help_text="HMAC signing secret (integration webhooks only).",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="webhookendpoint",
            name="url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Consumer URL (HTTP transport).",
                max_length=512,
            ),
        ),
    ]
