# Generated by Django 6.0.6 on 2026-06-11 06:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "webhooks",
            "0004_webhookendpoint_body_format_webhookendpoint_headers_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="webhookendpoint",
            name="kafka_config",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Kafka transport: {bootstrap_servers, topic, config:{...}}.",
            ),
        ),
        migrations.AlterField(
            model_name="webhookendpoint",
            name="url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Consumer URL (HTTP transport).",
                max_length=512,
            ),
        ),
    ]
