# Generated by Django 6.0.8 on 2026-08-17 14:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("webhooks", "0005_alter_webhookendpoint_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="webhookendpoint",
            name="is_published",
        ),
    ]
