# Generated by Django 6.0.6 on 2026-06-12 08:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webhooks", "0005_webhookendpoint_kafka_config_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="webhookendpoint",
            name="syslog_config",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Syslog transport: {host, port, protocol: tcp|udp|tls}.",
            ),
        ),
        migrations.AlterField(
            model_name="webhookendpoint",
            name="body_format",
            field=models.CharField(
                choices=[
                    ("ciso_native", "CISO Assistant (HMAC-signed)"),
                    ("ocsf", "OCSF"),
                    ("raw", "Raw LogEntry"),
                    ("cef", "CEF"),
                    ("leef", "LEEF"),
                ],
                default="ocsf",
                help_text="Canonical event schema for audit sinks.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="webhookendpoint",
            name="transport",
            field=models.CharField(
                choices=[("http", "HTTP"), ("kafka", "Kafka"), ("syslog", "Syslog")],
                default="http",
                help_text="Delivery transport (audit sinks only). Kafka is not yet implemented.",
                max_length=10,
            ),
        ),
    ]
