# Generated by Django 6.1.1 on 2026-09-18 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webhooks", "0006_remove_webhookendpoint_is_published"),
    ]

    operations = [
        migrations.AddField(
            model_name="webhookendpoint",
            name="auth_type",
            field=models.CharField(
                choices=[
                    ("static", "Static headers"),
                    ("oauth2_client_credentials", "OAuth 2.0 client credentials"),
                ],
                default="static",
                help_text="Authentication for HTTP audit sinks.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="webhookendpoint",
            name="body_wrapper",
            field=models.CharField(
                choices=[("none", "None"), ("array", "JSON array")],
                default="none",
                help_text="Envelope applied to the HTTP body. Azure Monitor Logs Ingestion requires an array.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="webhookendpoint",
            name="oauth_config",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="OAuth2 client credentials: {token_url, client_id, client_secret, scope, extra_params}.",
            ),
        ),
    ]
