# Generated by Django 5.0.2 on 2024-02-13 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='dependencies',
            field=models.ManyToManyField(blank=True, to='core.library', verbose_name='Dependencies'),
        ),
        migrations.AlterField(
            model_name='requirementassessment',
            name='compliance_assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_assessments', to='core.complianceassessment', verbose_name='Compliance assessment'),
        ),
    ]
