# Generated by Django 5.0.2 on 2024-02-14 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_library_dependencies_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
            ],
            options={
                'verbose_name': 'Policy',
                'verbose_name_plural': 'Policies',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.securitymeasure',),
        ),
    ]
