# Generated by Django 5.0.2 on 2024-02-29 20:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_riskscenario_strength_of_knowledge"),
    ]

    operations = [
        migrations.AddField(
            model_name="complianceassessment",
            name="is_published",
            field=models.BooleanField(default=False, verbose_name="published"),
        ),
        migrations.AddField(
            model_name="evidence",
            name="is_published",
            field=models.BooleanField(default=False, verbose_name="published"),
        ),
        migrations.AddField(
            model_name="framework",
            name="is_published",
            field=models.BooleanField(default=False, verbose_name="published"),
        ),
        migrations.AddField(
            model_name="library",
            name="is_published",
            field=models.BooleanField(default=False, verbose_name="published"),
        ),
        migrations.AddField(
            model_name="project",
            name="is_published",
            field=models.BooleanField(default=False, verbose_name="published"),
        ),
        migrations.AddField(
            model_name="requirementassessment",
            name="is_published",
            field=models.BooleanField(default=False, verbose_name="published"),
        ),
        migrations.AddField(
            model_name="requirementlevel",
            name="is_published",
            field=models.BooleanField(default=False, verbose_name="published"),
        ),
        migrations.AddField(
            model_name="requirementnode",
            name="is_published",
            field=models.BooleanField(default=False, verbose_name="published"),
        ),
        migrations.AddField(
            model_name="riskacceptance",
            name="is_published",
            field=models.BooleanField(default=False, verbose_name="published"),
        ),
        migrations.AddField(
            model_name="riskassessment",
            name="is_published",
            field=models.BooleanField(default=False, verbose_name="published"),
        ),
        migrations.AddField(
            model_name="riskmatrix",
            name="is_published",
            field=models.BooleanField(default=False, verbose_name="published"),
        ),
        migrations.AddField(
            model_name="riskscenario",
            name="is_published",
            field=models.BooleanField(default=False, verbose_name="published"),
        ),
        migrations.AddField(
            model_name="securitymeasure",
            name="is_published",
            field=models.BooleanField(default=False, verbose_name="published"),
        ),
        migrations.AlterField(
            model_name="asset",
            name="is_published",
            field=models.BooleanField(default=False, verbose_name="published"),
        ),
        migrations.AlterField(
            model_name="securityfunction",
            name="is_published",
            field=models.BooleanField(default=False, verbose_name="published"),
        ),
        migrations.AlterField(
            model_name="threat",
            name="is_published",
            field=models.BooleanField(default=False, verbose_name="published"),
        ),
    ]
