# Generated by Django 5.0.2 on 2024-02-29 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_riskscenario_strength_of_knowledge'),
        ('core', '0004_alter_asset_is_published_and_more'),
    ]

    operations = [
    ]
