# Generated by Django 5.0.2 on 2024-03-04 20:07

import django.db.models.deletion
import iam.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_project_lc_status_alter_securitymeasure_effort"),
        ("iam", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel("SecurityFunction", "ReferenceControl"),
        migrations.DeleteModel("Policy"),
        migrations.RenameModel("SecurityMeasure", "AppliedControl"),
        migrations.AlterModelOptions(
            name="appliedcontrol",
            options={
                "verbose_name": "Applied control",
                "verbose_name_plural": "Applied controls",
            },
        ),
        migrations.AlterModelOptions(
            name="referencecontrol",
            options={
                "verbose_name": "Reference control",
                "verbose_name_plural": "Reference controls",
            },
        ),
        migrations.RenameField(
            model_name="appliedcontrol",
            old_name="security_function",
            new_name="reference_control",
        ),
        migrations.RenameField(
            model_name="requirementassessment",
            old_name="security_measures",
            new_name="applied_controls",
        ),
        migrations.RenameField(
            model_name="requirementnode",
            old_name="security_functions",
            new_name="reference_controls",
        ),
        migrations.RenameField(
            model_name="riskscenario",
            old_name="security_measures",
            new_name="applied_controls",
        ),
        migrations.AlterField(
            model_name="appliedcontrol",
            name="evidences",
            field=models.ManyToManyField(
                blank=True,
                related_name="applied_controls",
                to="core.evidence",
                verbose_name="Evidences",
            ),
        ),
        migrations.AlterField(
            model_name="appliedcontrol",
            name="expiry_date",
            field=models.DateField(
                blank=True,
                help_text="Date after which the applied control is no longer valid",
                null=True,
                verbose_name="Expiry date",
            ),
        ),
        migrations.AlterField(
            model_name="referencecontrol",
            name="library",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reference_controls",
                to="core.library",
            ),
        ),
        migrations.RenameField(
            model_name="riskscenario",
            old_name="existing_measures",
            new_name="existing_controls",
        ),
        migrations.AlterField(
            model_name="riskscenario",
            name="existing_controls",
            field=models.TextField(
                blank=True,
                help_text="The existing controls to manage this risk. Edit the risk scenario to add extra applied controls.",
                max_length=2000,
                verbose_name="Existing controls",
            ),
        ),
        migrations.CreateModel(
            name="Policy",
            fields=[],
            options={
                "verbose_name": "Policy",
                "verbose_name_plural": "Policies",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.appliedcontrol",),
        ),
        migrations.AlterField(
            model_name="appliedcontrol",
            name="reference_control",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.referencecontrol",
                verbose_name="Reference Control",
            ),
        ),
        migrations.AlterField(
            model_name="requirementassessment",
            name="applied_controls",
            field=models.ManyToManyField(
                blank=True,
                related_name="requirement_assessments",
                to="core.appliedcontrol",
                verbose_name="Applied controls",
            ),
        ),
        migrations.AlterField(
            model_name="requirementnode",
            name="reference_controls",
            field=models.ManyToManyField(
                blank=True,
                related_name="requirements",
                to="core.referencecontrol",
                verbose_name="Reference controls",
            ),
        ),
        migrations.AlterField(
            model_name="riskscenario",
            name="applied_controls",
            field=models.ManyToManyField(
                blank=True,
                related_name="risk_scenarios",
                to="core.appliedcontrol",
                verbose_name="Applied controls",
            ),
        ),
    ]
