# Generated by Django 5.0.2 on 2024-03-05 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_securitymeasure_security_function_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirementlevel',
            name='framework',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requirement_levels', to='core.framework', verbose_name='Framework'),
        ),
        migrations.AlterField(
            model_name='requirementnode',
            name='framework',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requirement_nodes', to='core.framework', verbose_name='Framework'),
        ),
    ]
