# Generated by Django 5.0.2 on 2024-03-04 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_securitymeasure_security_function_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appliedcontrol',
            options={'verbose_name': 'Applied control', 'verbose_name_plural': 'Applied controls'},
        ),
        migrations.AlterModelOptions(
            name='referencecontrol',
            options={'verbose_name': 'Reference control', 'verbose_name_plural': 'Reference controls'},
        ),
        migrations.RemoveField(
            model_name='appliedcontrol',
            name='security_function',
        ),
        migrations.RemoveField(
            model_name='requirementassessment',
            name='security_measures',
        ),
        migrations.RemoveField(
            model_name='requirementnode',
            name='security_functions',
        ),
        migrations.RemoveField(
            model_name='riskscenario',
            name='security_measures',
        ),
        migrations.AddField(
            model_name='appliedcontrol',
            name='reference_control',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.referencecontrol', verbose_name='Reference Control'),
        ),
        migrations.AddField(
            model_name='requirementassessment',
            name='applied_controls',
            field=models.ManyToManyField(blank=True, related_name='requirement_assessments', to='core.appliedcontrol', verbose_name='Applied controls'),
        ),
        migrations.AddField(
            model_name='requirementnode',
            name='reference_controls',
            field=models.ManyToManyField(blank=True, related_name='requirements', to='core.referencecontrol', verbose_name='Reference controls'),
        ),
        migrations.AddField(
            model_name='riskscenario',
            name='applied_controls',
            field=models.ManyToManyField(blank=True, related_name='risk_scenarios', to='core.appliedcontrol', verbose_name='Applied controls'),
        ),
        migrations.AlterField(
            model_name='appliedcontrol',
            name='evidences',
            field=models.ManyToManyField(blank=True, related_name='applied_controls', to='core.evidence', verbose_name='Evidences'),
        ),
        migrations.AlterField(
            model_name='appliedcontrol',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Date after which the applied control is no longer valid', null=True, verbose_name='Expiry date'),
        ),
        migrations.AlterField(
            model_name='referencecontrol',
            name='library',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reference_controls', to='core.library'),
        ),
        migrations.AlterField(
            model_name='riskscenario',
            name='existing_measures',
            field=models.TextField(blank=True, help_text='The existing applied controls to manage this risk. Edit the risk scenario to add extra applied controls.', max_length=2000, verbose_name='Existing measures'),
        ),
    ]
