# Generated by Django 5.0.2 on 2024-03-04 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_appliedcontrol_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
            ],
            options={
                'verbose_name': 'Policy',
                'verbose_name_plural': 'Policies',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.appliedcontrol',),
        ),
    ]
