# Generated by Django 5.0.4 on 2024-04-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_complianceassessment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='framework',
            name='max_score',
            field=models.IntegerField(default=100, verbose_name='Maximum score'),
        ),
        migrations.AddField(
            model_name='framework',
            name='min_score',
            field=models.IntegerField(default=0, verbose_name='Minimum score'),
        ),
        migrations.AddField(
            model_name='requirementassessment',
            name='score',
            field=models.IntegerField(blank=True, null=True, verbose_name='Score'),
        ),
    ]
