# Generated by Django 5.0.4 on 2024-04-18 17:38

import django.db.models.deletion
import iam.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_complianceassessment_status_and_more'),
        ('iam', '0002_purge_validator'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadedLibrary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='UpdatedÒ at')),
                ('is_published', models.BooleanField(default=False, verbose_name='published')),
                ('urn', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='URN')),
                ('ref_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Reference ID')),
                ('locale', models.CharField(default='en', max_length=100, verbose_name='Locale')),
                ('default_locale', models.BooleanField(default=True, verbose_name='Default locale')),
                ('provider', models.CharField(blank=True, max_length=200, null=True, verbose_name='Provider')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('annotation', models.TextField(blank=True, null=True, verbose_name='Annotation')),
                ('copyright', models.CharField(blank=True, max_length=4096, null=True, verbose_name='Copyright')),
                ('version', models.IntegerField(verbose_name='Version')),
                ('packager', models.CharField(blank=True, help_text='Packager of the library', max_length=100, null=True, verbose_name='Packager')),
                ('builtin', models.BooleanField(default=False)),
                ('objects_meta', models.JSONField()),
                ('dependencies', models.ManyToManyField(blank=True, to='core.loadedlibrary', verbose_name='Dependencies')),
                ('folder', models.ForeignKey(default=iam.models.Folder.get_root_folder, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_folder', to='iam.folder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='framework',
            name='library',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='frameworks', to='core.loadedlibrary'),
        ),
        migrations.AlterField(
            model_name='referencecontrol',
            name='library',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reference_controls', to='core.loadedlibrary'),
        ),
        migrations.AlterField(
            model_name='riskmatrix',
            name='library',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risk_matrices', to='core.loadedlibrary'),
        ),
        migrations.AlterField(
            model_name='threat',
            name='library',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='threats', to='core.loadedlibrary'),
        ),
        migrations.CreateModel(
            name='StoredLibrary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='UpdatedÒ at')),
                ('is_published', models.BooleanField(default=False, verbose_name='published')),
                ('urn', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='URN')),
                ('ref_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Reference ID')),
                ('locale', models.CharField(default='en', max_length=100, verbose_name='Locale')),
                ('default_locale', models.BooleanField(default=True, verbose_name='Default locale')),
                ('provider', models.CharField(blank=True, max_length=200, null=True, verbose_name='Provider')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('annotation', models.TextField(blank=True, null=True, verbose_name='Annotation')),
                ('copyright', models.CharField(blank=True, max_length=4096, null=True, verbose_name='Copyright')),
                ('version', models.IntegerField(verbose_name='Version')),
                ('packager', models.CharField(blank=True, help_text='Packager of the library', max_length=100, null=True, verbose_name='Packager')),
                ('builtin', models.BooleanField(default=False)),
                ('objects_meta', models.JSONField()),
                ('dependencies', models.CharField(max_length=16384, null=True)),
                ('is_obsolete', models.BooleanField(default=False)),
                ('is_imported', models.BooleanField(default=False)),
                ('hash_checksum', models.CharField(max_length=64)),
                ('content', models.TextField()),
                ('folder', models.ForeignKey(default=iam.models.Folder.get_root_folder, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_folder', to='iam.folder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Library',
        ),
    ]
