# Generated by Django 5.0.4 on 2024-04-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_framework_max_score_framework_min_score_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="framework",
            old_name="score_definition",
            new_name="scores_definition",
        ),
        migrations.RemoveField(
            model_name="requirementnode",
            name="level",
        ),
        migrations.RemoveField(
            model_name="requirementnode",
            name="maturity",
        ),
        migrations.AddField(
            model_name="complianceassessment",
            name="max_score",
            field=models.IntegerField(null=True, verbose_name="Maximum score"),
        ),
        migrations.AddField(
            model_name="complianceassessment",
            name="min_score",
            field=models.IntegerField(null=True, verbose_name="Minimum score"),
        ),
        migrations.AddField(
            model_name="complianceassessment",
            name="scores_definition",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Score definition"
            ),
        ),
        migrations.AddField(
            model_name="complianceassessment",
            name="selected_implementation_groups",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Selected implementation groups"
            ),
        ),
        migrations.AddField(
            model_name="framework",
            name="implementation_groups_definition",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Implementation groups definition"
            ),
        ),
        migrations.AddField(
            model_name="requirementassessment",
            name="selected",
            field=models.BooleanField(default=True, verbose_name="Selected"),
        ),
        migrations.AddField(
            model_name="requirementnode",
            name="implementation_groups",
            field=models.JSONField(null=True, verbose_name="Implementation groups"),
        ),
        migrations.DeleteModel(
            name="RequirementLevel",
        ),
    ]
