# Generated by Django 5.0.4 on 2024-04-24 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_loadedlibrary_alter_framework_library_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storedlibrary",
            name="dependencies",
            field=models.JSONField(null=True),
        ),
    ]
