# Generated by Django 5.0.6 on 2024-06-25 07:06

import django.db.models.deletion
import iam.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20240522_1731'),
        ('iam', '0004_ssosettings_user_is_sso'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequirementMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(choices=[('superset', 'Superset'), ('subset', 'Subset'), ('equal', 'Equal'), ('intersect', 'Intersect'), ('not_related', 'Not related')], default='not_related', max_length=20, verbose_name='Relationship')),
                ('rationale', models.CharField(choices=[('syntactic', 'Syntactic'), ('semantic', 'Semantic'), ('functional', 'Functional')], default='syntactic', max_length=20, verbose_name='Rationale')),
                ('annotation', models.TextField(blank=True, null=True, verbose_name='Annotation')),
                ('focal_requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.requirementnode', verbose_name='Focal requirement')),
                ('reference_requirements', models.ManyToManyField(related_name='reference_requirements', to='core.requirementnode', verbose_name='reference requirements')),
            ],
        ),
        migrations.CreateModel(
            name='RequirementMappingSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_published', models.BooleanField(default=False, verbose_name='published')),
                ('urn', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='URN')),
                ('ref_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Reference ID')),
                ('provider', models.CharField(blank=True, max_length=200, null=True, verbose_name='Provider')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('annotation', models.TextField(blank=True, null=True, verbose_name='Annotation')),
                ('version', models.IntegerField(default=1, help_text='Version of the mapping set', verbose_name='Version')),
                ('focal_framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='focal_framework', to='core.framework', verbose_name='Focal framework')),
                ('folder', models.ForeignKey(default=iam.models.Folder.get_root_folder, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_folder', to='iam.folder')),
                ('mappings', models.ManyToManyField(related_name='mappings', to='core.requirementmapping', verbose_name='Mappings')),
                ('reference_framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_framework', to='core.framework', verbose_name='Reference framework')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
