# Generated by Django 5.0.6 on 2024-06-25 07:23

from django.db import migrations, models


def create_result(apps, schema_editor):
    RequirementAssessment = apps.get_model("core", "RequirementAssessment")
    for assessment in RequirementAssessment.objects.all():
        if assessment.status == "non_compliant":
            assessment.result = "non_compliant_minor"
            assessment.status = "in_progress"
        elif assessment.status == "partially_compliant":
            assessment.result = "non_compliant_minor"
            assessment.status = "in_progress"
        elif assessment.status == "compliant":
            assessment.result = "compliant"
            assessment.status = "in_progress"
        elif assessment.status == "not_applicable":
            assessment.result = "not_applicable"
            assessment.status = "in_progress"
        assessment.save()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_auto_20240522_1731"),
    ]

    operations = [
        migrations.AddField(
            model_name="requirementassessment",
            name="due_date",
            field=models.DateField(blank=True, null=True, verbose_name="Due date"),
        ),
        migrations.AddField(
            model_name="requirementassessment",
            name="eta",
            field=models.DateField(blank=True, null=True, verbose_name="ETA"),
        ),
        migrations.AddField(
            model_name="requirementassessment",
            name="result",
            field=models.CharField(
                blank=True,
                choices=[
                    ("non_compliant_minor", "Non-compliant minor"),
                    ("non_compliant_major", "Non-compliant major"),
                    ("compliant", "Compliant"),
                    ("not_applicable", "Not applicable"),
                ],
                max_length=64,
                null=True,
                verbose_name="Result",
            ),
        ),
        migrations.AlterField(
            model_name="complianceassessment",
            name="due_date",
            field=models.DateField(blank=True, null=True, verbose_name="Due date"),
        ),
        migrations.AlterField(
            model_name="complianceassessment",
            name="eta",
            field=models.DateField(blank=True, null=True, verbose_name="ETA"),
        ),
        migrations.AlterField(
            model_name="requirementassessment",
            name="status",
            field=models.CharField(
                choices=[
                    ("to_do", "To do"),
                    ("in_progress", "In progress"),
                    ("done", "Done"),
                ],
                default="to_do",
                max_length=100,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="riskassessment",
            name="due_date",
            field=models.DateField(blank=True, null=True, verbose_name="Due date"),
        ),
        migrations.AlterField(
            model_name="riskassessment",
            name="eta",
            field=models.DateField(blank=True, null=True, verbose_name="ETA"),
        ),
        migrations.RunPython(create_result),
    ]
