# Generated by Django 5.0.6 on 2024-07-06 13:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_remove_complianceassessment_result_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="riskscenario",
            name="owner",
            field=models.ManyToManyField(
                blank=True,
                related_name="risk_scenarios",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Owner",
            ),
        ),
    ]
