# Generated by Django 5.0.6 on 2024-06-24 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_requirementmapping_requirementmappingset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirementmapping',
            name='rationale',
            field=models.CharField(choices=[('syntactic', 'Syntactic'), ('semantic', 'Semantic'), ('functional', 'Functional')], default='syntactic', max_length=20, verbose_name='Rationale'),
        ),
    ]
