# Generated by Django 5.0.4 on 2024-07-22 08:02

from django.db import migrations, models
from core.models import StoredLibrary, LoadedLibrary


def fix_urns_for_enisa_5g_scm(apps, schema_editor):
    enisa_5g_scm_stored_library = StoredLibrary.objects.filter(
        urn="urn:intuitem:risk:library:enisa-5g-scm-v1.3"
    )
    if enisa_5g_scm_stored_library:
        enisa_5g_scm_stored_library[
            0
        ].delete()  # the lib will be added again in the store at the end of the migration
    enisa_5g_scm_loaded_library = LoadedLibrary.objects.filter(
        urn="urn:intuitem:risk:library:enisa-5g-scm-v1.3"
    )
    if enisa_5g_scm_loaded_library:
        count = 0
        for b in enisa_5g_scm_loaded_library[0].reference_controls.all():
            if b.urn[:4] != "urn:":
                b.urn = "urn:intuitem:" + b.urn
                b.save()
                count += 1
        print(f"fixed {count} URNs")


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_requirementassessment_mapping_inference_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="framework",
            name="translations",
            field=models.JSONField(blank=True, null=True, verbose_name="Translations"),
        ),
        migrations.AddField(
            model_name="loadedlibrary",
            name="translations",
            field=models.JSONField(blank=True, null=True, verbose_name="Translations"),
        ),
        migrations.AddField(
            model_name="referencecontrol",
            name="translations",
            field=models.JSONField(blank=True, null=True, verbose_name="Translations"),
        ),
        migrations.AddField(
            model_name="requirementmappingset",
            name="translations",
            field=models.JSONField(blank=True, null=True, verbose_name="Translations"),
        ),
        migrations.AddField(
            model_name="requirementnode",
            name="translations",
            field=models.JSONField(blank=True, null=True, verbose_name="Translations"),
        ),
        migrations.AddField(
            model_name="riskmatrix",
            name="translations",
            field=models.JSONField(blank=True, null=True, verbose_name="Translations"),
        ),
        migrations.AddField(
            model_name="storedlibrary",
            name="translations",
            field=models.JSONField(blank=True, null=True, verbose_name="Translations"),
        ),
        migrations.AddField(
            model_name="threat",
            name="translations",
            field=models.JSONField(blank=True, null=True, verbose_name="Translations"),
        ),
        migrations.RunPython(fix_urns_for_enisa_5g_scm),
    ]
