# Generated by Django 5.0.4 on 2024-07-07 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_requirementassessment_mapping_inference_and_more'),
        ('core', '0016_riskscenario_owner'),
    ]

    operations = [
    ]
