# Generated by Django 5.0.6 on 2024-07-20 22:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_requirementassessment_mapping_inference_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appliedcontrol",
            name="csf_function",
            field=models.CharField(
                blank=True,
                choices=[
                    ("govern", "Govern"),
                    ("identify", "Identify"),
                    ("protect", "Protect"),
                    ("detect", "Detect"),
                    ("respond", "Respond"),
                    ("recover", "Recover"),
                ],
                max_length=20,
                null=True,
                verbose_name="CSF Function",
            ),
        ),
        migrations.AddField(
            model_name="referencecontrol",
            name="csf_function",
            field=models.CharField(
                blank=True,
                choices=[
                    ("govern", "Govern"),
                    ("identify", "Identify"),
                    ("protect", "Protect"),
                    ("detect", "Detect"),
                    ("respond", "Respond"),
                    ("recover", "Recover"),
                ],
                max_length=20,
                null=True,
                verbose_name="CSF Function",
            ),
        ),
    ]
