# Generated by Django 5.0.4 on 2024-07-07 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_merge_20240707_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirementmappingset',
            name='version',
        ),
    ]
