# Generated by Django 5.0.6 on 2024-07-26 21:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0018_appliedcontrol_csf_function_and_more"),
        ("core", "0018_framework_translations_loadedlibrary_translations_and_more"),
    ]

    operations = []
