# Generated by Django 5.0.7 on 2024-08-19 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_fix_libraries_objects_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskscenario',
            name='qualification',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Financial'),
        ),
    ]
