# Generated by Django 5.0.7 on 2024-08-26 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0021_alter_framework_urn_alter_loadedlibrary_urn_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="riskscenario",
            name="qualifications",
            field=models.JSONField(default=list, verbose_name="Qualifications"),
        ),
    ]
