# Generated by Django 5.1 on 2024-08-29 13:41

from django.db import migrations, models


def update_status(apps, schema_editor):
    AppliedControl = apps.get_model("core", "AppliedControl")
    for control in AppliedControl.objects.all():
        if control.status == "planned":
            control.status = "to_do"
            control.save()
        elif control.status == "inactive":
            control.status = "deprecated"
            control.save()
        elif control.status is None:
            control.status = "--"
            control.save()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0022_riskscenario_qualifications"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appliedcontrol",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("to_do", "To do"),
                    ("in_progress", "In progress"),
                    ("active", "Active"),
                    ("on_hold", "On hold"),
                    ("deprecated", "Deprecated"),
                    ("--", "Undefined"),
                ],
                default="--",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.RunPython(update_status),
    ]
