# Generated by Django 5.1 on 2024-08-30 11:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0023_alter_appliedcontrol_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="appliedcontrol",
            name="owner",
            field=models.ManyToManyField(
                blank=True,
                related_name="applied_controls",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Owner",
            ),
        ),
    ]
