# Generated by Django 5.1 on 2024-09-04 13:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0024_appliedcontrol_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="requirementassessment",
            name="answer",
            field=models.JSONField(blank=True, null=True, verbose_name="Answer"),
        ),
        migrations.AddField(
            model_name="requirementnode",
            name="question",
            field=models.JSONField(blank=True, null=True, verbose_name="Question"),
        ),
    ]
