# Generated by Django 5.1 on 2024-09-13 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_complianceassessment_folder_riskassessment_folder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedcontrol',
            name='cost',
            field=models.FloatField(help_text='Cost of the measure (using globally-chosen currency)', null=True, verbose_name='Cost'),
        ),
    ]
