# Generated by Django 5.1.1 on 2024-09-13 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_complianceassessment_folder_riskassessment_folder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirementassessment',
            name='answer',
            field=models.JSONField(blank=True, null=True, verbose_name='Answer'),
        ),
        migrations.AddField(
            model_name='requirementnode',
            name='question',
            field=models.JSONField(blank=True, null=True, verbose_name='Question'),
        ),
    ]
