# Generated by Django 5.1 on 2024-09-13 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_requirementassessment_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complianceassessment',
            name='observation',
            field=models.TextField(blank=True, null=True, verbose_name='Observation'),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='observation',
            field=models.TextField(blank=True, null=True, verbose_name='Observation'),
        ),
    ]
