# Generated by Django 5.1 on 2024-09-17 19:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0028_complianceassessment_observation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appliedcontrol",
            name="link",
            field=models.CharField(
                blank=True,
                help_text="External url for action follow-up (eg. Jira ticket)",
                max_length=2048,
                null=True,
                verbose_name="Link",
            ),
        ),
        migrations.AlterField(
            model_name="evidence",
            name="link",
            field=models.URLField(
                blank=True,
                help_text="Link to the evidence (eg. Jira ticket, etc.)",
                max_length=2048,
                null=True,
                verbose_name="Link",
            ),
        ),
    ]
