# Generated by Django 5.1.1 on 2024-11-18 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_remove_project_internal_reference_and_more'),
        ('core', '0035_riskscenario_existing_applied_controls'),
    ]

    operations = [
    ]
