# Generated by Django 5.1.1 on 2024-11-12 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_riskscenario_existing_applied_controls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedcontrol',
            name='cost',
            field=models.FloatField(blank=True, help_text='Cost of the measure (using globally-chosen currency)', null=True, verbose_name='Cost'),
        ),
    ]
