# Generated by Django 5.1.1 on 2024-11-19 00:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0035_riskscenario_existing_applied_controls"),
    ]

    operations = [
        migrations.AddField(
            model_name="appliedcontrol",
            name="priority",
            field=models.CharField(
                blank=True,
                choices=[("P1", "P1"), ("P2", "P2"), ("P3", "P3"), ("P4", "P4")],
                max_length=20,
                null=True,
                verbose_name="Priority",
            ),
        ),
    ]
