# Generated by Django 5.1.1 on 2024-11-18 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_merge_20241118_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='ref_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='reference id'),
        ),
    ]
