# Generated by Django 5.1.1 on 2024-11-20 12:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0036_asset_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="riskscenario",
            name="ref_id",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Reference ID"
            ),
        ),
    ]
