# Generated by Django 5.1.1 on 2024-11-21 17:22

from django.db import migrations, models


def populate_default_ref_ids(apps, schema_editor):
    RiskAssessment = apps.get_model("core", "RiskAssessment")

    def get_default_ref_id(risk_assessment):
        """Return a unique reference ID for a given risk assessment."""
        scenarios_ref_ids = [
            x.ref_id for x in risk_assessment.risk_scenarios.all() if x.ref_id
        ]
        nb_scenarios = len(scenarios_ref_ids) + 1
        candidates = [f"R.{i + 1}" for i in range(nb_scenarios)]
        return next(x for x in candidates if x not in scenarios_ref_ids)

    for risk_assessment in RiskAssessment.objects.all():
        for scenario in risk_assessment.risk_scenarios.filter(ref_id=""):
            scenario.ref_id = get_default_ref_id(risk_assessment)
            scenario.save()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0039_make_urn_lowercase"),
    ]

    operations = [
        migrations.AddField(
            model_name="riskscenario",
            name="ref_id",
            field=models.CharField(
                blank=True, max_length=8, verbose_name="Reference ID"
            ),
            preserve_default=False,
        ),
        migrations.RunPython(populate_default_ref_ids),
    ]
