# Generated by Django 5.1.1 on 2024-11-14 11:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0040_alter_framework_ref_id_alter_loadedlibrary_ref_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="internal_reference",
        ),
    ]
