# Generated by Django 5.1.1 on 2024-11-14 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0041_remove_project_internal_reference"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="internal_reference",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Internal reference"
            ),
        ),
    ]
