# Generated by Django 5.1.1 on 2024-12-09 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_qualification'),
        ('ebios_rm', '0002_remove_ebiosrmstudy_risk_assessments'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskassessment',
            name='ebios_rm_study',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risk_assessments', to='ebios_rm.ebiosrmstudy', verbose_name='EBIOS RM study'),
        ),
    ]
