# Generated by Django 5.1.1 on 2024-12-07 22:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0044_qualification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appliedcontrol",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("policy", "Policy"),
                    ("process", "Process"),
                    ("technical", "Technical"),
                    ("physical", "Physical"),
                    ("procedure", "Procedure"),
                ],
                max_length=20,
                null=True,
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="referencecontrol",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("policy", "Policy"),
                    ("process", "Process"),
                    ("technical", "Technical"),
                    ("physical", "Physical"),
                    ("procedure", "Procedure"),
                ],
                max_length=20,
                null=True,
                verbose_name="Category",
            ),
        ),
    ]
