# Generated by Django 5.1.4 on 2024-12-11 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0045_alter_appliedcontrol_category_and_more"),
        ("ebios_rm", "0003_remove_ebiosrmstudy_risk_assessments"),
    ]

    operations = [
        migrations.AddField(
            model_name="riskassessment",
            name="ebios_rm_study",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="risk_assessments",
                to="ebios_rm.ebiosrmstudy",
                verbose_name="EBIOS RM study",
            ),
        ),
    ]
