# Generated by Django 5.1.4 on 2025-01-08 10:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0046_riskassessment_ebios_rm_study"),
    ]

    operations = [
        migrations.AddField(
            model_name="complianceassessment",
            name="show_documentation_score",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="requirementassessment",
            name="documentation_score",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Documentation Score"
            ),
        ),
    ]
