# Generated by Django 5.1.4 on 2025-01-11 11:53

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0047_loadedlibrary_publication_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="security_objectives",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="The security objectives of the asset",
                validators=[
                    core.validators.JSONSchemaInstanceValidator(
                        {
                            "$id": "https://ciso-assistant.com/schemas/assets/security_objectives.schema.json",
                            "$schema": "https://json-schema.org/draft/2020-12/schema",
                            "description": "The security objectives of the asset",
                            "properties": {
                                "objectives": {
                                    "patternProperties": {
                                        "^[a-z_]+$": {
                                            "properties": {
                                                "is_enabled": {"type": "boolean"},
                                                "value": {
                                                    "maximum": 3,
                                                    "minimum": 0,
                                                    "type": "integer",
                                                },
                                            },
                                            "type": "object",
                                        }
                                    },
                                    "type": "object",
                                }
                            },
                            "title": "Security objectives",
                            "type": "object",
                        }
                    )
                ],
                verbose_name="Security objectives",
            ),
        ),
    ]
