# Generated by Django 5.1.5 on 2025-01-30 11:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0049_complianceassessment_show_documentation_score_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appliedcontrol",
            name="progress_field",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="Progress cannot be less than 0"
                    ),
                    django.core.validators.MaxValueValidator(
                        100, message="Progress cannot be more than 100"
                    ),
                ],
                verbose_name="Progress Field",
            ),
        ),
    ]
