# Generated by Django 5.1.4 on 2025-01-28 11:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0049_complianceassessment_show_documentation_score_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appliedcontrol",
            name="progress_field",
            field=models.IntegerField(default=0, verbose_name="Progress Field"),
        ),
    ]
