# Generated by Django 5.1.4 on 2025-02-01 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0050_appliedcontrol_progress_field"),
        ("iam", "0010_user_preferences"),
        ("tprm", "0003_entityassessment_representatives"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Project",
            new_name="Perimeter",
        ),
        migrations.AlterModelOptions(
            name="perimeter",
            options={"verbose_name": "Perimeter", "verbose_name_plural": "Perimeters"},
        ),
        migrations.RemoveField(
            model_name="complianceassessment",
            name="project",
        ),
        migrations.RemoveField(
            model_name="riskassessment",
            name="project",
        ),
        migrations.AddField(
            model_name="complianceassessment",
            name="perimeter",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.perimeter",
                verbose_name="Perimeter",
            ),
        ),
        migrations.AddField(
            model_name="riskassessment",
            name="perimeter",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.perimeter",
                verbose_name="Perimeter",
            ),
        ),
    ]
