# Generated by Django 5.1.5 on 2025-02-04 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0050_appliedcontrol_progress_field"),
        ("iam", "0010_user_preferences"),
        ("tprm", "0003_entityassessment_representatives"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Project",
            new_name="Perimeter",
        ),
        migrations.AlterModelOptions(
            name="perimeter",
            options={"verbose_name": "Perimeter", "verbose_name_plural": "Perimeters"},
        ),
        migrations.RenameField(
            model_name="complianceassessment",
            old_name="project",
            new_name="perimeter",
        ),
        migrations.RenameField(
            model_name="riskassessment",
            old_name="project",
            new_name="perimeter",
        ),
        migrations.AlterField(
            model_name="complianceassessment",
            name="perimeter",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.perimeter",
                verbose_name="Perimeter",
            ),
        ),
        migrations.AlterField(
            model_name="riskassessment",
            name="perimeter",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.perimeter",
                verbose_name="Perimeter",
            ),
        ),
    ]
