# Generated by Django 5.1.5 on 2025-02-21 12:07

from django.db import migrations, models


def update_is_published(apps, schema_editor):
    AppliedControl = apps.get_model("core", "AppliedControl")
    Asset = apps.get_model("core", "Asset")
    Evidence = apps.get_model("core", "Evidence")
    ReferenceControl = apps.get_model("core", "ReferenceControl")
    SecurityException = apps.get_model("core", "SecurityException")
    Threat = apps.get_model("core", "Threat")
    Vulnerability = apps.get_model("core", "Vulnerability")

    AppliedControl.objects.update(is_published=True)
    Asset.objects.update(is_published=True)
    Evidence.objects.update(is_published=True)
    ReferenceControl.objects.update(is_published=True)
    SecurityException.objects.update(is_published=True)
    Threat.objects.update(is_published=True)
    Vulnerability.objects.update(is_published=True)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0053_asset_ref_id_alter_riskscenario_ref_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appliedcontrol",
            name="is_published",
            field=models.BooleanField(default=True, verbose_name="published"),
        ),
        migrations.AlterField(
            model_name="asset",
            name="is_published",
            field=models.BooleanField(default=True, verbose_name="published"),
        ),
        migrations.AlterField(
            model_name="evidence",
            name="is_published",
            field=models.BooleanField(default=True, verbose_name="published"),
        ),
        migrations.AlterField(
            model_name="referencecontrol",
            name="is_published",
            field=models.BooleanField(default=True, verbose_name="published"),
        ),
        migrations.AlterField(
            model_name="securityexception",
            name="is_published",
            field=models.BooleanField(default=True, verbose_name="published"),
        ),
        migrations.AlterField(
            model_name="threat",
            name="is_published",
            field=models.BooleanField(default=True, verbose_name="published"),
        ),
        migrations.AlterField(
            model_name="vulnerability",
            name="is_published",
            field=models.BooleanField(default=True, verbose_name="published"),
        ),
        migrations.RunPython(update_is_published),
    ]
