# Generated by Django 5.1.5 on 2025-02-19 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_asset_ref_id_alter_riskscenario_ref_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedlibrary',
            name='content',
            field=models.JSONField(),
        ),
    ]
