# Generated by Django 5.1.5 on 2025-02-21 14:18

from django.db import migrations

import json


def make_matrix_json_definition_dict(apps, schema_editor):
    RiskMatrix = apps.get_model("core", "RiskMatrix")

    for matrix in RiskMatrix.objects.all():
        matrix.json_definition = json.loads(matrix.json_definition)
        matrix.save()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0053_asset_ref_id_alter_riskscenario_ref_id"),
    ]

    operations = [migrations.RunPython(make_matrix_json_definition_dict)]
