# Generated by Django 5.1.4 on 2025-02-21 23:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0054_alter_appliedcontrol_is_published_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storedlibrary",
            name="content",
            field=models.JSONField(),
        ),
    ]
