# Generated by Django 5.1.5 on 2025-02-24 18:13

import json
from django.db import migrations


def make_storedlibrary_json_definition_dict(apps, schema_editor):
    StoredLibrary = apps.get_model("core", "StoredLibrary")

    for lib in StoredLibrary.objects.all():
        try:
            lib.content = json.loads(lib.content)
            lib.save()
        except Exception as e:
            if type(lib.content) is dict:
                continue
            print(f"Error converting library {lib.id} to dict: {e}")


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0056_data_store_matrix_json_as_dict_not_str"),
    ]

    operations = []
