# Generated by Django 5.1.5 on 2025-02-24 11:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0056_data_store_matrix_json_as_dict_not_str"),
    ]

    operations = [
        migrations.AddField(
            model_name="appliedcontrol",
            name="label",
            field=models.ManyToManyField(
                blank=True,
                related_name="applied_controls",
                to="core.filteringlabel",
                verbose_name="Labels",
            ),
        ),
        migrations.AddField(
            model_name="referencecontrol",
            name="label",
            field=models.ManyToManyField(
                blank=True,
                related_name="reference_controls",
                to="core.filteringlabel",
                verbose_name="Labels",
            ),
        ),
        migrations.AddField(
            model_name="threat",
            name="label",
            field=models.ManyToManyField(
                blank=True,
                related_name="threats",
                to="core.filteringlabel",
                verbose_name="Labels",
            ),
        ),
    ]
