# Generated by Django 5.1.5 on 2025-03-03 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_store_storedlibrary_content_as_dict_not_str'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirementassessment',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='requirementnode',
            name='question',
        ),
        migrations.AddField(
            model_name='requirementassessment',
            name='answers',
            field=models.JSONField(blank=True, null=True, verbose_name='Answers'),
        ),
        migrations.AddField(
            model_name='requirementnode',
            name='questions',
            field=models.JSONField(blank=True, null=True, verbose_name='Questions'),
        ),
    ]
