# Generated by Django 5.1.5 on 2025-02-28 10:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0058_findingsassessment_finding"),
    ]

    operations = [
        migrations.AddField(
            model_name="appliedcontrol",
            name="filtering_labels",
            field=models.ManyToManyField(
                blank=True, to="core.filteringlabel", verbose_name="Labels"
            ),
        ),
        migrations.AddField(
            model_name="referencecontrol",
            name="filtering_labels",
            field=models.ManyToManyField(
                blank=True, to="core.filteringlabel", verbose_name="Labels"
            ),
        ),
        migrations.AddField(
            model_name="threat",
            name="filtering_labels",
            field=models.ManyToManyField(
                blank=True, to="core.filteringlabel", verbose_name="Labels"
            ),
        ),
    ]
