# Generated by Django 5.1.5 on 2025-02-28 10:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0058_findingsassessment_finding"),
    ]

    operations = [
        migrations.AddField(
            model_name="complianceassessment",
            name="assets",
            field=models.ManyToManyField(
                blank=True,
                help_text="Assets related to the compliance assessment",
                related_name="compliance_assessments",
                to="core.asset",
                verbose_name="Related assets",
            ),
        ),
    ]
