# Generated by Django 5.1.5 on 2025-03-07 18:46

from django.db import migrations
import json


def fix_matrix_json_definition(apps, schema_editor):
    RiskMatrix = apps.get_model("core", "RiskMatrix")

    for matrix in RiskMatrix.objects.all():
        if isinstance(matrix.json_definition, str):
            matrix.json_definition = json.loads(matrix.json_definition)
            matrix.save()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0059_complianceassessment_assets"),
    ]

    operations = [migrations.RunPython(fix_matrix_json_definition)]
