# Generated by Django 5.1.7 on 2025-03-17 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0060_fix_matrix_json_definition"),
    ]

    operations = [
        migrations.AddField(
            model_name="findingsassessment",
            name="ref_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="reference id"
            ),
        ),
    ]
