# Generated by Django 5.1.7 on 2025-03-26 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0062_appliedcontrol_filtering_labels_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appliedcontrol",
            name="assets",
            field=models.ManyToManyField(
                blank=True,
                related_name="applied_controls",
                to="core.asset",
                verbose_name="Assets",
            ),
        ),
    ]
