# Generated by Django 5.1.7 on 2025-03-27 13:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0063_appliedcontrol_assets"),
    ]

    operations = [
        migrations.AddField(
            model_name="evidence",
            name="filtering_labels",
            field=models.ManyToManyField(
                blank=True, to="core.filteringlabel", verbose_name="Labels"
            ),
        ),
    ]
