# Generated by Django 5.1.8 on 2025-04-06 20:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0065_vulnerability_assets_alter_finding_severity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="evidence",
            name="filtering_labels",
            field=models.ManyToManyField(
                blank=True, to="core.filteringlabel", verbose_name="Labels"
            ),
        ),
    ]
