# Generated by Django 5.1.7 on 2025-04-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0066_alter_vulnerability_severity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="finding",
            name="severity",
            field=models.SmallIntegerField(
                choices=[
                    (-1, "undefined"),
                    (0, "low"),
                    (1, "medium"),
                    (2, "high"),
                    (3, "critical"),
                ],
                default=-1,
                verbose_name="Severity",
            ),
        ),
    ]
