# Generated by Django 5.1.8 on 2025-04-13 21:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0066_evidence_filtering_labels"),
    ]

    operations = [
        migrations.AddField(
            model_name="appliedcontrol",
            name="control_impact",
            field=models.SmallIntegerField(
                blank=True,
                choices=[
                    (1, "Very Low"),
                    (2, "Low"),
                    (3, "Medium"),
                    (4, "High"),
                    (5, "Very High"),
                ],
                null=True,
                verbose_name="Impact",
            ),
        ),
        migrations.AlterField(
            model_name="appliedcontrol",
            name="effort",
            field=models.CharField(
                blank=True,
                choices=[
                    ("XS", "Extra Small"),
                    ("S", "Small"),
                    ("M", "Medium"),
                    ("L", "Large"),
                    ("XL", "Extra Large"),
                ],
                help_text="Relative effort of the measure (using T-Shirt sizing)",
                max_length=2,
                null=True,
                verbose_name="Effort",
            ),
        ),
    ]
