# Generated by Django 5.1.8 on 2025-04-07 11:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_tasknode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasknode',
            name='owner',
        ),
        migrations.AddField(
            model_name='tasknode',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Assigned to'),
        ),
    ]
