# Generated by Django 5.1.8 on 2025-04-14 20:23

from django.db import migrations
from core.utils import UserGroupCodename, RoleCodename


def add_missing_ug_and_ra(apps, schema_editor):
    Folder = apps.get_model("iam", "Folder")
    UserGroup = apps.get_model("iam", "UserGroup")
    RoleAssignment = apps.get_model("iam", "RoleAssignment")
    Role = apps.get_model("iam", "Role")
    root_folder = Folder.objects.filter(content_type="GL").first()
    if not root_folder:
        print("Skipping migration: root folder (GL) not found.")
        return

    for folder in Folder.objects.filter(content_type="DO"):
        if not RoleAssignment.objects.filter(perimeter_folders=folder):
            print(f" [Repair folder {folder.name}]", end="")
            readers = UserGroup.objects.create(
                name=UserGroupCodename.READER, folder=folder, builtin=True
            )
            approvers = UserGroup.objects.create(
                name=UserGroupCodename.APPROVER, folder=folder, builtin=True
            )
            analysts = UserGroup.objects.create(
                name=UserGroupCodename.ANALYST, folder=folder, builtin=True
            )
            managers = UserGroup.objects.create(
                name=UserGroupCodename.DOMAIN_MANAGER, folder=folder, builtin=True
            )
            ra1 = RoleAssignment.objects.create(
                user_group=readers,
                role=Role.objects.get(name=RoleCodename.READER),
                builtin=True,
                folder=root_folder,
                is_recursive=True,
            )
            ra1.perimeter_folders.add(folder)
            ra2 = RoleAssignment.objects.create(
                user_group=approvers,
                role=Role.objects.get(name=RoleCodename.APPROVER),
                builtin=True,
                folder=root_folder,
                is_recursive=True,
            )
            ra2.perimeter_folders.add(folder)
            ra3 = RoleAssignment.objects.create(
                user_group=analysts,
                role=Role.objects.get(name=RoleCodename.ANALYST),
                builtin=True,
                folder=root_folder,
                is_recursive=True,
            )
            ra3.perimeter_folders.add(folder)
            ra4 = RoleAssignment.objects.create(
                user_group=managers,
                role=Role.objects.get(name=RoleCodename.DOMAIN_MANAGER),
                builtin=True,
                folder=root_folder,
                is_recursive=True,
            )
            ra4.perimeter_folders.add(folder)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0067_appliedcontrol_control_impact_and_more"),
    ]

    operations = [
        migrations.RunPython(add_missing_ug_and_ra),
    ]
