# Generated by Django 5.1.8 on 2025-04-20 15:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0068_tasktemplate_tasknode"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComplianceAssessmentSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
                ("format", models.IntegerField(default=1)),
                ("revision", models.IntegerField(default=1)),
                ("key_indicators", models.JSONField()),
                ("data", models.JSONField()),
                (
                    "compliance_assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.complianceassessment",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
