# Generated by Django 5.1.8 on 2025-05-11 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0072_assetclass"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="asset_class",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.assetclass",
            ),
        ),
    ]
