# Generated by Django 5.1.9 on 2025-05-16 07:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0073_alter_asset_security_objectives"),
    ]

    operations = [
        migrations.AddField(
            model_name="findingsassessment",
            name="evidences",
            field=models.ManyToManyField(
                blank=True,
                help_text="Evidences related to the follow-up",
                related_name="findings",
                to="core.evidence",
            ),
        ),
    ]
