# Generated by Django 5.1.9 on 2025-05-19 09:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0074_tasktemplate_findings_assessment"),
    ]

    operations = [
        migrations.AddField(
            model_name="finding",
            name="due_date",
            field=models.DateField(blank=True, null=True, verbose_name="Due date"),
        ),
        migrations.AddField(
            model_name="finding",
            name="eta",
            field=models.DateField(blank=True, null=True, verbose_name="ETA"),
        ),
    ]
