# Generated by Django 5.1.8 on 2025-05-19 14:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0074_tasktemplate_findings_assessment"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="detection",
            field=models.CharField(
                blank=True,
                choices=[
                    ("internally_detected", "Internal"),
                    ("externally_detected", "External"),
                ],
                default="internally_detected",
                max_length=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="incident",
            name="reported_at",
            field=models.DateTimeField(
                blank=True,
                default=django.utils.timezone.now,
                null=True,
                verbose_name="Reported at",
            ),
        ),
    ]
