# Generated by Django 5.1.9 on 2025-05-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0076_finding_due_date_finding_eta"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="link",
            field=models.CharField(
                blank=True, max_length=2048, null=True, verbose_name="Link"
            ),
        ),
    ]
