# Generated by Django 5.1.9 on 2025-05-30 10:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0077_incident_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="complianceassessment",
            name="evidences",
            field=models.ManyToManyField(
                blank=True,
                help_text="Evidences related to the compliance assessment",
                related_name="compliance_assessments",
                to="core.evidence",
                verbose_name="Evidences",
            ),
        ),
    ]
