# Generated by Django 5.1.9 on 2025-06-09 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0078_campaign_complianceassessment_campaign"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("draft", "Draft"),
                    ("in_progress", "In progress"),
                    ("in_review", "In review"),
                    ("done", "Done"),
                    ("deprecated", "Deprecated"),
                ],
                default="draft",
                max_length=100,
                null=True,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="complianceassessment",
            name="campaign",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="compliance_assessments",
                to="core.campaign",
            ),
        ),
    ]
