# Generated by Django 5.1.9 on 2025-06-25 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_finding_evidences_findingsassessment_evidences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='parent_assets',
            field=models.ManyToManyField(blank=True, related_name='child_assets', to='core.asset', verbose_name='parent assets'),
        ),
    ]
