# Generated by Django 5.1.10 on 2025-07-03 12:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0079_finding_evidences_findingsassessment_evidences"),
    ]

    operations = [
        migrations.RunSQL(
            sql="UPDATE core_qualification SET is_published = TRUE;",
            reverse_sql="UPDATE core_qualification SET is_published = FALSE;",
        ),
    ]
