# Generated by Django 5.1.9 on 2025-06-25 07:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0080_campaign_complianceassessment_campaign"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="frameworks",
            field=models.ManyToManyField(related_name="campaigns", to="core.framework"),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="perimeters",
            field=models.ManyToManyField(related_name="campaigns", to="core.perimeter"),
        ),
    ]
