# Generated by Django 5.1.10 on 2025-07-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0081_campaign_complianceassessment_campaign"),
    ]

    operations = [
        migrations.AddField(
            model_name="riskscenario",
            name="inherent_impact",
            field=models.SmallIntegerField(default=-1, verbose_name="inherent impact"),
        ),
        migrations.AddField(
            model_name="riskscenario",
            name="inherent_level",
            field=models.SmallIntegerField(
                default=-1,
                help_text="The risk level if no measures are applied. Automatically updated on Save, based on the chosen risk matrix",
                verbose_name="inherent level",
            ),
        ),
        migrations.AddField(
            model_name="riskscenario",
            name="inherent_proba",
            field=models.SmallIntegerField(
                default=-1, verbose_name="inherent probability"
            ),
        ),
    ]
