# Generated by Django 5.1.10 on 2025-07-10 16:12

from django.db import migrations, models

def fix_nis2_framework(apps, schema_editor):
    Framework = apps.get_model("core", "Framework")
    ComplianceAssessment = apps.get_model("core", "ComplianceAssessment")
    framework=Framework.objects.get(urn='urn:intuitem:risk:framework:annex-technical-and-methodological-requirements-nis2')
    framework.save()
    print("custom migration for", framework.urn)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_campaign_complianceassessment_campaign'),
    ]

    operations = [
                migrations.RunPython(fix_nis2_framework),
    ]



