# Generated by Django 5.1.9 on 2025-06-25 07:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0081_campaign_frameworks_alter_campaign_perimeters"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="campaign",
            name="framework",
        ),
    ]
