# Generated by Django 5.1.10 on 2025-07-10 16:12

from django.db import migrations, models


def fix_nis2_framework(apps, schema_editor):
    """fix inconsistent urn if present"""
    RequirementNode = apps.get_model("core", "RequirementNode")
    if node := RequirementNode.objects.filter(
        urn="urn:intuitem:risk:req_node:annex-technical-and-methodological-requirements-nis2:2.1.2;g"
    ).first():
        print("custom migration for", node.urn)
        node.urn = "urn:intuitem:risk:req_node:annex-technical-and-methodological-requirements-nis2:2.1.2.g"
        node.save()

    elif node := RequirementNode.objects.filter(
        urn="urn:intuitem:risk:req_node:annex-technical-and-methodological-requirements-nis2:2.1.2_g"
    ).first():
        print("custom migration for", node.urn)
        node.urn = "urn:intuitem:risk:req_node:annex-technical-and-methodological-requirements-nis2:2.1.2.g"
        node.save()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0082_riskscenario_inherent_impact_and_more"),
    ]

    operations = [
        migrations.RunPython(fix_nis2_framework),
    ]
