# Generated by Django 5.1.10 on 2025-07-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_riskscenario_inherent_impact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='parent_assets',
            field=models.ManyToManyField(blank=True, related_name='child_assets', to='core.asset', verbose_name='parent assets'),
        ),
    ]
