# Generated by Django 5.1.10 on 2025-07-25 09:39

from django.db import migrations


def update_timeline_entries_folder(apps, schema_editor):
    TimelineEntry = apps.get_model("core", "TimelineEntry")
    for entry in TimelineEntry.objects.all():
        if entry.incident:
            entry.folder = entry.incident.folder
            entry.save()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0084_perimeter_default_assignee"),
    ]

    operations = [
        migrations.RunPython(update_timeline_entries_folder),
    ]
