# Generated by Django 5.1.10 on 2025-07-15 14:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0084_perimeter_default_assignee"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="evidence",
            name="expiry_date",
            field=models.DateField(
                blank=True,
                help_text="Date after which the applied control is no longer valid",
                null=True,
                verbose_name="Expiry date",
            ),
        ),
        migrations.AddField(
            model_name="evidence",
            name="owner",
            field=models.ManyToManyField(
                blank=True,
                related_name="evidences",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Owner",
            ),
        ),
    ]
