# Generated by Django 5.1.10 on 2025-07-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0084_perimeter_default_assignee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="parent_assets",
            field=models.ManyToManyField(
                blank=True,
                related_name="child_assets",
                to="core.asset",
                verbose_name="parent assets",
            ),
        ),
    ]
