# Generated by Django 5.1.10 on 2025-07-14 14:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0084_perimeter_default_assignee"),
    ]

    operations = [
        migrations.AddField(
            model_name="riskassessment",
            name="risk_appetite",
            field=models.SmallIntegerField(default=-1, verbose_name="Risk appetite"),
        ),
    ]
