# Generated by Django 5.1.10 on 2025-07-27 18:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0085_auto_20250725_0939"),
    ]

    operations = [
        migrations.AddField(
            model_name="riskassessment",
            name="risk_tolerance",
            field=models.SmallIntegerField(default=-1, verbose_name="Risk tolerance"),
        ),
    ]
