# Generated by Django 5.1.10 on 2025-08-13 12:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0086_riskassessment_risk_tolerance"),
    ]

    operations = [
        migrations.AddField(
            model_name="appliedcontrol",
            name="observation",
            field=models.TextField(blank=True, null=True, verbose_name="Observation"),
        ),
        migrations.AddField(
            model_name="asset",
            name="observation",
            field=models.TextField(blank=True, null=True, verbose_name="Observation"),
        ),
        migrations.AddField(
            model_name="finding",
            name="observation",
            field=models.TextField(blank=True, null=True, verbose_name="Observation"),
        ),
    ]
