# Generated by Django 5.1.10 on 2025-08-14 08:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0087_appliedcontrol_observation_asset_observation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasktemplate",
            name="link",
            field=models.URLField(
                blank=True,
                help_text="Link to the evidence (eg. Jira ticket, etc.)",
                max_length=2048,
                null=True,
                verbose_name="Link",
            ),
        ),
    ]
