# Generated by Django 5.1.10 on 2025-08-20 14:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0089_organisationissue_organisationobjective"),
    ]

    operations = [
        migrations.AddField(
            model_name="complianceassessment",
            name="is_locked",
            field=models.BooleanField(default=False, verbose_name="Is locked"),
        ),
    ]
