# Generated by Django 5.1.10 on 2025-08-19 16:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0089_organisationissue_organisationobjective"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="organisationissue",
            name="ref_id",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Reference ID"
            ),
        ),
        migrations.AddField(
            model_name="organisationobjective",
            name="assigned_to",
            field=models.ManyToManyField(
                blank=True, to=settings.AUTH_USER_MODEL, verbose_name="Assigned to"
            ),
        ),
        migrations.AddField(
            model_name="organisationobjective",
            name="health",
            field=models.CharField(
                choices=[
                    ("--", "Undefined"),
                    ("on_track", "On track"),
                    ("at_risk", "At risk"),
                    ("off_track", "Off track"),
                ],
                default="--",
                max_length=100,
                verbose_name="Health",
            ),
        ),
        migrations.AddField(
            model_name="organisationobjective",
            name="ref_id",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Reference ID"
            ),
        ),
        migrations.AddField(
            model_name="organisationobjective",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("in_progress", "In progress"),
                    ("achieved", "Achieved"),
                    ("degraded", "Degraded"),
                    ("deprecated", "Deprecated"),
                ],
                default="draft",
                max_length=100,
                verbose_name="Status",
            ),
        ),
    ]
