# Generated by Django 5.1.10 on 2025-08-22 08:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0089_organisationissue_organisationobjective"),
    ]

    operations = [
        migrations.AddField(
            model_name="complianceassessment",
            name="is_locked",
            field=models.BooleanField(
                default=False, null=True, verbose_name="Is locked"
            ),
        ),
        migrations.AddField(
            model_name="findingsassessment",
            name="is_locked",
            field=models.BooleanField(
                default=False, null=True, verbose_name="Is locked"
            ),
        ),
        migrations.AddField(
            model_name="riskassessment",
            name="is_locked",
            field=models.BooleanField(
                default=False, null=True, verbose_name="Is locked"
            ),
        ),
    ]
