# Generated by Django 5.1.10 on 2025-08-26 10:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0090_complianceassessment_is_locked_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appliedcontrol",
            name="objectives",
            field=models.ManyToManyField(
                blank=True,
                related_name="applied_controls",
                to="core.organisationobjective",
                verbose_name="Objectives",
            ),
        ),
    ]
