# Generated by Django 5.1.10 on 2025-08-26 15:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0090_complianceassessment_is_locked_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appliedcontrol",
            name="objectives",
            field=models.ManyToManyField(
                blank=True,
                related_name="applied_controls",
                to="core.organisationobjective",
                verbose_name="Objectives",
            ),
        ),
        migrations.AddField(
            model_name="organisationobjective",
            name="due_date",
            field=models.DateField(blank=True, null=True, verbose_name="Due date"),
        ),
        migrations.AddField(
            model_name="organisationobjective",
            name="eta",
            field=models.DateField(blank=True, null=True, verbose_name="ETA"),
        ),
        migrations.AlterField(
            model_name="organisationissue",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("--", "Undefined"),
                    ("political", "Political"),
                    ("economic", "Economic"),
                    ("social", "Social"),
                    ("technology", "Technology"),
                    ("legal", "Legal"),
                    ("environmental", "Environmental"),
                    ("organisationStructure", "Organisation Structure"),
                    ("humanResources", "Human resources"),
                    ("internalProcesses", "Internal processes"),
                    ("financialCapacity", "Financial capacity"),
                    ("companyCulture", "Company culture / communication"),
                ],
                default="--",
                max_length=32,
                verbose_name="Category",
            ),
        ),
    ]
