# Generated by Django 5.1.10 on 2025-08-25 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0091_appliedcontrol_objectives_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="qualification",
            name="library",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="qualifications",
                to="core.loadedlibrary",
            ),
        ),
        migrations.AlterField(
            model_name="qualification",
            name="is_published",
            field=models.BooleanField(default=True, verbose_name="published"),
        ),
    ]
