# Generated by Django 5.1.10 on 2025-08-28 14:56

import django.db.models.deletion
import iam.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0091_appliedcontrol_objectives_and_more"),
        ("iam", "0014_user_observation"),
    ]

    operations = [
        migrations.CreateModel(
            name="Terminology",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "field_path",
                    models.CharField(
                        choices=[("ro_to.risk_origin", "ro_to/risk_origin")],
                        max_length=100,
                        verbose_name="Field path",
                    ),
                ),
                (
                    "builtin",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if the terminology is built-in and cannot be modified",
                        verbose_name="Built-in",
                    ),
                ),
                (
                    "is_visible",
                    models.BooleanField(
                        default=True,
                        help_text="Indicates if the terminology is visible in the UI",
                        verbose_name="Is Visible",
                    ),
                ),
                (
                    "translations",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON field to store translations for different languages",
                        null=True,
                        verbose_name="Translations",
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        default=iam.models.Folder.get_root_folder_id,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_folder",
                        to="iam.folder",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "abstract": False,
            },
        ),
    ]
