# Generated by Django 5.1.10 on 2025-08-28 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0092_terminology'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminology',
            name='translations',
            field=models.JSONField(blank=True, default=dict, help_text='JSON field to store translations for different languages', null=True, verbose_name='Translations'),
        ),
    ]
