# Generated by Django 5.1.10 on 2025-09-03 16:56

import core.models
import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0094_alter_appliedcontrol_cost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appliedcontrol",
            name="cost",
            field=models.JSONField(
                blank=True,
                default=core.models.AppliedControl._get_default_cost,
                help_text="Detailed cost structure including build and run costs",
                null=True,
                validators=[
                    core.validators.JSONSchemaInstanceValidator(
                        {
                            "additionalProperties": False,
                            "properties": {
                                "amortization_period": {
                                    "default": 3,
                                    "maximum": 50,
                                    "minimum": 1,
                                    "type": "number",
                                },
                                "build": {
                                    "additionalProperties": False,
                                    "properties": {
                                        "fixed_cost": {"minimum": 0, "type": "number"},
                                        "people_days": {"minimum": 0, "type": "number"},
                                    },
                                    "type": "object",
                                },
                                "currency": {"type": "string"},
                                "run": {
                                    "additionalProperties": False,
                                    "properties": {
                                        "fixed_cost": {"minimum": 0, "type": "number"},
                                        "people_days": {"minimum": 0, "type": "number"},
                                    },
                                    "type": "object",
                                },
                            },
                            "type": "object",
                        }
                    )
                ],
                verbose_name="Cost",
            ),
        ),
    ]
