# Generated by Django 5.1.10 on 2025-09-11 07:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0094_alter_incident_qualifications_and_more"),
        ("ebios_rm", "0016_alter_fearedevent_qualifications"),
        ("resilience", "0003_alter_escalationthreshold_qualifications"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Qualification",
        ),
    ]
