# Generated by Django 5.1.10 on 2025-08-28 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0094_alter_terminology_field_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminology',
            name='field_path',
            field=models.CharField(choices=[('ro_to.risk_origin', 'ro_to/risk_origin')], max_length=100, verbose_name='Field path'),
        ),
    ]
