# Generated by Django 5.1.10 on 2025-09-11 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0094_alter_incident_qualifications_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Qualification',
        ),
    ]
