# Generated by Django 5.2.6 on 2025-09-17 09:44

import core.validators
import django.db.models.deletion
import iam.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0096_appliedcontrol_cost_to_json"),
        ("iam", "0014_user_observation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="evidence",
            name="expiry_date",
            field=models.DateField(blank=True, null=True, verbose_name="Expiry date"),
        ),
        migrations.AddField(
            model_name="evidence",
            name="owner",
            field=models.ManyToManyField(
                blank=True, to=settings.AUTH_USER_MODEL, verbose_name="Owner"
            ),
        ),
        migrations.AddField(
            model_name="evidence",
            name="status",
            field=models.CharField(
                choices=[
                    ("missing", "Missing"),
                    ("in_review", "In review"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("expired", "Expired"),
                ],
                default="missing",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="EvidenceRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    models.IntegerField(default=1, verbose_name="version number"),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="",
                        validators=[
                            core.validators.validate_file_size,
                            core.validators.validate_file_name,
                        ],
                        verbose_name="Attachment",
                    ),
                ),
                (
                    "link",
                    models.URLField(
                        blank=True, max_length=2048, null=True, verbose_name="Link"
                    ),
                ),
                (
                    "observation",
                    models.TextField(blank=True, null=True, verbose_name="Observation"),
                ),
                (
                    "evidence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revision",
                        to="core.evidence",
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        default=iam.models.Folder.get_root_folder_id,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_folder",
                        to="iam.folder",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
