# Generated by Django 5.2.6 on 2025-09-18 06:47

from django.db import migrations


def migrate_evidence_data_to_revisions(apps, schema_editor):
    """
    Migrate existing Evidence attachment and link data to EvidenceRevision
    BEFORE removing the fields from Evidence
    """
    Evidence = apps.get_model("core", "Evidence")
    EvidenceRevision = apps.get_model("core", "EvidenceRevision")

    # Process all Evidence objects
    for evidence in Evidence.objects.all():
        # Get attachment and link from the Evidence object
        attachment = getattr(evidence, "attachment", None)
        link = getattr(evidence, "link", None)

        # Check if this evidence already has a revision
        if attachment or link:
            EvidenceRevision.objects.create(
                evidence=evidence,
                version=1,
                attachment=attachment,
                link=link,
                folder=evidence.folder,
            )


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0097_evidence_lifecycle_schema"),
    ]

    operations = [
        # Migrate data from Evidence to EvidenceRevision
        migrations.RunPython(migrate_evidence_data_to_revisions),
        # Remove old fields from Evidence model
        migrations.RemoveField(
            model_name="evidence",
            name="attachment",
        ),
        migrations.RemoveField(
            model_name="evidence",
            name="link",
        ),
    ]
