# Generated by Django 5.2.6 on 2025-09-17 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0098_alter_evidencerevision_is_published"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="evidencerevision",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="evidence",
            name="attachment",
        ),
        migrations.RemoveField(
            model_name="evidence",
            name="link",
        ),
        migrations.AlterField(
            model_name="evidencerevision",
            name="is_published",
            field=models.BooleanField(default=False, verbose_name="published"),
        ),
    ]
