# Generated by Django 5.2.6 on 2025-09-23 09:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0098_evidence_lifecycle_data_migration"),
        ("tprm", "0006_entityassessment_is_locked"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="entities",
            field=models.ManyToManyField(
                blank=True,
                related_name="incidents",
                to="tprm.entity",
                verbose_name="Entities",
            ),
        ),
    ]
