# Generated by Django 5.2.6 on 2025-09-17 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0099_alter_evidencerevision_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evidencerevision",
            name="evidence",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="revisions",
                to="core.evidence",
            ),
        ),
    ]
