# Generated by Django 5.2.7 on 2025-10-03 10:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0099_incident_entities"),
    ]

    operations = [
        migrations.AlterField(
            model_name="terminology",
            name="field_path",
            field=models.CharField(
                choices=[
                    ("ro_to.risk_origin", "ro_to/risk_origin"),
                    ("qualifications", "qualifications"),
                    ("accreditation.status", "accreditationStatus"),
                    ("accreditation.category", "accreditationCategory"),
                ],
                max_length=100,
                verbose_name="Field path",
            ),
        ),
    ]
