# Generated by Django 5.2.7 on 2025-10-03 12:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0100_alter_terminology_field_path"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasktemplate",
            name="assigned_to",
            field=models.ManyToManyField(
                blank=True,
                related_name="task_templates",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Assigned to",
            ),
        ),
    ]
