# Generated by Django 5.2.6 on 2025-09-18 06:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0100_alter_evidencerevision_evidence"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evidence",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("missing", "Missing"),
                    ("in_review", "In review"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("expired", "Expired"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
