# Generated by Django 5.2.7 on 2025-10-04 09:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0103_alter_terminology_field_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="finding",
            name="status",
            field=models.CharField(
                choices=[
                    ("--", "Undefined"),
                    ("identified", "Identified"),
                    ("confirmed", "Confirmed"),
                    ("dismissed", "Dismissed"),
                    ("assigned", "Assigned"),
                    ("in_progress", "In Progress"),
                    ("mitigated", "Mitigated"),
                    ("resolved", "Resolved"),
                    ("closed", "Closed"),
                    ("deprecated", "Deprecated"),
                ],
                default="--",
                max_length=32,
                verbose_name="Status",
            ),
        ),
    ]
