# Generated by Django 5.2.7 on 2025-10-10 18:59

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0104_add_info_severity"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="recovery_capabilities",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Actual recovery objectives",
                validators=[
                    core.validators.JSONSchemaInstanceValidator(
                        {
                            "$id": "https://ciso-assistant.com/schemas/assets/security_objectives.schema.json",
                            "$schema": "https://json-schema.org/draft/2020-12/schema",
                            "description": "The security objectives of the asset",
                            "properties": {
                                "objectives": {
                                    "patternProperties": {
                                        "^[a-z_]+$": {
                                            "properties": {
                                                "value": {
                                                    "minimum": 0,
                                                    "type": "integer",
                                                }
                                            },
                                            "type": "object",
                                        }
                                    },
                                    "type": "object",
                                }
                            },
                            "title": "Security objectives",
                            "type": "object",
                        }
                    )
                ],
                verbose_name="Recovery objectives",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="security_capabilities",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Actual security capabilities",
                validators=[
                    core.validators.JSONSchemaInstanceValidator(
                        {
                            "$id": "https://ciso-assistant.com/schemas/assets/security_objectives.schema.json",
                            "$schema": "https://json-schema.org/draft/2020-12/schema",
                            "description": "The security objectives of the asset",
                            "properties": {
                                "objectives": {
                                    "patternProperties": {
                                        "^[a-z_]+$": {
                                            "properties": {
                                                "is_enabled": {"type": "boolean"},
                                                "value": {
                                                    "maximum": 4,
                                                    "minimum": 0,
                                                    "type": "integer",
                                                },
                                            },
                                            "type": "object",
                                        }
                                    },
                                    "type": "object",
                                }
                            },
                            "title": "Security objectives",
                            "type": "object",
                        }
                    )
                ],
                verbose_name="Security capabilities",
            ),
        ),
    ]
