# Generated by Django 5.2.7 on 2025-10-13

from django.db import migrations


def create_entity_relationship_terminology(apps, schema_editor):
    """Create terminology records for entity relationships"""
    Terminology = apps.get_model("core", "Terminology")

    DEFAULT_ENTITY_RELATIONSHIPS = [
        {
            "name": "regulatory_authority",
            "builtin": True,
            "field_path": "entity.relationship",
            "is_visible": True,
        },
        {
            "name": "partner",
            "builtin": True,
            "field_path": "entity.relationship",
            "is_visible": True,
        },
        {
            "name": "accreditation_authority",
            "builtin": True,
            "field_path": "entity.relationship",
            "is_visible": True,
        },
        {
            "name": "client",
            "builtin": True,
            "field_path": "entity.relationship",
            "is_visible": True,
        },
        {
            "name": "supplier",
            "builtin": True,
            "field_path": "entity.relationship",
            "is_visible": True,
        },
        {
            "name": "contractor",
            "builtin": True,
            "field_path": "entity.relationship",
            "is_visible": True,
        },
        {
            "name": "other",
            "builtin": True,
            "field_path": "entity.relationship",
            "is_visible": True,
        },
    ]

    # Use update_or_create for idempotency (safe for users who already have these records)
    for item in DEFAULT_ENTITY_RELATIONSHIPS:
        Terminology.objects.update_or_create(
            name=item["name"],
            field_path=item["field_path"],
            defaults={
                "builtin": item["builtin"],
                "is_visible": item["is_visible"],
            },
        )


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0104_add_info_severity"),
    ]

    operations = [
        migrations.RunPython(
            create_entity_relationship_terminology, migrations.RunPython.noop
        ),
    ]
