# Generated by Django 5.2.6 on 2025-10-14 12:56

from django.db import migrations


def publish_terminologies(apps, schema_editor):
    """Publish terminologies that are not published yet."""
    Terminology = apps.get_model("core", "Terminology")

    Terminology.objects.filter(is_published=False).update(is_published=True)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0104_add_info_severity"),
    ]

    operations = [
        migrations.RunPython(publish_terminologies, migrations.RunPython.noop)
    ]
