# Generated by Django 5.2.6 on 2025-10-14 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0105_publish_terminologies"),
    ]

    operations = [
        migrations.AlterField(
            model_name="terminology",
            name="is_published",
            field=models.BooleanField(default=True, verbose_name="published"),
        ),
    ]
