# Generated by Django 5.2.7 on 2025-10-04 10:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0105_add_info_severity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="finding",
            name="severity",
            field=models.SmallIntegerField(
                choices=[
                    (-1, "undefined"),
                    (0, "info"),
                    (1, "low"),
                    (2, "medium"),
                    (3, "high"),
                    (4, "critical"),
                ],
                default=-1,
                verbose_name="Severity",
            ),
        ),
        migrations.AlterField(
            model_name="securityexception",
            name="severity",
            field=models.SmallIntegerField(
                choices=[
                    (-1, "undefined"),
                    (0, "info"),
                    (1, "low"),
                    (2, "medium"),
                    (3, "high"),
                    (4, "critical"),
                ],
                default=-1,
                verbose_name="Severity",
            ),
        ),
        migrations.AlterField(
            model_name="vulnerability",
            name="severity",
            field=models.SmallIntegerField(
                choices=[
                    (-1, "undefined"),
                    (0, "info"),
                    (1, "low"),
                    (2, "medium"),
                    (3, "high"),
                    (4, "critical"),
                ],
                default=-1,
                verbose_name="Severity",
            ),
        ),
    ]
