# Generated by Django 5.2.6 on 2025-10-17 11:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0107_asset_recovery_capabilities_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="requirementnode",
            name="importance",
            field=models.CharField(
                choices=[
                    ("mandatory", "Mandatory"),
                    ("recommended", "Recommended"),
                    ("nice_to_have", "Nice to have"),
                    ("undefined", "Undefined"),
                ],
                default="undefined",
                max_length=20,
                verbose_name="Importance",
            ),
        ),
        migrations.AddField(
            model_name="requirementnode",
            name="weight",
            field=models.IntegerField(default=1, verbose_name="Weight"),
        ),
    ]
