# Generated by Django 5.2.7 on 2025-10-28 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0108_requirementnode_importance_requirementnode_weight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="asset_class",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assets",
                to="core.assetclass",
            ),
        ),
    ]
