# Generated by Django 5.2.7 on 2025-11-01 11:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0109_alter_asset_asset_class"),
    ]

    operations = [
        migrations.AlterField(
            model_name="riskscenario",
            name="justification",
            field=models.CharField(
                blank=True, max_length=2000, null=True, verbose_name="Justification"
            ),
        ),
    ]
