# Generated by Django 5.2.7 on 2025-11-07 17:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0111_finding_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="is_critical",
            field=models.BooleanField(default=False, verbose_name="is_critical"),
        ),
    ]
