# Generated by Django 5.2.7 on 2025-11-11 08:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0112_asset_is_critical"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="is_business_function",
            field=models.BooleanField(
                default=False, verbose_name="is_business_function"
            ),
        ),
    ]
