# Generated by Django 5.2.7 on 2025-11-04 12:36

from django.db import migrations
from django.db.models import Q
import structlog

logger = structlog.get_logger(__name__)


def autoload_mapping_libraries(apps, schema_editor):
    StoredLibrary = apps.get_model("core", "StoredLibrary")
    try:
        StoredLibrary.objects.filter(
            Q(content__requirement_mapping_set__isnull=False)
            | Q(content__requirement_mapping_sets__isnull=False)
        ).update(autoload=True)
    except Exception:
        logger.error("Error autoloading mapping sets", exc_info=True)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0112_storedlibrary_autoload"),
    ]

    operations = [
        migrations.RunPython(autoload_mapping_libraries),
    ]
