# Generated by Django 5.2.7 on 2025-11-17 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0114_asset_dora_criticality_assessment_and_more"),
        ("ebios_rm", "0019_alter_ebiosrmstudy_quotation_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="riskscenario",
            name="operational_scenario",
            field=models.ForeignKey(
                blank=True,
                help_text="EBIOS RM operational scenario that generated this risk scenario",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="risk_scenarios",
                to="ebios_rm.operationalscenario",
                verbose_name="Operational scenario",
            ),
        ),
    ]
