# Generated by Django 5.2.7 on 2025-11-18 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0114_asset_dora_criticality_assessment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedcontrol',
            name='is_synced_from_reference_control',
            field=models.BooleanField(default=True, verbose_name='Is synced from reference control'),
        ),
        migrations.AlterField(
            model_name='appliedcontrol',
            name='reference_control',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applied_controls', to='core.referencecontrol', verbose_name='Reference Control'),
        ),
    ]
