# Generated by Django 5.2.7 on 2025-11-20 17:51

import django.db.models.deletion
import iam.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0115_riskscenario_operational_scenario"),
        ("crq", "0001_initial"),
        ("ebios_rm", "0019_alter_ebiosrmstudy_quotation_method"),
        ("iam", "0016_folder_filtering_labels"),
        ("resilience", "0003_alter_escalationthreshold_qualifications"),
        ("tprm", "0008_entity_country_entity_currency_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ValidationFlow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
                ("request_notes", models.TextField(blank=True, null=True)),
                (
                    "ref_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="Reference ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("revoked", "Revoked"),
                            ("expired", "Expired"),
                            ("dropped", "Dropped"),
                            ("change_requested", "Change requested"),
                        ],
                        default="submitted",
                        max_length=20,
                    ),
                ),
                (
                    "validation_deadline",
                    models.DateField(
                        blank=True, null=True, verbose_name="Validation deadline"
                    ),
                ),
                (
                    "approver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "business_impact_analysis",
                    models.ManyToManyField(
                        blank=True, to="resilience.businessimpactanalysis"
                    ),
                ),
                (
                    "compliance_assessments",
                    models.ManyToManyField(blank=True, to="core.complianceassessment"),
                ),
                (
                    "crq_studies",
                    models.ManyToManyField(blank=True, to="crq.quantitativeriskstudy"),
                ),
                (
                    "ebios_studies",
                    models.ManyToManyField(blank=True, to="ebios_rm.ebiosrmstudy"),
                ),
                (
                    "entity_assessments",
                    models.ManyToManyField(blank=True, to="tprm.entityassessment"),
                ),
                ("evidences", models.ManyToManyField(blank=True, to="core.evidence")),
                (
                    "filtering_labels",
                    models.ManyToManyField(
                        blank=True, to="core.filteringlabel", verbose_name="Labels"
                    ),
                ),
                (
                    "findings_assessments",
                    models.ManyToManyField(blank=True, to="core.findingsassessment"),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        default=iam.models.Folder.get_root_folder_id,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_folder",
                        to="iam.folder",
                    ),
                ),
                ("policies", models.ManyToManyField(blank=True, to="core.policy")),
                (
                    "requester",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="validation_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Requester",
                    ),
                ),
                (
                    "risk_assessments",
                    models.ManyToManyField(blank=True, to="core.riskassessment"),
                ),
                (
                    "security_exceptions",
                    models.ManyToManyField(blank=True, to="core.securityexception"),
                ),
            ],
            options={
                "verbose_name": "Validation flow",
                "verbose_name_plural": "Validation flows",
            },
        ),
        migrations.CreateModel(
            name="FlowEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
                (
                    "event_type",
                    models.CharField(max_length=50, verbose_name="Event type"),
                ),
                (
                    "event_notes",
                    models.TextField(blank=True, null=True, verbose_name="Event notes"),
                ),
                (
                    "is_tainted",
                    models.BooleanField(default=False, verbose_name="Is tainted"),
                ),
                (
                    "event_actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Event actor",
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        default=iam.models.Folder.get_root_folder_id,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_folder",
                        to="iam.folder",
                    ),
                ),
                (
                    "validation_flow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="core.validationflow",
                        verbose_name="Validation flow",
                    ),
                ),
            ],
            options={
                "verbose_name": "Flow event",
                "verbose_name_plural": "Flow events",
                "ordering": ["-created_at"],
            },
        ),
    ]
