# Generated by Django 5.2.7 on 2025-11-21 08:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0115_riskscenario_operational_scenario"),
    ]

    operations = [
        migrations.AddField(
            model_name="storedlibrary",
            name="filtering_labels",
            field=models.ManyToManyField(
                blank=True, to="core.filteringlabel", verbose_name="Labels"
            ),
        ),
    ]
