# Generated by Django 5.2.7 on 2025-11-19 12:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0116_validationflow"),
        ("resilience", "0003_alter_escalationthreshold_qualifications"),
    ]

    operations = [
        migrations.AddField(
            model_name="validationflow",
            name="business_impact_analysis",
            field=models.ManyToManyField(
                blank=True, to="resilience.businessimpactanalysis"
            ),
        ),
    ]
