# Generated by Django 5.2.7 on 2025-11-20 17:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0116_validationflow_flowevent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="validationflow",
            name="expiration_date",
        ),
        migrations.AddField(
            model_name="validationflow",
            name="validation_deadline",
            field=models.DateField(
                blank=True, null=True, verbose_name="Validation deadline"
            ),
        ),
    ]
