# Generated by Django 5.2.7 on 2025-11-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0116_validationflow_flowevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasktemplate",
            name="evidences",
            field=models.ManyToManyField(
                blank=True,
                help_text="Evidences related to the task",
                related_name="task_templates",
                to="core.evidence",
            ),
        ),
    ]
