# Generated by Django 5.2.7 on 2025-11-26 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0117_tasktemplate_evidences'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencerevision',
            name='task_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_revisions', to='core.tasknode', verbose_name='Task Node'),
        ),
    ]
