# Generated by Django 5.2.7 on 2025-12-02 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0117_evidencerevision_task_node_tasktemplate_evidences"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="riskscenario",
            name="existing_controls",
        ),
        migrations.AddField(
            model_name="riskscenario",
            name="antecedent_scenarios",
            field=models.ManyToManyField(
                blank=True,
                help_text="Risk scenarios that precede this scenario",
                related_name="consequent_scenarios",
                to="core.riskscenario",
                verbose_name="Antecedent scenarios",
            ),
        ),
        migrations.AddField(
            model_name="riskscenario",
            name="filtering_labels",
            field=models.ManyToManyField(
                blank=True, to="core.filteringlabel", verbose_name="Labels"
            ),
        ),
        migrations.AddField(
            model_name="riskscenario",
            name="risk_origin",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={
                    "field_path": "ro_to.risk_origin",
                    "is_visible": True,
                },
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="risk_scenario_risk_origins",
                to="core.terminology",
                verbose_name="Risk origin",
            ),
        ),
    ]
