# Generated by Django 5.2.7 on 2025-11-19 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0117_validationflow_business_impact_analysis"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="validationflow",
            name="requester",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="validation_requests",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Requester",
            ),
        ),
    ]
