# Generated by Django 5.2.7 on 2025-12-01 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0117_evidencerevision_task_node_tasktemplate_evidences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedcontrol',
            name='reference_control',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applied_controls', to='core.referencecontrol', verbose_name='Reference Control'),
        ),
    ]
