# Generated by Django 5.2.8 on 2025-12-15 14:07

import hashlib
from django.db import migrations, models
from django.core.files.storage import default_storage


def backfill_attachment_hashes(apps, schema_editor):
    """
    Compute and store SHA256 hashes for all existing attachments.
    Uses chunked reading to avoid loading large files into memory.
    """
    EvidenceRevision = apps.get_model("core", "EvidenceRevision")

    revisions_with_attachments = EvidenceRevision.objects.filter(
        attachment__isnull=False
    ).exclude(attachment="")

    total = revisions_with_attachments.count()
    processed = 0
    errors = 0

    print(f"Backfilling attachment hashes for {total} evidence revisions...")

    for revision in revisions_with_attachments.iterator(chunk_size=100):
        try:
            if revision.attachment and default_storage.exists(revision.attachment.name):
                hash_obj = hashlib.sha256()
                with default_storage.open(revision.attachment.name, "rb") as f:
                    for chunk in iter(lambda: f.read(1024 * 1024), b""):  # 1MB chunks
                        hash_obj.update(chunk)

                revision.attachment_hash = hash_obj.hexdigest()
                revision.save(update_fields=["attachment_hash"])
                processed += 1

                if processed % 100 == 0:
                    print(f"  Processed {processed}/{total} revisions...")
        except Exception as e:
            errors += 1
            print(f"  Error processing revision {revision.id}: {e}")

    print(f"Completed: {processed} hashes computed, {errors} errors")


def reverse_backfill(apps, schema_editor):
    """
    Clear all attachment hashes (reverse operation).
    """
    EvidenceRevision = apps.get_model("core", "EvidenceRevision")
    EvidenceRevision.objects.update(attachment_hash=None)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0118_riskscenario_antecedent_scenarios_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="evidencerevision",
            name="attachment_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="SHA256 hash of the attachment file for integrity verification",
                max_length=64,
                null=True,
                verbose_name="Attachment SHA256 Hash",
            ),
        ),
        migrations.RunPython(backfill_attachment_hashes, reverse_backfill),
    ]
