# Generated by Django 5.2.7 on 2025-12-12 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0118_riskscenario_antecedent_scenarios_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedlibrary',
            name='filtering_labels',
            field=models.ManyToManyField(blank=True, to='core.filteringlabel', verbose_name='Labels'),
        ),
    ]
