# Generated by Django 5.2.9 on 2025-12-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0118_riskscenario_antecedent_scenarios_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="securityexception",
            name="observation",
            field=models.TextField(blank=True, null=True, verbose_name="Observation"),
        ),
    ]
