# Generated by Django 5.2.7 on 2025-11-19 18:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0118_validationflow_requester"),
    ]

    operations = [
        migrations.AddField(
            model_name="validationflow",
            name="filtering_labels",
            field=models.ManyToManyField(
                blank=True, to="core.filteringlabel", verbose_name="Labels"
            ),
        ),
    ]
