# Generated by Django 5.2.7 on 2025-12-19 18:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0119_libraryfilteringlabel_storedlibrary_filtering_labels"),
    ]

    operations = [
        migrations.AlterField(
            model_name="terminology",
            name="field_path",
            field=models.CharField(
                choices=[
                    ("ro_to.risk_origin", "ro_to/risk_origin"),
                    ("qualifications", "qualifications"),
                    ("accreditation.status", "accreditationStatus"),
                    ("accreditation.category", "accreditationCategory"),
                    ("entity.relationship", "entityRelationship"),
                    ("metric_definition.unit", "metricUnit"),
                ],
                max_length=100,
                verbose_name="Field path",
            ),
        ),
    ]
