# Generated by Django 5.2.7 on 2025-11-19 18:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0119_validationflow_filtering_labels"),
        ("crq", "0001_initial"),
        ("ebios_rm", "0019_alter_ebiosrmstudy_quotation_method"),
        ("iam", "0016_folder_filtering_labels"),
        ("resilience", "0003_alter_escalationthreshold_qualifications"),
        ("tprm", "0008_entity_country_entity_currency_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="validationflow",
            constraint=models.UniqueConstraint(
                fields=("folder", "ref_id"),
                name="unique_validation_flow_ref_id_per_folder",
            ),
        ),
    ]
