# Generated by Django 5.2.9 on 2025-12-23 15:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0119_securityexception_observation"),
        ("core", "0120_alter_terminology_field_path"),
    ]

    operations = []
