# Generated by Django 5.2.7 on 2025-11-19 19:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0120_validationflow_unique_validation_flow_ref_id_per_folder"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="validationflow",
            name="unique_validation_flow_ref_id_per_folder",
        ),
        migrations.AlterField(
            model_name="validationflow",
            name="ref_id",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Reference ID",
            ),
        ),
    ]
