# Generated by Django 5.2.7 on 2025-11-19 20:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "core",
            "0121_remove_validationflow_unique_validation_flow_ref_id_per_folder_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="validationflow",
            name="approver_observation",
        ),
        migrations.AddField(
            model_name="validationflow",
            name="accept_notes",
            field=models.TextField(blank=True, null=True, verbose_name="Accept notes"),
        ),
        migrations.AddField(
            model_name="validationflow",
            name="changes_request_notes",
            field=models.TextField(
                blank=True, null=True, verbose_name="Changes request notes"
            ),
        ),
        migrations.AddField(
            model_name="validationflow",
            name="drop_notes",
            field=models.TextField(blank=True, null=True, verbose_name="Drop notes"),
        ),
        migrations.AddField(
            model_name="validationflow",
            name="rejection_notes",
            field=models.TextField(
                blank=True, null=True, verbose_name="Rejection notes"
            ),
        ),
        migrations.AddField(
            model_name="validationflow",
            name="revocation_notes",
            field=models.TextField(
                blank=True, null=True, verbose_name="Revocation notes"
            ),
        ),
        migrations.AlterField(
            model_name="validationflow",
            name="status",
            field=models.CharField(
                choices=[
                    ("submitted", "Submitted"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                    ("revoked", "Revoked"),
                    ("expired", "Expired"),
                    ("dropped", "Dropped"),
                    ("change_requested", "Change requested"),
                ],
                default="submitted",
                max_length=20,
            ),
        ),
    ]
