# Generated by Django 5.2.9 on 2025-12-30 17:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0122_complianceassessment_extended_result_enabled_and_more"),
        ("metrology", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisationobjective",
            name="metrics",
            field=models.ManyToManyField(
                blank=True,
                related_name="organisation_objectives",
                to="metrology.metricinstance",
                verbose_name="Tracking metrics",
            ),
        ),
    ]
