# Generated by Django 5.2.7 on 2025-11-19 21:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0122_remove_validationflow_approver_observation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="validationflow",
            name="resubmission_notes",
            field=models.TextField(
                blank=True, null=True, verbose_name="Resubmission notes"
            ),
        ),
    ]
