# Generated by Django 5.2.7 on 2025-11-20 07:28

import django.db.models.deletion
import iam.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0123_validationflow_resubmission_notes"),
        ("iam", "0016_folder_filtering_labels"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="validationflow",
            name="accept_notes",
        ),
        migrations.RemoveField(
            model_name="validationflow",
            name="changes_request_notes",
        ),
        migrations.RemoveField(
            model_name="validationflow",
            name="drop_notes",
        ),
        migrations.RemoveField(
            model_name="validationflow",
            name="rejection_notes",
        ),
        migrations.RemoveField(
            model_name="validationflow",
            name="resubmission_notes",
        ),
        migrations.RemoveField(
            model_name="validationflow",
            name="revocation_notes",
        ),
        migrations.CreateModel(
            name="ValidationFlowEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
                ("event_notes", models.TextField(blank=True, null=True)),
                ("is_tainted", models.BooleanField(default=False)),
                (
                    "event_actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        default=iam.models.Folder.get_root_folder_id,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_folder",
                        to="iam.folder",
                    ),
                ),
                (
                    "validation_flow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="core.validationflow",
                    ),
                ),
            ],
            options={
                "verbose_name": "Validation flow event",
                "verbose_name_plural": "Validation flow events",
                "ordering": ["-created_at"],
            },
        ),
    ]
