# Generated by Django 5.2.9 on 2026-01-06 16:01

import django.db.models.deletion
import iam.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0124_evidencerevision_attachment_hash"),
        ("iam", "0016_folder_filtering_labels"),
        ("tprm", "0009_migrate_solution_to_solutions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "team_email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Team Email"
                    ),
                ),
                (
                    "deputies",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The deputies of the team",
                        related_name="deputy_teams",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Team Deputies",
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        default=iam.models.Folder.get_root_folder_id,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_folder",
                        to="iam.folder",
                    ),
                ),
                (
                    "leader",
                    models.ForeignKey(
                        help_text="The leader of the team",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="led_teams",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Team Leader",
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The members of the team",
                        related_name="teams",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Team Members",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Actor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
                (
                    "entity",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actor",
                        to="tprm.entity",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actor",
                        to="core.team",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("entity__isnull", True),
                                ("team__isnull", True),
                                ("user__isnull", False),
                            ),
                            models.Q(
                                ("entity__isnull", True),
                                ("team__isnull", False),
                                ("user__isnull", True),
                            ),
                            models.Q(
                                ("entity__isnull", False),
                                ("team__isnull", True),
                                ("user__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="actor_exactly_one_link",
                    )
                ],
            },
        ),
    ]
