# Generated by Django 5.2.7 on 2025-11-20 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0124_remove_validationflow_accept_notes_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="validationflowevent",
            name="event_type",
            field=models.CharField(
                default="submitted", max_length=50, verbose_name="Event type"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="validationflowevent",
            name="event_actor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Event actor",
            ),
        ),
        migrations.AlterField(
            model_name="validationflowevent",
            name="event_notes",
            field=models.TextField(blank=True, null=True, verbose_name="Event notes"),
        ),
        migrations.AlterField(
            model_name="validationflowevent",
            name="is_tainted",
            field=models.BooleanField(default=False, verbose_name="Is tainted"),
        ),
        migrations.AlterField(
            model_name="validationflowevent",
            name="validation_flow",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="core.validationflow",
                verbose_name="Validation flow",
            ),
        ),
    ]
