# Generated by Django 5.2.9 on 2026-01-06 16:02
from django.db import migrations
from django.db.models import Subquery, OuterRef


def backfill_actors(apps, schema_editor):
    Actor = apps.get_model("core", "Actor")
    Entity = apps.get_model("tprm", "Entity")
    User = apps.get_model("iam", "User")

    user_ids = User.objects.values_list("id", flat=True)
    Actor.objects.bulk_create(
        (Actor(user_id=uid, is_published=True) for uid in user_ids),
        ignore_conflicts=True,  # Skips duplicates (like get_or_create)
        batch_size=5000,
    )

    entity_ids = Entity.objects.values_list("id", flat=True)
    Actor.objects.bulk_create(
        (Actor(entity_id=eid, is_published=True) for eid in entity_ids),
        ignore_conflicts=True,
        batch_size=5000,
    )


def migrate_user_to_actor(apps, schema_editor):
    Actor = apps.get_model("core", "Actor")

    FK_MAPPINGS = [
        ("webhooks", "WebhookEndpoint", "owner", "new_owner"),
    ]

    M2M_MAPPINGS = [
        ("core", "ComplianceAssessment", "authors", "new_authors"),
        ("core", "ComplianceAssessment", "reviewers", "new_reviewers"),
        ("core", "RiskAssessment", "authors", "new_authors"),
        ("core", "RiskAssessment", "reviewers", "new_reviewers"),
        ("crq", "QuantitativeRiskStudy", "authors", "new_authors"),
        ("crq", "QuantitativeRiskStudy", "reviewers", "new_reviewers"),
        ("ebios_rm", "EbiosRMStudy", "authors", "new_authors"),
        ("ebios_rm", "EbiosRMStudy", "reviewers", "new_reviewers"),
        ("core", "FindingsAssessment", "authors", "new_authors"),
        ("core", "FindingsAssessment", "reviewers", "new_reviewers"),
        ("core", "FindingsAssessment", "owner", "new_owner"),
        ("resilience", "BusinessImpactAnalysis", "authors", "new_authors"),
        ("resilience", "BusinessImpactAnalysis", "reviewers", "new_reviewers"),
        ("core", "Incident", "owners", "new_owners"),
        ("core", "SecurityException", "owners", "new_owners"),
        ("core", "Asset", "owner", "new_owner"),
        ("core", "Evidence", "owner", "new_owner"),
        ("core", "AppliedControl", "owner", "new_owner"),
        ("core", "RiskScenario", "owner", "new_owner"),
        ("core", "Finding", "owner", "new_owner"),
        ("tprm", "Solution", "owner", "new_owner"),
        ("tprm", "Contract", "owner", "new_owner"),
        ("crq", "QuantitativeRiskScenario", "owner", "new_owner"),
        ("metrology", "MetricInstance", "owner", "new_owner"),
        ("privacy", "RightRequest", "owner", "new_owner"),
    ]

    # FKs
    for app_label, model_name, old_field, new_field in FK_MAPPINGS:
        Model = apps.get_model(app_label, model_name)
        print(f"FK: {model_name}.{old_field} -> {new_field}")

        actor_subquery = Subquery(
            Actor.objects.filter(user_id=OuterRef(f"{old_field}_id")).values("pk")[:1]
        )
        Model.objects.filter(**{f"{old_field}__isnull": False}).update(
            **{new_field: actor_subquery}
        )

    # M2M
    user_to_actor_map = dict(
        Actor.objects.filter(user__isnull=False).values_list("user_id", "id")
    )

    for app_label, model_name, old_field, new_field in M2M_MAPPINGS:
        Model = apps.get_model(app_label, model_name)
        print(f"M2M: {model_name}.{old_field} -> {new_field}")

        OldThrough = getattr(Model, old_field).through
        NewThrough = getattr(Model, new_field).through

        parent_field_name = next(
            f.name
            for f in NewThrough._meta.get_fields()
            if f.is_relation and f.name not in ("id", "actor")
        )

        old_relations = OldThrough.objects.values_list(parent_field_name, "user_id")

        new_relations = []
        for parent_id, user_id in old_relations:
            actor_id = user_to_actor_map.get(user_id)
            if actor_id:
                new_relations.append(
                    NewThrough(
                        **{
                            f"{parent_field_name}_id": parent_id,
                            "actor_id": actor_id,
                        }
                    )
                )

        if new_relations:
            NewThrough.objects.bulk_create(
                new_relations, ignore_conflicts=True, batch_size=5000
            )


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0125_team_actor"),
        ("crq", "0002_quantitativeriskscenario_new_owner_and_more"),
        ("metrology", "0002_metricinstance_new_owner"),
        ("privacy", "0012_rightrequest_new_owner"),
        ("resilience", "0004_businessimpactanalysis_new_authors_and_more"),
        ("tprm", "0010_contract_new_owner_entityassessment_new_authors_and_more"),
        ("ebios_rm", "0022_ebiosrmstudy_new_authors_ebiosrmstudy_new_reviewers"),
        ("webhooks", "0002_webhookendpoint_new_owner"),
    ]

    operations = [
        migrations.RunPython(backfill_actors),
        migrations.RunPython(migrate_user_to_actor),
    ]
