# Generated by Django 5.2.9 on 2026-01-06 16:02

from django.db import migrations


def backfill_actors(apps, schema_editor):
    Actor = apps.get_model("core", "Actor")
    Entity = apps.get_model("tprm", "Entity")
    User = apps.get_model("iam", "User")

    for user in User.objects.all():
        Actor.objects.get_or_create(user=user)

    for entity in Entity.objects.all():
        Actor.objects.get_or_create(entity=entity)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0125_team_actor"),
    ]

    operations = [
        migrations.RunPython(backfill_actors),
    ]
