# Generated by Django 5.2.9 on 2026-01-06 16:02

from django.db import migrations
from django.db.models import Subquery, OuterRef


def backfill_actors(apps, schema_editor):
    Actor = apps.get_model("core", "Actor")
    Entity = apps.get_model("tprm", "Entity")
    User = apps.get_model("iam", "User")

    for user in User.objects.all():
        Actor.objects.get_or_create(user=user, defaults={"is_published": True})

    for entity in Entity.objects.all():
        Actor.objects.get_or_create(entity=entity, defaults={"is_published": True})


def migrate_user_to_actor(apps, schema_editor):
    Actor = apps.get_model("core", "Actor")

    FK_MAPPINGS = [
        # (App Label, Model Name, Old Field, New Field)
        ("webhooks", "WebhookEndpoint", "owner", "new_owner"),
    ]

    M2M_MAPPINGS = [
        # (App Label, Model Name, Old Field, New Field)
        ("core", "ComplianceAssessment", "authors", "new_authors"),
        ("core", "ComplianceAssessment", "reviewers", "new_reviewers"),
        ("core", "RiskAssessment", "authors", "new_authors"),
        ("core", "RiskAssessment", "reviewers", "new_reviewers"),
        ("crq", "QuantitativeRiskStudy", "authors", "new_authors"),
        ("crq", "QuantitativeRiskStudy", "reviewers", "new_reviewers"),
        ("ebios_rm", "EbiosRMStudy", "authors", "new_authors"),
        ("ebios_rm", "EbiosRMStudy", "reviewers", "new_reviewers"),
        ("core", "FindingsAssessment", "authors", "new_authors"),
        ("core", "FindingsAssessment", "reviewers", "new_reviewers"),
        ("core", "FindingsAssessment", "owner", "new_owner"),
        ("resilience", "BusinessImpactAnalysis", "authors", "new_authors"),
        ("resilience", "BusinessImpactAnalysis", "reviewers", "new_reviewers"),
        ("core", "Incident", "owners", "new_owners"),
        ("core", "SecurityException", "owners", "new_owners"),
        ("core", "Asset", "owner", "new_owner"),
        ("core", "Evidence", "owner", "new_owner"),
        ("core", "AppliedControl", "owner", "new_owner"),
        ("core", "RiskScenario", "owner", "new_owner"),
        ("core", "Finding", "owner", "new_owner"),
        ("tprm", "Solution", "owner", "new_owner"),
        ("tprm", "Contract", "owner", "new_owner"),
        ("crq", "QuantitativeRiskScenario", "owner", "new_owner"),
        ("metrology", "MetricInstance", "owner", "new_owner"),
        ("privacy", "RightRequest", "owner", "new_owner"),
    ]

    # fk migrations
    for app_label, model_name, old_field, new_field in FK_MAPPINGS:
        Model = apps.get_model(app_label, model_name)
        print(f"FK: {model_name}.{old_field} -> {new_field}")

        actor_subquery = Subquery(
            Actor.objects.filter(user_id=OuterRef(f"{old_field}_id")).values("pk")[:1]
        )
        Model.objects.filter(**{f"{old_field}__isnull": False}).update(
            **{new_field: actor_subquery}
        )

    # m2m migrations
    for app_label, model_name, old_field, new_field in M2M_MAPPINGS:
        Model = apps.get_model(app_label, model_name)
        print(f"M2M: {model_name}.{old_field} -> {new_field}")

        NewThrough = getattr(Model, new_field).through
        new_relations = []

        # Determine the column name for the model (e.g. 'riskassessment_id')
        # Standard Django behavior is lowercase model name + _id
        model_fk_column = f"{model_name.lower()}_id"

        # Fetch items with existing relations, prefetching the actor
        items = Model.objects.exclude(
            **{f"{old_field}__isnull": True}
        ).prefetch_related(f"{old_field}__actor")

        for item in items:
            for user in getattr(item, old_field).all():
                if hasattr(user, "actor"):
                    new_relations.append(
                        NewThrough(
                            **{model_fk_column: item.id, "actor_id": user.actor.id}
                        )
                    )

            # Batch insert every 2000 items
            if len(new_relations) > 2000:
                NewThrough.objects.bulk_create(new_relations, ignore_conflicts=True)
                new_relations = []

        # Insert remaining
        if new_relations:
            NewThrough.objects.bulk_create(new_relations, ignore_conflicts=True)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0125_team_actor"),
        ("crq", "0002_quantitativeriskscenario_new_owner_and_more"),
        ("metrology", "0002_metricinstance_new_owner"),
        ("privacy", "0012_rightrequest_new_owner"),
        ("resilience", "0004_businessimpactanalysis_new_authors_and_more"),
        ("tprm", "0010_contract_new_owner_entityassessment_new_authors_and_more"),
        ("ebios_rm", "0022_ebiosrmstudy_new_authors_ebiosrmstudy_new_reviewers"),
        ("webhooks", "0002_webhookendpoint_new_owner"),
    ]

    operations = [
        migrations.RunPython(backfill_actors),
        migrations.RunPython(migrate_user_to_actor),
    ]
