# Generated by Django 5.2.9 on 2026-01-06 16:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0126_data_backfill_actors"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="team",
            options={},
        ),
    ]
