# Generated by Django 5.2.9 on 2026-01-08 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0126_alter_team_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedcontrol',
            name='new_owner',
            field=models.ManyToManyField(blank=True, related_name='applied_controls', to='core.actor', verbose_name='Owner'),
        ),
        migrations.AddField(
            model_name='asset',
            name='new_owner',
            field=models.ManyToManyField(blank=True, related_name='assets', to='core.actor', verbose_name='Owner'),
        ),
        migrations.AddField(
            model_name='complianceassessment',
            name='new_authors',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_authors_new', to='core.actor', verbose_name='Authors'),
        ),
        migrations.AddField(
            model_name='complianceassessment',
            name='new_reviewers',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_reviewers_new', to='core.actor', verbose_name='Reviewers'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='new_owner',
            field=models.ManyToManyField(blank=True, related_name='evidences', to='core.actor', verbose_name='Owner'),
        ),
        migrations.AddField(
            model_name='finding',
            name='new_owner',
            field=models.ManyToManyField(blank=True, related_name='findings', to='core.actor', verbose_name='Owner'),
        ),
        migrations.AddField(
            model_name='findingsassessment',
            name='new_authors',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_authors_new', to='core.actor', verbose_name='Authors'),
        ),
        migrations.AddField(
            model_name='findingsassessment',
            name='new_owner',
            field=models.ManyToManyField(blank=True, related_name='findings_assessments', to='core.actor', verbose_name='Owner'),
        ),
        migrations.AddField(
            model_name='findingsassessment',
            name='new_reviewers',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_reviewers_new', to='core.actor', verbose_name='Reviewers'),
        ),
        migrations.AddField(
            model_name='incident',
            name='new_owners',
            field=models.ManyToManyField(blank=True, related_name='incidents', to='core.actor', verbose_name='Owner'),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='new_authors',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_authors_new', to='core.actor', verbose_name='Authors'),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='new_reviewers',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_reviewers_new', to='core.actor', verbose_name='Reviewers'),
        ),
        migrations.AddField(
            model_name='riskscenario',
            name='new_owner',
            field=models.ManyToManyField(blank=True, related_name='risk_scenarios', to='core.actor', verbose_name='Owner'),
        ),
        migrations.AddField(
            model_name='securityexception',
            name='new_owners',
            field=models.ManyToManyField(blank=True, related_name='security_exceptions', to='core.actor', verbose_name='Owner'),
        ),
    ]
