# Generated by Django 5.2.9 on 2026-01-20 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0127_remove_appliedcontrol_new_owner_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisationobjective",
            name="new_assigned_to",
            field=models.ManyToManyField(
                blank=True,
                to="core.actor",
                verbose_name="Assigned to",
                related_name="assigned_organisation_objectives",
            ),
        ),
        migrations.AddField(
            model_name="tasktemplate",
            name="new_assigned_to",
            field=models.ManyToManyField(
                blank=True,
                to="core.actor",
                verbose_name="Assigned to",
                related_name="assigned_task_templates",
            ),
        ),
        migrations.AddField(
            model_name="perimeter",
            name="new_default_assignee",
            field=models.ManyToManyField(
                blank=True,
                related_name="perimeter_default_assignee",
                to="core.actor",
                verbose_name="Default assignee",
            ),
        ),
        migrations.AddField(
            model_name="timelineentry",
            name="new_author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="timeline_entries",
                to="core.actor",
                verbose_name="Author",
            ),
        ),
    ]
