# Generated by Django 5.2.9 on 2026-01-20 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0127_remove_appliedcontrol_new_owner_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisationobjective",
            name="new_assigned_to",
            field=models.ManyToManyField(
                blank=True,
                to="core.actor",
                verbose_name="Assigned to",
                related_name="assigned_organisation_objectives",
            ),
        ),
        migrations.AddField(
            model_name="tasktemplate",
            name="new_assigned_to",
            field=models.ManyToManyField(
                blank=True,
                to="core.actor",
                verbose_name="Assigned to",
                related_name="assigned_task_templates",
            ),
        ),
    ]
