# Generated by Django 5.2.9 on 2026-01-20 14:17

from django.db import migrations
from django.db.models import Subquery, OuterRef


def migrate_user_to_actor(apps, schema_editor):
    Actor = apps.get_model("core", "Actor")

    FK_MAPPINGS = [
        ("core", "TimelineEntry", "author", "new_author"),
    ]

    M2M_MAPPINGS = [
        ("core", "OrganisationObjective", "assigned_to", "new_assigned_to"),
        ("core", "TaskTemplate", "assigned_to", "new_assigned_to"),
        ("core", "Perimeter", "default_assignee", "new_default_assignee"),
        ("privacy", "DataBreach", "assigned_to", "new_assigned_to"),
        ("privacy", "Processing", "assigned_to", "new_assigned_to"),
    ]

    # FKs
    for app_label, model_name, old_field, new_field in FK_MAPPINGS:
        Model = apps.get_model(app_label, model_name)
        print(f"FK: {model_name}.{old_field} -> {new_field}")

        actor_subquery = Subquery(
            Actor.objects.filter(user_id=OuterRef(f"{old_field}_id")).values("pk")[:1]
        )
        Model.objects.filter(**{f"{old_field}__isnull": False}).update(
            **{new_field: actor_subquery}
        )

    # M2M
    user_to_actor_map = dict(
        Actor.objects.filter(user__isnull=False).values_list("user_id", "id")
    )

    for app_label, model_name, old_field, new_field in M2M_MAPPINGS:
        Model = apps.get_model(app_label, model_name)
        print(f"M2M: {model_name}.{old_field} -> {new_field}")

        OldThrough = getattr(Model, old_field).through
        NewThrough = getattr(Model, new_field).through

        parent_field_name = next(
            f.name
            for f in NewThrough._meta.get_fields()
            if f.is_relation and f.name not in ("id", "actor")
        )

        old_relations = OldThrough.objects.values_list(parent_field_name, "user_id")

        new_relations = []
        for parent_id, user_id in old_relations:
            actor_id = user_to_actor_map.get(user_id)
            if actor_id:
                new_relations.append(
                    NewThrough(
                        **{
                            f"{parent_field_name}_id": parent_id,
                            "actor_id": actor_id,
                        }
                    )
                )

        if new_relations:
            NewThrough.objects.bulk_create(
                new_relations, ignore_conflicts=True, batch_size=5000
            )


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0128_alter_organisationobjective_assigned_to_and_more"),
        ("privacy", "0014_remove_processing_owner"),
    ]

    operations = [migrations.RunPython(migrate_user_to_actor)]
