# Generated by Django 5.2.9 on 2026-01-20 14:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "core",
            "0129_data_backfill_organisationobjective_tasktemplete_databreach_processing_actor",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organisationobjective",
            name="assigned_to",
        ),
        migrations.RemoveField(
            model_name="tasktemplate",
            name="assigned_to",
        ),
        migrations.RemoveField(
            model_name="perimeter",
            name="default_assignee",
        ),
        migrations.RemoveField(
            model_name="timelineentry",
            name="author",
        ),
        migrations.RenameField(
            model_name="organisationobjective",
            old_name="new_assigned_to",
            new_name="assigned_to",
        ),
        migrations.RenameField(
            model_name="tasktemplate",
            old_name="new_assigned_to",
            new_name="assigned_to",
        ),
        migrations.RenameField(
            model_name="perimeter",
            old_name="new_default_assignee",
            new_name="default_assignee",
        ),
        migrations.RenameField(
            model_name="timelineentry",
            old_name="new_author",
            new_name="author",
        ),
    ]
