# Generated by Django 5.2.9 on 2026-01-22 09:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0130_remove_organisationobjective_new_assigned_to_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="findingsassessment",
            name="owner",
        ),
    ]
