# Generated by Django 5.2.9 on 2026-01-21 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0130_remove_organisationobjective_new_assigned_to_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="requirementnode",
            name="parent_node",
            field=models.ForeignObject(
                from_fields=["parent_urn"],
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="child_nodes",
                to="core.requirementnode",
                to_fields=["urn"],
            ),
        ),
    ]
