# Generated by Django 5.2.9 on 2026-01-26 13:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0131_remove_findingsassessment_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="complianceassessment",
            name="score_calculation_method",
            field=models.CharField(
                choices=[("average", "Average"), ("sum", "Sum")],
                default="average",
                max_length=100,
                verbose_name="Score Calculation Method",
            ),
        ),
    ]
