# Generated by Django 5.2.9 on 2026-01-31 06:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0132_complianceassessment_score_calculation_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisationissue",
            name="expiration_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Expiration date"
            ),
        ),
        migrations.AddField(
            model_name="organisationissue",
            name="start_date",
            field=models.DateField(blank=True, null=True, verbose_name="Start date"),
        ),
        migrations.AddField(
            model_name="organisationissue",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                ],
                default="draft",
                max_length=100,
                verbose_name="Status",
            ),
        ),
    ]
