# Generated by Django 5.2.9 on 2026-01-29 13:40

import django.db.models.deletion
import iam.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0132_complianceassessment_score_calculation_method"),
        ("iam", "0019_add_view_globalsettings_in_custom_roles"),
    ]

    operations = [
        migrations.AddField(
            model_name="riskscenario",
            name="folder",
            field=models.ForeignKey(
                default=iam.models.Folder.get_root_folder_id,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_folder",
                to="iam.folder",
            ),
        ),
        migrations.AlterField(
            model_name="complianceassessment",
            name="perimeter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.perimeter",
                verbose_name="Perimeter",
            ),
        ),
        migrations.AlterField(
            model_name="findingsassessment",
            name="perimeter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.perimeter",
                verbose_name="Perimeter",
            ),
        ),
        migrations.AlterField(
            model_name="riskassessment",
            name="perimeter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.perimeter",
                verbose_name="Perimeter",
            ),
        ),
    ]
