# Generated by Django 5.2.9 on 2026-01-28 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0132_complianceassessment_score_calculation_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complianceassessment",
            name="perimeter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.perimeter",
                verbose_name="Perimeter",
            ),
        ),
        migrations.AlterField(
            model_name="findingsassessment",
            name="perimeter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.perimeter",
                verbose_name="Perimeter",
            ),
        ),
        migrations.AlterField(
            model_name="riskassessment",
            name="perimeter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.perimeter",
                verbose_name="Perimeter",
            ),
        ),
    ]
