# Generated by Django 6.0.2 on 2026-02-06 16:47

import django.db.models.deletion
import iam.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0134_populate_riskscenario_folder"),
        ("iam", "0019_add_view_globalsettings_in_custom_roles"),
    ]

    operations = [
        migrations.CreateModel(
            name="RequirementAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requirement_assignments",
                        to="core.actor",
                        verbose_name="Assigned To",
                    ),
                ),
                (
                    "compliance_assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requirement_assignments",
                        to="core.complianceassessment",
                        verbose_name="Compliance Assessment",
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        default=iam.models.Folder.get_root_folder_id,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_folder",
                        to="iam.folder",
                    ),
                ),
                (
                    "requirement_assessments",
                    models.ManyToManyField(
                        blank=True,
                        related_name="assignments",
                        to="core.requirementassessment",
                        verbose_name="Requirement Assessments",
                    ),
                ),
            ],
            options={
                "verbose_name": "Requirement Assignment",
                "verbose_name_plural": "Requirement Assignments",
                "ordering": ["created_at"],
            },
        ),
    ]
