# Generated by Django 6.0.2 on 2026-02-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0135_requirementassignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="filtering_labels",
            field=models.ManyToManyField(
                blank=True, to="core.filteringlabel", verbose_name="Labels"
            ),
        ),
    ]
