# Generated by Django 5.2.9 on 2026-02-16 16:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0136_incident_filtering_labels"),
    ]

    operations = [
        migrations.AddField(
            model_name="finding",
            name="threats",
            field=models.ManyToManyField(
                blank=True,
                related_name="findings",
                to="core.threat",
                verbose_name="Threats",
            ),
        ),
    ]
