# Generated by Django 5.2.9 on 2026-02-16 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0136_incident_filtering_labels"),
    ]

    operations = [
        migrations.AddField(
            model_name="complianceassessment",
            name="auto_sync",
            field=models.BooleanField(
                default=False, verbose_name="Automatic sync to actions"
            ),
        ),
        migrations.AddField(
            model_name="findingsassessment",
            name="auto_sync",
            field=models.BooleanField(
                default=False, verbose_name="Automatic sync to actions"
            ),
        ),
        migrations.AddField(
            model_name="riskassessment",
            name="auto_sync",
            field=models.BooleanField(
                default=False, verbose_name="Automatic sync to actions"
            ),
        ),
    ]
