# Generated by Django 6.0.2 on 2026-02-26 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0137_add_threats_to_finding"),
        ("pmbok", "0003_remove_accreditation_new_author_and_more"),
        ("privacy", "0017_data_split_legal_basis_choices"),
        ("tprm", "0014_alter_solution_dora_alternative_providers_identified"),
    ]

    operations = [
        migrations.AddField(
            model_name="validationflow",
            name="accreditations",
            field=models.ManyToManyField(blank=True, to="pmbok.accreditation"),
        ),
        migrations.AddField(
            model_name="validationflow",
            name="contracts",
            field=models.ManyToManyField(blank=True, to="tprm.contract"),
        ),
        migrations.AddField(
            model_name="validationflow",
            name="processings",
            field=models.ManyToManyField(blank=True, to="privacy.processing"),
        ),
    ]
