# Generated by Django 6.0.2 on 2026-02-17 11:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0137_add_auto_sync_to_risk_compliance_assessments"),
        ("core", "0137_add_threats_to_finding"),
    ]

    operations = []
