# Generated by Django 6.0.2 on 2026-02-20 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0140_remove_requirementassessment_answers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requirementnode',
            old_name='questions',
            new_name='questions_json',
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_answers', to='core.question', verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='requirement_assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.requirementassessment', verbose_name='Requirement assessment'),
        ),
        migrations.AlterField(
            model_name='question',
            name='requirement_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.requirementnode', verbose_name='Requirement node'),
        ),
    ]
