# Generated by Django 6.0.2 on 2026-03-02 07:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0140_populate_tasknode_scheduled_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="requirementassignment",
            name="reviewer_observation",
            field=models.TextField(
                blank=True, null=True, verbose_name="Reviewer Observation"
            ),
        ),
        migrations.AddField(
            model_name="requirementassignment",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("in_progress", "In Progress"),
                    ("submitted", "Submitted"),
                    ("closed", "Closed"),
                    ("changes_requested", "Changes Requested"),
                ],
                default="draft",
                max_length=32,
                verbose_name="Status",
            ),
        ),
    ]
