# Generated by Django 6.0.2 on 2026-02-20 09:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0140_populate_tasknode_scheduled_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="complianceassessment",
            name="auto_sync",
            field=models.BooleanField(
                default=False, verbose_name="Automatic sync to actions"
            ),
        ),
        migrations.AddField(
            model_name="riskassessment",
            name="auto_sync",
            field=models.BooleanField(
                default=False, verbose_name="Automatic sync to actions"
            ),
        ),
    ]
