# Generated by Django 6.0.2 on 2026-02-20 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0141_rename_questions_requirementnode_questions_json_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirementnode',
            name='questions_json',
        ),
    ]
