# Generated by Django 6.0.2 on 2026-03-03 07:42

import django.db.models.deletion
import iam.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0141_complianceassessment_auto_sync_and_more"),
        ("iam", "0021_fix_auditee_iam_groups"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="requirementassignment",
            options={
                "ordering": ["created_at"],
                "permissions": [
                    (
                        "transition_requirementassignment",
                        "Can transition requirement assignment status",
                    )
                ],
                "verbose_name": "Requirement Assignment",
                "verbose_name_plural": "Requirement Assignments",
            },
        ),
        migrations.AddField(
            model_name="requirementassignment",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("in_progress", "In Progress"),
                    ("submitted", "Submitted"),
                    ("closed", "Closed"),
                    ("changes_requested", "Changes Requested"),
                ],
                default="draft",
                max_length=32,
                verbose_name="Status",
            ),
        ),
        migrations.CreateModel(
            name="RequirementAssignmentEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("in_progress", "In Progress"),
                            ("submitted", "Submitted"),
                            ("closed", "Closed"),
                            ("changes_requested", "Changes Requested"),
                        ],
                        max_length=50,
                        verbose_name="Event type",
                    ),
                ),
                (
                    "event_notes",
                    models.TextField(
                        blank=True,
                        max_length=2000,
                        null=True,
                        verbose_name="Event notes",
                    ),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="core.requirementassignment",
                    ),
                ),
                (
                    "event_actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Event actor",
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        default=iam.models.Folder.get_root_folder_id,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_folder",
                        to="iam.folder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Requirement assignment event",
                "verbose_name_plural": "Requirement assignment events",
                "ordering": ["-created_at"],
            },
        ),
    ]
