# Generated by Django 6.0.2 on 2026-03-03 05:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0141_requirementassignment_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requirementassignmentevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("in_progress", "In Progress"),
                    ("submitted", "Submitted"),
                    ("closed", "Closed"),
                    ("changes_requested", "Changes Requested"),
                ],
                max_length=50,
                verbose_name="Event type",
            ),
        ),
    ]
