# Generated by Django 6.0.2 on 2026-03-03 12:19

import django.db.models.deletion
import iam.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0142_alter_requirementassignment_options_and_more"),
        ("iam", "0021_fix_auditee_iam_groups"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("body", models.TextField(verbose_name="Body")),
                (
                    "is_tainted",
                    models.BooleanField(default=False, verbose_name="Edited"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                ("is_published", models.BooleanField(default=True)),
                (
                    "applied_control",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="core.appliedcontrol",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "finding",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="core.finding",
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        default=iam.models.Folder.get_root_folder_id,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_folder",
                        to="iam.folder",
                    ),
                ),
                (
                    "requirement_assessment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="core.requirementassessment",
                    ),
                ),
                (
                    "risk_scenario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="core.riskscenario",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("applied_control__isnull", True),
                                ("finding__isnull", True),
                                ("requirement_assessment__isnull", False),
                                ("risk_scenario__isnull", True),
                            ),
                            models.Q(
                                ("applied_control__isnull", True),
                                ("finding__isnull", True),
                                ("requirement_assessment__isnull", True),
                                ("risk_scenario__isnull", False),
                            ),
                            models.Q(
                                ("applied_control__isnull", False),
                                ("finding__isnull", True),
                                ("requirement_assessment__isnull", True),
                                ("risk_scenario__isnull", True),
                            ),
                            models.Q(
                                ("applied_control__isnull", True),
                                ("finding__isnull", False),
                                ("requirement_assessment__isnull", True),
                                ("risk_scenario__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="comment_exactly_one_parent",
                    )
                ],
            },
        ),
    ]
