# Generated by Django 6.0.2 on 2026-03-08 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0144_presetjourney_presetjourneystep"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="leader",
            field=models.ForeignKey(
                blank=True,
                help_text="The leader of the team",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="led_teams",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Team Leader",
            ),
        ),
    ]
