# Generated by Django 6.0.2 on 2026-03-08 07:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0145_alter_team_leader"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisationobjective",
            name="closing_date",
            field=models.DateField(blank=True, null=True, verbose_name="Closing date"),
        ),
        migrations.AddField(
            model_name="organisationobjective",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is active"),
        ),
        migrations.AddField(
            model_name="organisationobjective",
            name="start_date",
            field=models.DateField(blank=True, null=True, verbose_name="Start date"),
        ),
        migrations.AlterField(
            model_name="organisationobjective",
            name="assets",
            field=models.ManyToManyField(
                blank=True,
                related_name="organisation_objectives",
                to="core.asset",
                verbose_name="asset",
            ),
        ),
    ]
