# Generated by Django 6.0.3 on 2026-03-12 06:08

import core.validators
import django.core.validators
import django.db.models.deletion
import iam.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0146_organisationobjective_closing_date_and_more"),
        ("iam", "0021_fix_auditee_iam_groups"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomEmailTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
                (
                    "template_key",
                    models.CharField(
                        help_text="Template identifier, e.g. 'expired_controls'",
                        max_length=100,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        help_text="Language code, e.g. 'en', 'fr'", max_length=10
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        help_text="Email subject line, supports ${variable} substitution",
                        max_length=500,
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="Email body, supports ${variable} substitution"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "folder",
                    models.ForeignKey(
                        default=iam.models.Folder.get_root_folder_id,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_folder",
                        to="iam.folder",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CustomWordTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
                (
                    "template_key",
                    models.CharField(
                        help_text="Template identifier, e.g. 'audit_report'",
                        max_length=100,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        help_text="Language code, e.g. 'en', 'fr'", max_length=10
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Custom .docx template file",
                        upload_to="custom_word_templates/",
                        validators=[
                            django.core.validators.FileExtensionValidator(["docx"]),
                            core.validators.validate_file_size,
                            core.validators.validate_file_name,
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "folder",
                    models.ForeignKey(
                        default=iam.models.Folder.get_root_folder_id,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_folder",
                        to="iam.folder",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
