# Generated by Django 6.0.3 on 2026-03-11 13:48

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0146_organisationobjective_closing_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evidencerevision",
            name="attachment",
            field=models.FileField(
                blank=True,
                max_length=500,
                null=True,
                upload_to="",
                validators=[
                    core.validators.validate_file_size,
                    core.validators.validate_file_name,
                ],
                verbose_name="Attachment",
            ),
        ),
    ]
