# Generated by Django 6.0.3 on 2026-03-26 08:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0150_add_editable_mixin_to_riskmatrix"),
    ]

    operations = [
        migrations.AddField(
            model_name="complianceassessment",
            name="scoring_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="complianceassessment",
            name="score_calculation_method",
            field=models.CharField(
                choices=[
                    ("average", "Average"),
                    ("sum", "Sum"),
                    ("average_of_averages", "Average of averages"),
                ],
                default="average",
                max_length=100,
                verbose_name="Score Calculation Method",
            ),
        ),
    ]
