# Generated by Django 6.0.3 on 2026-03-29 05:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0154_questionnaire_cleanup"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appliedcontrol",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("to_do", "To do"),
                    ("in_progress", "In progress"),
                    ("on_hold", "On hold"),
                    ("active", "Active"),
                    ("degraded", "Degraded"),
                    ("deprecated", "Deprecated"),
                    ("--", "Undefined"),
                ],
                default="--",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
