# Generated by Django 6.0.3 on 2026-04-04 07:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0155_alter_appliedcontrol_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="is_bcp_activated",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="BCP activated"
            ),
        ),
        migrations.AddField(
            model_name="incident",
            name="occurred_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Occurred at"
            ),
        ),
        migrations.AddField(
            model_name="incident",
            name="resolution",
            field=models.TextField(blank=True, null=True, verbose_name="Resolution"),
        ),
        migrations.AddField(
            model_name="incident",
            name="resolved_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Resolved at"
            ),
        ),
    ]
