# Generated by Django 6.0.3 on 2026-03-24 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0155_add_editable_mixin_to_framework'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirementnodeattachment',
            name='framework',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_attachments', to='core.framework', verbose_name='Framework'),
        ),
        migrations.AlterField(
            model_name='requirementnodeattachment',
            name='requirement_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.requirementnode', verbose_name='Requirement node'),
        ),
    ]
