# Generated by Django 6.0.3 on 2026-04-09 06:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0156_incident_is_bcp_activated_incident_occurred_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="requirementnode",
            name="visibility_expression",
            field=models.TextField(
                blank=True,
                help_text="CEL expression that must evaluate to true for this requirement to be visible in an assessment.",
                null=True,
                verbose_name="Visibility expression",
            ),
        ),
    ]
