# Generated by Django 6.0.3 on 2026-03-25 18:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0157_requirementnodeattachment_nullable_node_add_framework"),
    ]

    operations = [
        migrations.AddField(
            model_name="complianceassessment",
            name="field_visibility",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Override visibility per field for this assessment. Overrides framework defaults.",
                verbose_name="Field visibility",
            ),
        ),
        migrations.AddField(
            model_name="framework",
            name="field_visibility",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Override visibility per field. Keys: field names. Values: 'everyone', 'auditor', or 'hidden'.",
                verbose_name="Field visibility",
            ),
        ),
    ]
