# Generated by Django 6.0.3 on 2026-04-09 06:10

from django.db import migrations


def convert_computed_outcome_to_dict(apps, schema_editor):
    """Convert existing computed_outcome values from single object or list to dict keyed by ref_id."""
    ComplianceAssessment = apps.get_model("core", "ComplianceAssessment")
    for ca in ComplianceAssessment.objects.exclude(computed_outcome__isnull=True):
        old = ca.computed_outcome
        # Old format: single dict {"ref_id": "x", ...}
        if isinstance(old, dict) and "ref_id" in old:
            ref_id = old.pop("ref_id")
            old.pop("expression", None)
            ca.computed_outcome = {ref_id: old}
            ca.save(update_fields=["computed_outcome"])
        # Intermediate format: list of dicts [{"ref_id": "x", ...}, ...]
        elif isinstance(old, list):
            new = {}
            for item in old:
                if isinstance(item, dict) and "ref_id" in item:
                    entry = {
                        k: v
                        for k, v in item.items()
                        if k not in ("ref_id", "expression")
                    }
                    new[item["ref_id"]] = entry
            ca.computed_outcome = new if new else None
            ca.save(update_fields=["computed_outcome"])


def revert_computed_outcome_to_single(apps, schema_editor):
    """Reverse: noop — the JSONField accepts any shape, no schema change to undo."""
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0157_cel_expression_engine"),
    ]

    operations = [
        migrations.RunPython(
            convert_computed_outcome_to_dict,
            revert_computed_outcome_to_single,
        ),
    ]
