# Generated by Django 6.0.3 on 2026-04-09 06:10

from django.db import migrations


def wrap_computed_outcome_in_array(apps, schema_editor):
    """Wrap existing single-object computed_outcome values in arrays."""
    ComplianceAssessment = apps.get_model("core", "ComplianceAssessment")
    for ca in ComplianceAssessment.objects.exclude(computed_outcome__isnull=True):
        if isinstance(ca.computed_outcome, dict):
            ca.computed_outcome = [ca.computed_outcome]
            ca.save(update_fields=["computed_outcome"])


def unwrap_computed_outcome_from_array(apps, schema_editor):
    """Reverse: unwrap single-element arrays back to single objects."""
    ComplianceAssessment = apps.get_model("core", "ComplianceAssessment")
    for ca in ComplianceAssessment.objects.exclude(computed_outcome__isnull=True):
        if isinstance(ca.computed_outcome, list) and len(ca.computed_outcome) == 1:
            ca.computed_outcome = ca.computed_outcome[0]
            ca.save(update_fields=["computed_outcome"])
        elif isinstance(ca.computed_outcome, list) and len(ca.computed_outcome) == 0:
            ca.computed_outcome = None
            ca.save(update_fields=["computed_outcome"])


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0157_cel_expression_engine"),
    ]

    operations = [
        migrations.RunPython(
            wrap_computed_outcome_in_array,
            unwrap_computed_outcome_from_array,
        ),
    ]
