# Generated by Django 6.0.3 on 2026-04-10 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0158_computed_outcome_to_array'),
    ]

    operations = [
        migrations.AddField(
            model_name='framework',
            name='urn_namespace',
            field=models.CharField(default='custom', help_text='Organization identifier used in the URN prefix.', max_length=50, verbose_name='URN namespace'),
        ),
    ]
