# Generated by Django 6.0.3 on 2026-03-27 11:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0158_add_field_visibility"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="requirementnode",
            options={
                "verbose_name": "RequirementNode",
                "verbose_name_plural": "RequirementNodes",
            },
        ),
    ]
