# Generated by Django 6.0.3 on 2026-04-12 06:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0159_vulnerability_cwes_vulnerability_detected_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="complianceassessment",
            name="anchor_na_to_target",
            field=models.BooleanField(
                default=False, verbose_name="Anchor N/A to target score"
            ),
        ),
        migrations.AddField(
            model_name="complianceassessment",
            name="target_score",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Target score"
            ),
        ),
    ]
