# Generated by Django 6.0.3 on 2026-04-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0159_vulnerability_cwes_vulnerability_detected_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="securityexception",
            name="link",
            field=models.URLField(blank=True, null=True, verbose_name="Link"),
        ),
    ]
