# Generated by Django 6.0.4 on 2026-04-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0160_complianceassessment_anchor_na_to_target_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="securityexception",
            name="link",
            field=models.URLField(blank=True, null=True, verbose_name="Link"),
        ),
    ]
