# Generated by Django 6.0.4 on 2026-04-15 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0160_complianceassessment_anchor_na_to_target_and_more'),
        ('core', '0160_securityexception_link'),
    ]

    operations = [
    ]
