# Generated by Django 6.0.3 on 2026-04-18 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0161_securityexception_link"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="requirementmapping",
            name="is_suggested",
            field=models.BooleanField(default=False, verbose_name="Machine-suggested"),
        ),
        migrations.AddField(
            model_name="requirementmapping",
            name="reviewed",
            field=models.BooleanField(default=False, verbose_name="Reviewed"),
        ),
        migrations.AddField(
            model_name="requirementmapping",
            name="reviewed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Reviewed at"
            ),
        ),
        migrations.AddField(
            model_name="requirementmapping",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_requirement_mappings",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Reviewed by",
            ),
        ),
        migrations.AddField(
            model_name="requirementmapping",
            name="suggestion_metadata",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Suggestion metadata"
            ),
        ),
        migrations.AddField(
            model_name="requirementmappingset",
            name="embedding_model",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="Embedding model"
            ),
        ),
        migrations.AddField(
            model_name="requirementmappingset",
            name="generated_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Suggestions generated at"
            ),
        ),
        migrations.AddField(
            model_name="requirementmappingset",
            name="generation_error",
            field=models.TextField(
                blank=True, default="", verbose_name="Generation error"
            ),
        ),
        migrations.AddField(
            model_name="requirementmappingset",
            name="generation_params",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Generation parameters"
            ),
        ),
        migrations.AddField(
            model_name="requirementmappingset",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("generating", "Generating"),
                    ("ready", "Ready for review"),
                    ("reviewed", "Reviewed"),
                    ("failed", "Failed"),
                ],
                default="draft",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
