# Generated by Django 6.0.3 on 2026-04-21 07:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0161_securityexception_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="applied_controls",
            field=models.ManyToManyField(
                blank=True,
                related_name="incidents",
                to="core.appliedcontrol",
                verbose_name="Applied controls",
            ),
        ),
        migrations.AddField(
            model_name="incident",
            name="task_templates",
            field=models.ManyToManyField(
                blank=True,
                related_name="incidents",
                to="core.tasktemplate",
                verbose_name="Task templates",
            ),
        ),
        migrations.AddField(
            model_name="riskscenario",
            name="incidents",
            field=models.ManyToManyField(
                blank=True,
                help_text="Incidents that materialized this risk scenario",
                related_name="risk_scenarios",
                to="core.incident",
                verbose_name="Incidents",
            ),
        ),
    ]
