# Generated by Django 6.0.3 on 2026-04-16 16:32

from django.db import migrations

RESULT_TO_ALIGNMENT = {
    "compliant": "yes",
    "non_compliant": "no",
    "partially_compliant": "in_progress",
    "not_applicable": "not_applicable",
}


def backfill_alignment(apps, schema_editor):
    RequirementAssessment = apps.get_model("core", "RequirementAssessment")
    qs = (
        RequirementAssessment.objects.filter(
            assignments__isnull=False,
            respondent_alignment__isnull=True,
        )
        .exclude(result="not_assessed")
        .distinct()
    )

    batch = []
    for ra in qs.only("id", "result").iterator():
        mapped = RESULT_TO_ALIGNMENT.get(ra.result)
        if mapped:
            ra.respondent_alignment = mapped
            batch.append(ra)
        if len(batch) >= 1000:
            RequirementAssessment.objects.bulk_update(batch, ["respondent_alignment"])
            batch = []
    if batch:
        RequirementAssessment.objects.bulk_update(batch, ["respondent_alignment"])


def reverse_backfill(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0162_add_respondent_alignment"),
    ]

    operations = [
        migrations.RunPython(backfill_alignment, reverse_backfill),
    ]
