# Generated by Django 6.0.3 on 2026-04-22 21:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0162_incident_risk_postmortem_links"),
    ]

    operations = [
        migrations.AlterField(
            model_name="riskscenario",
            name="treatment",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("mitigate", "Mitigate"),
                    ("accept", "Accept"),
                    ("avoid", "Avoid"),
                    ("transfer", "Transfer"),
                    ("cancelled", "Cancelled"),
                ],
                default="open",
                max_length=20,
                verbose_name="Treatment status",
            ),
        ),
    ]
