# Generated by Django 6.0.3 on 2026-04-24 11:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0163_add_cancelled_treatment_risk_scenario"),
    ]

    operations = [
        migrations.AddField(
            model_name="presetjourneystep",
            name="target_params",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="presetjourneystep",
            name="target_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
