# Generated by Django 6.0.3 on 2026-04-24 20:35

import django.db.models.deletion
import iam.models
import uuid
from django.db import migrations, models


def backfill_presets(apps, schema_editor):
    StoredLibrary = apps.get_model("core", "StoredLibrary")
    Preset = apps.get_model("core", "Preset")
    PresetJourney = apps.get_model("core", "PresetJourney")
    Folder = apps.get_model("iam", "Folder")

    root_folder = Folder.objects.filter(content_type="GL").first()

    for lib in StoredLibrary.objects.all():
        content = lib.content or {}
        if not isinstance(content, dict) or "preset" not in content:
            continue
        preset_content = content.get("preset", {}) or {}
        journey_content = preset_content.get("journey", {}) or {}
        Preset.objects.update_or_create(
            urn=lib.urn,
            defaults={
                "name": lib.name,
                "description": lib.description or "",
                "ref_id": lib.ref_id,
                "version": lib.version,
                "provider": lib.provider,
                "translations": lib.translations or {},
                "profile": preset_content.get("profile", {}) or {},
                "feature_flags": preset_content.get("feature_flags", {}) or {},
                "scaffolded_objects": preset_content.get("scaffolded_objects", [])
                or [],
                "steps": journey_content.get("steps", []) or [],
                "dependencies": list(lib.dependencies or []),
                "folder": root_folder,
            },
        )

    for journey in PresetJourney.objects.all():
        urn = getattr(journey, "urn", None)
        if not urn:
            continue
        preset = Preset.objects.filter(urn=urn).first()
        if preset:
            journey.preset = preset
            journey.save(update_fields=["preset"])


def unbackfill_presets(apps, schema_editor):
    Preset = apps.get_model("core", "Preset")
    Preset.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0164_preset_step_url_target"),
        ("iam", "0021_fix_auditee_iam_groups"),
    ]

    operations = [
        migrations.RenameField(
            model_name="presetjourney",
            old_name="version",
            new_name="applied_version",
        ),
        migrations.CreateModel(
            name="Preset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "editing_draft",
                    models.JSONField(
                        blank=True,
                        default=None,
                        help_text="Work-in-progress definition. Null when no active draft.",
                        null=True,
                        verbose_name="Editing draft",
                    ),
                ),
                (
                    "editing_version",
                    models.IntegerField(
                        default=1,
                        help_text="Incremented on each publish.",
                        verbose_name="Editing version",
                    ),
                ),
                (
                    "editing_history",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Snapshots of previous published definitions.",
                        verbose_name="Editing history",
                    ),
                ),
                (
                    "urn",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("ref_id", models.CharField(blank=True, max_length=255, null=True)),
                ("version", models.IntegerField(default=1)),
                ("provider", models.CharField(blank=True, max_length=255, null=True)),
                ("translations", models.JSONField(blank=True, default=dict)),
                ("profile", models.JSONField(blank=True, default=dict)),
                ("feature_flags", models.JSONField(blank=True, default=dict)),
                ("scaffolded_objects", models.JSONField(blank=True, default=list)),
                ("steps", models.JSONField(blank=True, default=list)),
                ("dependencies", models.JSONField(blank=True, default=list)),
                (
                    "folder",
                    models.ForeignKey(
                        default=iam.models.Folder.get_root_folder_id,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_folder",
                        to="iam.folder",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="presetjourney",
            name="preset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="journeys",
                to="core.preset",
            ),
        ),
        migrations.RunPython(backfill_presets, unbackfill_presets),
        migrations.RemoveField(
            model_name="presetjourney",
            name="urn",
        ),
    ]
