# Generated by Django 6.0.5 on 2026-05-20 07:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0169_tasktemplate_filtering_labels"),
    ]

    operations = [
        migrations.AlterField(
            model_name="terminology",
            name="field_path",
            field=models.CharField(
                choices=[
                    ("ro_to.risk_origin", "ro_to/risk_origin"),
                    ("qualifications", "qualifications"),
                    ("accreditation.status", "accreditationStatus"),
                    ("accreditation.category", "accreditationCategory"),
                    ("entity.relationship", "entityRelationship"),
                    ("metric_definition.unit", "metricUnit"),
                    ("project.status", "projectStatus"),
                    ("project.health", "projectHealth"),
                ],
                max_length=100,
                verbose_name="Field path",
            ),
        ),
    ]
