# Generated by Django 6.0.6 on 2026-07-03 13:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0172_view_compliance_assessment_full_permission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="findingsassessment",
            name="category",
            field=models.CharField(
                choices=[
                    ("--", "Undefined"),
                    ("pentest", "Pentest"),
                    ("threat_hunting", "Threat hunting"),
                    ("red_teaming", "Red teaming"),
                    ("audit", "Audit"),
                    ("self_identified", "Self-identified"),
                ],
                default="--",
                max_length=32,
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="securityexception",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "draft"),
                    ("in_review", "in review"),
                    ("approved", "approved"),
                    ("rejected", "rejected"),
                    ("resolved", "resolved"),
                    ("expired", "expired"),
                    ("deprecated", "deprecated"),
                ],
                default="draft",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
