# Generated by Django 6.0.6 on 2026-07-07 11:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0173_alter_findingsassessment_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="terminology",
            name="field_path",
            field=models.CharField(
                choices=[
                    ("ro_to.risk_origin", "ro_to/risk_origin"),
                    ("qualifications", "qualifications"),
                    ("accreditation.status", "accreditationStatus"),
                    ("accreditation.category", "accreditationCategory"),
                    ("entity.relationship", "entityRelationship"),
                    ("metric_definition.unit", "metricUnit"),
                    ("project.status", "projectStatus"),
                    ("project.health", "projectHealth"),
                    ("processing.nature", "processingNature"),
                    ("personal_data.category", "personalDataCategory"),
                ],
                max_length=100,
                verbose_name="Field path",
            ),
        ),
    ]
