# Generated by Django 6.0.6 on 2026-07-05 08:28

import django.core.validators
import django.db.models.deletion
import iam.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0173_alter_findingsassessment_category_and_more'),
        ('iam', '0023_alter_folder_content_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_published', models.BooleanField(default=False, verbose_name='published')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('packager', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='invalidLibraryIdentity', regex='^[a-z0-9_-]+$')], verbose_name='Packager')),
                ('ref_id', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='invalidLibraryIdentity', regex='^[a-z0-9_-]+$')], verbose_name='Reference ID')),
                ('urn', models.CharField(blank=True, max_length=255, null=True, verbose_name='URN')),
                ('locale', models.CharField(default='en', max_length=100, verbose_name='Locale')),
                ('version', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Version')),
                ('provider', models.CharField(blank=True, max_length=200, null=True, verbose_name='Provider')),
                ('copyright', models.CharField(blank=True, max_length=4096, null=True, verbose_name='Copyright')),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('annotation', models.TextField(blank=True, null=True, verbose_name='Annotation')),
                ('translations', models.JSONField(blank=True, default=dict)),
                ('dependencies', models.JSONField(blank=True, default=list)),
                ('labels', models.JSONField(blank=True, default=list)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('first_published_at', models.DateTimeField(blank=True, null=True)),
                ('last_published_at', models.DateTimeField(blank=True, null=True)),
                ('folder', models.ForeignKey(default=iam.models.Folder.get_root_folder_id, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_folder', to='iam.folder')),
            ],
            options={
                'verbose_name': 'Library draft',
                'verbose_name_plural': 'Library drafts',
            },
        ),
    ]
