# Generated by Django 6.0.6 on 2026-07-04 06:36

import core.validators
import django.core.validators
import django.db.models.deletion
import iam.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0173_alter_findingsassessment_category_and_more"),
        ("iam", "0023_alter_folder_content_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomDocHtmlTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
                (
                    "template_key",
                    models.CharField(
                        help_text="Template identifier, e.g. 'document_pdf'",
                        max_length=100,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        help_text="Language code, e.g. 'en', 'fr'", max_length=10
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Custom .html template file (Django template syntax)",
                        upload_to="custom_html_templates/",
                        validators=[
                            django.core.validators.FileExtensionValidator(["html"]),
                            core.validators.validate_file_size,
                            core.validators.validate_file_name,
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "folder",
                    models.ForeignKey(
                        default=iam.models.Folder.get_root_folder_id,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_folder",
                        to="iam.folder",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
