# Generated by Django 6.0.6 on 2026-07-08 17:43

import core.validators
import django.core.validators
import django.db.models.deletion
import iam.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0174_alter_terminology_field_path"),
        ("iam", "0023_alter_folder_content_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomDocHtmlTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
                (
                    "template_key",
                    models.CharField(
                        help_text="Template identifier, e.g. 'document_pdf'",
                        max_length=100,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        help_text="Language code, e.g. 'en', 'fr'", max_length=10
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Custom .html template file (Django template syntax)",
                        upload_to="custom_html_templates/",
                        validators=[
                            django.core.validators.FileExtensionValidator(["html"]),
                            core.validators.validate_file_size,
                            core.validators.validate_html_template_file_name,
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "folder",
                    models.ForeignKey(
                        default=iam.models.Folder.get_root_folder_id,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_folder",
                        to="iam.folder",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ObjectClassification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "ref_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Reference ID"
                    ),
                ),
                (
                    "builtin",
                    models.BooleanField(default=False, verbose_name="Built-in"),
                ),
                (
                    "is_visible",
                    models.BooleanField(default=True, verbose_name="Is Visible"),
                ),
                (
                    "translations",
                    models.JSONField(
                        blank=True, default=dict, null=True, verbose_name="Translations"
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        default=iam.models.Folder.get_root_folder_id,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_folder",
                        to="iam.folder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Object classification",
                "verbose_name_plural": "Object classifications",
            },
        ),
        migrations.CreateModel(
            name="ClassificationLevel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                ("rank", models.PositiveIntegerField(default=0, verbose_name="Rank")),
                (
                    "hexcolor",
                    models.CharField(
                        blank=True, default="", max_length=9, verbose_name="Color"
                    ),
                ),
                (
                    "abbreviation",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        verbose_name="Abbreviation",
                    ),
                ),
                (
                    "builtin",
                    models.BooleanField(default=False, verbose_name="Built-in"),
                ),
                (
                    "is_visible",
                    models.BooleanField(default=True, verbose_name="Is Visible"),
                ),
                (
                    "translations",
                    models.JSONField(
                        blank=True, default=dict, null=True, verbose_name="Translations"
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        default=iam.models.Folder.get_root_folder_id,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_folder",
                        to="iam.folder",
                    ),
                ),
                (
                    "object_classification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="levels",
                        to="core.objectclassification",
                        verbose_name="Object classification",
                    ),
                ),
            ],
            options={
                "verbose_name": "Classification level",
                "verbose_name_plural": "Classification levels",
                "ordering": ["object_classification", "rank"],
            },
        ),
    ]
