# Generated by Django 6.0.6 on 2026-07-08 16:08

import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0175_customdochtmltemplate_objectclassification_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customdochtmltemplate",
            name="file",
            field=models.FileField(
                help_text="Custom .html template file (Django template syntax)",
                upload_to="custom_html_templates/",
                validators=[
                    django.core.validators.FileExtensionValidator(["html"]),
                    core.validators.validate_file_size,
                    core.validators.validate_html_template_file_name,
                ],
            ),
        ),
    ]
