# Generated by Django 6.0.6 on 2026-07-13 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0175_customdochtmltemplate_objectclassification_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="finding",
            name="asset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="findings",
                to="core.asset",
                verbose_name="Asset",
            ),
        ),
        migrations.AddField(
            model_name="finding",
            name="requirement_node",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="findings",
                to="core.requirementnode",
                verbose_name="Requirement",
            ),
        ),
    ]
