# Generated by Django 6.0.6 on 2026-07-10 20:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0175_wrap_editing_drafts"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="framework",
            name="editing_draft",
        ),
        migrations.RemoveField(
            model_name="framework",
            name="editing_history",
        ),
        migrations.RemoveField(
            model_name="framework",
            name="editing_version",
        ),
        migrations.RemoveField(
            model_name="preset",
            name="editing_draft",
        ),
        migrations.RemoveField(
            model_name="preset",
            name="editing_history",
        ),
        migrations.RemoveField(
            model_name="preset",
            name="editing_version",
        ),
        migrations.RemoveField(
            model_name="riskmatrix",
            name="editing_draft",
        ),
        migrations.RemoveField(
            model_name="riskmatrix",
            name="editing_history",
        ),
        migrations.RemoveField(
            model_name="riskmatrix",
            name="editing_version",
        ),
    ]
