# Generated by Django 6.0.6 on 2026-07-16 20:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0176_librarydraft"),
    ]

    operations = [
        migrations.AlterField(
            model_name="securityexception",
            name="link",
            field=models.URLField(
                blank=True, max_length=2048, null=True, verbose_name="Link"
            ),
        ),
    ]
