# Generated by Django 6.0.6 on 2026-07-13 16:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0176_finding_asset_finding_requirement_node"),
    ]

    operations = [
        migrations.AlterField(
            model_name="findingsassessment",
            name="category",
            field=models.CharField(
                choices=[
                    ("--", "Undefined"),
                    ("pentest", "Pentest"),
                    ("threat_hunting", "Threat hunting"),
                    ("red_teaming", "Red teaming"),
                    ("audit", "Audit"),
                    ("self_identified", "Self-identified"),
                    ("posture", "Posture follow-up"),
                ],
                default="--",
                max_length=32,
                verbose_name="Category",
            ),
        ),
    ]
