# Generated by Django 6.0.6 on 2026-07-16 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0176_librarydraft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedcontrol',
            name='link',
            field=models.CharField(blank=True, help_text='External url for action follow-up (eg. Jira ticket)', max_length=4096, null=True, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='reference_link',
            field=models.URLField(blank=True, help_text='External url for action follow-up (eg. Jira ticket)', max_length=4096, null=True, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='evidencerevision',
            name='link',
            field=models.URLField(blank=True, max_length=4096, null=True, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='link',
            field=models.CharField(blank=True, max_length=4096, null=True, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='securityexception',
            name='link',
            field=models.URLField(blank=True, max_length=4096, null=True, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='tasktemplate',
            name='link',
            field=models.URLField(blank=True, help_text='Link to the evidence (eg. Jira ticket, etc.)', max_length=4096, null=True, verbose_name='Link'),
        ),
    ]
