# Generated by Django 6.0.6 on 2026-07-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0177_finding_asset_finding_requirement_node_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasktemplate",
            name="findings",
            field=models.ManyToManyField(
                blank=True,
                help_text="Findings related to the task",
                related_name="task_templates",
                to="core.finding",
                verbose_name="Findings",
            ),
        ),
    ]
