# Generated by Django 6.0.6 on 2026-07-21 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0177_alter_securityexception_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="finding",
            name="asset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="findings",
                to="core.asset",
                verbose_name="Asset",
            ),
        ),
        migrations.AddField(
            model_name="finding",
            name="requirement_node",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="findings",
                to="core.requirementnode",
                verbose_name="Requirement",
            ),
        ),
        migrations.AddField(
            model_name="tasktemplate",
            name="findings",
            field=models.ManyToManyField(
                blank=True,
                help_text="Findings related to the task",
                related_name="task_templates",
                to="core.finding",
                verbose_name="Findings",
            ),
        ),
        migrations.AlterField(
            model_name="findingsassessment",
            name="category",
            field=models.CharField(
                choices=[
                    ("--", "Undefined"),
                    ("pentest", "Pentest"),
                    ("threat_hunting", "Threat hunting"),
                    ("red_teaming", "Red teaming"),
                    ("audit", "Audit"),
                    ("self_identified", "Self-identified"),
                    ("posture", "Posture follow-up"),
                ],
                default="--",
                max_length=32,
                verbose_name="Category",
            ),
        ),
    ]
