# Generated by Django 6.0.7 on 2026-07-24 18:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0178_finding_asset_finding_requirement_node_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="requirementassessment",
            name="is_score_overridden",
            field=models.BooleanField(
                default=False,
                help_text="When set, the score is manually pinned and no longer recomputed from the questionnaire answers.",
                verbose_name="Is score overridden",
            ),
        ),
    ]
