# Generated by Django 6.0.7 on 2026-07-26 08:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0178_finding_asset_finding_requirement_node_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="findingsassessment",
            name="filtering_labels",
            field=models.ManyToManyField(
                blank=True, to="core.filteringlabel", verbose_name="Labels"
            ),
        ),
        migrations.AddField(
            model_name="findingsassessment",
            name="reported_at",
            field=models.DateField(blank=True, null=True, verbose_name="Reported at"),
        ),
        migrations.AlterField(
            model_name="findingsassessment",
            name="category",
            field=models.CharField(
                choices=[
                    ("--", "Undefined"),
                    ("pentest", "Pentest"),
                    ("threat_hunting", "Threat hunting"),
                    ("red_teaming", "Red teaming"),
                    ("audit", "Audit"),
                    ("self_identified", "Self-identified"),
                    ("posture", "Posture follow-up"),
                    ("responsible_disclosure", "Responsible disclosure"),
                ],
                default="--",
                max_length=32,
                verbose_name="Category",
            ),
        ),
    ]
