# Generated by Django 6.0.6 on 2026-07-21 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0178_finding_asset_finding_requirement_node_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="securityexception",
            name="evidences",
            field=models.ManyToManyField(
                blank=True,
                related_name="security_exceptions",
                to="core.evidence",
                verbose_name="Evidences",
            ),
        ),
    ]
