# Generated by Django 6.0.7 on 2026-07-28 17:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0179_findingsassessment_filtering_labels_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="securityexception",
            name="evidences",
            field=models.ManyToManyField(
                blank=True,
                related_name="security_exceptions",
                to="core.evidence",
                verbose_name="Evidences",
            ),
        ),
    ]
