# Generated by Django 6.0.7 on 2026-07-30 13:58

import django.db.models.deletion
import iam.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0180_securityexception_evidences"),
        ("iam", "0023_alter_folder_content_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="threat",
            name="groups",
            field=models.JSONField(blank=True, null=True, verbose_name="Groups"),
        ),
        migrations.AddField(
            model_name="threat",
            name="is_deprecated",
            field=models.BooleanField(default=False, verbose_name="Deprecated"),
        ),
        migrations.AddField(
            model_name="threat",
            name="order_id",
            field=models.IntegerField(null=True, verbose_name="Order ID"),
        ),
        migrations.AddField(
            model_name="threat",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="core.threat",
                verbose_name="Parent",
            ),
        ),
        migrations.AddField(
            model_name="threat",
            name="reference_controls",
            field=models.ManyToManyField(
                blank=True,
                related_name="threats",
                to="core.referencecontrol",
                verbose_name="Reference controls",
            ),
        ),
        migrations.AddField(
            model_name="threat",
            name="selectable",
            field=models.BooleanField(default=True, verbose_name="Selectable"),
        ),
        migrations.AddField(
            model_name="threat",
            name="type",
            field=models.CharField(
                choices=[
                    ("generic", "Generic"),
                    ("event", "Event"),
                    ("technique", "Technique"),
                ],
                default="generic",
                max_length=20,
                verbose_name="Type",
            ),
        ),
        migrations.CreateModel(
            name="ThreatCatalog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
                (
                    "urn",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="URN",
                    ),
                ),
                (
                    "ref_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Reference ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Provider"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, null=True, verbose_name="Name"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "annotation",
                    models.TextField(blank=True, null=True, verbose_name="Annotation"),
                ),
                (
                    "translations",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Translations"
                    ),
                ),
                (
                    "locale",
                    models.CharField(
                        default="en", max_length=100, verbose_name="Locale"
                    ),
                ),
                (
                    "default_locale",
                    models.BooleanField(default=True, verbose_name="Default locale"),
                ),
                (
                    "grouping_definition",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Grouping definition"
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        default=iam.models.Folder.get_root_folder_id,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_folder",
                        to="iam.folder",
                    ),
                ),
                (
                    "library",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="threat_catalogs",
                        to="core.loadedlibrary",
                    ),
                ),
            ],
            options={
                "verbose_name": "Threat catalog",
                "verbose_name_plural": "Threat catalogs",
            },
        ),
        migrations.AddField(
            model_name="threat",
            name="catalog",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="threats",
                to="core.threatcatalog",
                verbose_name="Catalog",
            ),
        ),
    ]
