# Generated by Django 6.0.8 on 2026-08-10 09:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0181_customizable_asset_classes"),
    ]

    operations = [
        migrations.AddField(
            model_name="requirementassessment",
            name="is_score_overridden",
            field=models.BooleanField(
                default=False,
                help_text="When set, the score is manually pinned and no longer recomputed from the questionnaire answers.",
                verbose_name="Is score overridden",
            ),
        ),
    ]
