# Generated by Django 6.0.8 on 2026-08-17 00:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0181_customizable_asset_classes'),
        ('iam', '0026_delete_cacheversion'),
        ('issues', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='comment',
            name='comment_exactly_one_parent',
        ),
        migrations.AddField(
            model_name='comment',
            name='remediation_issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='issues.remediationissue'),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='remediation_issues',
            field=models.ManyToManyField(blank=True, help_text='Remediation issues related to the task', related_name='task_templates', to='issues.remediationissue', verbose_name='Remediation issues'),
        ),
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('applied_control__isnull', True), ('finding__isnull', True), ('remediation_issue__isnull', True), ('requirement_assessment__isnull', False), ('risk_scenario__isnull', True)), models.Q(('applied_control__isnull', True), ('finding__isnull', True), ('remediation_issue__isnull', True), ('requirement_assessment__isnull', True), ('risk_scenario__isnull', False)), models.Q(('applied_control__isnull', False), ('finding__isnull', True), ('remediation_issue__isnull', True), ('requirement_assessment__isnull', True), ('risk_scenario__isnull', True)), models.Q(('applied_control__isnull', True), ('finding__isnull', False), ('remediation_issue__isnull', True), ('requirement_assessment__isnull', True), ('risk_scenario__isnull', True)), models.Q(('applied_control__isnull', True), ('finding__isnull', True), ('remediation_issue__isnull', False), ('requirement_assessment__isnull', True), ('risk_scenario__isnull', True)), _connector='OR'), name='comment_exactly_one_parent'),
        ),
    ]
