# Generated by Django 6.0.8 on 2026-08-25 11:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0182_requirementassessment_is_score_overridden"),
    ]

    operations = [
        migrations.AddField(
            model_name="finding",
            name="recommendation",
            field=models.TextField(
                blank=True, null=True, verbose_name="Recommendation"
            ),
        ),
        migrations.AddField(
            model_name="findingsassessment",
            name="budget",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=14,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Budget",
            ),
        ),
        migrations.AddField(
            model_name="findingsassessment",
            name="expenses",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Budget consumed so far",
                max_digits=14,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Expenses",
            ),
        ),
        migrations.AddField(
            model_name="findingsassessment",
            name="objectives",
            field=models.TextField(blank=True, null=True, verbose_name="Objectives"),
        ),
        migrations.AddField(
            model_name="findingsassessment",
            name="reference_link",
            field=models.URLField(
                blank=True,
                help_text="External url for follow-up (eg. report, Jira ticket)",
                max_length=2048,
                null=True,
                verbose_name="Reference link",
            ),
        ),
        migrations.AddField(
            model_name="findingsassessment",
            name="start_date",
            field=models.DateField(blank=True, null=True, verbose_name="Start date"),
        ),
        migrations.AlterField(
            model_name="finding",
            name="findings_assessment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="findings",
                to="core.findingsassessment",
                verbose_name="Findings assessment",
            ),
        ),
    ]
