# Generated by Django 6.0.8 on 2026-08-24 16:00


"""
migration 0006: SecurityFunction -> ReferenceControl
migration 0006: SecurityMeasure  -> AppliedControl
migration 0012: Library          -> LoadedLibrary
migration 0051: Project          -> Perimeter
"""

from django.db import migrations


RENAMED_MODELS = {
    "securityfunction": ("core", "referencecontrol"),
    "securitymeasure": ("core", "appliedcontrol"),
    "library": ("core", "loadedlibrary"),
    "project": ("core", "perimeter"),
}


def delete_stale_renamed_model_permissions(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    Permission = apps.get_model("auth", "Permission")

    for old_name, (app_label, model) in RENAMED_MODELS.items():
        try:
            ct = ContentType.objects.get(app_label=app_label, model=model)
        except ContentType.DoesNotExist:
            continue

        stale_codenames = [
            f"{action}_{old_name}" for action in ("add", "change", "delete", "view")
        ]
        Permission.objects.filter(
            content_type=ct, codename__in=stale_codenames
        ).delete()


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0182_requirementassessment_is_score_overridden"),
    ]
    operations = [
        migrations.RunPython(delete_stale_renamed_model_permissions, noop),
    ]
