# Generated by Django 6.0.7 on 2026-08-02 10:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0182_threatmodel_threatmodelnode_threatmodeledge"),
        ("iam", "0023_alter_folder_content_type"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="threatmodelnode",
            constraint=models.UniqueConstraint(
                fields=("threat_model", "technique", "tactic"),
                name="unique_threat_model_node_placement",
            ),
        ),
    ]
