# Generated by Django 6.0.7 on 2026-08-02 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0183_threatmodelnode_unique_threat_model_node_placement"),
    ]

    operations = [
        migrations.AddField(
            model_name="threatmodel",
            name="risk_scenarios",
            field=models.ManyToManyField(
                blank=True,
                related_name="threat_models",
                to="core.riskscenario",
                verbose_name="Risk scenarios",
            ),
        ),
        migrations.AddField(
            model_name="threatmodelnode",
            name="applied_controls",
            field=models.ManyToManyField(
                blank=True,
                related_name="threat_model_nodes",
                to="core.appliedcontrol",
                verbose_name="Applied controls",
            ),
        ),
        migrations.AddField(
            model_name="threatmodelnode",
            name="assets",
            field=models.ManyToManyField(
                blank=True,
                related_name="threat_model_nodes",
                to="core.asset",
                verbose_name="Assets",
            ),
        ),
        migrations.AddField(
            model_name="threatmodelnode",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="threatmodelnode",
            name="is_highlighted",
            field=models.BooleanField(default=False, verbose_name="Highlighted"),
        ),
        migrations.AddField(
            model_name="threatmodelnode",
            name="kind",
            field=models.CharField(
                choices=[
                    ("technique", "Technique"),
                    ("operator", "Operator"),
                    ("custom", "Custom"),
                ],
                default="technique",
                max_length=20,
                verbose_name="Kind",
            ),
        ),
        migrations.AddField(
            model_name="threatmodelnode",
            name="operator",
            field=models.CharField(
                blank=True,
                choices=[("AND", "AND"), ("OR", "OR")],
                max_length=3,
                null=True,
                verbose_name="Operator",
            ),
        ),
        migrations.AddField(
            model_name="threatmodelnode",
            name="properties",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="threatmodel",
            name="graph_columns",
            field=models.JSONField(
                blank=True, default=dict, help_text="Lane sizes in the editor"
            ),
        ),
        migrations.AlterField(
            model_name="threatmodelnode",
            name="technique",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="threat_model_nodes",
                to="core.technique",
                verbose_name="Technique",
            ),
        ),
    ]
