# Generated by Django 6.0.8 on 2026-08-26 05:47

import django.core.validators
import django.db.models.deletion
import iam.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0183_cleanup_stale_permissions_from_model_renamed"),
        ("iam", "0027_cleanup_stray_domain_iam_groups"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Commitment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
                ("object_id", models.UUIDField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("--", "Undefined"),
                            ("in_negotiation", "In negotiation"),
                            ("committed", "Committed"),
                            ("declined", "Declined"),
                            ("fulfilled", "Fulfilled"),
                        ],
                        default="in_negotiation",
                        max_length=32,
                        verbose_name="Commitment state",
                    ),
                ),
                (
                    "committed_eta",
                    models.DateField(
                        blank=True,
                        help_text="The date promised, frozen when the commitment is made",
                        null=True,
                        verbose_name="Committed date",
                    ),
                ),
                (
                    "committed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the promise was made — not the date promised",
                        null=True,
                        verbose_name="Committed at",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="Commitment notes"
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(default=True, verbose_name="Is current"),
                ),
            ],
            options={
                "verbose_name": "Commitment",
                "verbose_name_plural": "Commitments",
                "ordering": ["created_at"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="comment",
            name="comment_exactly_one_parent",
        ),
        migrations.AddField(
            model_name="comment",
            name="task_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="core.tasktemplate",
            ),
        ),
        migrations.AddField(
            model_name="finding",
            name="recommendation",
            field=models.TextField(
                blank=True, null=True, verbose_name="Recommendation"
            ),
        ),
        migrations.AddField(
            model_name="finding",
            name="requirement_assessment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="findings",
                to="core.requirementassessment",
                verbose_name="Requirement assessment",
            ),
        ),
        migrations.AddField(
            model_name="findingsassessment",
            name="budget",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=14,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Budget",
            ),
        ),
        migrations.AddField(
            model_name="findingsassessment",
            name="compliance_assessment",
            field=models.ForeignKey(
                blank=True,
                help_text="The audit whose findings this binder captures",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="findings_assessments",
                to="core.complianceassessment",
                verbose_name="Audit",
            ),
        ),
        migrations.AddField(
            model_name="findingsassessment",
            name="expenses",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Budget consumed so far",
                max_digits=14,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Expenses",
            ),
        ),
        migrations.AddField(
            model_name="findingsassessment",
            name="objectives",
            field=models.TextField(blank=True, null=True, verbose_name="Objectives"),
        ),
        migrations.AddField(
            model_name="findingsassessment",
            name="reference_link",
            field=models.URLField(
                blank=True,
                help_text="External url for follow-up (eg. report, Jira ticket)",
                max_length=2048,
                null=True,
                verbose_name="Reference link",
            ),
        ),
        migrations.AddField(
            model_name="findingsassessment",
            name="start_date",
            field=models.DateField(blank=True, null=True, verbose_name="Start date"),
        ),
        migrations.AlterField(
            model_name="finding",
            name="findings_assessment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="findings",
                to="core.findingsassessment",
                verbose_name="Findings assessment",
            ),
        ),
        migrations.AddConstraint(
            model_name="comment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("applied_control__isnull", True),
                        ("finding__isnull", True),
                        ("requirement_assessment__isnull", False),
                        ("risk_scenario__isnull", True),
                        ("task_template__isnull", True),
                    ),
                    models.Q(
                        ("applied_control__isnull", True),
                        ("finding__isnull", True),
                        ("requirement_assessment__isnull", True),
                        ("risk_scenario__isnull", False),
                        ("task_template__isnull", True),
                    ),
                    models.Q(
                        ("applied_control__isnull", False),
                        ("finding__isnull", True),
                        ("requirement_assessment__isnull", True),
                        ("risk_scenario__isnull", True),
                        ("task_template__isnull", True),
                    ),
                    models.Q(
                        ("applied_control__isnull", True),
                        ("finding__isnull", False),
                        ("requirement_assessment__isnull", True),
                        ("risk_scenario__isnull", True),
                        ("task_template__isnull", True),
                    ),
                    models.Q(
                        ("applied_control__isnull", True),
                        ("finding__isnull", True),
                        ("requirement_assessment__isnull", True),
                        ("risk_scenario__isnull", True),
                        ("task_template__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="comment_exactly_one_parent",
            ),
        ),
        migrations.AddField(
            model_name="commitment",
            name="committed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="commitments",
                to="core.actor",
                verbose_name="Committed by",
            ),
        ),
        migrations.AddField(
            model_name="commitment",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="commitment",
            name="folder",
            field=models.ForeignKey(
                default=iam.models.Folder.get_root_folder_id,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_folder",
                to="iam.folder",
            ),
        ),
        migrations.AddIndex(
            model_name="commitment",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="core_commit_content_7cef7a_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="commitment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True)),
                fields=("content_type", "object_id"),
                name="unique_current_commitment_per_object",
            ),
        ),
    ]
