# Generated by Django 6.0.8 on 2026-08-28 06:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0184_clear_assessable_on_splash_nodes"),
        ("core", "0184_commitment_remove_comment_comment_exactly_one_parent_and_more"),
    ]

    operations = []
