# Generated by Django 6.0.8 on 2026-08-27 07:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0184_clear_assessable_on_splash_nodes"),
    ]

    operations = [
        migrations.AddField(
            model_name="presetjourney",
            name="sequence",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
