# Generated by Django 6.0.7 on 2026-08-02 11:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0184_threatmodel_risk_scenarios_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="threatmodelnode",
            name="vulnerabilities",
            field=models.ManyToManyField(
                blank=True,
                related_name="threat_model_nodes",
                to="core.vulnerability",
                verbose_name="Vulnerabilities",
            ),
        ),
    ]
