# Generated by Django 6.0.8 on 2026-08-28 06:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0185_merge_20260828_0648"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasktemplate",
            name="requirement_assessments",
            field=models.ManyToManyField(
                blank=True,
                help_text="Requirement assessments related to the task",
                related_name="task_templates",
                to="core.requirementassessment",
                verbose_name="Requirement assessments",
            ),
        ),
    ]
