# Generated by Django 6.0.8 on 2026-08-28 12:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0185_commitment_remove_comment_comment_exactly_one_parent_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="commitment",
            options={
                "ordering": ["created_at"],
                "permissions": [
                    ("transition_commitment", "Can take a commitment step")
                ],
                "verbose_name": "Commitment",
                "verbose_name_plural": "Commitments",
            },
        ),
    ]
