# Generated by Django 6.0.8 on 2026-08-30 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0185_presetjourney_sequence'),
        ('tprm', '0019_null_perimeter_on_enclave_audits'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='entities',
            field=models.ManyToManyField(blank=True, related_name='campaigns', to='tprm.entity', verbose_name='Entities'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='target_scope',
            field=models.CharField(choices=[('internal', 'Internal'), ('external', 'External')], default='internal', max_length=10, verbose_name='Target scope'),
        ),
    ]
