# Generated by Django 6.1.1 on 2026-09-07 20:13

import django.db.models.deletion
import iam.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0186_commitment_remove_comment_comment_exactly_one_parent_and_more"),
        ("iam", "0028_idpgroup_source_user_is_jit_provisioned"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuickFormResponse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                ("eta", models.DateField(blank=True, null=True, verbose_name="ETA")),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="Due date"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In progress"),
                            ("submitted", "Submitted"),
                            ("closed", "Closed"),
                        ],
                        default="in_progress",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "computed_outcome",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Computed outcome"
                    ),
                ),
                (
                    "score",
                    models.IntegerField(blank=True, null=True, verbose_name="Score"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Started at"
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Submitted at"
                    ),
                ),
                (
                    "observation",
                    models.TextField(blank=True, null=True, verbose_name="Observation"),
                ),
            ],
            options={
                "verbose_name": "Quick form response",
                "verbose_name_plural": "Quick form responses",
            },
        ),
        migrations.AddField(
            model_name="question",
            name="required",
            field=models.BooleanField(default=True, verbose_name="Required"),
        ),
        migrations.AlterField(
            model_name="answer",
            name="requirement_assessment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="core.requirementassessment",
                verbose_name="Requirement assessment",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="requirement_node",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="core.requirementnode",
                verbose_name="Requirement node",
            ),
        ),
        migrations.CreateModel(
            name="QuickForm",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
                (
                    "urn",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="URN",
                    ),
                ),
                (
                    "ref_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Reference ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Provider"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, null=True, verbose_name="Name"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "annotation",
                    models.TextField(blank=True, null=True, verbose_name="Annotation"),
                ),
                (
                    "translations",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Translations"
                    ),
                ),
                (
                    "locale",
                    models.CharField(
                        default="en", max_length=100, verbose_name="Locale"
                    ),
                ),
                (
                    "default_locale",
                    models.BooleanField(default=True, verbose_name="Default locale"),
                ),
                (
                    "urn_namespace",
                    models.CharField(
                        default="custom", max_length=50, verbose_name="URN namespace"
                    ),
                ),
                (
                    "outcomes_definition",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Outcomes definition"
                    ),
                ),
                (
                    "scores_definition",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Scores definition"
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        default=iam.models.Folder.get_root_folder_id,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_folder",
                        to="iam.folder",
                    ),
                ),
                (
                    "library",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quick_forms",
                        to="core.loadedlibrary",
                        verbose_name="Library",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quick form",
                "verbose_name_plural": "Quick forms",
            },
        ),
        migrations.CreateModel(
            name="QuickFormPage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
                (
                    "urn",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="URN",
                    ),
                ),
                (
                    "ref_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Reference ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Provider"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, null=True, verbose_name="Name"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "annotation",
                    models.TextField(blank=True, null=True, verbose_name="Annotation"),
                ),
                (
                    "translations",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Translations"
                    ),
                ),
                (
                    "locale",
                    models.CharField(
                        default="en", max_length=100, verbose_name="Locale"
                    ),
                ),
                (
                    "default_locale",
                    models.BooleanField(default=True, verbose_name="Default locale"),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Order")),
                (
                    "visibility_expression",
                    models.TextField(
                        blank=True,
                        help_text="CEL expression; the page is hidden when it evaluates to false",
                        null=True,
                        verbose_name="Visibility expression",
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        default=iam.models.Folder.get_root_folder_id,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_folder",
                        to="iam.folder",
                    ),
                ),
                (
                    "quick_form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="core.quickform",
                        verbose_name="Quick form",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quick form page",
                "verbose_name_plural": "Quick form pages",
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="question",
            name="page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="core.quickformpage",
                verbose_name="Quick form page",
            ),
        ),
        migrations.AddConstraint(
            model_name="question",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("page__isnull", True), ("requirement_node__isnull", False)
                    ),
                    models.Q(
                        ("page__isnull", False), ("requirement_node__isnull", True)
                    ),
                    _connector="OR",
                ),
                name="question_exactly_one_parent",
            ),
        ),
        migrations.AddField(
            model_name="quickformresponse",
            name="folder",
            field=models.ForeignKey(
                default=iam.models.Folder.get_root_folder_id,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_folder",
                to="iam.folder",
            ),
        ),
        migrations.AddField(
            model_name="quickformresponse",
            name="quick_form",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="responses",
                to="core.quickform",
                verbose_name="Quick form",
            ),
        ),
        migrations.AddField(
            model_name="quickformresponse",
            name="respondents",
            field=models.ManyToManyField(
                blank=True,
                related_name="quick_form_responses_as_respondent",
                to="core.actor",
                verbose_name="Respondents",
            ),
        ),
        migrations.AddField(
            model_name="quickformresponse",
            name="reviewers",
            field=models.ManyToManyField(
                blank=True,
                related_name="quick_form_responses_as_reviewer",
                to="core.actor",
                verbose_name="Reviewers",
            ),
        ),
        migrations.AddField(
            model_name="answer",
            name="response",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="core.quickformresponse",
                verbose_name="Quick form response",
            ),
        ),
        migrations.AddConstraint(
            model_name="answer",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("requirement_assessment__isnull", False),
                        ("response__isnull", True),
                    ),
                    models.Q(
                        ("requirement_assessment__isnull", True),
                        ("response__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="answer_exactly_one_parent",
            ),
        ),
        migrations.AddConstraint(
            model_name="answer",
            constraint=models.UniqueConstraint(
                fields=("response", "question"),
                name="answer_unique_per_response_question",
            ),
        ),
    ]
