# Generated by Django 6.0.8 on 2026-09-02 07:43

from django.db import migrations, models


def backfill_target_domains(apps, schema_editor):
    """Existing campaigns targeted perimeters; keep them working by pointing them at
    those perimeters' domains. `perimeters` is left intact."""
    Campaign = apps.get_model("core", "Campaign")
    for campaign in Campaign.objects.prefetch_related("perimeters"):
        folders = {p.folder_id for p in campaign.perimeters.all() if p.folder_id}
        if folders:
            campaign.folders.set(folders)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0186_commitment_remove_comment_comment_exactly_one_parent_and_more"),
        ("iam", "0028_idpgroup_source_user_is_jit_provisioned"),
        ("tprm", "0021_normalize_entity_workspaces"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="entities",
            field=models.ManyToManyField(
                blank=True,
                related_name="campaigns",
                to="tprm.entity",
                verbose_name="Third parties",
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="folders",
            field=models.ManyToManyField(
                blank=True,
                related_name="campaigns",
                to="iam.folder",
                verbose_name="Target domains",
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="kind",
            field=models.CharField(
                choices=[("internal", "Internal"), ("third_party", "Third-party")],
                default="internal",
                max_length=20,
                verbose_name="Kind",
            ),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="perimeters",
            field=models.ManyToManyField(
                blank=True, related_name="campaigns", to="core.perimeter"
            ),
        ),
        migrations.RunPython(backfill_target_domains, migrations.RunPython.noop),
    ]
