# Generated by Django 6.0.8 on 2026-08-31 09:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0186_commitment_remove_comment_comment_exactly_one_parent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="requirementassessment",
            name="review_state",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "None"),
                    ("changes_requested", "Changes requested"),
                    ("resubmitted", "Resubmitted"),
                    ("accepted", "Accepted"),
                ],
                default="",
                max_length=32,
                verbose_name="Review state",
            ),
        ),
    ]
