# Generated by Django 6.1.1 on 2026-09-08 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0186_commitment_remove_comment_comment_exactly_one_parent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="flowevent",
            name="residual_risk_accepted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="flowevent",
            name="risk_snapshot",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="validationflow",
            name="risk_approval_stage",
            field=models.CharField(
                blank=True,
                choices=[
                    ("assessment", "Assessment"),
                    ("treatment", "Treatment and residual risk"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="validationflow",
            name="risk_scenario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="risk_approvals",
                to="core.riskscenario",
            ),
        ),
        migrations.AddField(
            model_name="validationflow",
            name="risk_snapshot",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
