# Generated by Django 6.1.1 on 2026-09-09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0187_risk_owner_approvals"),
    ]

    operations = [
        migrations.AlterField(
            model_name="validationflow",
            name="risk_approval_stage",
            field=models.CharField(
                blank=True,
                choices=[
                    ("assessment", "Assessment"),
                    ("treatment", "Treatment"),
                    ("residual_acceptance", "Residual risk acceptance"),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
