# Generated by Django 6.1.1 on 2026-09-08 13:03

import django.db.models.deletion
import iam.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0187_quick_forms"),
        ("iam", "0028_idpgroup_source_user_is_jit_provisioned"),
    ]

    operations = [
        migrations.AddField(
            model_name="quickformresponse",
            name="outcome_refs",
            field=models.TextField(blank=True, default="", verbose_name="Outcome refs"),
        ),
        migrations.CreateModel(
            name="QuickFormOutcome",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
                (
                    "ref_id",
                    models.CharField(max_length=100, verbose_name="Reference ID"),
                ),
                (
                    "label",
                    models.CharField(blank=True, max_length=255, verbose_name="Label"),
                ),
                (
                    "color",
                    models.CharField(blank=True, max_length=50, verbose_name="Color"),
                ),
                (
                    "fired_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fired at"),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        default=iam.models.Folder.get_root_folder_id,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_folder",
                        to="iam.folder",
                    ),
                ),
                (
                    "response",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outcomes",
                        to="core.quickformresponse",
                        verbose_name="Quick form response",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quick form outcome",
                "verbose_name_plural": "Quick form outcomes",
                "ordering": ["ref_id"],
                "unique_together": {("response", "ref_id")},
            },
        ),
    ]
