# Generated by Django 6.1.1 on 2026-09-12 09:02

import django.db.models.deletion
import iam.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0187_remove_actor_is_published_remove_answer_is_published_and_more"),
        ("iam", "0031_remove_iam_is_published_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QuickFormPublication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                ("enabled", models.BooleanField(default=True, verbose_name="Enabled")),
                (
                    "allow_multiple_drafts",
                    models.BooleanField(
                        default=False,
                        help_text="Off: a requester with an unfinished draft is handed it back instead of starting a new one. Submitted requests are never limited.",
                        verbose_name="Allow multiple drafts",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="Icon"
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Order")),
            ],
            options={
                "verbose_name": "Quick form publication",
                "verbose_name_plural": "Quick form publications",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="QuickFormResponse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                ("eta", models.DateField(blank=True, null=True, verbose_name="ETA")),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="Due date"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("in_review", "In review"),
                            ("closed", "Closed"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "resolution",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("dropped", "Dropped"),
                            ("auto", "Closed automatically"),
                        ],
                        default="",
                        max_length=20,
                        verbose_name="Resolution",
                    ),
                ),
                (
                    "computed_outcome",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Computed outcome"
                    ),
                ),
                (
                    "outcome_refs",
                    models.TextField(
                        blank=True, default="", verbose_name="Outcome refs"
                    ),
                ),
                (
                    "score",
                    models.IntegerField(blank=True, null=True, verbose_name="Score"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Started at"
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Submitted at"
                    ),
                ),
                (
                    "observation",
                    models.TextField(blank=True, null=True, verbose_name="Observation"),
                ),
                (
                    "ref_id",
                    models.CharField(
                        blank=True,
                        max_length=32,
                        null=True,
                        unique=True,
                        verbose_name="Reference ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quick form response",
                "verbose_name_plural": "Quick form responses",
                "permissions": [
                    (
                        "approve_quickformresponse",
                        "Can decide on a request (close, send back, take in review)",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="question",
            name="required",
            field=models.BooleanField(default=True, verbose_name="Required"),
        ),
        migrations.AlterField(
            model_name="answer",
            name="requirement_assessment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="core.requirementassessment",
                verbose_name="Requirement assessment",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="requirement_node",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="core.requirementnode",
                verbose_name="Requirement node",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("number", "Number"),
                    ("boolean", "Boolean"),
                    ("unique_choice", "Unique choice"),
                    ("multiple_choice", "Multiple choice"),
                    ("date", "Date"),
                    ("file", "File"),
                    ("object_reference", "Object reference"),
                ],
                default="text",
                max_length=20,
                verbose_name="Type",
            ),
        ),
        migrations.CreateModel(
            name="AnswerAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="answer_attachments", verbose_name="File"
                    ),
                ),
                (
                    "filename",
                    models.CharField(max_length=255, verbose_name="File name"),
                ),
                ("size", models.PositiveIntegerField(default=0, verbose_name="Size")),
                ("mime_type", models.CharField(blank=True, default="", max_length=127)),
                (
                    "file_hash",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                (
                    "answer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="core.answer",
                        verbose_name="Answer",
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        default=iam.models.Folder.get_root_folder_id,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_folder",
                        to="iam.folder",
                    ),
                ),
                (
                    "promoted_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="promoted_from_answers",
                        to="core.evidence",
                        verbose_name="Promoted to evidence",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="answer_attachments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Uploaded by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Answer attachment",
                "verbose_name_plural": "Answer attachments",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProducedObjectLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("source_object_id", models.UUIDField()),
                ("object_id", models.UUIDField()),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="What performed the creation, e.g. the workflow that ran.",
                        max_length=255,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="produced_links_as_target",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "source_content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="produced_links_as_source",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Produced object link",
                "verbose_name_plural": "Produced object links",
            },
        ),
        migrations.CreateModel(
            name="QuickForm",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "urn",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="URN",
                    ),
                ),
                (
                    "ref_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Reference ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Provider"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, null=True, verbose_name="Name"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "annotation",
                    models.TextField(blank=True, null=True, verbose_name="Annotation"),
                ),
                (
                    "translations",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Translations"
                    ),
                ),
                (
                    "locale",
                    models.CharField(
                        default="en", max_length=100, verbose_name="Locale"
                    ),
                ),
                (
                    "default_locale",
                    models.BooleanField(default=True, verbose_name="Default locale"),
                ),
                (
                    "urn_namespace",
                    models.CharField(
                        default="custom", max_length=50, verbose_name="URN namespace"
                    ),
                ),
                (
                    "outcomes_definition",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Outcomes definition"
                    ),
                ),
                (
                    "scores_definition",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Scores definition"
                    ),
                ),
                (
                    "title_question_urn",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="URN of the question whose answer names each response. Without it every response from the same entry point carries the same name.",
                        max_length=255,
                        verbose_name="Title question",
                    ),
                ),
                (
                    "ref_id_prefix",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Prefix for the human reference of each response (e.g. DER gives DER.000042). Derived from the form's reference ID when left empty.",
                        max_length=8,
                        verbose_name="Reference ID prefix",
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        default=iam.models.Folder.get_root_folder_id,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_folder",
                        to="iam.folder",
                    ),
                ),
                (
                    "library",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quick_forms",
                        to="core.loadedlibrary",
                        verbose_name="Library",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quick form",
                "verbose_name_plural": "Quick forms",
            },
        ),
        migrations.CreateModel(
            name="QuickFormOutcome",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "ref_id",
                    models.CharField(max_length=100, verbose_name="Reference ID"),
                ),
                (
                    "label",
                    models.CharField(blank=True, max_length=255, verbose_name="Label"),
                ),
                (
                    "color",
                    models.CharField(blank=True, max_length=50, verbose_name="Color"),
                ),
                (
                    "fired_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fired at"),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        default=iam.models.Folder.get_root_folder_id,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_folder",
                        to="iam.folder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quick form outcome",
                "verbose_name_plural": "Quick form outcomes",
                "ordering": ["ref_id"],
            },
        ),
        migrations.CreateModel(
            name="QuickFormPage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "urn",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="URN",
                    ),
                ),
                (
                    "ref_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Reference ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Provider"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, null=True, verbose_name="Name"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "annotation",
                    models.TextField(blank=True, null=True, verbose_name="Annotation"),
                ),
                (
                    "translations",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Translations"
                    ),
                ),
                (
                    "locale",
                    models.CharField(
                        default="en", max_length=100, verbose_name="Locale"
                    ),
                ),
                (
                    "default_locale",
                    models.BooleanField(default=True, verbose_name="Default locale"),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Order")),
                (
                    "visibility_expression",
                    models.TextField(
                        blank=True,
                        help_text="CEL expression; the page is hidden when it evaluates to false",
                        null=True,
                        verbose_name="Visibility expression",
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        default=iam.models.Folder.get_root_folder_id,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_folder",
                        to="iam.folder",
                    ),
                ),
                (
                    "quick_form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="core.quickform",
                        verbose_name="Quick form",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quick form page",
                "verbose_name_plural": "Quick form pages",
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="question",
            name="page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="core.quickformpage",
                verbose_name="Quick form page",
            ),
        ),
        migrations.AddConstraint(
            model_name="question",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("page__isnull", True), ("requirement_node__isnull", False)
                    ),
                    models.Q(
                        ("page__isnull", False), ("requirement_node__isnull", True)
                    ),
                    _connector="OR",
                ),
                name="question_exactly_one_parent",
            ),
        ),
        migrations.AddField(
            model_name="quickformpublication",
            name="audience_groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="Groups that may file this request. Empty means every user.",
                related_name="quick_form_publications",
                to="iam.usergroup",
                verbose_name="Audience groups",
            ),
        ),
        migrations.AddField(
            model_name="quickformpublication",
            name="default_reviewers",
            field=models.ManyToManyField(
                blank=True,
                related_name="quick_form_publications_as_reviewer",
                to="core.actor",
                verbose_name="Default reviewers",
            ),
        ),
        migrations.AddField(
            model_name="quickformpublication",
            name="folder",
            field=models.ForeignKey(
                default=iam.models.Folder.get_root_folder_id,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_folder",
                to="iam.folder",
            ),
        ),
        migrations.AddField(
            model_name="quickformpublication",
            name="quick_form",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="publications",
                to="core.quickform",
                verbose_name="Quick form",
            ),
        ),
        migrations.AddField(
            model_name="quickformpublication",
            name="submission_folder",
            field=models.ForeignKey(
                blank=True,
                help_text="Where responses land. The publication's own domain when left empty.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="quick_form_submissions",
                to="iam.folder",
                verbose_name="Submission domain",
            ),
        ),
        migrations.AddField(
            model_name="quickformresponse",
            name="assignee",
            field=models.ForeignKey(
                blank=True,
                help_text="The reviewer who picked this up. `reviewers` is the pool and may be a team; this is the one person working it.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quick_form_responses_as_assignee",
                to="core.actor",
                verbose_name="Assignee",
            ),
        ),
        migrations.AddField(
            model_name="quickformresponse",
            name="cloned_from",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clones",
                to="core.quickformresponse",
                verbose_name="Cloned from",
            ),
        ),
        migrations.AddField(
            model_name="quickformresponse",
            name="decided_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Who closed this request. `assignee` is who picked it up and is optional; this is who actually rendered the verdict, which is what a produced record needs as its approver.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quick_form_responses_decided",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Decided by",
            ),
        ),
        migrations.AddField(
            model_name="quickformresponse",
            name="folder",
            field=models.ForeignKey(
                default=iam.models.Folder.get_root_folder_id,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_folder",
                to="iam.folder",
            ),
        ),
        migrations.AddField(
            model_name="quickformresponse",
            name="publication",
            field=models.ForeignKey(
                blank=True,
                help_text="Set when the response was filed through a published entry point.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="responses",
                to="core.quickformpublication",
                verbose_name="Publication",
            ),
        ),
        migrations.AddField(
            model_name="quickformresponse",
            name="quick_form",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="responses",
                to="core.quickform",
                verbose_name="Quick form",
            ),
        ),
        migrations.AddField(
            model_name="quickformresponse",
            name="respondents",
            field=models.ManyToManyField(
                blank=True,
                related_name="quick_form_responses_as_respondent",
                to="core.actor",
                verbose_name="Respondents",
            ),
        ),
        migrations.AddField(
            model_name="quickformresponse",
            name="reviewers",
            field=models.ManyToManyField(
                blank=True,
                related_name="quick_form_responses_as_reviewer",
                to="core.actor",
                verbose_name="Reviewers",
            ),
        ),
        migrations.AddField(
            model_name="quickformresponse",
            name="submitted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submitted_quick_form_responses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Submitted by",
            ),
        ),
        migrations.AddField(
            model_name="quickformoutcome",
            name="response",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="outcomes",
                to="core.quickformresponse",
                verbose_name="Quick form response",
            ),
        ),
        migrations.AddField(
            model_name="answer",
            name="response",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="core.quickformresponse",
                verbose_name="Quick form response",
            ),
        ),
        migrations.AddConstraint(
            model_name="answer",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("requirement_assessment__isnull", False),
                        ("response__isnull", True),
                    ),
                    models.Q(
                        ("requirement_assessment__isnull", True),
                        ("response__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="answer_exactly_one_parent",
            ),
        ),
        migrations.AddConstraint(
            model_name="answer",
            constraint=models.UniqueConstraint(
                fields=("response", "question"),
                name="answer_unique_per_response_question",
            ),
        ),
        migrations.AddIndex(
            model_name="producedobjectlink",
            index=models.Index(
                fields=["source_content_type", "source_object_id"],
                name="core_produc_source__533443_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="producedobjectlink",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="core_produc_content_f68943_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="producedobjectlink",
            constraint=models.UniqueConstraint(
                fields=(
                    "source_content_type",
                    "source_object_id",
                    "content_type",
                    "object_id",
                ),
                name="unique_produced_object_link",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="quickformoutcome",
            unique_together={("response", "ref_id")},
        ),
    ]
