# Generated by Django 6.1.1 on 2026-09-14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0188_quickformpublication_quickformresponse_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="validationflow",
            name="risk_scenarios",
            field=models.ManyToManyField(blank=True, to="core.riskscenario"),
        ),
        migrations.AddField(
            model_name="validationflow",
            name="subject",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Validation subject"
            ),
        ),
    ]
