# Generated by Django 6.1.1 on 2026-09-08 13:40

import re

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _prefix_for(form):
    prefix = (form.ref_id_prefix or "").upper()
    if prefix:
        return prefix
    token = re.split(r"[^A-Za-z0-9]+", form.ref_id or "")[0] if form.ref_id else ""
    return (token[:4].upper() or "QF") if token else "QF"


def backfill_ref_ids(apps, schema_editor):
    """Mint a reference for every existing response, oldest first, so the numbering
    follows creation order. Counters are per form prefix."""
    QuickFormResponse = apps.get_model("core", "QuickFormResponse")
    counters = {}
    updates = []
    for response in QuickFormResponse.objects.select_related("quick_form").order_by(
        "created_at"
    ):
        if response.ref_id:
            continue
        prefix = _prefix_for(response.quick_form)
        counters[prefix] = counters.get(prefix, 0) + 1
        response.ref_id = f"{prefix}.{counters[prefix]:06d}"
        updates.append(response)
    if updates:
        QuickFormResponse.objects.bulk_update(updates, ["ref_id"], batch_size=500)


def unbackfill_ref_ids(apps, schema_editor):
    apps.get_model("core", "QuickFormResponse").objects.update(ref_id=None)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0188_quickformresponse_outcome_refs_quickformoutcome"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="quickform",
            name="ref_id_prefix",
            field=models.CharField(
                blank=True,
                default="",
                help_text=(
                    "Prefix for the human reference of each response (e.g. DER "
                    "gives DER.000042). Derived from the form's reference ID when "
                    "left empty."
                ),
                max_length=8,
                verbose_name="Reference ID prefix",
            ),
        ),
        migrations.AddField(
            model_name="quickformresponse",
            name="ref_id",
            field=models.CharField(
                blank=True,
                max_length=32,
                null=True,
                unique=True,
                verbose_name="Reference ID",
            ),
        ),
        migrations.AddField(
            model_name="quickformresponse",
            name="submitted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submitted_quick_form_responses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Submitted by",
            ),
        ),
        migrations.RunPython(backfill_ref_ids, unbackfill_ref_ids),
    ]
