# Generated by Django 6.1.1 on 2026-09-18 11:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0188_quickformpublication_quickformresponse_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="evidencerevision",
            name="original_filename",
            field=models.CharField(
                blank=True,
                help_text="The name the file was uploaded with",
                max_length=255,
                verbose_name="Original file name",
            ),
        ),
    ]
