# Generated by Django 6.1.1 on 2026-09-08 13:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0189_quickform_ref_id_prefix_quickformresponse_ref_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quickform",
            name="title_question_urn",
            field=models.CharField(
                blank=True,
                default="",
                help_text="URN of the question whose answer names each response. Without it every response from the same entry point carries the same name.",
                max_length=255,
                verbose_name="Title question",
            ),
        ),
    ]
