# Generated by Django 6.1.1 on 2026-09-26 10:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0189_evidencerevision_original_filename"),
    ]

    operations = [
        migrations.AddField(
            model_name="complianceassessment",
            name="score_scale_preset",
            field=models.CharField(
                blank=True,
                choices=[
                    ("0-100", "0-100"),
                    ("0-5", "0-5"),
                    ("1-5", "1-5"),
                    ("1-4", "1-4"),
                    ("0-4", "0-4"),
                ],
                max_length=20,
                null=True,
                verbose_name="Score scale preset",
            ),
        ),
    ]
