# Generated by Django 6.1.1 on 2026-09-08 14:11

import django.db.models.deletion
import iam.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0190_quickform_title_question_urn"),
        ("iam", "0028_idpgroup_source_user_is_jit_provisioned"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuickFormPublication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                ("enabled", models.BooleanField(default=True, verbose_name="Enabled")),
                (
                    "allow_multiple_drafts",
                    models.BooleanField(
                        default=False,
                        help_text="Off: a requester with an unfinished draft is handed it back instead of starting a new one. Submitted requests are never limited.",
                        verbose_name="Allow multiple drafts",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="Icon"
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Order")),
                (
                    "audience_groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Groups that may file this request. Empty means every user.",
                        related_name="quick_form_publications",
                        to="iam.usergroup",
                        verbose_name="Audience groups",
                    ),
                ),
                (
                    "default_reviewers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="quick_form_publications_as_reviewer",
                        to="core.actor",
                        verbose_name="Default reviewers",
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        default=iam.models.Folder.get_root_folder_id,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_folder",
                        to="iam.folder",
                    ),
                ),
                (
                    "quick_form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="publications",
                        to="core.quickform",
                        verbose_name="Quick form",
                    ),
                ),
                (
                    "submission_folder",
                    models.ForeignKey(
                        blank=True,
                        help_text="Where responses land. The publication's own domain when left empty.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quick_form_submissions",
                        to="iam.folder",
                        verbose_name="Submission domain",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quick form publication",
                "verbose_name_plural": "Quick form publications",
                "ordering": ["order", "name"],
            },
        ),
        migrations.AddField(
            model_name="quickformresponse",
            name="publication",
            field=models.ForeignKey(
                blank=True,
                help_text="Set when the response was filed through a published entry point.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="responses",
                to="core.quickformpublication",
                verbose_name="Publication",
            ),
        ),
    ]
