# Generated by Django 6.1.1 on 2026-09-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0190_framework_result_aggregation'),
    ]

    operations = [
        migrations.AddField(
            model_name='framework',
            name='question_groups_definition',
            field=models.JSONField(blank=True, default=list, help_text='Reusable question-group metadata. Requirements choose their order and questions reference one group by ref_id.', verbose_name='Question groups definition'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_group',
            field=models.CharField(blank=True, help_text="Reference ID of this question's framework-level group.", max_length=100, null=True, verbose_name='Question group'),
        ),
        migrations.AddField(
            model_name='requirementnode',
            name='questions_properties',
            field=models.JSONField(blank=True, default=dict, help_text='Presentation metadata for the requirement questions.', verbose_name='Questions properties'),
        ),
    ]
