# Generated by Django 6.1.1 on 2026-10-02 10:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0190_compliance_assessment_score_scale"),
    ]

    operations = [
        migrations.AlterField(
            model_name="terminology",
            name="field_path",
            field=models.CharField(
                choices=[
                    ("ro_to.risk_origin", "ro_to/risk_origin"),
                    (
                        "ro_to.target_objective_category",
                        "ro_to/target_objective_category",
                    ),
                    ("qualifications", "qualifications"),
                    ("accreditation.status", "accreditationStatus"),
                    ("accreditation.category", "accreditationCategory"),
                    ("entity.relationship", "entityRelationship"),
                    ("metric_definition.unit", "metricUnit"),
                    ("project.status", "projectStatus"),
                    ("project.health", "projectHealth"),
                    ("processing.nature", "processingNature"),
                    ("personal_data.category", "personalDataCategory"),
                    ("entity_score.provider", "entityScoreProvider"),
                ],
                max_length=100,
                verbose_name="Field path",
            ),
        ),
    ]
