# Generated by Django 6.1.1 on 2026-10-03 09:46

import django.db.models.deletion
import iam.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0190_compliance_assessment_score_scale"),
        ("iam", "0031_remove_iam_is_published_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QuickFormApplication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("target", models.CharField(max_length=100, verbose_name="Target")),
                ("subject_object_id", models.UUIDField(verbose_name="Subject")),
                (
                    "previous_value",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Previous value"
                    ),
                ),
                (
                    "previous_display",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="Previous"
                    ),
                ),
                (
                    "new_value",
                    models.JSONField(blank=True, null=True, verbose_name="New value"),
                ),
                (
                    "new_display",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="New"
                    ),
                ),
                (
                    "overridden",
                    models.BooleanField(default=False, verbose_name="Overridden"),
                ),
                ("note", models.TextField(blank=True, default="", verbose_name="Note")),
            ],
            options={
                "verbose_name": "Quick form application",
                "verbose_name_plural": "Quick form applications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="quickform",
            name="subject_question_urn",
            field=models.CharField(
                blank=True,
                default="",
                help_text="URN of a single-object reference question naming what each response is about, e.g. the vendor being assessed.",
                max_length=255,
                verbose_name="Subject question",
            ),
        ),
        migrations.AddField(
            model_name="quickformpage",
            name="aggregation",
            field=models.CharField(
                choices=[("sum", "Sum"), ("max", "Maximum"), ("mean", "Mean")],
                default="sum",
                help_text="How the page's question scores combine into the page score",
                max_length=10,
                verbose_name="Aggregation",
            ),
        ),
        migrations.AddField(
            model_name="quickformpublication",
            name="on_accept",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Apply on accept"
            ),
        ),
        migrations.AddField(
            model_name="quickformresponse",
            name="computed_values",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Computed values"
            ),
        ),
        migrations.AddField(
            model_name="quickformresponse",
            name="subject_content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="contenttypes.contenttype",
                verbose_name="Subject type",
            ),
        ),
        migrations.AddField(
            model_name="quickformresponse",
            name="subject_object_id",
            field=models.UUIDField(blank=True, null=True, verbose_name="Subject"),
        ),
        migrations.AlterField(
            model_name="quickformresponse",
            name="score",
            field=models.FloatField(blank=True, null=True, verbose_name="Score"),
        ),
        migrations.AddIndex(
            model_name="quickformresponse",
            index=models.Index(
                fields=["subject_content_type", "subject_object_id"],
                name="qf_response_subject_idx",
            ),
        ),
        migrations.AddField(
            model_name="quickformapplication",
            name="applied_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quick_form_applications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Applied by",
            ),
        ),
        migrations.AddField(
            model_name="quickformapplication",
            name="folder",
            field=models.ForeignKey(
                default=iam.models.Folder.get_root_folder_id,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_folder",
                to="iam.folder",
            ),
        ),
        migrations.AddField(
            model_name="quickformapplication",
            name="response",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="core.quickformresponse",
                verbose_name="Quick form response",
            ),
        ),
        migrations.AddField(
            model_name="quickformapplication",
            name="subject_content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="contenttypes.contenttype",
                verbose_name="Subject type",
            ),
        ),
    ]
