# Generated by Django 6.1.1 on 2026-09-08 15:25

import django.db.models.deletion
from django.db import migrations, models


def rename_in_progress_to_draft(apps, schema_editor):
    """`in_progress` meant "the requester is still writing". The reviewer now has an
    in-progress phase of their own (`in_review`), so the drafting state is `draft`."""
    apps.get_model("core", "QuickFormResponse").objects.filter(
        status="in_progress"
    ).update(status="draft")


def rename_draft_to_in_progress(apps, schema_editor):
    apps.get_model("core", "QuickFormResponse").objects.filter(status="draft").update(
        status="in_progress"
    )


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0191_quickformpublication_quickformresponse_publication"),
    ]

    operations = [
        migrations.AddField(
            model_name="quickformresponse",
            name="assignee",
            field=models.ForeignKey(
                blank=True,
                help_text="The reviewer who picked this up. `reviewers` is the pool and may be a team; this is the one person working it.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quick_form_responses_as_assignee",
                to="core.actor",
                verbose_name="Assignee",
            ),
        ),
        migrations.AddField(
            model_name="quickformresponse",
            name="cloned_from",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clones",
                to="core.quickformresponse",
                verbose_name="Cloned from",
            ),
        ),
        migrations.AddField(
            model_name="quickformresponse",
            name="resolution",
            field=models.CharField(
                blank=True,
                choices=[
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                    ("dropped", "Dropped"),
                    ("auto", "Closed automatically"),
                ],
                default="",
                max_length=20,
                verbose_name="Resolution",
            ),
        ),
        migrations.AlterField(
            model_name="quickformresponse",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("submitted", "Submitted"),
                    ("in_review", "In review"),
                    ("closed", "Closed"),
                ],
                default="draft",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.RunPython(rename_in_progress_to_draft, rename_draft_to_in_progress),
    ]
