# Generated by Django 6.1.1 on 2026-10-03 20:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0191_roto_target_objective_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="framework",
            name="score_calculation_method",
            field=models.CharField(
                default="average",
                help_text="Calculation method proposed for new audits.",
                max_length=30,
                verbose_name="Score calculation method",
            ),
        ),
        migrations.AddField(
            model_name="framework",
            name="score_scale_locked",
            field=models.BooleanField(
                default=False,
                help_text="The standard defines the score scale: audits cannot change it.",
                verbose_name="Score scale locked",
            ),
        ),
    ]
