# Generated by Django 6.1.1 on 2026-10-08 06:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0194_quick_form_tiering"),
    ]

    operations = [
        migrations.AddField(
            model_name="complianceassessment",
            name="computed_values",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Computed values"
            ),
        ),
    ]
