# Generated by Django 6.0.7 on 2026-08-02 13:41

import django.db.models.deletion
import iam.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0186_remove_tactic_catalog_remove_tactic_folder_and_more"),
        ("iam", "0023_alter_folder_content_type"),
        ("sec_intel", "0002_tactic_ttpcatalog_technique_tactic_catalog"),
    ]

    operations = [
        migrations.CreateModel(
            name="ThreatModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "ref_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Reference ID"
                    ),
                ),
                (
                    "graph_columns",
                    models.JSONField(
                        blank=True, default=dict, help_text="Lane sizes in the editor"
                    ),
                ),
                (
                    "catalog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="threat_models",
                        to="sec_intel.ttpcatalog",
                        verbose_name="TTP catalog",
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        default=iam.models.Folder.get_root_folder_id,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_folder",
                        to="iam.folder",
                    ),
                ),
                (
                    "risk_scenarios",
                    models.ManyToManyField(
                        blank=True,
                        related_name="threat_models",
                        to="core.riskscenario",
                        verbose_name="Risk scenarios",
                    ),
                ),
            ],
            options={
                "verbose_name": "Threat model",
                "verbose_name_plural": "Threat models",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ThreatModelNode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("technique", "Technique"),
                            ("operator", "Operator"),
                            ("custom", "Custom"),
                        ],
                        default="technique",
                        max_length=20,
                        verbose_name="Kind",
                    ),
                ),
                (
                    "operator",
                    models.CharField(
                        blank=True,
                        choices=[("AND", "AND"), ("OR", "OR")],
                        max_length=3,
                        null=True,
                        verbose_name="Operator",
                    ),
                ),
                (
                    "label",
                    models.CharField(blank=True, max_length=255, verbose_name="Label"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "is_highlighted",
                    models.BooleanField(default=False, verbose_name="Highlighted"),
                ),
                ("properties", models.JSONField(blank=True, default=dict)),
                ("position_x", models.FloatField(default=0)),
                ("position_y", models.FloatField(default=0)),
                (
                    "applied_controls",
                    models.ManyToManyField(
                        blank=True,
                        related_name="threat_model_nodes",
                        to="core.appliedcontrol",
                        verbose_name="Applied controls",
                    ),
                ),
                (
                    "assets",
                    models.ManyToManyField(
                        blank=True,
                        related_name="threat_model_nodes",
                        to="core.asset",
                        verbose_name="Assets",
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        default=iam.models.Folder.get_root_folder_id,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_folder",
                        to="iam.folder",
                    ),
                ),
                (
                    "tactic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="threat_model_nodes",
                        to="sec_intel.tactic",
                        verbose_name="Tactic",
                    ),
                ),
                (
                    "technique",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="threat_model_nodes",
                        to="sec_intel.technique",
                        verbose_name="Technique",
                    ),
                ),
                (
                    "threat_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nodes",
                        to="threat_modeling.threatmodel",
                    ),
                ),
                (
                    "vulnerabilities",
                    models.ManyToManyField(
                        blank=True,
                        related_name="threat_model_nodes",
                        to="core.vulnerability",
                        verbose_name="Vulnerabilities",
                    ),
                ),
            ],
            options={
                "verbose_name": "Threat model node",
                "verbose_name_plural": "Threat model nodes",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ThreatModelEdge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
                (
                    "label",
                    models.CharField(blank=True, max_length=255, verbose_name="Label"),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        default=iam.models.Folder.get_root_folder_id,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_folder",
                        to="iam.folder",
                    ),
                ),
                (
                    "threat_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="edges",
                        to="threat_modeling.threatmodel",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing",
                        to="threat_modeling.threatmodelnode",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming",
                        to="threat_modeling.threatmodelnode",
                    ),
                ),
            ],
            options={
                "verbose_name": "Threat model edge",
                "verbose_name_plural": "Threat model edges",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="threatmodelnode",
            constraint=models.UniqueConstraint(
                fields=("threat_model", "technique", "tactic"),
                name="unique_threat_model_node_placement",
            ),
        ),
    ]
