# Generated by Django 6.0.8 on 2026-08-17 14:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("threat_modeling", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="threatmodel",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="threatmodeledge",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="threatmodelnode",
            name="is_published",
        ),
    ]
