export default {
	assessmentName: 'Test assessment',
	assetName: 'Test asset',
	evidenceName: 'Test evidence',
	folderName: 'Test domain',
	perimeterName: 'Test perimeter',
	riskAcceptanceName: 'Test risk acceptance',
	riskAssessmentName: 'Test risk assessment',
	riskAssessmentVersion: '1.4.2',
	riskAssessmentVersion2: '1.4.3',
	riskScenarioName: 'Test risk scenario',
	referenceControlName: 'Test reference control',
	appliedControlName: 'Test applied control',
	securityExceptionName: 'Test exception',
	threatName: 'Test threat',
	description: 'Test description',
	biaName: 'Test BIA',
	file: new URL('../utils/test_image.jpg', import.meta.url).pathname,
	file2: new URL('../utils/test_file.txt', import.meta.url).pathname,
	user: {
		email: 'user@tests.com',
		password: 'pass123wordTest',
		firstName: 'Test',
		lastName: 'User'
	},
	usergroups: {
		// this lists needs to be updated when updating permissions in apps.py in order to avoid test failures
		analyst: {
			name: 'Analyst',
			perms: [
				'add_filteringlabel',
				'view_filteringlabel',
				'add_appliedcontrol',
				'add_asset',
				'add_complianceassessment',
				'add_evidence',
				'add_policy',
				'add_perimeter',
				'add_riskacceptance',
				'add_riskassessment',
				'add_riskscenario',
				'add_solution',
				'add_threat',
				'add_vulnerability',
				'change_appliedcontrol',
				'change_asset',
				'change_complianceassessment',
				'change_entity',
				'change_entityassessment',
				'change_evidence',
				'change_policy',
				'change_perimeter',
				'change_referencecontrol',
				'change_vulnerability',
				'change_representative',
				'change_requirementassessment',
				'change_riskacceptance',
				'change_riskassessment',
				'change_riskscenario',
				'change_solution',
				'change_threat',
				'delete_appliedcontrol',
				'delete_asset',
				'delete_complianceassessment',
				'delete_entity',
				'delete_entityassessment',
				'delete_evidence',
				'delete_policy',
				'delete_perimeter',
				'delete_referencecontrol',
				'delete_vulnerability',
				'delete_representative',
				'delete_riskacceptance',
				'delete_riskassessment',
				'delete_riskscenario',
				'delete_solution',
				'delete_threat',
				'view_appliedcontrol',
				'view_asset',
				'view_complianceassessment',
				'view_entity',
				'view_entityassessment',
				'view_evidence',
				'view_folder',
				'view_framework',
				'view_loadedlibrary',
				'view_policy',
				'view_perimeter',
				'view_referencecontrol',
				'view_vulnerability',
				'view_representative',
				'view_requirementassessment',
				'view_requirementmapping',
				'view_requirementmappingset',
				'view_requirementnode',
				'view_riskacceptance',
				'view_riskassessment',
				'view_riskmatrix',
				'view_riskscenario',
				'view_solution',
				'view_storedlibrary',
				'view_threat',
				'view_user',
				'view_usergroup',
				'add_ebiosrmstudy',
				'view_ebiosrmstudy',
				'change_ebiosrmstudy',
				'delete_ebiosrmstudy',
				'add_fearedevent',
				'view_fearedevent',
				'change_fearedevent',
				'delete_fearedevent',
				'add_roto',
				'view_roto',
				'change_roto',
				'delete_roto',
				'add_stakeholder',
				'view_stakeholder',
				'change_stakeholder',
				'delete_stakeholder',
				'add_strategicscenario',
				'view_strategicscenario',
				'change_strategicscenario',
				'delete_strategicscenario',
				'add_attackpath',
				'view_attackpath',
				'change_attackpath',
				'delete_attackpath',
				'add_operationalscenario',
				'view_operationalscenario',
				'change_operationalscenario',
				'delete_operationalscenario',
				'view_qualification',
				'view_globalsettings',
				'view_securityexception',
				'add_securityexception',
				'change_securityexception',
				'delete_securityexception',
				'add_finding',
				'view_finding',
				'change_finding',
				'delete_finding',
				'add_findingsassessment',
				'view_findingsassessment',
				'change_findingsassessment',
				'delete_findingsassessment',
				'add_incident',
				'view_incident',
				'change_incident',
				'delete_incident',
				'add_timelineentry',
				'view_timelineentry',
				'change_timelineentry',
				'delete_timelineentry',
				'add_tasktemplate',
				'view_tasktemplate',
				'change_tasktemplate',
				'delete_tasktemplate',
				'view_tasknode',
				'change_tasknode',
				'delete_tasknode',
				'add_businessimpactanalysis',
				'view_businessimpactanalysis',
				'change_businessimpactanalysis',
				'delete_businessimpactanalysis',
				'add_escalationthreshold',
				'view_escalationthreshold',
				'change_escalationthreshold',
				'delete_escalationthreshold',
				'add_assetassessment',
				'view_assetassessment',
				'change_assetassessment',
				'delete_assetassessment',
				'view_assetclass',
				'view_campaign',
				'add_processing',
				'change_processing',
				'view_processing',
				'delete_processing',
				'view_processingnature',
				'add_purpose',
				'change_purpose',
				'view_purpose',
				'delete_purpose',
				'add_personaldata',
				'change_personaldata',
				'view_personaldata',
				'delete_personaldata',
				'add_datasubject',
				'change_datasubject',
				'view_datasubject',
				'delete_datasubject',
				'add_datarecipient',
				'change_datarecipient',
				'view_datarecipient',
				'delete_datarecipient',
				'add_datacontractor',
				'change_datacontractor',
				'view_datacontractor',
				'delete_datacontractor',
				'add_datatransfer',
				'change_datatransfer',
				'view_datatransfer',
				'delete_datatransfer',
				'view_elementaryaction',
				'add_elementaryaction',
				'change_elementaryaction',
				'delete_elementaryaction',
				'view_operatingmode',
				'add_operatingmode',
				'change_operatingmode',
				'delete_operatingmode',
				'view_killchain',
				'add_killchain',
				'change_killchain',
				'delete_killchain'
			]
		},
		reader: {
			name: 'Reader',
			perms: [
				'view_appliedcontrol',
				'view_asset',
				'view_complianceassessment',
				'view_entity',
				'view_entityassessment',
				'view_evidence',
				'view_folder',
				'view_framework',
				'view_loadedlibrary',
				'view_policy',
				'view_perimeter',
				'view_referencecontrol',
				'view_representative',
				'view_requirementassessment',
				'view_requirementmapping',
				'view_requirementmappingset',
				'view_requirementnode',
				'view_riskacceptance',
				'view_riskassessment',
				'view_riskmatrix',
				'view_riskscenario',
				'view_solution',
				'view_storedlibrary',
				'view_threat',
				'view_vulnerability',
				'view_user',
				'view_usergroup',
				'view_ebiosrmstudy',
				'view_fearedevent',
				'view_roto',
				'view_stakeholder',
				'view_strategicscenario',
				'view_attackpath',
				'view_operationalscenario',
				'view_qualification',
				'view_globalsettings',
				'view_securityexception',
				'view_finding',
				'view_findingsassessment',
				'view_incident',
				'view_timelineentry',
				'view_tasknode',
				'view_tasktemplate',
				'view_businessimpactanalysis',
				'view_assetassessment',
				'view_escalationthreshold',
				'view_assetclass',
				'view_processing',
				'view_processingnature',
				'view_purpose',
				'view_personaldata',
				'view_datasubject',
				'view_datarecipient',
				'view_datacontractor',
				'view_datatransfer',
				'view_campaign',
				'view_elementaryaction',
				'view_operatingmode',
				'view_killchain'
			]
		},
		domainManager: {
			name: 'Domain manager',
			perms: [
				'add_filteringlabel',
				'view_filteringlabel',
				'add_appliedcontrol',
				'add_asset',
				'add_complianceassessment',
				'add_entity',
				'add_entityassessment',
				'add_evidence',
				'add_folder',
				'add_policy',
				'add_perimeter',
				'add_riskacceptance',
				'add_riskassessment',
				'add_riskmatrix',
				'add_riskscenario',
				'add_solution',
				'add_threat',
				'change_appliedcontrol',
				'change_asset',
				'change_complianceassessment',
				'change_entity',
				'change_entityassessment',
				'change_evidence',
				'change_folder',
				'change_policy',
				'change_perimeter',
				'change_referencecontrol',
				'change_representative',
				'change_requirementassessment',
				'change_riskacceptance',
				'change_riskassessment',
				'change_riskmatrix',
				'change_riskscenario',
				'change_solution',
				'change_threat',
				'delete_appliedcontrol',
				'delete_asset',
				'delete_complianceassessment',
				'delete_entity',
				'delete_entityassessment',
				'delete_evidence',
				'delete_folder',
				'delete_policy',
				'delete_perimeter',
				'delete_referencecontrol',
				'delete_representative',
				'delete_riskacceptance',
				'delete_riskassessment',
				'delete_riskmatrix',
				'add_vulnerability',
				'view_vulnerability',
				'change_vulnerability',
				'delete_vulnerability',
				'delete_riskscenario',
				'delete_solution',
				'delete_threat',
				'view_appliedcontrol',
				'view_asset',
				'view_complianceassessment',
				'view_entity',
				'view_entityassessment',
				'view_evidence',
				'view_folder',
				'view_framework',
				'view_loadedlibrary',
				'view_policy',
				'view_perimeter',
				'view_referencecontrol',
				'view_representative',
				'view_requirementassessment',
				'view_requirementmapping',
				'view_requirementmappingset',
				'view_requirementnode',
				'view_riskacceptance',
				'view_riskassessment',
				'view_riskmatrix',
				'view_riskscenario',
				'view_solution',
				'view_storedlibrary',
				'view_threat',
				'view_user',
				'view_usergroup',
				'add_ebiosrmstudy',
				'view_ebiosrmstudy',
				'change_ebiosrmstudy',
				'delete_ebiosrmstudy',
				'add_fearedevent',
				'view_fearedevent',
				'change_fearedevent',
				'delete_fearedevent',
				'add_roto',
				'view_roto',
				'change_roto',
				'delete_roto',
				'add_stakeholder',
				'view_stakeholder',
				'change_stakeholder',
				'delete_stakeholder',
				'add_strategicscenario',
				'view_strategicscenario',
				'change_strategicscenario',
				'delete_strategicscenario',
				'add_attackpath',
				'view_attackpath',
				'change_attackpath',
				'delete_attackpath',
				'add_operationalscenario',
				'view_operationalscenario',
				'change_operationalscenario',
				'delete_operationalscenario',
				'view_qualification',
				'view_globalsettings',
				'view_securityexception',
				'add_securityexception',
				'change_securityexception',
				'delete_securityexception',
				'add_finding',
				'view_finding',
				'change_finding',
				'delete_finding',
				'add_findingsassessment',
				'view_findingsassessment',
				'change_findingsassessment',
				'delete_findingsassessment',
				'add_incident',
				'view_incident',
				'change_incident',
				'delete_incident',
				'add_timelineentry',
				'view_timelineentry',
				'change_timelineentry',
				'delete_timelineentry',
				'add_tasktemplate',
				'view_tasktemplate',
				'change_tasktemplate',
				'delete_tasktemplate',
				'view_tasknode',
				'change_tasknode',
				'delete_tasknode',
				'add_businessimpactanalysis',
				'view_businessimpactanalysis',
				'change_businessimpactanalysis',
				'delete_businessimpactanalysis',
				'add_escalationthreshold',
				'view_escalationthreshold',
				'change_escalationthreshold',
				'delete_escalationthreshold',
				'add_assetassessment',
				'view_assetassessment',
				'change_assetassessment',
				'delete_assetassessment',
				'view_assetclass',
				'add_campaign',
				'view_campaign',
				'change_campaign',
				'delete_campaign',
				'add_processing',
				'change_processing',
				'view_processing',
				'delete_processing',
				'view_processingnature',
				'add_purpose',
				'change_purpose',
				'view_purpose',
				'delete_purpose',
				'add_personaldata',
				'change_personaldata',
				'view_personaldata',
				'delete_personaldata',
				'add_datasubject',
				'change_datasubject',
				'view_datasubject',
				'delete_datasubject',
				'add_datarecipient',
				'change_datarecipient',
				'view_datarecipient',
				'delete_datarecipient',
				'add_datacontractor',
				'change_datacontractor',
				'view_datacontractor',
				'delete_datacontractor',
				'add_datatransfer',
				'change_datatransfer',
				'view_datatransfer',
				'delete_datatransfer',
				'view_elementaryaction',
				'add_elementaryaction',
				'change_elementaryaction',
				'delete_elementaryaction',
				'view_operatingmode',
				'add_operatingmode',
				'change_operatingmode',
				'delete_operatingmode',
				'view_killchain',
				'add_killchain',
				'change_killchain',
				'delete_killchain'
			]
		},
		approver: {
			name: 'Approver',
			perms: [
				'view_perimeter',
				'view_riskassessment',
				'view_appliedcontrol',
				'view_policy',
				'view_riskscenario',
				'view_riskacceptance',
				'approve_riskacceptance',
				'view_asset',
				'view_threat',
				'view_vulnerability',
				'view_referencecontrol',
				'view_folder',
				'view_usergroup',
				'view_riskmatrix',
				'view_complianceassessment',
				'view_requirementassessment',
				'view_requirementnode',
				'view_evidence',
				'view_framework',
				'view_storedlibrary',
				'view_loadedlibrary',
				'view_user',
				'view_requirementmappingset',
				'view_requirementmapping',
				'view_ebiosrmstudy',
				'view_fearedevent',
				'view_roto',
				'view_stakeholder',
				'view_strategicscenario',
				'view_attackpath',
				'view_operationalscenario',
				'view_qualification',
				'view_globalsettings',
				'view_securityexception',
				'view_finding',
				'view_findingsassessment',
				'view_incident',
				'view_timelineentry',
				'view_tasknode',
				'view_tasktemplate',
				'view_businessimpactanalysis',
				'view_assetassessment',
				'view_escalationthreshold',
				'view_assetclass',
				'view_campaign',
				'view_processing',
				'view_processingnature',
				'view_purpose',
				'view_personaldata',
				'view_datasubject',
				'view_datarecipient',
				'view_datacontractor',
				'view_datatransfer',
				'view_elementaryaction',
				'view_operatingmode',
				'view_killchain'
			]
		}
	},
	framework: {
		name: 'NIST CSF v1.1',
		ref: 'NIST-CSF-1.1',
		urn: 'urn:intuitem:risk:library:nist-csf-1.1'
	},
	matrix: {
		name: 'Critical risk matrix 5x5',
		displayName: 'critical 5x5',
		urn: 'urn:intuitem:risk:library:critical_risk_matrix_5x5'
	},
	referenceControl: {
		name: 'POL.PHYSICAL - Physical security policy',
		// category: 'policy',
		// csf_function: 'govern',
		library: {
			name: 'Usual reference controls',
			ref: 'doc-pol',
			urn: 'urn:intuitem:risk:library:doc-pol'
		},
		urn: 'urn:intuitem:risk:function:POL.PHYSICAL'
	},
	referenceControl2: {
		name: 'DOC.CONTROLS - Controls accountability matrix',
		// category: 'process',
		// csf_function: 'protect',
		library: {
			name: 'Usual reference controls',
			ref: 'doc-pol',
			urn: 'urn:intuitem:risk:library:doc-pol'
		},
		urn: 'urn:intuitem:risk:function:DOC.CONTROLS'
	},
	threat: {
		name: 'T1011 - Exfiltration Over Other Network Medium',
		library: {
			name: 'Mitre ATT&CK v16 - Threats and mitigations',
			ref: 'mitre-attack',
			urn: 'urn:intuitem:risk:library:mitre-attack'
		},
		urn: 'urn:intuitem:risk:threat:mitre-attack:T1011'
	},
	threat2: {
		name: 'T1052 - Exfiltration Over Physical Medium',
		library: {
			name: 'Mitre ATT&CK v16 - Threats and mitigations',
			ref: 'mitre-attack',
			urn: 'urn:intuitem:risk:library:mitre-attack'
		},
		urn: 'urn:intuitem:risk:threat:mitre-attack:T1052'
	},
	requirement_assessment: {
		name: 'RC.RP - Recovery Planning',
		library: {
			name: 'NIST CSF v1.1',
			ref: 'NIST-CSF-1.1',
			urn: 'urn:intuitem:risk:library:nist-csf-1.1'
		}
	},
	requirement_assessment2: {
		name: 'ID.GV - Governance',
		library: {
			name: 'NIST CSF v1.1',
			ref: 'NIST-CSF-1.1',
			urn: 'urn:intuitem:risk:library:nist-csf-1.1'
		}
	}
} as { [key: string]: any };
