name: Build and Push Helm Charts

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

env:
  UBUNTU_VERSION: "ubuntu-24.04"
  CHART_NAME: "ciso-assistant-next"
  CHART_PATH: "./charts/${{ env.CHART_NAME }}"
  REGISTRY: "ghcr.io/${{ github.repository_owner }}/${{ env.CHART_NAME }}-helm"

jobs:
  build-and-push:
    runs-on: ${{ env.UBUNTU_VERSION }}
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: latest

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io --username $GITHUB_ACTOR --password-stdin

      - name: Get Version from Git Tags
        run: |
          echo "VERSION=$(git describe --tags --always)" >> $GITHUB_ENV
          echo "BUILD=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Update Helm Dependencies
        run: |
          echo "Updating dependencies for ${CHART_PATH}"
          helm dependency update "${CHART_PATH}"

      - name: Package Helm Chart
        run: |
          helm package $CHART_PATH --version $VERSION
          helm repo index .

      - name: Push Helm Chart to GHCR
        run: |
          helm push ${{ env.CHART_NAME }}-${{ env.VERSION }}.tgz oci://${{ env.REGISTRY }}
